const assert=require('assert');
const fs=require('fs');
const html=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const build=fs.readFileSync('app-build.js','utf8');
const controller=fs.readFileSync('src/app_update_controller.js','utf8');
assert(html.includes('src/app_update_controller.js'),'host must load update controller');
assert(sw.includes('./src/app_update_controller.js'),'offline shell must cache update controller');
assert(sw.includes("importScripts('./app-build.js')"),'service worker and page must share build descriptor');
assert(html.includes('appBuildLabel()'),'Settings must display version and build');
assert(html.includes('Check for Update'),'Settings must offer a large manual check control');
assert(controller.includes('registration.update()'),'manual check must call the service worker update request');
assert(controller.includes('Update found — ready to apply.'),'waiting update must be visibly reported');
assert(html.includes('id="applyUpdateButton"'),'Settings must offer controlled Apply Update');
assert(controller.includes("type:'SKIP_WAITING'"),'Apply Update must use controlled worker activation');
assert(html.includes("addEventListener('controllerchange'"),'activation must retain controlled reload');
assert(html.includes('Reload & Update'),'automatic update-ready banner must remain intact');
assert(html.includes("hidden disabled')+'>Apply Update"),'Apply Update must not be offered without a waiting worker');
assert(controller.includes("you're offline"),'offline state must be honest');
assert(controller.includes('Update check failed — Try Again.'),'failure state must be honest');
assert(!/(localStorage\.clear|indexedDB\.deleteDatabase)/.test(controller),'update workflow must not clear classroom data');
assert(html.includes('installOverscrollGuard()'),'Samsung pull-to-refresh protection must remain');
assert(sw.includes("request.mode==='navigate'")&&sw.includes("'./index.html'")&&sw.includes('caches.match(target)'),'offline navigation fallback must remain');
assert(build.includes("build:'arc-schema-v8-integration-verification-12-sidebar-repair-2-repair-1-fixture-init-repair-1-stage2-physical-verification-bridge-1-reload-rehydration-repair-1-repair-2-cleanup-isolation-repair-1-production-academic-configuration-1-parity-p3-schedule-adapter-1-parity-p4-academic-consumers-1-parity-p5-attendance-pass-1-parity-p6-project-technical-1-parity-p7-competency-evidence-open-shop-1-parity-p8a-behavior-structural-foundation-1-parity-p8-workplace-safety-behavior-1-parity-p9-gradebook-authority-1'"),'tested shell must have a truthful stable build label');
console.log('PASS App update Settings and safety contracts');
