const assert=require('assert');
const crypto=require('crypto').webcrypto;
const Storage=require('../src/arc_v8_storage');
const Backup=require('../src/arc_v8_backup_recovery');
const Production=require('../src/arc_v8_production_initialization');
const S=Storage.STORES;

const KEYS={metadata:'key',migration_log:'id',infrastructure_records:'id',students:'studentId',courses:'courseId',school_years:'schoolYearId',semesters:'semesterId',grading_periods:'gradingPeriodId',sections:'sectionId',course_enrollments:'enrollmentId',enrollment_schedule_assignments:'scheduleAssignmentId',activity_definitions:'definitionId',activity_versions:'versionId',activity_evidence_declarations:'declarationId',activity_assignments:'assignmentId',student_activities:'studentActivityId',activity_attempts:'attemptId',project_instances:'projectId',project_build_attempts:'buildId',project_checkpoint_events:'eventId',project_manual_need_events:'needEventId',project_rubric_assessments:'rubricAssessmentId',competency_definitions:'competencyId',competency_versions:'competencyVersionId',competency_strategy_configurations:'strategyConfigId',evidence_sources:'sourceId',evidence_records:'evidenceRecordId',instructor_overrides:'overrideId',workplace_days:'workplaceDayId',workplace_events:'workplaceEventId',positive_workplace_observations:'observationId',safety_events:'safetyEventId',workplace_week_finalizations:'weekFinalizationId',activity_assessment_finalizations:'activityAssessmentFinalizationId',assessment_results:'assessmentResultId',gradebook_policy_versions:'gradebookPolicyVersionId',gradebook_entries:'gradebookEntryId',gradebook_entry_revisions:'gradebookEntryRevisionId',gradebook_posting_instances:'postingInstanceId',gradebook_posting_memberships:'postingMembershipId',gradebook_posting_events:'postingEventId',quarter_grade_snapshots:'quarterGradeSnapshotId',attendance_records:'attendanceRecordId',pass_events:'passEventId',supplemental_shop_sessions:'supplementalSessionId',attendance_grade_decisions:'attendanceGradeDecisionId',artifacts:'artifactId',artifact_media_blobs:'mediaBlobId',artifact_links:'artifactLinkId',booth_definitions:'boothId',booth_resources:'boothResourceId',booth_assignments:'boothAssignmentId',booth_issues:'boothIssueId'};
const clone=x=>x===undefined?undefined:structuredClone(x);

function environment(options={}){
  let exists=!!options.exists,version=options.version===undefined?10:options.version,storeNames=(options.storeNames||Object.values(S)).slice(),maps={},failTransaction=!!options.failTransaction,resets=0;
  const v7={weld_v013:'protected-v7-sentinel'},photos={name:'WeldingClassroomPhotoStore',sentinel:'protected-photo-sentinel'};
  function fresh(){maps={};storeNames.forEach(name=>maps[name]=new Map());if(storeNames.includes(S.metadata))maps[S.metadata].set('database',{key:'database',schemaFamily:'arc-classroom',schemaVersion:options.schemaVersion===undefined?8:options.schemaVersion,indexedDbVersion:version,initializationState:'ready',createdAt:'2026-09-27T00:00:00.000Z'});if(storeNames.includes(S.migrations))for(let i=0;i<10;i++)maps[S.migrations].set(`indexeddb-${i}-to-${i+1}`,{id:`indexeddb-${i}-to-${i+1}`,status:'succeeded',schemaVersion:8});if(storeNames.includes(S.infrastructure))for(const row of options.infrastructure||[])maps[S.infrastructure].set(row.id,clone(row));if(options.domainRecord)maps[S.students].set(options.domainRecord.studentId,clone(options.domainRecord));}
  fresh();
  function snapshot(){let counts={};storeNames.forEach(name=>counts[name]=maps[name].size);return{exists,databaseName:Storage.DATABASE_NAME,indexedDbVersion:version,storeNames:storeNames.slice(),counts,metadata:maps[S.metadata]&&clone(maps[S.metadata].get('database')),infrastructure:maps[S.infrastructure]?Array.from(maps[S.infrastructure].values()).map(clone):[],knownDatabases:[Storage.DATABASE_NAME,'arc_classroom_v8_engineering_verification','unrelated_test_database']};}
  function connection(){
    function txApi(work){return{get:async(s,k)=>clone(work[s].get(k)),query:async s=>Array.from(work[s].values()).map(clone),add:async(s,v)=>{let k=v[KEYS[s]];if(work[s].has(k))throw Error('duplicate');work[s].set(k,clone(v));},put:async(s,v)=>work[s].set(v[KEYS[s]],clone(v)),delete:async(s,k)=>work[s].delete(k),clear:async s=>work[s].clear()};}
    return{metadata:clone(maps[S.metadata].get('database')),storeNames:storeNames.slice(),read:async(s,k)=>clone(maps[s].get(k)),query:async s=>Array.from(maps[s].values()).map(clone),add:async(s,v)=>txApi(maps).add(s,v),put:async(s,v)=>txApi(maps).put(s,v),delete:async(s,k)=>maps[s].delete(k),async transaction(stores,fn){let work={};storeNames.forEach(s=>work[s]=new Map(Array.from(maps[s]).map(([k,v])=>[k,clone(v)])));let result=await fn(txApi(work)),names=Array.isArray(stores)?stores:[stores];if(failTransaction&&names.length===1&&names[0]===S.infrastructure){failTransaction=false;throw new Storage.StorageError('TRANSACTION_ABORTED','injected');}maps=work;return result;},close(){}};
  }
  const storage={constants:{databaseName:Storage.DATABASE_NAME,schemaFamily:Storage.SCHEMA_FAMILY,schemaVersion:8,indexedDbVersion:10,stores:S},async open(){if(!exists){exists=true;version=10;storeNames=Object.values(S);fresh();}return connection();},async resetDevelopmentDatabase(){let protection=maps[S.infrastructure]&&maps[S.infrastructure].get('database-protection');if(protection&&protection.mode==='Production/Classroom Protected')throw new Storage.StorageError('PROTECTED_DATABASE','blocked');exists=false;resets++;fresh();},generateId:()=>crypto.randomUUID()};
  const inspector={inspect:async()=>snapshot()};
  const service=Production.create({inspector,storageFactory:()=>storage,backupFactory:db=>Backup.create({storage:db,crypto,now:()=> '2026-09-27T12:00:00.000Z',build:{version:'0.18',build:'stage-14-test'}}),crypto,now:()=> '2026-09-27T12:00:00.000Z',build:{version:'0.18',build:'stage-14-test'}});
  return{service,storage,inspector,snapshot,get maps(){return maps;},v7,photos,get resets(){return resets;}};
}
function authority(){return{confirmedBy:'Stage 14 authorized operator',rollbackRef:'rollback/stage-14-cutover-stage-1',startingCommit:'ed771e94719bf57283a9474cf92a01c0610911e4',startingTree:'8647e81b533397c343e9436bfe47c48b8f9d8ccd'};}
let pass=0,total=0;async function test(name,fn){total++;try{await fn();pass++;console.log('PASS',name);}catch(e){console.error('FAIL',name,e);process.exitCode=1;}}

(async()=>{
await test('native inspector enumerates and reads an existing database without requesting an upgrade',async()=>{
  let openArgs=0,stores=Object.values(S);
  let meta={key:'database',schemaFamily:'arc-classroom',schemaVersion:8,indexedDbVersion:10,initializationState:'ready'},infra=[{id:'sentinel'}];
  function request(value){let r={};queueMicrotask(()=>{r.result=clone(value);if(r.onsuccess)r.onsuccess();});return r;}
  let idb={
    databases:async()=>[{name:'arc_classroom_v8',version:10},{name:'arc_classroom_v8_engineering_verification',version:10}],
    open(name){
      openArgs=arguments.length;assert.equal(name,'arc_classroom_v8');let r={};
      queueMicrotask(()=>{
        r.result={version:10,objectStoreNames:stores,transaction(){return{objectStore(store){return{
          count:()=>request(store===S.metadata?1:store===S.infrastructure?1:0),
          get:key=>request(store===S.metadata&&key==='database'?meta:undefined),
          getAll:()=>request(store===S.infrastructure?infra:[])
        };}};},close(){}};
        if(r.onsuccess)r.onsuccess();
      });
      return r;
    }
  };
  let report=await Production.nativeInspector(idb).inspect('arc_classroom_v8');
  assert.equal(openArgs,1);assert(report.exists);assert.equal(report.indexedDbVersion,10);assert.equal(report.storeNames.length,53);assert.deepEqual(report.metadata,meta);assert.deepEqual(report.infrastructure,infra);assert(report.knownDatabases.includes('arc_classroom_v8_engineering_verification'));
});
await test('initializes exact protected empty production authority with 53 stores',async()=>{let e=environment(),r=await e.service.initialize(authority());assert.equal(r.databaseName,'arc_classroom_v8');assert.equal(r.schemaVersion,8);assert.equal(r.indexedDbVersion,10);assert.equal(r.storeCount,53);assert.equal(r.empty.domainRecordCount,0);assert.equal(r.empty.excludedIdentityCount,0);assert.equal(r.authorityState,'V7_ONLY');assert.equal(r.classroomAuthorityTransferred,false);assert.equal(r.realStudentDataAuthorized,false);assert.equal(r.manifests.initialization.expectedStoreCount,53);assert.equal(r.manifests.reconciliation.importedRecordCount,0);assert.deepEqual(r.manifests.reconciliation.excludedDataClasses,['engineering','simulation','pilot','test','fictional-transactional']);});
await test('creates verified complete recovery package with empty media SHA-256 and readback',async()=>{let r=await environment().service.initialize(authority());assert(r.preProtectionRecovery.verified);assert(r.recovery.verification.verified);assert.equal(r.recovery.media.blobCount,0);assert.equal(r.recovery.media.totalBytes,0);assert.equal(r.recovery.checksum.length,64);assert.equal(r.audit.status,'Verified Healthy');assert(r.audit.healthy);});
await test('preserves v7 local storage photo authority and engineering database isolation',async()=>{let e=environment(),beforeV7=clone(e.v7),beforePhotos=clone(e.photos),r=await e.service.initialize(authority());assert.deepEqual(e.v7,beforeV7);assert.deepEqual(e.photos,beforePhotos);assert(r.knownDatabases.includes('arc_classroom_v8_engineering_verification'));assert.equal(e.maps[S.students].size,0);});
await test('atomic manifest transaction and protected reset refusal survive reopen',async()=>{let e=environment(),first=await e.service.initialize(authority()),second=await e.service.initialize(authority());assert(first.protectedResetRefused&&second.protectedResetRefused);assert.equal(e.maps[S.infrastructure].size,3);assert.equal(e.resets,0);assert.equal(second.manifests.initialization.status,'complete');});
await test('deterministic reopen rejects different rollback authority',async()=>{let e=environment();await e.service.initialize(authority());let changed=authority();changed.rollbackRef='rollback/different-authority';await assert.rejects(e.service.initialize(changed),x=>x.code==='ROLLBACK_AUTHORITY_MISMATCH');assert.equal(e.maps[S.infrastructure].size,3);});
await test('refuses unexpected existing domain records without overwriting',async()=>{let e=environment({exists:true,domainRecord:{studentId:'unexpected-student',name:'Unexpected'}});await assert.rejects(e.service.initialize(authority()),x=>x.code==='UNEXPECTED_PRODUCTION_RECORDS');assert.equal(e.maps[S.students].get('unexpected-student').name,'Unexpected');assert.equal(e.maps[S.infrastructure].size,0);});
await test('refuses unrecognized empty existing production database',async()=>{let e=environment({exists:true});await assert.rejects(e.service.initialize(authority()),x=>x.code==='UNEXPECTED_EXISTING_DATABASE');assert.equal(e.maps[S.infrastructure].size,0);});
await test('refuses incompatible schema version and mismatched store manifest',async()=>{let wrong=environment({exists:true,schemaVersion:7});await assert.rejects(wrong.service.initialize(authority()),x=>x.code==='METADATA_INCONSISTENT');let stores=Object.values(S).slice(0,-1),missing=environment({exists:true,storeNames:stores});await assert.rejects(missing.service.initialize(authority()),x=>x.code==='STORE_INVENTORY_MISMATCH');});
await test('refuses wrong production database identity at construction',async()=>{assert.throws(()=>Production.create({databaseName:'arc_classroom_v8_engineering_verification',inspector:{inspect:async()=>({exists:false})}}),x=>x.code==='PRODUCTION_IDENTITY_REQUIRED');});
await test('requires explicit rollback and operator authority before inspecting or creating',async()=>{let e=environment();await assert.rejects(e.service.initialize({confirmedBy:'operator'}),x=>x.code==='AUTHORIZATION_REQUIRED');assert.equal((await e.inspector.inspect()).exists,false);assert.equal(e.resets,0);});
await test('transaction failure leaves no partial manifests and removes only newly created database',async()=>{let e=environment({failTransaction:true});await assert.rejects(e.service.initialize(authority()),x=>x.code==='TRANSACTION_ABORTED');let state=await e.inspector.inspect();assert.equal(state.exists,false);assert.equal(e.v7.weld_v013,'protected-v7-sentinel');assert.equal(e.photos.sentinel,'protected-photo-sentinel');});
await test('source remains explicit tooling and is absent from classroom and service-worker runtime',async()=>{let fs=require('fs'),src=fs.readFileSync('src/arc_v8_production_initialization.js','utf8'),html=fs.readFileSync('index.html','utf8'),sw=fs.readFileSync('sw.js','utf8');assert(!html.includes('arc_v8_production_initialization.js'));assert(sw.includes('./src/arc_v8_production_initialization.js'));assert(!html.includes('arc_v8_stage2_verification.html'));assert(!/localStorage|WeldingClassroomPhotoStore|weld_v013/.test(src));assert(!/Taylor Reed|projectBank|competency catalog/i.test(src));});
if(!process.exitCode)console.log(`\n${pass}/${total} ARC v8 Production Initialization tests passed.`);
})();
