const assert=require('assert');
const fs=require('fs');
const html=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const source=fs.readFileSync('src/arc_v8_storage.js','utf8');
assert(html.includes('<script src="src/arc_v8_storage.js"></script>'),'page must load the v8 infrastructure module');
assert(sw.includes("'./src/arc_v8_storage.js'"),'offline shell must cache the v8 infrastructure module');
assert(html.includes('<script src="src/arc_v8_academic.js"></script>'),'page must load the academic repository without invoking it');
assert(sw.includes("'./src/arc_v8_academic.js'"),'offline shell must cache the academic repository');
assert(html.includes('<script src="src/arc_v8_activity.js"></script>'),'page must load the Activity repository without invoking it');
assert(sw.includes("'./src/arc_v8_activity.js'"),'offline shell must cache the Activity repository');
assert(html.includes('<script src="src/arc_v8_project.js"></script>'),'page must load the Project repository without invoking it');
assert(sw.includes("'./src/arc_v8_project.js'"),'offline shell must cache the Project repository');
assert(html.includes('<script src="src/arc_v8_evidence.js"></script>'),'page must load the Evidence repository without invoking it');
assert(sw.includes("'./src/arc_v8_evidence.js'"),'offline shell must cache the Evidence repository');
assert(html.includes('<script src="src/arc_v8_workplace_safety.js"></script>'),'page must load the Workplace/Safety repository without invoking it');
assert(sw.includes("'./src/arc_v8_workplace_safety.js'"),'offline shell must cache the Workplace/Safety repository');
assert(html.includes('<script src="src/arc_v8_gradebook.js"></script>'),'page must load the Gradebook repository without invoking it');
assert(sw.includes("'./src/arc_v8_gradebook.js'"),'offline shell must cache the Gradebook repository');
assert(html.includes('<script src="src/arc_v8_attendance.js"></script>'),'page must load the Attendance repository without invoking it');
assert(sw.includes("'./src/arc_v8_attendance.js'"),'offline shell must cache the Attendance repository');
assert(html.includes('<script src="src/arc_v8_artifacts.js"></script>'),'page must load the Artifact repository without invoking it');
assert(sw.includes("'./src/arc_v8_artifacts.js'"),'offline shell must cache the Artifact repository');
assert(html.includes('const STORAGE_KEY = "weld_v013"'),'v7 classroom storage key must remain unchanged');
assert(html.includes('const CURRENT_SCHEMA_VERSION = 7'),'v7 classroom schema must remain unchanged');
assert(source.includes("DATABASE_NAME='arc_classroom_v8'"),'v8 database must have an isolated identity');
assert(source.includes("driver.remove(DATABASE_NAME"),'development reset must target only the isolated v8 database');
assert(!source.includes('weld_v013'),'v8 infrastructure must not read, write, migrate, or reset v7 classroom state');
assert(!source.includes('WeldingClassroomPhotoStore'),'v8 reset must not target the v7 photo database');
assert(!/\.open\(\)\s*[;.]/.test(source.split('return {create:create')[1]||''),'module export must not automatically open storage');
console.log('PASS ARC v8 storage shell isolation contracts');
