const assert=require('assert'),fs=require('fs'),Migration=require('../src/arc_v8_schedule_configuration_migration');
const fixturePath='tests/fixtures/arc_current_editable_school_config_parity_fixture_20261004.json';
const fixture=JSON.parse(fs.readFileSync(fixturePath,'utf8'));
let pass=0,total=0;function test(name,fn){total++;try{fn();pass++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1}}
function plan(value=fixture){return Migration.project(value)}
function copy(){return structuredClone(fixture)}
test('supplied editable configuration projects all three exact Bell templates',()=>{let p=plan(),source=fixture.currentStateExample;assert.equal(p.bellSchedules.length,3);for(const row of p.bellSchedules){let original=source.bellSchedules[row.sourceId];assert(original);assert.deepEqual(row.periods.map(x=>({start:x.startTime,end:x.endTime})),Object.keys(original.times).sort((a,b)=>Number(a)-Number(b)).map(key=>original.times[key]));assert(row.periods.every(x=>!Object.hasOwn(x,'kind')));}});
test('Planning remains a separate period-6 placement intent',()=>{let p=plan();assert.equal(p.planningPlacement.periodCode,'6');assert(!p.bellSchedules.some(x=>x.periods.some(y=>y.kind==='Planning')));});
test('all Section placement intents remain editable data',()=>{let p=plan(),source=fixture.currentStateExample.sections;assert.equal(p.sectionPlacementIntents.length,source.length);for(const row of source)assert(p.sectionPlacementIntents.some(x=>x.sourceSectionId===row.id&&x.periodCode===String(row.period)&&x.courseCode===row.course.toUpperCase()));});
test('Friday preserves shortened Bell Schedule and Open Shop mode',()=>{let friday=plan().weeklyDefaults.find(x=>x.weekday==='friday');assert.equal(friday.bellScheduleSourceId,'friday');assert.equal(friday.instructionMode,'open_shop');});
test('all source events and overrides are represented exactly once',()=>{let p=plan(),source=fixture.currentStateExample;assert.equal(p.calendarEvents.length,source.calendarEvents.length);assert.equal(p.calendarOverrides.length,Object.keys(source.calendarOverrides).length);for(const row of source.calendarEvents)assert(p.calendarEvents.some(x=>x.id===row.id&&x.schoolDate===row.date&&x.title===row.title));for(const key of Object.keys(source.calendarOverrides))assert(p.calendarOverrides.some(x=>x.schoolDate===key));});
test('December 14 PD is retained as no instruction',()=>{let row=plan().calendarOverrides.find(x=>x.schoolDate==='2026-12-14');assert.equal(row.dayType,'pd');assert.equal(row.instructionMode,'none');});
test('noninstructional override is Bell-independent when schedule identity is missing',()=>{let changed=copy();changed.currentStateExample.calendarOverrides['2026-12-14']={dayType:'pd',instructionMode:'none'};let row=plan(changed).calendarOverrides.find(x=>x.schoolDate==='2026-12-14');assert.equal(row.bellScheduleSourceId,null);assert.equal(row.instructionMode,'none');});
test('noninstructional override ignores incidental unknown Bell identity',()=>{let changed=copy();changed.currentStateExample.calendarOverrides['2026-12-14']={dayType:'holiday',instructionMode:'regular',scheduleId:'retired-bell'};let row=plan(changed).calendarOverrides.find(x=>x.schoolDate==='2026-12-14');assert.equal(row.bellScheduleSourceId,null);assert.equal(row.instructionMode,'none');});
test('instructional override requires a known Bell identity',()=>{for(let scheduleId of [undefined,'unknown']){let changed=copy();changed.currentStateExample.calendarOverrides['2026-10-02']={dayType:'school',instructionMode:'regular',scheduleId};assert.throws(()=>plan(changed),x=>x.code==='INVALID_CALENDAR_OVERRIDE');}});
test('duplicate normalized Bell source identities are refused',()=>{let changed=copy();changed.currentStateExample.bellSchedules.copy=structuredClone(changed.currentStateExample.bellSchedules.regular);changed.currentStateExample.bellSchedules.copy.id='regular';assert.throws(()=>plan(changed),x=>x.code==='DUPLICATE_BELL_SOURCE_ID');});
test('changing a Bell time changes the plan without runtime constants',()=>{let changed=copy();changed.currentStateExample.bellSchedules.regular.times['1'].start='08:06';assert.notDeepEqual(plan(changed).bellSchedules,plan().bellSchedules);assert.equal(plan(changed).bellSchedules.find(x=>x.sourceId==='regular').periods[0].startTime,'08:06');});
test('changing Planning changes only the projected Planning intent',()=>{let changed=copy();changed.currentStateExample.planningPeriod=5;assert.equal(plan(changed).planningPlacement.periodCode,'5');assert.deepEqual(plan(changed).bellSchedules,plan().bellSchedules);});
test('changing one Section period changes that projected intent',()=>{let changed=copy(),id=changed.currentStateExample.sections[0].id;changed.currentStateExample.sections[0].period=7;assert.equal(plan(changed).sectionPlacementIntents.find(x=>x.sourceSectionId===id).periodCode,'7');});
test('changing a calendar override changes its projection',()=>{let changed=copy();changed.currentStateExample.calendarOverrides['2026-10-02'].dayType='school';changed.currentStateExample.calendarOverrides['2026-10-02'].instructionMode='special';let row=plan(changed).calendarOverrides.find(x=>x.schoolDate==='2026-10-02');assert.equal(row.dayType,'school');assert.equal(row.instructionMode,'special');});
test('missing structured academic boundaries are reviewed and never guessed from event titles',()=>{let p=plan(),codes=p.reviewRequirements.map(x=>x.code);assert.deepEqual(codes,['SCHOOL_YEAR_BOUNDARY_REQUIRED','SEMESTER_BOUNDARY_REQUIRED','GRADING_PERIOD_BOUNDARIES_REQUIRED']);assert.equal(p.readyForApply,false);assert.equal(p.mutates,false);assert(!Object.hasOwn(p,'schoolYear'));assert(!Object.hasOwn(p,'semester'));});
test('planner is pure read-only and contains no environment or production coupling',()=>{let source=fs.readFileSync('src/arc_v8_schedule_configuration_migration.js','utf8'),before=fs.readFileSync(fixturePath);plan();assert(before.equals(fs.readFileSync(fixturePath)));assert(!/document\.|localStorage|indexedDB|arc_classroom_v8|\.add\(|\.put\(|transaction\(/.test(source));});
test('normal ARC remains Schema 7 V7_ONLY with only the authorized PD correction',()=>{let html=fs.readFileSync('index.html','utf8');assert(html.includes('const CURRENT_SCHEMA_VERSION = 7;'));assert(html.includes('ArcScheduleAuthorityAdapter.create({ authorityState: "V7_ONLY" })'));assert(html.includes('"2026-12-14":{"dayType":"pd","scheduleId":"regular","instructionMode":"none"}'));assert(!html.includes('src/arc_v8_schedule_configuration_migration.js'));});
if(!process.exitCode)console.log(`\n${pass}/${total} ARC schedule configuration migration tests passed.`);
