const assert=require('assert'),Storage=require('../src/arc_v8_storage'),Coordinator=require('../src/arc_v8_academic_semester_transition');
const S=Storage.STORES,keys={[S.students]:'studentId',[S.enrollments]:'enrollmentId',[S.scheduleAssignments]:'scheduleAssignmentId',[S.sections]:'sectionId'};
function fixture(options={}){let maps={};Object.values(S).forEach(s=>maps[s]=new Map());let n=1,restores=0,failAdd=false;function add(s,v){maps[s].set(v[keys[s]||'id'],structuredClone(v))}add(S.students,{studentId:'student-1',preferredName:'Student',lifecycle:'active',revision:1});add(S.sections,{sectionId:'section-old',courseId:'arc-course-wt',schoolYearId:'year-1',revision:1,lifecycle:'active'});add(S.sections,{sectionId:'section-new',courseId:'arc-course-wt',schoolYearId:options.crossYear?'year-2':'year-1',revision:1,lifecycle:'active'});add(S.enrollments,{enrollmentId:'enrollment-1',studentId:'student-1',courseId:'arc-course-wt',schoolYearId:'year-1',enrollmentStart:'2026-08-20',enrollmentEnd:null,status:'active',lifecycle:'active',revision:1});add(S.scheduleAssignments,{scheduleAssignmentId:'assignment-1',enrollmentId:'enrollment-1',sectionId:'section-old',effectiveFrom:'2026-08-20',effectiveTo:null,lifecycle:'active',revision:1});let cp=x=>x==null?x:structuredClone(x),snapshot=()=>Object.fromEntries(Object.entries(maps).map(([s,m])=>[s,Array.from(m.entries()).map(cp)])),restore=s=>{for(const [name,rows] of Object.entries(s))maps[name]=new Map(rows.map(cp))},storage={generateId:()=>`00000000-0000-4000-8000-${(n++).toString().padStart(12,'0')}`,query:async s=>Array.from(maps[s].values()).map(cp),async transaction(stores,fn){let before=snapshot(),tx={get:async(s,k)=>cp(maps[s].get(k)),put:async(s,v)=>{maps[s].set(v[keys[s]||'id'],cp(v))},add:async(s,v)=>{if(failAdd&&s===S.scheduleAssignments)throw Error('injected academic write failure');maps[s].set(v[keys[s]||'id'],cp(v))}};try{return await fn(tx)}catch(e){restore(before);throw e}}},preview={ready:true,effectiveFrom:options.crossYear?'2027-08-20':'2027-01-05',targetEffectiveTo:options.crossYear?'2028-05-25':'2027-05-28',targetSchoolYearId:options.crossYear?'year-2':'year-1',targetSemesterId:options.crossYear?'semester-3':'semester-2',planningPeriodCode:'4',choices:[{sectionId:'section-old',action:options.action||'continue',periodCode:'2',expectedRevision:1}]},admin={previewSemesterTransition:async()=>cp(preview),prepareRecovery:async()=>({token:'admin-recovery'}),applySemesterTransition:async()=>({results:[{sourceSectionId:'section-old',action:options.action||'continue',sectionId:(options.action||'continue')==='continue'?'section-new':null}],planning:{id:'planning'},audit:{id:'audit'}})},initial=snapshot(),backup={exportBackup:async()=>({text:'backup',package:{manifest:{packageIntegrity:{checksum:'checksum'}}},verification:{verified:true}}),restoreBackup:async()=>{restores++;restore(initial);return{parity:{matched:true}}}},coordinator=Coordinator.create({storage,administration:admin,backup,actor:'Instructor',now:()=> '2027-01-05T12:00:00.000Z'});return{storage,maps,coordinator,setFail:()=>{failAdd=true},get restores(){return restores}};}
let pass=0,total=0;async function test(name,fn){total++;try{await fn();pass++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1}}
(async()=>{
await test('unknown future schedule stays unknown and mutates nothing',async()=>{let f=fixture();f.coordinator=Coordinator.create({storage:f.storage,administration:{previewSemesterTransition:async()=>({ready:false,reason:'FUTURE_SCHEDULE_UNKNOWN'})},backup:{}});let p=await f.coordinator.preview({});assert.equal(p.ready,false);assert.equal(p.reason,'FUTURE_SCHEDULE_UNKNOWN');assert.equal(f.maps[S.scheduleAssignments].size,1);});
await test('same-year continue preserves Student and Enrollment identity with append-first assignment history',async()=>{let f=fixture(),prepared=await f.coordinator.prepareRecovery({}),result=await f.coordinator.apply({},prepared.token),student=f.maps[S.students].get('student-1'),enrollment=f.maps[S.enrollments].get('enrollment-1'),assignments=Array.from(f.maps[S.scheduleAssignments].values());assert.equal(student.studentId,'student-1');assert.equal(enrollment.lifecycle,'active');assert.equal(assignments.length,2);assert.equal(assignments.find(x=>x.scheduleAssignmentId==='assignment-1').lifecycle,'ended');assert.equal(assignments.find(x=>x.lifecycle==='active').sectionId,'section-new');assert.equal(result.studentIdentityPreserved,true);assert.equal(result.historyAppendFirst,true);});
await test('cross-year continue closes prior Enrollment and creates a new linked Enrollment/Assignment',async()=>{let f=fixture({crossYear:true}),prepared=await f.coordinator.prepareRecovery({}),result=await f.coordinator.apply({},prepared.token),enrollments=Array.from(f.maps[S.enrollments].values()),assignments=Array.from(f.maps[S.scheduleAssignments].values());assert.equal(enrollments.length,2);assert.equal(enrollments.find(x=>x.enrollmentId==='enrollment-1').lifecycle,'closed');let current=enrollments.find(x=>x.lifecycle==='active');assert.equal(current.studentId,'student-1');assert.equal(current.schoolYearId,'year-2');assert.equal(assignments.find(x=>x.lifecycle==='active').enrollmentId,current.enrollmentId);assert.equal(result.academic[0].studentId,'student-1');});
await test('fresh and end choices never enroll prior Students into replacement Sections',async()=>{for(const action of ['new','end']){let f=fixture({action}),prepared=await f.coordinator.prepareRecovery({});await f.coordinator.apply({},prepared.token);assert.equal(Array.from(f.maps[S.scheduleAssignments].values()).filter(x=>x.lifecycle==='active').length,0,action);assert.equal(Array.from(f.maps[S.enrollments].values()).filter(x=>x.lifecycle==='active').length,0,action);}});
await test('academic failure restores exact pretransition database parity',async()=>{let f=fixture();f.setFail();let before=JSON.stringify(Array.from(f.maps[S.scheduleAssignments].entries())),prepared=await f.coordinator.prepareRecovery({});await assert.rejects(f.coordinator.apply({},prepared.token),e=>e.rollback&&e.rollback.restored);assert.equal(f.restores,1);assert.equal(JSON.stringify(Array.from(f.maps[S.scheduleAssignments].entries())),before);});
if(!process.exitCode)console.log(`\n${pass}/${total} Academic Semester Transition coordinator tests passed.`);
})();
