const assert=require('assert'),fs=require('fs'),vm=require('vm'),Coordinator=require('../src/arc_v8_production_academic_configuration');
const page=fs.readFileSync('engineering/arc_v8_production_academic_configuration_page.js','utf8');
const sourceFixture=JSON.parse(fs.readFileSync('tests/fixtures/arc_current_editable_school_config_parity_fixture_20261004.json','utf8')).currentStateExample;
function clone(value){return JSON.parse(JSON.stringify(value));}
function fixture(withAcademic=true){let snapshot=clone(sourceFixture);if(withAcademic)snapshot.academicStructure={version:1,schoolYear:{key:'2026-27',label:'2026-27',startDate:'2026-08-03',endDate:'2027-07-30'},semesters:[{key:'s1',code:'S1',label:'Semester 1',startDate:'2026-08-03',endDate:'2026-12-31',order:1,gradingPeriods:[{key:'q1',code:'Q1',label:'Quarter 1',startDate:'2026-08-03',endDate:'2026-10-14',order:1},{key:'q2',code:'Q2',label:'Quarter 2',startDate:'2026-10-15',endDate:'2026-12-31',order:2}]},{key:'s2',code:'S2',label:'Semester 2',startDate:'2027-01-01',endDate:'2027-07-30',order:2,gradingPeriods:[{key:'q3',code:'Q3',label:'Quarter 3',startDate:'2027-01-01',endDate:'2027-03-10',order:1},{key:'q4',code:'Q4',label:'Quarter 4',startDate:'2027-03-11',endDate:'2027-07-30',order:2}]}],currentSemesterKey:'s1'};return snapshot;}
function harness(captureLiveSchedule,review){let handlers={},elements=new Map(),element=id=>{if(!elements.has(id))elements.set(id,{id,value:'',textContent:'',disabled:false,files:[],addEventListener:()=>{}});return elements.get(id);};['identity','commit','tree','output','scheduleSnapshot','configuration','operator','rollback','confirmation','recoveryConfirmation','recoveryFile'].forEach(element);let buttons=['capture','review'].map(action=>({dataset:{action},textContent:action,disabled:false,addEventListener:(name,handler)=>{if(name==='click')handlers[action]=handler;}})),controls=[...buttons,...elements.values()],coordinator={constants:{databaseName:'arc_classroom_v8',authorityState:'V7_ONLY'},captureLiveSchedule,review,prepare(){throw Error('not used');},inspectState(){},loadRecovery(){},apply(){},recoverInterrupted(){},summary(){},reopenSummary(){}};let context={window:{ARC_BUILD:{build:'test'},location:{search:'?publicationCommit=commit&publicationTree=tree'},localStorage:{}},document:{getElementById:element,querySelectorAll:selector=>selector==='[data-action]'?buttons:controls,createElement:()=>({click(){},remove(){}}),body:{appendChild(){}}},URLSearchParams,URL,Blob,ArcV8Storage:{create:()=>({})},ArcV8ProductionAcademicConfiguration:{RUNTIME_REVISION:'stage2-production-academic-configuration-closure-1',DATABASE_NAME:'arc_classroom_v8',create:()=>coordinator},console};vm.runInNewContext(page,context);return{elements,click:action=>handlers[action]()};}
let passed=0,total=0;async function test(name,fn){total++;try{await fn();passed++;console.log('PASS',name);}catch(error){console.error('FAIL',name,error);process.exitCode=1;}}
(async()=>{
await test('Capture serializes exactly snapshot and structured academic authority',async()=>{let snapshot=fixture(true),result={sourceKey:'weld_v013',snapshot:clone(snapshot),snapshotFingerprint:'fingerprint',migrationPlan:{wrapperOnly:true}},h=harness(async()=>result,()=>{throw Error('review not expected');});await h.click('capture');assert.equal(h.elements.get('scheduleSnapshot').value,JSON.stringify(snapshot,null,2));assert.equal(h.elements.get('configuration').value,JSON.stringify(snapshot.academicStructure,null,2));let output=JSON.parse(h.elements.get('output').textContent);assert.equal(output.academicConfigurationCaptured,true);assert(!JSON.parse(h.elements.get('scheduleSnapshot').value).sourceKey);assert(!JSON.parse(h.elements.get('scheduleSnapshot').value).migrationPlan);});
await test('Capture without Academic Structure still populates schedule and leaves configuration blank',async()=>{let snapshot=fixture(false),h=harness(async()=>({sourceKey:'weld_v013',snapshot:clone(snapshot)}),()=>{});await h.click('capture');assert.equal(h.elements.get('scheduleSnapshot').value,JSON.stringify(snapshot,null,2));assert.equal(h.elements.get('configuration').value,'');assert.equal(JSON.parse(h.elements.get('output').textContent).academicConfigurationCaptured,false);});
await test('Capture then real Review composes exact values with no paste or invented Semester 2 placement',async()=>{let snapshot=fixture(true),reviewedInput,h=harness(async()=>({sourceKey:'weld_v013',snapshot:clone(snapshot),snapshotFingerprint:'fingerprint'}),input=>(reviewedInput=clone(input),Coordinator.review(input)));await h.click('capture');await h.click('review');assert.equal(JSON.parse(h.elements.get('output').textContent).readyForApply,true);assert.deepEqual(reviewedInput.scheduleSnapshot,snapshot);assert.equal(reviewedInput.currentSemesterKey,'s1');assert.equal(reviewedInput.scheduleSnapshot.sections.length,6);assert.equal(reviewedInput.scheduleSnapshot.planningPeriod,6);assert(!('students'in reviewedInput.scheduleSnapshot));assert(!('semester2Sections'in reviewedInput.scheduleSnapshot));assert(!('sourceKey'in reviewedInput.scheduleSnapshot));});
await test('Capture failure clears stale inputs and Review reports actionable missing snapshot',async()=>{let error=Object.assign(new Error('Live Schema 7 configuration is unavailable.'),{code:'LIVE_SCHEMA7_STATE_MISSING'}),h=harness(async()=>{throw error;},()=>{throw Error('review must not run');});h.elements.get('scheduleSnapshot').value='{"stale":true}';h.elements.get('configuration').value='{"stale":true}';await h.click('capture');assert.equal(h.elements.get('scheduleSnapshot').value,'');assert.equal(h.elements.get('configuration').value,'');assert.equal(JSON.parse(h.elements.get('output').textContent).code,'LIVE_SCHEMA7_STATE_MISSING');await h.click('review');let output=JSON.parse(h.elements.get('output').textContent);assert.equal(output.code,'SCHEDULE_SNAPSHOT_REQUIRED');assert(!/Unexpected end of JSON input/.test(output.message));});
if(!process.exitCode)console.log(`\n${passed}/${total} PACR Capture-to-Review page composition tests passed.`);
})();
