const assert=require('assert'),fs=require('fs'),Adapter=require('../src/arc_curriculum_pacing_authority_adapter');
let pass=0,total=0;async function test(name,fn){total++;try{await fn();pass++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1}}
(async()=>{
await test('exclusive adapter rejects production and unapproved authority states',()=>{assert.throws(()=>Adapter.create({authorityState:'V8_AUTHORITATIVE'}),e=>e.code==='AUTHORITY_STATE_BLOCKED');assert.throws(()=>Adapter.create({authorityState:Adapter.states.V8_ISOLATED_VERIFICATION,databaseName:'arc_classroom_v8',service:{}}),e=>e.code==='ISOLATED_AUTHORITY_REQUIRED');assert.throws(()=>Adapter.create({authorityState:Adapter.states.V8_ISOLATED_VERIFICATION,databaseName:'arc_classroom_v8_p10b_other',service:{}}),e=>e.code==='ISOLATED_AUTHORITY_REQUIRED');});
await test('V7_ONLY performs exactly one accepted legacy operation and never v8',async()=>{let count=0,a=Adapter.create({authorityState:'V7_ONLY'}),value=a.runLegacy('renderCurriculum',{course:'WT'},payload=>{count++;return payload.course;});assert.equal(value,'WT');assert.equal(count,1);await assert.rejects(a.runIsolated('getCurriculumMap',{}),e=>e.code==='V8_AUTHORITY_BLOCKED');assert.equal(a.dualWrite,false);assert.equal(a.isAuthoritativeV8,false);});
await test('isolated adapter exposes every frozen read and pacing command through one service',async()=>{let calls=[],service={};for(const name of Adapter.readInterfaces.concat(Adapter.commandInterfaces))service[name]=async payload=>(calls.push([name,payload]),{name,payload});let a=Adapter.create({authorityState:Adapter.states.V8_ISOLATED_VERIFICATION,databaseName:Adapter.isolatedDatabaseName,service});for(const name of Adapter.readInterfaces.concat(Adapter.commandInterfaces)){let result=await a.runIsolated(name,{fixture:true});assert.equal(result.name,name);}assert.deepEqual(calls.map(x=>x[0]),Adapter.readInterfaces.concat(Adapter.commandInterfaces));assert.equal(a.databaseName,'arc_classroom_v8_p10b_verification');assert.equal(a.uiConnected,false);});
await test('isolated errors propagate without fallback legacy mutation',async()=>{let stale=new Error('stale');stale.code='WRITE_CONFLICT',legacy=0,a=Adapter.create({authorityState:Adapter.states.V8_ISOLATED_VERIFICATION,databaseName:Adapter.isolatedDatabaseName,service:{appendPacingCommand:async()=>{throw stale;}}});await assert.rejects(a.runIsolated('appendPacingCommand',{}),e=>e.code==='WRITE_CONFLICT');assert.equal(legacy,0);assert.throws(()=>a.runLegacy('fallback',{},()=>legacy++),e=>e.code==='LEGACY_AUTHORITY_BLOCKED');});
await test('P10B adapter adds no store UI connection publication or production access',()=>{let source=fs.readFileSync('src/arc_curriculum_pacing_authority_adapter.js','utf8'),html=fs.readFileSync('index.html','utf8'),sw=fs.readFileSync('sw.js','utf8');assert(!source.includes('createObjectStore'));assert(!source.includes("'arc_classroom_v8'"));assert(!html.includes('arc_curriculum_pacing_authority_adapter.js'));assert(!sw.includes('arc_curriculum_pacing_authority_adapter.js'));assert(source.includes('arc_classroom_v8_p10b_verification'));});
if(!process.exitCode)console.log(`\n${pass}/${total} ARC Stage 14 P10B exclusive adapter tests passed.`);
})();
