const assert=require('assert'),fs=require('fs'),crypto=require('crypto').webcrypto;
const Storage=require('../src/arc_v8_storage'),Backup=require('../src/arc_v8_backup_recovery'),PU1=require('../src/arc_v8_protected_production_upgrade'),Physical=require('../src/arc_v8_protected_production_upgrade_physical');
const DB='arc_classroom_v8',COMMIT='a'.repeat(40),TREE='b'.repeat(40),ROLLBACK='rollback/pre-pu2-physical';
const clone=x=>x===undefined?undefined:structuredClone(x),canonical=x=>x===null||typeof x!=='object'?JSON.stringify(x):Array.isArray(x)?'['+x.map(canonical).join(',')+']':'{'+Object.keys(x).sort().filter(k=>x[k]!==undefined).map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}';
function rows(){const stores=Object.fromEntries(PU1.HISTORICAL_STORES.map(name=>[name,[]])),at='2026-10-03T00:00:00.000Z',common={createdAt:at,createdBy:'stage14-instructor-production-initialization',startingCommit:'52b7d1b3ed920c0e889e211e41ea34b6e0395bbd',startingTree:'521e44fa1254e3f70b47b91d99d5749f7dabdcc0',rollbackRef:'rollback/pre-stage-14-stage-2-production-v8-initialization'};
  stores.metadata=[{key:'database',schemaFamily:'arc-classroom',schemaVersion:8,indexedDbVersion:10,initializationState:'ready'}];
  stores.migration_log=Array.from({length:10},(_,i)=>({id:`indexeddb-${i}-to-${i+1}`,schemaVersion:8,fromIndexedDbVersion:i,toIndexedDbVersion:i+1,status:'succeeded',startedAt:at,completedAt:at}));
  stores.infrastructure_records=[Object.assign({id:'production-v8-initialization-manifest',status:'complete',databaseName:DB,schemaFamily:'arc-classroom',schemaVersion:8,indexedDbVersion:10,expectedStoreCount:53,expectedStores:PU1.HISTORICAL_STORES.slice(),authorityState:'V7_ONLY',classroomAuthorityTransferred:false,realStudentDataAuthorized:false,contentImported:false},common),Object.assign({id:'production-v8-reconciliation-manifest',status:'complete',importedRecordCount:0,excludedIdentityCount:0,excludedDataClasses:['engineering','simulation','pilot','test','fictional-transactional'],reusableAuthorityImported:false,classroomTransactionsImported:false},common),Object.assign({id:'database-protection',mode:'Production/Classroom Protected',protectedBy:'stage14-instructor-production-initialization'},common)];return stores;}
function inspection(stores=rows()){return{exists:true,databaseName:DB,indexedDbVersion:10,storeNames:PU1.HISTORICAL_STORES.slice(),counts:Object.fromEntries(PU1.HISTORICAL_STORES.map(name=>[name,stores[name].length])),metadata:clone(stores.metadata[0]),infrastructure:clone(stores.infrastructure_records),knownDatabases:[DB,'arc_classroom_v8_engineering_verification']};}
function fakeIndexedDB(stores,onOpen){
  return{open(name){
    assert.equal(name,DB);if(onOpen)onOpen();const req={};
    setTimeout(()=>{
      let pending=0;
      const db={version:10,objectStoreNames:PU1.HISTORICAL_STORES.slice(),close(){},transaction(names,mode){
        assert.equal(mode,'readonly');
        const tx={objectStore(store){return{getAll(){
          pending++;const q={};
          setTimeout(()=>{q.result=clone(stores[store]);q.onsuccess&&q.onsuccess();pending--;if(!pending)setTimeout(()=>tx.oncomplete&&tx.oncomplete(),0);},0);
          return q;
        }}}};
        return tx;
      }};
      req.result=db;req.onsuccess&&req.onsuccess();
    },0);
    return req;
  }};
}
function environment(options={}){const stores=rows();let report=inspection(stores),opened=0,calls=0;const postBackup={text:'{"verified":"post"}',fileChecksum:'post-file',packageChecksum:'post-package',totalRecordCount:17,verification:{verified:true}};const post={schemaVersion:8,indexedDbVersion:14,storeCount:74,newStores:PU1.NEW_STORES.slice(),newStoresEmpty:true,historicalDomainPreserved:true,infrastructurePreserved:true,migrationPrefixCount:10,migrations:clone(PU1.MIGRATION_STEPS),metadata:{key:'database',schemaFamily:'arc-classroom',schemaVersion:8,indexedDbVersion:14,initializationState:'ready'},counts:Object.fromEntries(Backup.EXPECTED_STORES.map(name=>[name,0])),audit:{healthy:true,status:'Verified Healthy'},protectedResetRefused:true};post.counts.metadata=1;post.counts.migration_log=14;post.counts.infrastructure_records=3;
  const api=Physical.create({crypto,indexedDB:fakeIndexedDB(stores,()=>opened++),inspector:{inspect:async()=>clone(report)},expectedPublicationCommit:COMMIT,expectedPublicationTree:TREE,build:{version:'0.18',build:'pu2-test'},now:()=> '2026-10-03T00:00:00.000Z',upgradeFactory:()=>({executeUpgrade:async input=>{calls++;await PU1.create({crypto}).verifyHistoricalBackup(input.historicalBackup);return{authorityState:'V7_ONLY',classroomAuthorityTransferred:false,realStudentDataAuthorized:false,postUpgrade:clone(post),postUpgradeBackup:clone(postBackup)};}})});return{api,stores,get opened(){return opened},get calls(){return calls},setReport:value=>{report=value},post};}
async function captured(e){return e.api.captureHistoricalBackup();}
function authority(extra={}){return Object.assign({confirmedBy:'instructor',startingCommit:COMMIT,startingTree:TREE,rollbackRef:ROLLBACK,confirmation:Physical.CONFIRMATION},extra);}
let pass=0,total=0;async function test(name,fn){total++;try{await fn();pass++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1;}}
(async()=>{
await test('module load is explicit and opens no database',async()=>{let opens=0;Physical.create({crypto,indexedDB:fakeIndexedDB(rows(),()=>opens++),inspector:{inspect:async()=>inspection()},expectedPublicationCommit:COMMIT,expectedPublicationTree:TREE});assert.equal(opens,0)});
await test('wrong production identity is refused',async()=>{assert.throws(()=>Physical.create({crypto,databaseName:'alternate'}),x=>x.code==='PRODUCTION_IDENTITY_REQUIRED')});
await test('unversioned inspection mismatch refuses before database open',async()=>{let e=environment(),bad=inspection();bad.indexedDbVersion=11;e.setReport(bad);await assert.rejects(e.api.captureHistoricalBackup(),x=>x.code==='PREUPGRADE_INSPECTION_MISMATCH');assert.equal(e.opened,0)});
await test('unexpected browser database identity refuses',async()=>{let e=environment(),bad=inspection();bad.knownDatabases.push('arc_classroom_v8_stage2_verification');e.setReport(bad);await assert.rejects(e.api.inspectProtectedProduction(),x=>x.code==='UNEXPECTED_PROFILE_DATABASE')});
await test('historical snapshot builds and verifies exact 53-store package',async()=>{let e=environment(),b=await captured(e),verified=await PU1.create({crypto}).verifyHistoricalBackup(b.text);assert(b.verified);assert.equal(b.storeCount,53);assert.equal(b.recordCount,14);assert.equal(verified.packageChecksum,b.packageChecksum);assert.equal(e.opened,1)});
await test('loaded backup tampering is refused by accepted PU1 verifier',async()=>{let e=environment(),b=await captured(e),pkg=JSON.parse(b.text);pkg.stores.metadata[0].indexedDbVersion=9;await assert.rejects(e.api.loadHistoricalBackup(JSON.stringify(pkg)),x=>x.code==='STORE_CHECKSUM_MISMATCH')});
await test('live inspection and verified backup mismatch refuses upgrade',async()=>{let e=environment();await captured(e);let bad=inspection();bad.metadata.build={changed:true};e.setReport(bad);await assert.rejects(e.api.upgradeProtectedProduction(authority()),x=>x.code==='LIVE_BACKUP_MISMATCH');assert.equal(e.calls,0)});
await test('operator commit tree rollback and exact confirmation are required',async()=>{for(const change of [{confirmedBy:''},{startingCommit:''},{startingTree:''},{rollbackRef:''},{confirmation:'wrong'}]){let e=environment();await captured(e);await assert.rejects(e.api.upgradeProtectedProduction(authority(change)),x=>['AUTHORIZATION_REQUIRED','EXPLICIT_CONFIRMATION_REQUIRED'].includes(x.code));assert.equal(e.calls,0)}});
await test('entered publication identity must equal page identity',async()=>{let e=environment();await captured(e);await assert.rejects(e.api.upgradeProtectedProduction(authority({startingCommit:'c'})),x=>x.code==='PUBLICATION_IDENTITY_MISMATCH');assert.equal(e.calls,0)});
await test('accepted PU1 coordinator performs the only upgrade and retains boundaries',async()=>{let e=environment();await captured(e);let result=await e.api.upgradeProtectedProduction(authority());assert.equal(e.calls,1);assert(result.upgraded);assert.equal(result.postUpgrade.storeCount,74);assert(result.postUpgrade.newStoresEmpty);assert.equal(result.authorityState,'V7_ONLY');assert.equal(result.instructionalContentImported,false);assert.equal(result.postUpgradeBackup.verified,true)});
await test('post-upgrade exact 14/74 read-only verification and backup pass',async()=>{let e=environment();await captured(e);await e.api.upgradeProtectedProduction(authority());let current={exists:true,databaseName:DB,indexedDbVersion:14,storeNames:Backup.EXPECTED_STORES.slice(),counts:clone(e.post.counts),knownDatabases:[DB,'arc_classroom_v8_engineering_verification']};e.setReport(current);let verified=await e.api.verifyUpgradedProduction();assert.equal(verified.storeCount,74);assert(verified.newStoresEmpty);assert.equal(verified.integrityStatus,'Verified Healthy');assert(verified.protectedResetRefused);assert.equal(verified.postUpgradeBackup.packageChecksum,'post-package')});
await test('post-upgrade nonempty new store refuses',async()=>{let e=environment();await captured(e);await e.api.upgradeProtectedProduction(authority());let current={exists:true,databaseName:DB,indexedDbVersion:14,storeNames:Backup.EXPECTED_STORES.slice(),counts:clone(e.post.counts)};current.counts.behavior_events=1;e.setReport(current);await assert.rejects(e.api.verifyUpgradedProduction(),x=>x.code==='NEW_STORE_NOT_EMPTY')});
await test('source contains no content import package event delete or reset success path',async()=>{let source=fs.readFileSync('src/arc_v8_protected_production_upgrade_physical.js','utf8');assert(!/importPackage|appendPackage|PACKAGE_AVAILABLE|deleteDatabase|resetDevelopmentDatabase/.test(source));assert(source.includes('ProtectedUpgrade.create'));assert(source.includes('executeUpgrade'))});
await test('existing engineering page is the only wired surface and normal ARC remains unwired',async()=>{let page=fs.readFileSync('engineering/arc_v8_stage2_verification.html','utf8'),index=fs.readFileSync('index.html','utf8');assert(page.includes('arc_v8_protected_production_upgrade_physical.js?v=p10d-pu2-protected-upgrade-bridge-1'));assert(page.includes('UPGRADE PROTECTED PRODUCTION TO IDB14'));assert(!index.includes('arc_v8_protected_production_upgrade_physical'))});
await test('cache and Pages contracts carry the exact PU2 runtime marker',async()=>{let sw=fs.readFileSync('sw.js','utf8'),workflow=fs.readFileSync('.github/workflows/pages-live-verification.yml','utf8');for(const value of ['src/arc_v8_protected_production_upgrade.js','src/arc_v8_protected_production_upgrade_physical.js','p10d-pu2-protected-upgrade-bridge-1']){assert(sw.includes(value),value);assert(workflow.includes(value),value)}});
if(!process.exitCode)console.log(`\n${pass}/${total} ARC P10D-PU2 protected physical upgrade bridge tests passed.`);
})();
