const assert=require('assert'),fs=require('fs'),LessonAdapter=require('../src/arc_lesson_authority_adapter'),PacingAdapter=require('../src/arc_curriculum_pacing_authority_adapter'),UI=require('../src/arc_lesson_pacing_ui');
let pass=0,total=0;async function test(name,fn){total++;try{await fn();pass++;console.log('PASS',name)}catch(error){console.error('FAIL',name,error);process.exitCode=1}}
function fixture(){
  const lessons=[
    {lessonId:'wt-1',lessonVersionId:'wt-1-v2',lessonCode:'1',title:'WT One',courseId:'wt',reusableKind:'numbered',lifecycle:'active'},
    {lessonId:'wt-2',lessonVersionId:'wt-2-v1',lessonCode:'2',title:'WT Two',courseId:'wt',reusableKind:'numbered',lifecycle:'active'},
    {lessonId:'wt-r',lessonVersionId:'wt-r-v1',lessonCode:'R-A',title:'WT Reusable',courseId:'wt',reusableKind:'reusable',lifecycle:'active'},
    {lessonId:'awt-1',lessonVersionId:'awt-1-v1',lessonCode:'1',title:'AWT One',courseId:'awt',reusableKind:'numbered',lifecycle:'active'}
  ];
  let plan={sectionPacingPlanId:'plan',sectionId:'section',courseId:'wt',semesterId:'sem1',revision:4,lastSequence:3},items=[{pacingItemId:'done',lessonPlanVersionId:'old-v1',status:'completed',order:0},{pacingItemId:'open',lessonPlanVersionId:'older-v1',status:'planned',order:1}],commits=0,ids=0;
  const lessonService={
    async getCourseLessons(q){return lessons.filter(x=>x.courseId===q.courseId&&(!q.reusableKind||x.reusableKind===q.reusableKind)&&(!q.search||x.title.toLowerCase().includes(q.search.toLowerCase()))).map(x=>({definition:x,currentVersion:x}))},
    async getLessonPlanbookProjection(q){let x=lessons.find(y=>y.lessonVersionId===q.lessonVersionId);return{title:x.title,learningTargets:['I am learning to weld.'],successCriteria:['I can weld.'],engagementStrategies:['demo'],assessment:'check',relationships:{standards:[{standardVersionId:'s-v1'}],competencies:[{competencyVersionId:'c-v1'}],curriculum:[{curriculumMapItemId:'map-item'}],activities:[{activityVersionId:'a-v1'}]}}},
    async getAutoBuildEligibleLessons(q){return lessons.filter(x=>x.courseId===q.courseId&&x.reusableKind==='numbered')},
    async getLessonVersion(q){return lessons.find(x=>x.lessonVersionId===q.lessonVersionId)},async getLessonDefinition(q){return lessons.find(x=>x.lessonId===q.lessonId)}
  };
  const hash=x=>'fingerprint-'+x.commands.map(c=>c.eventType+':'+c.pacingItemId).join('|');
  const pacingService={
    async getSectionPacing(q){if(q.semesterId==='sem2')return{configured:false,reason:'unknown/not configured'};return{configured:true,plan:{...plan},current:{anchorDate:'2026-09-01',includeOpenShop:false,items:structuredClone(items)}}},
    async previewPacingBatch(q){if(q.expectedRevision!==plan.revision||q.expectedSequence!==plan.lastSequence)throw Object.assign(Error('stale'),{code:'WRITE_CONFLICT'});let after=structuredClone(items);for(const c of q.commands){if(c.eventType==='ITEM_REMOVED')after=after.filter(x=>x.pacingItemId!==c.pacingItemId);else after.push({pacingItemId:c.pacingItemId,lessonPlanVersionId:c.lessonPlanVersionId,status:'planned',...c.payload});}return{write:false,atomic:true,before:{plan:{...plan},current:{items:structuredClone(items)}},after:{plan:{...plan},current:{items:after}},previewFingerprint:hash(q)}},
    async appendPacingBatch(q){let preview=await this.previewPacingBatch(q);if(q.previewFingerprint!==preview.previewFingerprint)throw Object.assign(Error('changed'),{code:'PREVIEW_CHANGED'});items=preview.after.current.items;plan.revision+=q.commands.length;plan.lastSequence+=q.commands.length;commits++;return{atomic:true,events:q.commands,projection:{plan:{...plan},current:{items:structuredClone(items)}},previewFingerprint:q.previewFingerprint}}
  };
  let lessonAdapter=LessonAdapter.create({authorityState:'V8_ISOLATED_VERIFICATION',databaseName:'arc_classroom_v8_p10c_verification',service:lessonService}),pacingAdapter=PacingAdapter.create({authorityState:'V8_ISOLATED_VERIFICATION',databaseName:'arc_classroom_v8_p10b_verification',service:pacingService}),ui=UI.create({lessonAdapter,pacingAdapter,idFactory:()=>`new-${++ids}`,calendarProjection:{preview:async q=>({source:'P2-calendar-projection',count:q.items.length})}});
  return{ui,lessonAdapter,pacingAdapter,lessonService,pacingService,get commits(){return commits},get items(){return items},plan};
}
(async()=>{
await test('Lesson Bank preserves WT/AWT filtering search display and normalized details',async()=>{let f=fixture(),wt=await f.ui.lessonBank({courseId:'wt',filter:'numbered'}),awt=await f.ui.lessonBank({courseId:'awt'}),search=await f.ui.lessonBank({courseId:'wt',search:'Reusable'});assert.equal(wt.total,2);assert.equal(awt.cards[0].title,'AWT One');assert.equal(search.total,1);assert.equal(wt.cards[0].standards[0].standardVersionId,'s-v1');assert.equal(wt.cards[0].learningTargets[0],'I am learning to weld.');});
await test('individual scheduling previews then atomically commits exact active Lesson version',async()=>{let f=fixture(),preview=await f.ui.previewScheduleLesson({courseId:'wt',sectionId:'section',semesterId:'sem1',lessonVersionId:'wt-1-v2',periods:3});assert.equal(preview.write,false);assert.equal(preview.request.commands[0].lessonPlanVersionId,'wt-1-v2');assert.equal(preview.forecast.source,'P2-calendar-projection');assert.equal(f.commits,0);let result=await f.ui.commitScheduleLesson(preview);assert(result.atomic);assert.equal(f.commits,1);assert.equal(f.items.at(-1).plannedDuration,3);});
await test('Auto Build range preserves completed items replaces unfinished and stores no competing truth',async()=>{let f=fixture(),preview=await f.ui.previewAutoBuild({courseId:'wt',sectionId:'section',semesterId:'sem1',startLesson:1,endLesson:2,durationModel:'uniform',fallbackPeriods:2,replaceUnfinished:true});assert.deepEqual(preview.completedProtected,['done']);assert.deepEqual(preview.removed,['open']);assert.equal(preview.added.length,2);assert.equal(f.commits,0);await f.ui.commitAutoBuild(preview);assert(f.items.some(x=>x.pacingItemId==='done'));assert(!f.items.some(x=>x.pacingItemId==='open'));assert.deepEqual(f.items.filter(x=>x.lessonPlanVersionId&&x.lessonPlanVersionId.startsWith('wt-')).map(x=>x.lessonPlanVersionId),['wt-1-v2','wt-2-v1']);assert.equal(f.ui.persistedAutoBuildTruth,false);});
await test('historical latest conservative and fallback duration choices are deterministic',async()=>{let history=[{lessonId:'wt-1',academicYear:'2024',periods:2},{lessonId:'wt-1',academicYear:'2025',periods:5},{lessonId:'wt-2',academicYear:'2024',periods:4}],f=fixture(),latest=await f.ui.previewAutoBuild({courseId:'wt',sectionId:'section',semesterId:'sem1',startLesson:1,endLesson:2,durationModel:'latest',fallbackPeriods:7,historyObservations:history}),choices=Object.fromEntries(latest.durationEvidence.map(x=>[x.lessonVersionId,x.choice]));assert.equal(choices['wt-1-v2'].periods,5);assert.equal(choices['wt-2-v1'].periods,4);let g=fixture(),conservative=await g.ui.previewAutoBuild({courseId:'wt',sectionId:'section',semesterId:'sem1',startLesson:1,endLesson:1,durationModel:'conservative',fallbackPeriods:7,historyObservations:[{lessonId:'wt-1',periods:2},{lessonId:'wt-1',periods:3}]});assert.equal(conservative.added[0].plannedDuration,3);});
await test('stale preview is refused and causes no partial pacing write',async()=>{let f=fixture(),preview=await f.ui.previewAutoBuild({courseId:'wt',sectionId:'section',semesterId:'sem1',startLesson:1,endLesson:1,durationModel:'uniform',fallbackPeriods:1});f.plan.revision++;await assert.rejects(f.ui.commitAutoBuild(preview),e=>e.code==='WRITE_CONFLICT');assert.equal(f.commits,0);assert.equal(f.items.length,2);});
await test('unknown future Semester remains absent and cross-course scheduling is refused',async()=>{let f=fixture();await assert.rejects(f.ui.previewAutoBuild({courseId:'wt',sectionId:'section',semesterId:'sem2',startLesson:1,endLesson:2}),e=>e.code==='PACING_NOT_CONFIGURED');await assert.rejects(f.ui.previewScheduleLesson({courseId:'wt',sectionId:'section',semesterId:'sem1',lessonVersionId:'awt-1-v1'}),e=>e.code==='LESSON_SCOPE_MISMATCH');assert.equal(f.commits,0);});
await test('production databases are rejected and V7 normal UI remains one legacy path',async()=>{assert.throws(()=>LessonAdapter.create({authorityState:'V8_ISOLATED_VERIFICATION',databaseName:'arc_classroom_v8',service:{}}),e=>e.code==='ISOLATED_AUTHORITY_REQUIRED');let calls=0,adapter=LessonAdapter.create({authorityState:'V7_ONLY'}),value=adapter.runLegacy('renderLessonBank',{},()=>++calls);assert.equal(value,1);assert.equal(calls,1);assert.equal(adapter.dualWrite,false);});
await test('normal ARC preserves accepted Lesson Bank and Auto Build actions through P10C adapter and caches modules',()=>{let html=fs.readFileSync('index.html','utf8'),sw=fs.readFileSync('sw.js','utf8'),build=fs.readFileSync('app-build.js','utf8');for(const name of ['renderLessonBank','filterLessonBank','scheduleLessonFromBank','confirmScheduleLesson','showAutoBuildPacing','updateHistoricalBuildPreview','confirmAutoBuildPacing'])assert(html.includes(name),name);assert(html.includes('ArcLessonAuthorityAdapter.create({ authorityState: "V7_ONLY" })'));for(const asset of ['arc_v8_lesson_plans.js','arc_lesson_authority_adapter.js','arc_lesson_pacing_ui.js'])assert(html.includes(asset)&&sw.includes(asset),asset);assert(build.includes('parity-p10c-ui-1'));});
if(!process.exitCode)console.log(`\n${pass}/${total} ARC P10C-UI Lesson Bank/Auto Build tests passed.`);
})();
