const assert=require('assert');
const {webcrypto}=require('crypto');
const Storage=require('../src/arc_v8_storage');
const Backup=require('../src/arc_v8_backup_recovery');
const PU1=require('../src/arc_v8_protected_production_upgrade');
const DB=PU1.DATABASE_NAME;
function clone(x){return x===undefined?undefined:structuredClone(x)}
function canonical(x){if(x===null||typeof x!=='object')return JSON.stringify(x);if(Array.isArray(x))return'['+x.map(canonical).join(',')+']';return'{'+Object.keys(x).sort().filter(k=>x[k]!==undefined).map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}'}
async function sha(v){const d=await webcrypto.subtle.digest('SHA-256',typeof v==='string'?new TextEncoder().encode(v):v);return Buffer.from(d).toString('hex')}
const keys={metadata:'key',migration_log:'id',infrastructure_records:'id',students:'studentId',courses:'courseId',school_years:'schoolYearId',semesters:'semesterId',grading_periods:'gradingPeriodId',sections:'sectionId',course_enrollments:'enrollmentId',enrollment_schedule_assignments:'scheduleAssignmentId',activity_definitions:'definitionId',activity_versions:'versionId',activity_evidence_declarations:'declarationId',activity_assignments:'assignmentId',student_activities:'studentActivityId',activity_attempts:'attemptId',project_instances:'projectId',project_build_attempts:'buildId',project_checkpoint_events:'eventId',project_manual_need_events:'needEventId',project_rubric_assessments:'rubricAssessmentId',competency_definitions:'competencyId',competency_versions:'competencyVersionId',competency_strategy_configurations:'strategyConfigId',evidence_sources:'sourceId',evidence_records:'evidenceRecordId',instructor_overrides:'overrideId',workplace_days:'workplaceDayId',workplace_events:'workplaceEventId',positive_workplace_observations:'observationId',safety_events:'safetyEventId',workplace_week_finalizations:'weekFinalizationId',activity_assessment_finalizations:'activityAssessmentFinalizationId',assessment_results:'assessmentResultId',gradebook_policy_versions:'gradebookPolicyVersionId',gradebook_entries:'gradebookEntryId',gradebook_entry_revisions:'gradebookEntryRevisionId',gradebook_posting_instances:'postingInstanceId',gradebook_posting_memberships:'postingMembershipId',gradebook_posting_events:'postingEventId',quarter_grade_snapshots:'quarterGradeSnapshotId',attendance_records:'attendanceRecordId',pass_events:'passEventId',supplemental_shop_sessions:'supplementalSessionId',attendance_grade_decisions:'attendanceGradeDecisionId',artifacts:'artifactId',artifact_media_blobs:'mediaBlobId',artifact_links:'artifactLinkId',booth_definitions:'boothId',booth_resources:'boothResourceId',booth_assignments:'boothAssignmentId',booth_issues:'boothIssueId'};
function authority(){const common={createdAt:'2026-10-02T00:00:00.000Z',createdBy:'stage14-instructor-production-initialization',startingCommit:'52b7d1b3ed920c0e889e211e41ea34b6e0395bbd',startingTree:'521e44fa1254e3f70b47b91d99d5749f7dabdcc0',rollbackRef:'rollback/pre-stage-14-stage-2-production-v8-initialization'};return[
  {...common,id:'production-v8-initialization-manifest',type:'ProductionV8InitializationManifest',status:'complete',databaseName:DB,schemaFamily:'arc-classroom',schemaVersion:8,indexedDbVersion:10,expectedStoreCount:53,expectedStores:PU1.HISTORICAL_STORES.slice(),authorityState:'V7_ONLY',classroomAuthorityTransferred:false,realStudentDataAuthorized:false,contentImported:false},
  {...common,id:'production-v8-reconciliation-manifest',type:'ProductionV8ReconciliationManifest',status:'complete',importedRecordCount:0,excludedIdentityCount:0,excludedDataClasses:['engineering','simulation','pilot','test','fictional-transactional'],reusableAuthorityImported:false,classroomTransactionsImported:false},
  {id:'database-protection',mode:'Production/Classroom Protected',protectedAt:'2026-10-02T00:00:00.000Z',protectedBy:'stage14-instructor-production-initialization',reason:'Stage 1 protected empty production foundation',revision:1}
]}
function prefix(){return Array.from({length:10},(_,i)=>({id:`indexeddb-${i}-to-${i+1}`,fromIndexedDbVersion:i,toIndexedDbVersion:i+1,status:'succeeded',startedAt:'2026-10-02T00:00:00.000Z',completedAt:'2026-10-02T00:00:00.000Z',schemaVersion:8,storesAdded:[]}))}
async function historical(){const stores={};for(const s of PU1.HISTORICAL_STORES)stores[s]=[];stores.metadata=[{key:'database',schemaFamily:'arc-classroom',schemaVersion:8,indexedDbVersion:10,initializationState:'ready',createdAt:'2026-10-02T00:00:00.000Z'}];stores.migration_log=prefix();stores.infrastructure_records=authority();const manifestStores={};for(const s of PU1.HISTORICAL_STORES)manifestStores[s]={recordCount:stores[s].length,checksumAlgorithm:'SHA-256',checksum:await sha(canonical(stores[s]))};const pkg={manifest:{format:'arc-v8-portable-backup',formatVersion:1,schemaFamily:'arc-classroom',schemaVersion:8,indexedDbVersion:10,databaseName:DB,applicationVersion:'fixture',build:'fixture',exportedAt:'2026-10-02T00:00:00.000Z',purpose:'fixture',storeInventory:PU1.HISTORICAL_STORES.slice(),stores:manifestStores,totalRecordCount:Object.values(stores).reduce((n,x)=>n+x.length,0),media:{blobCount:0,totalBytes:0,items:[]},checksumAlgorithm:'SHA-256',audit:{status:'Verified Healthy',errorCount:0,warningCount:0,issues:[]},packageIntegrity:{algorithm:'SHA-256',checksum:''}},stores};pkg.manifest.packageIntegrity.checksum=await sha(canonical(pkg));return{pkg,text:canonical(pkg)}}
function inspection(h){return{exists:true,databaseName:DB,indexedDbVersion:10,storeNames:PU1.HISTORICAL_STORES.slice(),counts:Object.fromEntries(PU1.HISTORICAL_STORES.map(s=>[s,h.pkg.stores[s].length])),metadata:clone(h.pkg.stores.metadata[0]),infrastructure:clone(h.pkg.stores.infrastructure_records),knownDatabases:[DB]}}
function currentRows(h){const rows={};for(const s of Backup.EXPECTED_STORES)rows[s]=clone(h.pkg.stores[s]||[]);rows.metadata[0]={...rows.metadata[0],indexedDbVersion:14,lastSuccessfulUpgrade:{fromIndexedDbVersion:13,toIndexedDbVersion:14,at:'2026-10-03T00:00:00.000Z'}};rows.migration_log.push(...PU1.MIGRATION_STEPS.map(x=>({...clone(x),status:'succeeded',startedAt:'2026-10-03T00:00:00.000Z',completedAt:'2026-10-03T00:00:00.000Z',schemaVersion:8})));return rows}
function fakeDb(rows){return{storeNames:Backup.EXPECTED_STORES.slice(),query:async s=>clone(rows[s]),read:async(s,id)=>clone((rows[s]||[]).find(x=>x[keys[s]]===id)),close(){}}}
function fixture(h,mutate){let opened=0,rows=currentRows(h);if(mutate)mutate(rows);const db=fakeDb(rows),controller={constants:{databaseName:DB,indexedDbVersion:14},open:async()=>{opened++;return db},resetDevelopmentDatabase:async()=>{throw new Storage.StorageError('PROTECTED_DATABASE','protected')}},backup={auditDatabase:async()=>({healthy:true,status:'Verified Healthy',errorCount:0,warningCount:0,issues:[],storeCount:74}),exportBackup:async()=>({text:'current-backup',package:{manifest:{indexedDbVersion:14,storeInventory:Backup.EXPECTED_STORES.slice()}},verification:{verified:true}}),verifyPackage:async()=>({verified:true,checksum:'current-package-sha',recordCount:18})};return{opened:()=>opened,api:PU1.create({crypto:webcrypto,inspector:{inspect:async()=>inspection(h)},storageFactory:()=>controller,backupFactory:()=>backup})}}
let pass=0,total=0;async function test(name,fn){total++;try{await fn();pass++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1}}
(async()=>{
await test('module load is explicit and has no IndexedDB side effect',async()=>{assert.equal(typeof PU1.create,'function');assert.equal(PU1.HISTORICAL_STORES.length,53);assert.equal(PU1.NEW_STORES.length,21)});
await test('alternate production database identity is refused',async()=>{assert.throws(()=>PU1.create({databaseName:'other',crypto:webcrypto}),e=>e.code==='PRODUCTION_IDENTITY_REQUIRED')});
await test('malformed historical backup refuses before storage open',async()=>{let opened=0,api=PU1.create({crypto:webcrypto,inspector:{inspect:async()=>{throw Error('must not inspect')}},storageFactory:()=>{opened++;throw Error('must not open')}});await assert.rejects(api.executeUpgrade({historicalBackup:'{'}),e=>e.code==='MALFORMED_PACKAGE');assert.equal(opened,0)});
await test('exact historical 53-store backup verifies',async()=>{const h=await historical(),v=await PU1.create({crypto:webcrypto}).verifyHistoricalBackup(h.text);assert.equal(v.storeCount,53);assert.equal(v.metadata.indexedDbVersion,10);assert.equal(v.manifests.protection.mode,'Production/Classroom Protected')});
await test('wrong format schema version database and store inventory refuse',async()=>{for(const change of [p=>p.manifest.format='bad',p=>p.manifest.schemaVersion=7,p=>p.manifest.indexedDbVersion=11,p=>p.manifest.databaseName='other',p=>{delete p.stores.courses;p.manifest.storeInventory=p.manifest.storeInventory.filter(x=>x!=='courses')}]){const h=await historical(),p=clone(h.pkg);change(p);await assert.rejects(PU1.create({crypto:webcrypto}).verifyHistoricalBackup(p))}});
await test('historical store checksum count identity and package tampering refuse',async()=>{for(const change of [p=>p.manifest.stores.students.checksum='0'.repeat(64),p=>p.manifest.stores.students.recordCount=1,p=>p.stores.students.push({studentId:'x'},{studentId:'x'}),p=>p.manifest.packageIntegrity.checksum='1'.repeat(64)]){const h=await historical(),p=clone(h.pkg);change(p);await assert.rejects(PU1.create({crypto:webcrypto}).verifyHistoricalBackup(p))}});
await test('wrong initialization reconciliation or protection authority refuses',async()=>{for(const change of [p=>p.stores.infrastructure_records[0].authorityState='V8_AUTHORITATIVE',p=>p.stores.infrastructure_records[1].importedRecordCount=1,p=>p.stores.infrastructure_records[2].mode='Development']){const h=await historical(),p=clone(h.pkg);change(p);await assert.rejects(PU1.create({crypto:webcrypto}).verifyHistoricalBackup(p))}});
await test('nonempty historical domain store refuses',async()=>{const h=await historical(),p=clone(h.pkg);p.stores.students=[{studentId:'forbidden'}];p.manifest.stores.students.recordCount=1;p.manifest.stores.students.checksum=await sha(canonical(p.stores.students));p.manifest.packageIntegrity.checksum='';p.manifest.packageIntegrity.checksum=await sha(canonical(p));await assert.rejects(PU1.create({crypto:webcrypto}).verifyHistoricalBackup(p),e=>e.code==='HISTORICAL_DOMAIN_NOT_EMPTY')});
await test('pre-upgrade inspection mismatch refuses before current storage open',async()=>{const h=await historical();let opened=0,report=inspection(h);report.indexedDbVersion=11;const api=PU1.create({crypto:webcrypto,inspector:{inspect:async()=>report},storageFactory:()=>{opened++;throw Error('opened')}});await assert.rejects(api.executeUpgrade({historicalBackup:h.text}),e=>e.code==='PREUPGRADE_INSPECTION_MISMATCH');assert.equal(opened,0)});
await test('pre-upgrade metadata and protection bytes must match backup',async()=>{const h=await historical();let report=inspection(h);report.infrastructure[2].revision=2;await assert.rejects(PU1.create({crypto:webcrypto,inspector:{inspect:async()=>report}}).inspectPreUpgrade(await PU1.create({crypto:webcrypto}).verifyHistoricalBackup(h.text)),e=>e.code==='PREUPGRADE_INSPECTION_MISMATCH')});
await test('task-owned profile refuses unexpected database identities',async()=>{const h=await historical(),report=inspection(h);report.knownDatabases.push('unrelated_database');await assert.rejects(PU1.create({crypto:webcrypto,inspector:{inspect:async()=>report}}).inspectPreUpgrade(await PU1.create({crypto:webcrypto}).verifyHistoricalBackup(h.text)),e=>e.code==='UNEXPECTED_PROFILE_DATABASE')});
await test('exact 10 to 14 upgrade validates four ordered migrations and 74 stores',async()=>{const h=await historical(),f=fixture(h),r=await f.api.executeUpgrade({historicalBackup:h.text});assert.equal(f.opened(),1);assert.equal(r.postUpgrade.storeCount,74);assert.deepEqual(r.postUpgrade.migrations.map(x=>x.id),PU1.MIGRATION_STEPS.map(x=>x.id));assert(r.postUpgrade.newStoresEmpty&&r.postUpgrade.historicalDomainPreserved&&r.postUpgrade.infrastructurePreserved)});
await test('missing or malformed migration step refuses',async()=>{for(const mutate of [r=>r.migration_log.pop(),r=>r.migration_log[10].status='failed']){const h=await historical(),f=fixture(h,mutate);await assert.rejects(f.api.executeUpgrade({historicalBackup:h.text}),e=>e.code==='MIGRATION_SEQUENCE_MISMATCH')}});
await test('all 21 new stores must remain empty',async()=>{const h=await historical(),f=fixture(h,r=>r.behavior_events.push({behaviorEventId:'x'}));await assert.rejects(f.api.executeUpgrade({historicalBackup:h.text}),e=>e.code==='NEW_STORE_NOT_EMPTY')});
await test('historical domain and infrastructure changes refuse',async()=>{for(const mutate of [r=>r.students.push({studentId:'x'}),r=>r.infrastructure_records[2].revision=2]){const h=await historical(),f=fixture(h,mutate);await assert.rejects(f.api.executeUpgrade({historicalBackup:h.text}),e=>['HISTORICAL_DOMAIN_CHANGED','PROTECTION_MANIFEST_CHANGED'].includes(e.code))}});
await test('post-upgrade current backup and protected reset are required',async()=>{const h=await historical();let f=fixture(h);f.api=PU1.create({crypto:webcrypto,inspector:{inspect:async()=>inspection(h)},storageFactory:()=>({constants:{indexedDbVersion:14},open:async()=>fakeDb(currentRows(h)),resetDevelopmentDatabase:async()=>{}}),backupFactory:()=>({auditDatabase:async()=>({healthy:true}),exportBackup:async()=>({text:'x',package:{manifest:{indexedDbVersion:14,storeInventory:Backup.EXPECTED_STORES}},verification:{verified:true}}),verifyPackage:async()=>({verified:true,checksum:'x',recordCount:1})})});await assert.rejects(f.api.executeUpgrade({historicalBackup:h.text}),e=>e.code==='PROTECTED_RESET_REFUSAL_FAILED')});
await test('V7_ONLY no real-data no-transfer boundaries and no import API remain frozen',async()=>{const h=await historical(),r=await fixture(h).api.executeUpgrade({historicalBackup:h.text});assert.equal(r.authorityState,'V7_ONLY');assert.equal(r.classroomAuthorityTransferred,false);assert.equal(r.realStudentDataAuthorized,false);assert.equal(typeof PU1.create({crypto:webcrypto}).importContent,'undefined');assert(!/importPackageRecord|PACKAGE_AVAILABLE|declarePackage/.test(require('fs').readFileSync('src/arc_v8_protected_production_upgrade.js','utf8')))});
if(!process.exitCode)console.log(`\n${pass}/${total} ARC P10D-PU1 protected production upgrade tests passed.`);
})();
