const assert=require('assert'),Storage=require('../src/arc_v8_storage'),Behavior=require('../src/arc_v8_behavior');
function memory(){let maps={};Object.values(Storage.STORES).forEach(s=>maps[s]=new Map());let n=1,failOnce=null,keys={students:'studentId',course_enrollments:'enrollmentId',sections:'sectionId',workplace_events:'workplaceEventId',safety_events:'safetyEventId',behavior_events:'behaviorEventId'},paths={behavior_events:{by_student:'studentId',by_enrollment:'enrollmentId',by_section:'sectionId',by_date:'schoolDate',by_category:'category',by_severity:'severity',by_workplace_event:'relatedWorkplaceEventId',by_safety_event:'relatedSafetyEventId',by_lifecycle:'lifecycle'}};const clone=x=>x===undefined?undefined:structuredClone(x),match=(v,p,k)=>JSON.stringify(v[p])===JSON.stringify(k);function api(work){return{get:async(s,k)=>clone(work[s].get(k)),add:async(s,v)=>{if(failOnce===s){failOnce=null;throw Error('forced')}let k=v[keys[s]];if(work[s].has(k))throw Error('duplicate');work[s].set(k,clone(v));},put:async(s,v)=>work[s].set(v[keys[s]],clone(v)),query:async(s,i,k)=>Array.from(work[s].values()).filter(v=>!i||k===undefined||match(v,paths[s][i],k)).map(clone)}}return{generateId:()=>`00000000-0000-4000-8000-${(n++).toString(16).padStart(12,'0')}`,read:async(s,k)=>clone(maps[s].get(k)),query:async(s,i,k)=>api(maps).query(s,i,k),async transaction(stores,fn){stores=Array.isArray(stores)?stores:[stores];let work={};Object.keys(maps).forEach(s=>work[s]=new Map(Array.from(maps[s]).map(([k,v])=>[k,clone(v)])));let out=await fn(api(work));stores.forEach(s=>maps[s]=work[s]);return out;},failOnce:s=>failOnce=s,_maps:maps};}
function fixture(){let storage=memory(),tick=0,repo=Behavior.create({storage,actor:'teacher',now:()=>`2026-09-28T12:00:${String(tick++).padStart(2,'0')}Z`}),S=Storage.STORES;storage._maps[S.students].set('s1',{studentId:'s1'});storage._maps[S.students].set('s2',{studentId:'s2'});storage._maps[S.enrollments].set('e1',{enrollmentId:'e1',studentId:'s1'});storage._maps[S.enrollments].set('e2',{enrollmentId:'e2',studentId:'s2'});storage._maps[S.sections].set('sec1',{sectionId:'sec1'});storage._maps[S.sections].set('sec2',{sectionId:'sec2'});return{storage,repo,S};}
function input(extra={}){return Object.assign({studentId:'s1',enrollmentId:'e1',sectionId:'sec1',schoolDate:'2026-09-28',occurredAt:'2026-09-28T10:00:00Z',category:'Safety',severity:'Serious',action:'Parent Contact',description:'Objective private documentation.',followUp:'Review next class'},extra);}
let pass=0,total=0;async function test(name,fn){total++;try{await fn();pass++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1}}
(async()=>{
await test('BehaviorEvent is private separate authority with no grade effect',async()=>{let f=fixture(),r=await f.repo.recordBehaviorEvent(input());assert.equal(r.privateInstructorDocumentation,true);assert.equal(r.gradeEffect,'none');assert.equal((await f.storage.query(f.S.workplaceEvents)).length,0);assert.equal((await f.storage.query(f.S.safetyEvents)).length,0);});
await test('existing instructor fields are preserved without enumerating new policy',async()=>{let f=fixture(),r=await f.repo.recordBehaviorEvent(input({category:'General Incident',severity:'Routine',action:'Redirected / Warning'}));assert.equal(r.category,'General Incident');assert.equal(r.severity,'Routine');assert.equal(r.action,'Redirected / Warning');assert.equal(r.description,'Objective private documentation.');assert.equal(r.followUp,'Review next class');});
await test('Student Enrollment and optional Section scope are validated by stable identity',async()=>{let f=fixture();await assert.rejects(f.repo.recordBehaviorEvent(input({enrollmentId:'e2'})),e=>e.code==='INTEGRITY_MISMATCH');await assert.rejects(f.repo.recordBehaviorEvent(input({sectionId:'missing'})),e=>e.code==='REFERENCE_NOT_FOUND');let a=await f.repo.recordBehaviorEvent(input()),b=await f.repo.recordBehaviorEvent(input({studentId:'s2',enrollmentId:'e2',sectionId:'sec2'}));assert.notEqual(a.studentId,b.studentId);});
await test('optional Workplace and Safety links require exact Student Enrollment lineage',async()=>{let f=fixture();f.storage._maps[f.S.workplaceEvents].set('w1',{workplaceEventId:'w1',studentId:'s1',enrollmentId:'e1'});f.storage._maps[f.S.safetyEvents].set('safe1',{safetyEventId:'safe1',studentId:'s1',enrollmentId:'e1'});let r=await f.repo.recordBehaviorEvent(input({relatedWorkplaceEventId:'w1',relatedSafetyEventId:'safe1'}));assert.equal(r.relatedWorkplaceEventId,'w1');assert.equal(r.relatedSafetyEventId,'safe1');f.storage._maps[f.S.safetyEvents].set('wrong',{safetyEventId:'wrong',studentId:'s2',enrollmentId:'e2'});await assert.rejects(f.repo.recordBehaviorEvent(input({relatedSafetyEventId:'wrong'})),e=>e.code==='INTEGRITY_MISMATCH');});
await test('correction supersession and void are append-first revision-safe and reasoned',async()=>{let f=fixture(),one=await f.repo.recordBehaviorEvent(input()),two=await f.repo.correctBehaviorEvent({supersedesBehaviorEventId:one.behaviorEventId,expectedRevision:1,reason:'Correct category',replacement:{category:'General Incident'}});assert.equal(two.event.supersedesBehaviorEventId,one.behaviorEventId);assert.equal(two.event.category,'General Incident');assert.equal(two.prior.lifecycle,'superseded');assert.equal(two.prior.revision,2);await assert.rejects(f.repo.correctBehaviorEvent({supersedesBehaviorEventId:one.behaviorEventId,expectedRevision:1,reason:'stale',replacement:{}}),e=>e.code==='WRITE_CONFLICT');let three=await f.repo.correctBehaviorEvent({supersedesBehaviorEventId:two.event.behaviorEventId,expectedRevision:1,reason:'Duplicate report',void:true,replacement:{}});assert.equal(three.prior.lifecycle,'superseded');assert.equal(three.event.lifecycle,'voided');assert.equal((await f.storage.query(f.S.behaviorEvents,'by_student','s1')).length,3);});
await test('Student and class projections are deterministic and retain full history',async()=>{let f=fixture(),one=await f.repo.recordBehaviorEvent(input()),two=await f.repo.correctBehaviorEvent({supersedesBehaviorEventId:one.behaviorEventId,expectedRevision:1,reason:'Correction',replacement:{description:'Corrected description'}}),a=await f.repo.studentProjection({studentId:'s1',enrollmentId:'e1'}),b=await Behavior.create({storage:f.storage,actor:'teacher'}).studentProjection({studentId:'s1',enrollmentId:'e1'}),c=await f.repo.classProjection({sectionId:'sec1',schoolDate:'2026-09-28'});assert.deepEqual(b,a);assert.equal(a.current.length,1);assert.equal(a.history.length,2);assert.equal(a.current[0].behaviorEventId,two.event.behaviorEventId);assert.equal(c.current.length,1);assert.equal(a.automaticGradeEffect,false);});
await test('failed write rolls back without touching linked authorities',async()=>{let f=fixture();f.storage._maps[f.S.workplaceEvents].set('w1',{workplaceEventId:'w1',studentId:'s1',enrollmentId:'e1'});f.storage.failOnce(f.S.behaviorEvents);await assert.rejects(f.repo.recordBehaviorEvent(input({relatedWorkplaceEventId:'w1'})));assert.equal((await f.storage.query(f.S.behaviorEvents)).length,0);assert.equal((await f.storage.query(f.S.workplaceEvents)).length,1);});
await test('P8 loads Behavior authority for its exclusive adapter while normal ARC stays V7_ONLY',()=>{let fs=require('fs'),sw=fs.readFileSync('sw.js','utf8'),html=fs.readFileSync('index.html','utf8'),build=fs.readFileSync('app-build.js','utf8');assert(sw.includes('./src/arc_v8_behavior.js'));assert(html.includes('src/arc_v8_behavior.js'));assert(html.includes('workplaceSafetyBehaviorAuthorityAdapter = ArcWorkplaceSafetyBehaviorAuthorityAdapter.create({ authorityState: "V7_ONLY" })'));assert(build.includes('parity-p8a-behavior-structural-foundation-1-parity-p8-workplace-safety-behavior-1-parity-p9-gradebook-authority-1'));});
if(!process.exitCode)console.log(`\n${pass}/${total} ARC v8 Behavior/Incident tests passed.`);
})();
