const assert=require('assert');
const Storage=require('../src/arc_v8_storage');

function memoryDriver(options={}){
  let database=null,opens=0,removes=0;
  function request(action){let req={};queueMicrotask(()=>{try{req.result=action();if(req.onsuccess)req.onsuccess();}catch(e){req.error=e;if(req.onerror)req.onerror();}});return req;}
  function makeDb(version){
    const stores={};
    const db={version,closed:false,onversionchange:null,
      createObjectStore(name){stores[name]=new Map();return objectStore(stores[name]);},
      transaction(names,mode){if(db.closed)throw Error('closed');names=Array.isArray(names)?names:[names];let aborted=false,finished=false,snapshots={};names.forEach(name=>snapshots[name]=new Map(Array.from(stores[name]||[]).map(([k,v])=>[k,structuredClone(v)])));let tx={error:null,oncomplete:null,onabort:null,onerror:null,objectStore(name){if(!names.includes(name)||!stores[name])throw Error('missing store');return objectStore(stores[name],tx);},abort(){aborted=true;names.forEach(name=>stores[name]=new Map(Array.from(snapshots[name]).map(([k,v])=>[k,structuredClone(v)])));finish();}};function finish(){if(finished)return;finished=true;queueMicrotask(()=>aborted?(tx.onabort&&tx.onabort()):(tx.oncomplete&&tx.oncomplete()));}queueMicrotask(()=>queueMicrotask(finish));return tx;},
      close(){db.closed=true;}
    };
    function objectStore(map,tx){return {add(value){return request(()=>{let key=value.key??value.id;if(map.has(key))throw Error('ConstraintError');map.set(key,structuredClone(value));return key;});},put(value){return request(()=>{let key=value.key??value.id;map.set(key,structuredClone(value));return key;});},get(key){return request(()=>map.has(key)?structuredClone(map.get(key)):undefined);},delete(key){return request(()=>map.delete(key));}};}
    db._stores=stores;return db;
  }
  return {open(config){opens++;if(options.openError)return Promise.reject(options.openError);if(options.blocked){config.blocked();return Promise.reject(new Storage.StorageError('UPGRADE_BLOCKED','blocked'));}if(database&&database.version>config.version)return Promise.reject(new Storage.StorageError('INCOMPATIBLE_DATABASE_VERSION','newer'));if(!database){database=makeDb(config.version);let tx={};config.upgrade(database,0,config.version,tx);}database.closed=false;return Promise.resolve(database);},remove(name,blocked){removes++;if(options.resetBlocked){blocked();return Promise.reject(new Storage.StorageError('RESET_BLOCKED','blocked'));}database=null;return Promise.resolve();},state(){return {database,opens,removes};},triggerVersionchange(next){if(database&&database.onversionchange)database.onversionchange({oldVersion:database.version,newVersion:next});}};
}

let pass=0,total=0;async function test(name,fn){total++;try{await fn();pass++;console.log('PASS',name);}catch(e){console.error('FAIL',name,e);process.exitCode=1;}}
(async()=>{
  await test('clean initialization creates isolated metadata and migration authority',async()=>{let driver=memoryDriver(),s=Storage.create({driver,now:()=>new Date('2026-09-27T12:00:00Z'),build:{version:'0.18',build:'test'}}),db=await s.open();assert.equal(s.constants.databaseName,'arc_classroom_v8');assert.equal(db.metadata.schemaVersion,8);assert.equal(db.metadata.indexedDbVersion,1);assert.equal(db.metadata.initializationState,'ready');let migration=await db.read(Storage.STORES.migrations,'indexeddb-0-to-1');assert.equal(migration.status,'succeeded');});
  await test('immutable IDs are RFC 4122 version 4 and unique',async()=>{let s=Storage.create({driver:memoryDriver()}),ids=new Set();for(let i=0;i<500;i++){let id=s.generateId();assert(s.validId(id));ids.add(id);}assert.equal(ids.size,500);});
  await test('tested secure fallback generates a valid UUID',async()=>{let n=0,c={getRandomValues(bytes){for(let i=0;i<bytes.length;i++)bytes[i]=(n++*17)&255;return bytes;}};assert(Storage.validId(Storage.generateId(c)));});
  await test('basic add read put and delete complete durably',async()=>{let s=Storage.create({driver:memoryDriver()}),db=await s.open(),store=Storage.STORES.infrastructure;await db.add(store,{id:'a',value:1});assert.equal((await db.read(store,'a')).value,1);await db.put(store,{id:'a',value:2});assert.equal((await db.read(store,'a')).value,2);await db.delete(store,'a');assert.equal(await db.read(store,'a'),undefined);});
  await test('multi-operation transaction commits',async()=>{let s=Storage.create({driver:memoryDriver()}),db=await s.open(),store=Storage.STORES.infrastructure;await db.transaction(store,async tx=>{await tx.add(store,{id:'a'});await tx.add(store,{id:'b'});});assert((await db.read(store,'a'))&&(await db.read(store,'b')));});
  await test('explicit abort propagates failure and rolls back earlier writes',async()=>{let s=Storage.create({driver:memoryDriver()}),db=await s.open(),store=Storage.STORES.infrastructure;await assert.rejects(db.transaction(store,async tx=>{await tx.add(store,{id:'rolled-back'});tx.abort('stop');}),e=>e.code==='TRANSACTION_ABORTED');assert.equal(await db.read(store,'rolled-back'),undefined);});
  await test('failed duplicate add propagates',async()=>{let s=Storage.create({driver:memoryDriver()}),db=await s.open(),store=Storage.STORES.infrastructure;await db.add(store,{id:'a'});await assert.rejects(db.add(store,{id:'a'}),e=>e.code==='REQUEST_FAILED');});
  await test('optimistic revision writes reject stale tab state',async()=>{let s=Storage.create({driver:memoryDriver()}),db=await s.open(),store=Storage.STORES.infrastructure;let saved=await db.putIfRevision(store,{id:'a',value:1},0);assert.equal(saved.revision,1);await assert.rejects(db.putIfRevision(store,{id:'a',value:2},0),e=>e.code==='WRITE_CONFLICT');assert.equal((await db.read(store,'a')).value,1);});
  await test('reopen preserves data and read does not mutate it',async()=>{let driver=memoryDriver(),s=Storage.create({driver}),db=await s.open(),store=Storage.STORES.infrastructure;await db.add(store,{id:'a',nested:{value:1}});let before=JSON.stringify(await db.read(store,'a'));db.close();db=await s.open();assert.equal(JSON.stringify(await db.read(store,'a')),before);});
  await test('ordered initialization upgrade is deterministic',async()=>{let driver=memoryDriver(),s=Storage.create({driver}),db=await s.open();assert.deepEqual(db.metadata.lastSuccessfulUpgrade.fromIndexedDbVersion,0);assert.deepEqual(db.metadata.lastSuccessfulUpgrade.toIndexedDbVersion,1);db.close();await s.open();assert.equal(driver.state().opens,2);});
  await test('newer incompatible database is surfaced',async()=>{let driver={open(){return Promise.reject(new Storage.StorageError('INCOMPATIBLE_DATABASE_VERSION','newer'));},remove(){return Promise.resolve();}},s=Storage.create({driver});await assert.rejects(s.open(),e=>e.code==='INCOMPATIBLE_DATABASE_VERSION');});
  await test('inconsistent metadata is detected and the connection is closed',async()=>{let driver=memoryDriver(),s=Storage.create({driver}),db=await s.open();db.close();driver.state().database._stores.metadata.set('database',{key:'database',schemaFamily:'wrong',schemaVersion:8,indexedDbVersion:1,initializationState:'ready'});await assert.rejects(s.open(),e=>e.code==='METADATA_INCONSISTENT');assert(driver.state().database.closed);});
  await test('v8 development reset deletes only named v8 database',async()=>{let removed=[],v7={weld_v013:'pilot'},photos={name:'WeldingClassroomPhotoStore'},driver=memoryDriver(),baseRemove=driver.remove;driver.remove=(name,blocked)=>{removed.push(name);return baseRemove(name,blocked);};let s=Storage.create({driver});await s.open();await s.resetDevelopmentDatabase();assert.deepEqual(removed,['arc_classroom_v8']);assert.equal(v7.weld_v013,'pilot');assert.equal(photos.name,'WeldingClassroomPhotoStore');});
  await test('blocked open and reset are surfaced',async()=>{let seen=[];let s=Storage.create({driver:memoryDriver({blocked:true}),onBlocked:x=>seen.push(x.operation)});await assert.rejects(s.open(),e=>e.code==='UPGRADE_BLOCKED');s=Storage.create({driver:memoryDriver({resetBlocked:true}),onBlocked:x=>seen.push(x.operation)});await assert.rejects(s.resetDevelopmentDatabase(),e=>e.code==='RESET_BLOCKED');assert.deepEqual(seen,['open','reset']);});
  await test('versionchange closes stale connection and permits reopen',async()=>{let driver=memoryDriver(),messages=[],s=Storage.create({driver,channelFactory:()=>({postMessage:m=>messages.push(m)})}),db=await s.open();driver.triggerVersionchange(2);assert(driver.state().database.closed);await s.open();assert(messages.some(x=>x.type==='stale-connection-closed'));});
  await test('unavailable durable storage fails without memory fallback',async()=>{assert.throws(()=>Storage.create({indexedDB:null}),e=>e.code==='INDEXEDDB_UNAVAILABLE');});
  if(!process.exitCode)console.log('\n'+pass+'/'+total+' ARC v8 Storage Foundation tests passed.');
})();
