const assert=require('assert'),cryptoNode=require('crypto'),fs=require('fs');
const Storage=require('../src/arc_v8_storage'),Backup=require('../src/arc_v8_backup_recovery');
const Physical=require('../src/arc_v8_instructional_package_availability_physical');
const DB=Physical.DATABASE_NAME,PKG=Physical.PACKAGE_ID,ATTEMPT=Physical.ATTEMPT_ID,COMMIT='a'.repeat(40),TREE='b'.repeat(40),ROLLBACK='rollback/pre-pa1',BASELINE='accepted-pi2-backup';
const clone=x=>x===undefined?undefined:structuredClone(x),S=Storage.STORES;
function hexBytes(hex){return Uint8Array.from(hex.match(/../g).map(x=>parseInt(x,16))).buffer}
const crypto={subtle:{digest:async(a,v)=>{const t=new TextDecoder().decode(v);if(t===BASELINE)return hexBytes(Physical.BASELINE_FILE_SHA256);return cryptoNode.createHash('sha256').update(Buffer.from(v)).digest().buffer}}};
function infrastructure(){return[{id:'production-v8-initialization-manifest',status:'complete',databaseName:DB,schemaFamily:'arc-classroom',schemaVersion:8,indexedDbVersion:10,expectedStoreCount:53,authorityState:'V7_ONLY',classroomAuthorityTransferred:false,realStudentDataAuthorized:false,contentImported:false},{id:'production-v8-reconciliation-manifest',status:'complete',importedRecordCount:0,excludedIdentityCount:0,reusableAuthorityImported:false,classroomTransactionsImported:false},{id:'database-protection',mode:'Production/Classroom Protected'}]}
const declaration={contractVersion:'p10d-r2-resolved-representation-repair-1',resolvedPayloadChecksum:'f1f7756242c1ef685ef4ce061507d03b8fc6834e0e448cde7510fc8e2ade79b1',frozenIdentityMapChecksum:'7ba2956022875c03cc1bea1ee9ffa205fa78c204bfdc967c06c66fc5b1c3b750',evidenceChecksum:'81d23b6fa9ee5daefd41a99ee5e3e49de67c1c948598659fad5d224efd45448a',expectedRoleCount:859,expectedRetainedLinkCount:359,expectedIntentionalAbsenceCount:259,canonicalCourseContexts:['arc-course-wt','arc-course-awt']};
const phases=[['STANDARDS',62,'b46500a170e4f3223fd1107766471f72c1c03e161651b93858dee8f8e6fc79d3'],['COMPETENCIES',120,'0373bba0713fd871e4e8d91f4ee70e989347188a89fdee1cb0463a5bbc01ed82'],['ESSENTIALS',10,'3f05ac1ae0f57be1ec2a26b0d175489f886bf034242d768471b2ff175eb06c98'],['CURRICULUM_CORE',60,'a49d80768229c62713fd470d64ebe568aa5bb76b0f47138a8973fed6361b2e93'],['CURRICULUM_STANDARD_LINKS',80,'a104bed403f6bef74c7bb235bc8e4090c65e821d29af82d4af4740142c598267'],['LESSON_CORE',248,'36a06016ff9048b185b7e9499091a4f01ea812150411cadd8750f69cda87628d'],['LESSON_STANDARD_LINKS',228,'c120f902c1ce96b735f20228017e38320ac0011115d5052c458ad27605e901b3'],['LESSON_COMPETENCY_LINKS',51,'1584621cd0a0381af5f9b91c0198ffa7ccc2db8aaa165aa91bae80af54f7a9d0']];
function history(){let rows=[{instructionalContentPackageRecordId:'p1',packageId:PKG,sequence:1,recordType:'PACKAGE_DECLARED',attemptId:null,payload:clone(declaration)},{instructionalContentPackageRecordId:'p2',packageId:PKG,sequence:2,recordType:'ATTEMPT_STARTED',attemptId:ATTEMPT,payload:{}}];phases.forEach((p,i)=>rows.push({instructionalContentPackageRecordId:'p'+(i+3),packageId:PKG,sequence:i+3,recordType:'PHASE_VERIFIED',attemptId:ATTEMPT,payload:{phase:p[0],memberCount:p[1],checksum:p[2],readbackVerified:true}}));rows.push({instructionalContentPackageRecordId:'p11',packageId:PKG,sequence:11,recordType:'PACKAGE_VERIFIED_COMPLETE',attemptId:ATTEMPT,payload:{roleCount:859,retainedLinkCount:359,intentionalAbsenceCount:259,resolvedPayloadChecksum:declaration.resolvedPayloadChecksum,frozenIdentityMapChecksum:declaration.frozenIdentityMapChecksum,ownerReadbackVerified:true,backupRecoveryVerified:true}});return rows}
function rows(n,make){return Array.from({length:n},(_,i)=>Object.assign({importPackageId:PKG},make(i)))}
function stores(){let x=Object.fromEntries(Backup.EXPECTED_STORES.map(n=>[n,[]]));x.metadata=[{key:'database',schemaFamily:'arc-classroom',schemaVersion:8,indexedDbVersion:14,initializationState:'ready'}];x.migration_log=Array.from({length:10},(_,i)=>({id:'legacy-'+i,status:'succeeded'})).concat(['indexeddb-10-to-11','indexeddb-11-to-12','indexeddb-12-to-13','indexeddb-13-to-14'].map(id=>({id,status:'succeeded'})));x.infrastructure_records=infrastructure();x.courses=[{courseId:'arc-course-wt',code:'WT',title:'Welding Technology'},{courseId:'arc-course-awt',code:'AWT',title:'Advanced Welding Technology'}];x.standard_catalogs=rows(2,i=>({standardCatalogId:'cat-'+i}));x.standard_catalog_versions=rows(2,i=>({standardCatalogVersionId:'catv-'+i}));x.standard_definitions=rows(29,i=>({standardDefinitionId:'sd-'+i}));x.standard_versions=rows(29,i=>({standardVersionId:'sv-'+i}));x.essential_standard_designations=rows(10,i=>({essentialStandardDesignationId:'es-'+i}));x.competency_definitions=rows(60,i=>({competencyDefinitionId:'cd-'+i,courseIds:[i<26?'arc-course-wt':'arc-course-awt']}));x.competency_versions=rows(60,i=>({competencyVersionId:'cv-'+i}));x.curriculum_maps=rows(2,i=>({curriculumMapId:'cm-'+i}));x.curriculum_map_versions=rows(2,i=>({curriculumMapVersionId:'cmv-'+i}));x.curriculum_map_items=rows(56,i=>({curriculumMapItemId:'cmi-'+i}));x.curriculum_item_standard_links=rows(80,i=>({curriculumItemStandardLinkId:'csl-'+i}));x.lesson_definitions=rows(124,i=>({lessonDefinitionId:'ld-'+i}));x.lesson_versions=rows(124,i=>({lessonVersionId:'lv-'+i,instructionalAvailability:'reference_only',immutableContent:true,ordinarySchedulingEligible:false,autoBuildEligible:false,instructionalAcceptanceRef:null,teachingGuide:null}));x.lesson_version_standard_links=rows(228,i=>({lessonVersionStandardLinkId:'lsl-'+i}));x.lesson_version_competency_links=rows(51,i=>({lessonVersionCompetencyLinkId:'lcl-'+i}));x.instructional_content_packages=history();return x}
function counts(x){return Object.fromEntries(Backup.EXPECTED_STORES.map(n=>[n,(x[n]||[]).length]))}
function manifest(x,integrity){let m={};Backup.EXPECTED_STORES.forEach(n=>m[n]={recordCount:x[n].length,checksum:cryptoNode.createHash('sha256').update(JSON.stringify(x[n])).digest('hex')});return{databaseName:DB,schemaVersion:8,indexedDbVersion:14,storeInventory:Backup.EXPECTED_STORES.slice(),stores:m,packageIntegrity:{checksum:integrity||'c'.repeat(64)}}}
function packageFrom(x,integrity){return{manifest:manifest(x,integrity),stores:clone(x)}}
function report(x){return{exists:true,databaseName:DB,indexedDbVersion:14,storeNames:Backup.EXPECTED_STORES.slice(),counts:counts(x),metadata:x.metadata[0],infrastructure:x.infrastructure_records,stores:clone(x)}}
function fixture(){let x=stores(),available=false,markCalls=0,baseline=packageFrom(x,Physical.BASELINE_PACKAGE_SHA256);function exported(){let p=packageFrom(x);return{text:JSON.stringify(p),package:p,verification:{verified:true,recordCount:Object.values(x).reduce((n,a)=>n+a.length,0)}}}let services={storage:{query:async n=>clone(x[n]||[])},packages:{assertOrdinaryReadGate:async()=>{if(!available)throw new Storage.StorageError('PACKAGE_READ_GATE_CLOSED','hidden')},markAvailable:async input=>{markCalls++;assert.equal(input.packageId,PKG);assert.equal(input.expectedSequence,11);x.instructional_content_packages.push({instructionalContentPackageRecordId:'p12',packageId:PKG,sequence:12,recordType:'PACKAGE_AVAILABLE',attemptId:ATTEMPT,payload:clone(input.payload)});available=true}},curriculum:{getCourseStandards:async({courseId})=>available?{catalogs:[{}],catalogVersions:[{standardCatalogVersionId:'catv'}],standards:Array.from({length:courseId==='arc-course-wt'?9:20})}:{catalogs:[],catalogVersions:[],standards:[]},getEssentialStandards:async({courseId})=>({designations:Array.from({length:courseId==='arc-course-wt'?4:6})}),getCurriculumMap:async({courseId})=>available?{items:Array.from({length:courseId==='arc-course-wt'?29:27})}:null},lessons:{getCourseLessons:async()=>[],getAutoBuildEligibleLessons:async()=>[],getLessonVersion:async()=>{throw new Storage.StorageError('LESSON_REFERENCE_ONLY','reference only')}},backup:{verifyPackage:async raw=>{let p=raw===BASELINE?baseline:JSON.parse(raw);return{verified:true,package:clone(p),recordCount:Object.values(p.stores).reduce((n,a)=>n+a.length,0)}},exportBackup:async()=>exported(),auditDatabase:async()=>({healthy:true,status:'Verified Healthy',errorCount:0,warningCount:0,storeCount:74})}};return{x,services,baseline,get markCalls(){return markCalls}}}
function make(f=fixture(),custom){return{f,api:Physical.create({databaseName:DB,crypto,expectedPublicationCommit:COMMIT,expectedPublicationTree:TREE,inspector:{inspect:async()=>report(custom||f.x)},services:f.services})}}
async function prepare(api){await api.loadAcceptedBaseline(BASELINE);await api.capturePreAvailabilityBackup()}
const auth={operator:'stage14-instructor-package-availability',publicationCommit:COMMIT,publicationTree:TREE,rollbackRef:ROLLBACK,confirmation:Physical.CONFIRMATION};
let pass=0,total=0;async function test(name,fn){total++;try{await fn();pass++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1}}
(async()=>{
await test('module creation is inert and rejects any nonproduction identity',async()=>{let calls=0;Physical.create({databaseName:DB,crypto,inspector:{inspect:async()=>{calls++}}});assert.equal(calls,0);assert.throws(()=>Physical.create({databaseName:'arc_classroom_v8_stage2_verification',crypto}),e=>e.code==='PRODUCTION_IDENTITY_REQUIRED')});
await test('exact verified-complete PI2 state is inspected without mutation',async()=>{let {api,f}=make(),r=await api.inspectReadiness();assert.equal(r.totalRecords,890);assert.equal(r.packageEvents,11);assert.equal(r.state,'verified_complete');assert.equal(r.available,false);assert.equal(f.markCalls,0);assert.equal(r.ownerReads.code,'PACKAGE_READ_GATE_CLOSED')});
await test('structure protection and empty-classroom gates refuse drift',async()=>{let f=fixture(),bad=stores();bad.students.push({studentId:'real'});await assert.rejects(make(f,bad).api.inspectReadiness(),e=>e.code==='UNEXPECTED_CLASSROOM_RECORDS');bad=stores();bad.infrastructure_records[2].mode='Development';await assert.rejects(make(f,bad).api.inspectReadiness(),e=>e.code==='PROTECTION_REQUIRED')});
await test('package lineage and reference-only Lesson policy are exact',async()=>{let f=fixture(),bad=stores();bad.instructional_content_packages[2].payload.checksum='bad';await assert.rejects(make(f,bad).api.inspectReadiness(),e=>e.code==='PACKAGE_HISTORY_MISMATCH');bad=stores();bad.lesson_versions[0].autoBuildEligible=true;await assert.rejects(make(f,bad).api.inspectReadiness(),e=>e.code==='LEGACY_LESSON_POLICY_VIOLATION')});
await test('accepted physical baseline file and package hashes are mandatory',async()=>{let {api}=make();await assert.rejects(api.loadAcceptedBaseline('wrong'),e=>e.code==='BASELINE_FILE_CHECKSUM_MISMATCH');let b=await api.loadAcceptedBaseline(BASELINE);assert.equal(b.fileChecksum,Physical.BASELINE_FILE_SHA256);assert.equal(b.packageChecksum,Physical.BASELINE_PACKAGE_SHA256)});
await test('fresh recovery must exactly match the accepted live baseline',async()=>{let {api}=make();await api.loadAcceptedBaseline(BASELINE);let b=await api.capturePreAvailabilityBackup();assert.equal(b.recordCount,890);assert.equal(b.storeCount,74)});
await test('authorization requires exact confirmation and publication authority',async()=>{let {api}=make();await prepare(api);await assert.rejects(api.makeAvailable({...auth,confirmation:'wrong'}),e=>e.code==='EXPLICIT_CONFIRMATION_REQUIRED');await assert.rejects(api.makeAvailable({...auth,publicationCommit:'wrong'}),e=>e.code==='PUBLICATION_IDENTITY_MISMATCH')});
await test('one owner call performs exact 890 to 891 package-only transition',async()=>{let {api,f}=make();await prepare(api);let r=await api.makeAvailable(auth);assert.equal(f.markCalls,1);assert.equal(r.totalRecords,891);assert.equal(r.packageEvents,12);assert.equal(r.state,'available');assert.equal(r.available,true);assert.equal(r.onlyChangedStore,'instructional_content_packages');assert.equal(r.normalAuthority,'V7_ONLY')});
await test('available owner projections expose exact Standards Curriculum and Competencies',async()=>{let {api}=make();await prepare(api);let r=await api.makeAvailable(auth);assert.deepEqual([r.ownerReads.wt.standards,r.ownerReads.awt.standards],[9,20]);assert.deepEqual([r.ownerReads.wt.essentialStandards,r.ownerReads.awt.essentialStandards],[4,6]);assert.deepEqual([r.ownerReads.wt.curriculumItems,r.ownerReads.awt.curriculumItems],[29,27]);assert.deepEqual([r.ownerReads.wt.competencies,r.ownerReads.awt.competencies],[26,34])});
await test('availability never exposes legacy Lessons to ordinary reads or Auto Build',async()=>{let {api}=make();await prepare(api);let r=await api.makeAvailable(auth);assert.deepEqual([r.ownerReads.wt.ordinaryLessons,r.ownerReads.awt.ordinaryLessons,r.ownerReads.wt.autoBuildLessons,r.ownerReads.awt.autoBuildLessons],[0,0,0,0]);assert.equal(r.ownerReads.legacyLessons.directOrdinaryReadCode,'LESSON_REFERENCE_ONLY')});
await test('safe retry appends no second availability event',async()=>{let {api,f}=make();await prepare(api);await api.makeAvailable(auth);let n=f.x.instructional_content_packages.length,r=await api.makeAvailable(auth);assert.equal(f.markCalls,1);assert.equal(f.x.instructional_content_packages.length,n);assert.equal(r.available,true)});
await test('public bridge has no delete restore reset or normal UI path',async()=>{let {api}=make();for(const name of ['deleteDatabase','restoreBackup','resetDevelopmentDatabase','markAvailable'])assert.equal(api[name],undefined);assert(!fs.readFileSync('index.html','utf8').includes('arc_v8_instructional_package_availability_physical'))});
if(!process.exitCode)console.log(`\n${pass}/${total} ARC P10D-PA1 Production Instructional Package Availability Physical Bridge tests passed.`)
})();
