const assert=require('assert'),fs=require('fs'),Adapter=require('../src/arc_curriculum_pacing_authority_adapter'),UI=require('../src/arc_curriculum_pacing_ui');
let pass=0,total=0;async function test(name,fn){total++;try{await fn();pass++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1}}
function fixture(){let calls=[],plans={
  'wt-1|sem1':{configured:true,plan:{sectionPacingPlanId:'plan-wt-1',revision:3,lastSequence:2},current:{currentCurriculumMapItemId:'wt-item-1',items:[]}},
  'wt-2|sem1':{configured:true,plan:{sectionPacingPlanId:'plan-wt-2',revision:7,lastSequence:6},current:{currentCurriculumMapItemId:'wt-item-2',items:[]}},
  'awt-1|sem1':{configured:true,plan:{sectionPacingPlanId:'plan-awt-1',revision:2,lastSequence:1},current:{currentCurriculumMapItemId:'awt-item-1',items:[]}},
  'wt-1|sem2':{configured:false,sectionId:'wt-1',semesterId:'sem2',reason:'unknown/not configured'}
};let service={
  async getCourseStandards(x){calls.push(['getCourseStandards',x]);return{courseId:x.courseId,standards:[{version:{wording:'Fictional '+x.courseId.toUpperCase()+' standard'}}]}},
  async getEssentialStandards(x){calls.push(['getEssentialStandards',x]);return{courseId:x.courseId,designations:[{standardVersionId:x.courseId+'-std',designation:'essential'}]}},
  async getCurriculumMap(x){calls.push(['getCurriculumMap',x]);let c=x.courseId;return{version:{curriculumMapVersionId:c+'-map-v1',courseId:c},items:[{item:{curriculumMapItemId:c+'-item-2',orderPath:'02'}},{item:{curriculumMapItemId:c+'-item-1',orderPath:'01'}}]}},
  async getCurriculumItem(x){calls.push(['getCurriculumItem',x]);return{item:{curriculumMapItemId:x.curriculumMapItemId},standardLinks:[],competencyLinks:[{competencyVersionId:'fictional-competency-v1'}]}},
  async getCurriculumCoverage(x){calls.push(['getCurriculumCoverage',x]);return{curriculumMapVersionId:x.curriculumMapVersionId,itemCount:2}},
  async getSectionPacing(x){calls.push(['getSectionPacing',x]);return structuredClone(plans[x.sectionId+'|'+x.semesterId])},
  async getSectionPacingHistory(x){calls.push(['getSectionPacingHistory',x]);return{configured:!!plans[x.sectionId+'|'+x.semesterId].configured,events:[{sequence:1}],snapshots:[]}},
  async previewPacingCommand(x){calls.push(['previewPacingCommand',x]);return{write:false,request:x}},
  async appendPacingCommand(x){calls.push(['appendPacingCommand',x]);return{event:{eventType:x.eventType},projection:{plan:{revision:x.expectedRevision+1}}}},
  async createPacingSnapshot(x){calls.push(['createPacingSnapshot',x]);return{snapshotType:x.snapshotType}},
  async previewSemesterPacingCloseout(x){calls.push(['previewSemesterPacingCloseout',x]);return{write:false,willCreateFuturePlan:false,to:{configured:false,reason:'unknown/not configured'}}},
  async closeSemesterPacing(x){calls.push(['closeSemesterPacing',x]);return{futurePlanCreated:false,choice:x.choice}}
};let adapter=Adapter.create({authorityState:Adapter.states.V8_ISOLATED_VERIFICATION,databaseName:Adapter.isolatedDatabaseName,service}),ui=UI.create({adapter});return{calls,plans,service,adapter,ui};}
(async()=>{
await test('course view switches WT/AWT and uses every frozen read interface',async()=>{let f=fixture(),wt=await f.ui.courseView({courseId:'wt',standardCatalogVersionId:'wt-cat-v1',curriculumMapVersionId:'wt-map-v1',sectionId:'wt-1',schoolYearId:'year',semesterId:'sem1',gradingPeriodId:'q1'}),awt=await f.ui.courseView({courseId:'awt',standardCatalogVersionId:'awt-cat-v1',curriculumMapVersionId:'awt-map-v1',sectionId:'awt-1',semesterId:'sem1'});await f.ui.curriculumItem({curriculumMapItemId:'wt-item-1'});assert.equal(wt.standards.courseId,'wt');assert.equal(awt.standards.courseId,'awt');assert.deepEqual(wt.curriculumMap.items.map(x=>x.item.orderPath),['01','02']);assert.equal(wt.essentialStandards.designations[0].designation,'essential');assert.equal(wt.academicContext.gradingPeriodId,'q1');for(const name of Adapter.readInterfaces)assert(f.calls.some(x=>x[0]===name),name);});
await test('independent Section positions agree exactly with authority projections',async()=>{let f=fixture(),one=await f.ui.courseView({courseId:'wt',curriculumMapVersionId:'wt-map-v1',sectionId:'wt-1',semesterId:'sem1'}),two=await f.ui.courseView({courseId:'wt',curriculumMapVersionId:'wt-map-v1',sectionId:'wt-2',semesterId:'sem1'});assert.equal(one.sectionPacing.current.currentCurriculumMapItemId,'wt-item-1');assert.equal(two.sectionPacing.current.currentCurriculumMapItemId,'wt-item-2');assert.notDeepEqual(one.sectionPacing,two.sectionPacing);});
await test('future Semester pacing stays absent and commands refuse fabrication',async()=>{let f=fixture(),view=await f.ui.courseView({courseId:'wt',curriculumMapVersionId:'wt-map-v1',sectionId:'wt-1',semesterId:'sem2'});assert.equal(view.futurePacingUnknown,true);await assert.rejects(f.ui.command({sectionId:'wt-1',semesterId:'sem2',command:{eventType:'MAP_POSITION_SET'}}),e=>e.code==='PACING_NOT_CONFIGURED');assert(!f.calls.some(x=>x[0]==='appendPacingCommand'));});
await test('pacing advancement adjustment and correction preview before append with current conflict tokens',async()=>{let f=fixture();for(const command of [{eventType:'MAP_POSITION_SET',curriculumMapItemId:'wt-item-2'},{eventType:'DURATION_ADJUSTED',pacingItemId:'item-1',payload:{plannedDuration:3}},{eventType:'ITEM_REORDERED',pacingItemId:'item-1',payload:{order:2}},{eventType:'CORRECTION',replacementEventType:'MAP_POSITION_SET',supersedesSectionPacingEventId:'event-1',curriculumMapItemId:'wt-item-1',reason:'fixture correction'}]){let result=await f.ui.command({sectionId:'wt-1',semesterId:'sem1',command});assert.equal(result.event.eventType,command.eventType);}let previews=f.calls.filter(x=>x[0]==='previewPacingCommand'),writes=f.calls.filter(x=>x[0]==='appendPacingCommand');assert.equal(previews.length,4);assert.equal(writes.length,4);assert(previews.every(x=>x[1].expectedRevision===3&&x[1].expectedSequence===2));assert.deepEqual(previews.map(x=>x[1]),writes.map(x=>x[1]));});
await test('preview-only command never appends and stale errors never fall back',async()=>{let f=fixture();await f.ui.command({sectionId:'wt-1',semesterId:'sem1',previewOnly:true,command:{eventType:'OPEN_SHOP_CHANGED',payload:{includeOpenShop:true}}});assert.equal(f.calls.filter(x=>x[0]==='previewPacingCommand').length,1);assert.equal(f.calls.filter(x=>x[0]==='appendPacingCommand').length,0);f.service.previewPacingCommand=async()=>{let e=Error('stale');e.code='WRITE_CONFLICT';throw e};await assert.rejects(f.ui.command({sectionId:'wt-1',semesterId:'sem1',command:{eventType:'ANCHOR_CHANGED'}}),e=>e.code==='WRITE_CONFLICT');});
await test('history snapshot and Semester closeout use owning commands without creating future pacing',async()=>{let f=fixture();assert.equal((await f.ui.snapshot({sectionPacingPlanId:'plan-wt-1',snapshotType:'manual_history',reason:'fixture'})).snapshotType,'manual_history');let preview=await f.ui.closeout({sectionId:'wt-1',fromSemesterId:'sem1',toSemesterId:'sem2',previewOnly:true});assert.equal(preview.willCreateFuturePlan,false);let close=await f.ui.closeout({sectionId:'wt-1',fromSemesterId:'sem1',toSemesterId:'sem2',choice:'continue',recoveryPointId:'fixture-recovery',reason:'fixture close'});assert.equal(close.futurePlanCreated,false);});
await test('Auto Build is explicitly held for P10C Lesson authority',()=>{let f=fixture();assert.throws(()=>f.ui.autoBuild(),e=>e.code==='LESSON_AUTHORITY_REQUIRED');});
await test('normal UI preserves every accepted handler through one V7 operation and caches the new modules',()=>{let html=fs.readFileSync('index.html','utf8'),sw=fs.readFileSync('sw.js','utf8'),build=fs.readFileSync('app-build.js','utf8');for(const name of ['renderCurriculumHub','setSectionCurriculumPosition','clearSectionCurriculumPosition','renderPacingPlanner','showAutoBuildPacing','confirmAutoBuildPacing','savePacingDuration','updatePacingAnchor','togglePacingOpenShop','applyPacingStatus','movePacingItem','removePacingItem','createPacingHistorySnapshot','renderPacingHistory'])assert(html.includes(name+':')||html.includes(name+',')||html.includes(name+' = function'),name);assert(html.includes('ArcCurriculumPacingAuthorityAdapter.create({ authorityState: "V7_ONLY" })'));for(const asset of ['arc_v8_curriculum_pacing.js','arc_curriculum_pacing_authority_adapter.js','arc_curriculum_pacing_ui.js'])assert(html.includes(asset)&&sw.includes(asset),asset);assert(build.includes('parity-p10b-ui-1-parity-p10c-ui-1'));});
if(!process.exitCode)console.log(`\n${pass}/${total} ARC Stage 14 P10B-UI tests passed.`);
})();
