const assert=require('assert'),nodeCrypto=require('crypto'),fs=require('fs'),path=require('path');
const Storage=require('../src/arc_v8_storage'),Backup=require('../src/arc_v8_backup_recovery'),Coordinator=require('../src/arc_v8_instructional_import_coordinator');
const Physical=require('../src/arc_v8_instructional_import_production_physical');
const DB='arc_classroom_v8',COMMIT='a'.repeat(40),TREE='b'.repeat(40),ROLLBACK='rollback/pre-pi1';
const PAYLOAD='payload-bytes',IDENTITY='identity-bytes',at='2026-10-03T12:00:00.000Z';
const clone=x=>x===undefined?undefined:structuredClone(x);
function hexBytes(hex){return Uint8Array.from(hex.match(/../g).map(x=>parseInt(x,16))).buffer}
const crypto={randomUUID:(()=>{let n=1;return()=>`00000000-0000-4000-8000-${String(n++).padStart(12,'0')}`})(),subtle:{digest:async(algorithm,value)=>{const text=new TextDecoder().decode(value);if(text===PAYLOAD)return hexBytes(Physical.PAYLOAD_SHA256);if(text===IDENTITY)return hexBytes(Physical.IDENTITY_SHA256);return nodeCrypto.createHash('sha256').update(Buffer.from(value)).digest().buffer}}};
function infrastructure(){return[{id:'production-v8-initialization-manifest',status:'complete',databaseName:DB,schemaFamily:'arc-classroom',schemaVersion:8,indexedDbVersion:10,expectedStoreCount:53,authorityState:'V7_ONLY',classroomAuthorityTransferred:false,realStudentDataAuthorized:false,contentImported:false},{id:'production-v8-reconciliation-manifest',status:'complete',importedRecordCount:0,excludedIdentityCount:0,reusableAuthorityImported:false,classroomTransactionsImported:false},{id:'database-protection',mode:'Production/Classroom Protected'}]}
function emptyStores(){const stores=Object.fromEntries(Backup.EXPECTED_STORES.map(name=>[name,[]]));stores.metadata=[{key:'database',schemaFamily:'arc-classroom',schemaVersion:8,indexedDbVersion:14,initializationState:'ready'}];stores.migration_log=Array.from({length:14},(_,i)=>({id:`indexeddb-${i}-to-${i+1}`,status:'succeeded'}));stores.infrastructure_records=infrastructure();return stores}
function report(stores=emptyStores(),version=14){return{exists:true,databaseName:DB,indexedDbVersion:version,storeNames:Backup.EXPECTED_STORES.slice(),counts:Object.fromEntries(Backup.EXPECTED_STORES.map(name=>[name,(stores[name]||[]).length])),metadata:stores.metadata[0],infrastructure:stores.infrastructure_records,stores}}
function model(){const specs=Object.values(Coordinator.ROLE_CONTRACTS),roles=Array.from({length:859},(_,i)=>{const spec=specs[i%specs.length];return{reviewRecordKey:`r${i}`,roleType:Object.keys(Coordinator.ROLE_CONTRACTS).find(k=>Coordinator.ROLE_CONTRACTS[k]===spec),targetRepresentation:{store:spec.store,targetIdentity:`id-${i}`}}});return{payload:{compilerRevision:'p10d-r2-resolved-representation-repair-1',packageEvidence:{r1bArtifact:{path:'r1b.json'},sourceResolutions:[{decisionId:'wt',course:'wt',selectedAuthority:'official'},{decisionId:'awt',course:'awt',selectedAuthority:'official'}]}},payloadChecksum:Physical.PAYLOAD_SHA256,identityMapChecksum:Physical.IDENTITY_SHA256,evidenceChecksum:'e'.repeat(64),roles,exclusions:Array.from({length:259}),phases:Coordinator.PHASES.map(clone)}}
function packageFrom(stores,purpose){const pkg={manifest:{databaseName:DB,schemaVersion:8,indexedDbVersion:14,storeInventory:Backup.EXPECTED_STORES.slice(),packageIntegrity:{checksum:'c'.repeat(64)},purpose},stores:clone(stores)};return{text:JSON.stringify(pkg),package:pkg,verification:{verified:true,recordCount:Object.values(stores).reduce((n,x)=>n+x.length,0)}}}
function servicesFixture(){
  const stores=emptyStores(),events=stores.instructional_content_packages,courses=stores.courses;let state=null,packageId=null,attemptId=null,lastSequence=0,availableCalled=false;
  const storage={constants:{databaseName:DB},generateId:crypto.randomUUID,query:async store=>clone(stores[store]||[]),resetDevelopmentDatabase:async()=>{throw new Storage.StorageError('PROTECTED_DATABASE','protected')}};
  const packages={
    declarePackage:async input=>{packageId=input.packageId;state='declared';events.push({instructionalContentPackageRecordId:crypto.randomUUID(),packageId,sequence:++lastSequence,recordType:'PACKAGE_DECLARED',payload:clone(input.declaration)});},
    startAttempt:async input=>{attemptId=input.attemptId;state='assembling';events.push({instructionalContentPackageRecordId:crypto.randomUUID(),packageId,sequence:++lastSequence,recordType:'ATTEMPT_STARTED',attemptId});},
    appendPhaseVerification:async input=>events.push({instructionalContentPackageRecordId:crypto.randomUUID(),packageId,sequence:++lastSequence,recordType:'PHASE_VERIFIED',attemptId,payload:{phase:input.phase,memberCount:input.memberCount,checksum:input.checksum,readbackVerified:true}}),
    markVerifiedComplete:async()=>{state='verified_complete';events.push({instructionalContentPackageRecordId:crypto.randomUUID(),packageId,sequence:++lastSequence,recordType:'PACKAGE_VERIFIED_COMPLETE',attemptId});},
    markAvailable:async()=>{availableCalled=true;throw Error('must not be called')},
    getPackageProjection:async()=>state?{packageId,state,declared:clone(events[0].payload),currentAttemptId:attemptId,lastSequence,available:false,verifiedComplete:state==='verified_complete'}:null,
    getPackageHistory:async()=>clone(events),
    assertOrdinaryReadGate:async()=>{throw new Storage.StorageError('PACKAGE_READ_GATE_CLOSED','hidden')}
  };
  const academic={initialize:async()=>{if(!courses.length)courses.push({courseId:'arc-course-wt',code:'WT',title:'Welding Technology'},{courseId:'arc-course-awt',code:'AWT',title:'Advanced Welding Technology'});return clone(courses)}};
  const coordinator={runPhase:async input=>({phase:input.phase,memberCount:Coordinator.PHASES.find(x=>x.name===input.phase).count,created:1,equivalent:0,checksum:input.phase.toLowerCase(),readbackVerified:true}),verifyAll:async()=>({roleCount:859,retainedLinkCount:359,intentionalAbsenceCount:259,exclusionsVerified:true,checksum:'v'.repeat(64)}),completionEvidence:input=>({roleCount:859,retainedLinkCount:359,intentionalAbsenceCount:259,memberChecksumsVerified:true,ownerReadbackVerified:true,canonicalCoursesVerified:true,evidenceVerified:true,conflictsAbsent:true,backupRecoveryVerified:true,resolvedPayloadChecksum:Physical.PAYLOAD_SHA256,frozenIdentityMapChecksum:Physical.IDENTITY_SHA256,readbackChecksum:input.verification.checksum,phaseChecksums:input.phaseSummaries.map(x=>({phase:x.phase,memberCount:x.memberCount,checksum:x.checksum}))})};
  const backup={exportBackup:async input=>packageFrom(stores,input.purpose),verifyPackage:async input=>{const pkg=typeof input==='string'?JSON.parse(input):input;return{verified:true,package:pkg,recordCount:Object.values(pkg.stores).reduce((n,x)=>n+x.length,0)}},auditDatabase:async()=>({healthy:true,status:'Verified Healthy',errorCount:0,warningCount:0,storeCount:74})};
  return{services:{storage,packages,academic,coordinator,backup},stores,get availableCalled(){return availableCalled}};
}
function bridge(fixture=servicesFixture(),customReport){return{bridge:Physical.create({databaseName:DB,crypto,expectedPublicationCommit:COMMIT,expectedPublicationTree:TREE,inspector:{inspect:async()=>clone(customReport||report(fixture.stores))},services:fixture.services}),fixture}}
let pass=0,total=0;async function test(name,fn){total++;try{await fn();pass++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1}}
(async()=>{const original=Coordinator.preflight;Coordinator.preflight=async()=>model();try{
await test('module load and bridge creation are inert',async()=>{let calls=0;Physical.create({databaseName:DB,crypto,expectedPublicationCommit:COMMIT,expectedPublicationTree:TREE,inspector:{inspect:async()=>{calls++;return report()}},services:servicesFixture().services});assert.equal(calls,0)});
await test('wrong production database identity is refused',async()=>{assert.throws(()=>Physical.create({databaseName:'arc_classroom_v8_p10d_persisted_rehearsal_1',crypto}),e=>e.code==='PRODUCTION_IDENTITY_REQUIRED')});
await test('wrong structural version and nonempty classroom state refuse before write',async()=>{let x=bridge(undefined,report(emptyStores(),13)).bridge;await assert.rejects(x.inspectReadiness(),e=>e.code==='PRODUCTION_STRUCTURE_MISMATCH');let stores=emptyStores();stores.students.push({studentId:'real'});x=bridge(undefined,report(stores)).bridge;await assert.rejects(x.inspectReadiness(),e=>e.code==='UNEXPECTED_CLASSROOM_RECORDS')});
await test('payload and identity byte mismatches refuse before database work',async()=>{const x=bridge().bridge;await assert.rejects(x.loadResolvedPayload('wrong'),e=>e.code==='PAYLOAD_CHECKSUM_MISMATCH');await assert.rejects(x.loadIdentityMap('wrong'),e=>e.code==='IDENTITY_CHECKSUM_MISMATCH')});
await test('production import requires backup exact files and publication authority',async()=>{const {bridge:x}=bridge();await x.loadResolvedPayload(PAYLOAD);await x.loadIdentityMap(IDENTITY);await assert.rejects(x.importVerifiedPackage({}),e=>e.code==='VERIFIED_BACKUP_REQUIRED');await x.capturePreImportBackup();await assert.rejects(x.importVerifiedPackage({operator:'teacher',publicationCommit:'wrong',publicationTree:TREE,rollbackRef:ROLLBACK,confirmation:Physical.CONFIRMATION}),e=>e.code==='PUBLICATION_IDENTITY_MISMATCH')});
await test('exact guarded import seeds only courses completes hidden and creates no availability event',async()=>{const {bridge:x,fixture}=bridge();let readiness=await x.inspectReadiness();assert.equal(readiness.state,'fresh');await x.capturePreImportBackup();await x.loadResolvedPayload(PAYLOAD);let verified=await x.loadIdentityMap(IDENTITY);assert.equal(verified.roleCount,859);let result=await x.importVerifiedPackage({operator:'stage14-instructor-production-import',publicationCommit:COMMIT,publicationTree:TREE,rollbackRef:ROLLBACK,confirmation:Physical.CONFIRMATION});assert.equal(result.roleCount,859);assert.equal(result.retainedLinkCount,359);assert.equal(result.intentionalAbsenceCount,259);assert.equal(result.state,'verified_complete');assert.equal(result.available,false);assert.equal(result.referenceOnlyLessons,124);assert.equal(result.teachingGuideFabricated,false);assert.equal(result.protectedResetRefused,true);assert.equal(fixture.stores.courses.length,2);assert.equal(fixture.stores.school_years.length,0);assert.equal(fixture.stores.students.length,0);assert.equal(fixture.availableCalled,false);assert(!fixture.stores.instructional_content_packages.some(x=>x.recordType==='PACKAGE_AVAILABLE'));assert.equal(result.postImportBackup.verified,true)});
await test('verified complete import becomes audit-only idempotent verification',async()=>{const {bridge:x,fixture}=bridge();await x.capturePreImportBackup();await x.loadResolvedPayload(PAYLOAD);await x.loadIdentityMap(IDENTITY);const auth={operator:'operator',publicationCommit:COMMIT,publicationTree:TREE,rollbackRef:ROLLBACK,confirmation:Physical.CONFIRMATION};const first=await x.importVerifiedPackage(auth),eventCount=fixture.stores.instructional_content_packages.length,second=await x.importVerifiedPackage(auth);assert.equal(second.packageId,first.packageId);assert.equal(fixture.stores.instructional_content_packages.length,eventCount)});
await test('browser owners use the opened connection with the controller identity API',async()=>{const source=fs.readFileSync(path.join(__dirname,'../src/arc_v8_instructional_import_production_physical.js'),'utf8');assert(source.includes('db=await storage.open();db.constants=storage.constants;db.generateId=storage.generateId'));for(const owner of ['Packages','Academic','Curriculum','Evidence','Lessons','Coordinator','BackupRecovery'])assert(source.includes(owner+(owner==='Coordinator'?'.createProduction({storage:db':'.create({storage:db')),owner);assert(!source.includes('BackupRecovery.create({storage:storage'));assert(source.includes('(service.controller||service.storage).generateId()'));assert(!source.includes('service.storage.generateId()'))});
await test('public bridge surface exposes no delete restore reset availability or normal-index wiring',async()=>{const api=bridge().bridge;for(const forbidden of ['deleteDatabase','restoreBackup','resetDevelopmentDatabase','markAvailable','makeAvailable'])assert.equal(api[forbidden],undefined);const index=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');assert(!index.includes('arc_v8_instructional_import_production_physical'))});
}finally{Coordinator.preflight=original}if(!process.exitCode)console.log(`\n${pass}/${total} ARC P10D-PI1 Production Instructional Import Physical Bridge tests passed.`)})();
