const assert=require('assert');
const Storage=require('../src/arc_v8_storage');
const Packages=require('../src/arc_v8_instructional_content_packages');
const S=Storage.STORES;
function memory(){let rows=new Map(),n=1;function clone(x){return x==null?x:structuredClone(x)}function api(map){return{get:async(s,id)=>clone(map.get(id)),add:async(s,row)=>{if(map.has(row.instructionalContentPackageRecordId))throw new Storage.StorageError('REQUEST_FAILED','duplicate');if(Array.from(map.values()).some(x=>x.packageId===row.packageId&&x.sequence===row.sequence))throw new Storage.StorageError('REQUEST_FAILED','duplicate sequence');map.set(row.instructionalContentPackageRecordId,clone(row));return clone(row)},put:async(s,row)=>{map.set(row.instructionalContentPackageRecordId,clone(row));return clone(row)},query:async(s,index,key)=>Array.from(map.values()).filter(row=>index==='by_package'?row.packageId===key:index==='by_package_sequence'?row.packageId===key[0]&&row.sequence===key[1]:index==='by_package_type'?row.packageId===key[0]&&row.recordType===key[1]:true).map(clone)}}return{generateId:()=>`00000000-0000-4000-8000-${String(n++).padStart(12,'0')}`,query:(s,i,k)=>api(rows).query(s,i,k),read:(s,k)=>api(rows).get(s,k),add:(s,r)=>api(rows).add(s,r),async transaction(stores,fn){let work=new Map(Array.from(rows).map(([k,v])=>[k,clone(v)])),out=await fn(api(work));rows=work;return out},_rows:rows};}
function declaration(){return{contractVersion:'p10d-r2-owner-fields-v1',resolvedPayloadChecksum:'a'.repeat(64),frozenIdentityMapChecksum:'b'.repeat(64),evidenceChecksum:'c'.repeat(64),evidenceReference:'synthetic-review-evidence',expectedRoleCount:859,expectedRetainedLinkCount:359,expectedIntentionalAbsenceCount:259,canonicalCourseContexts:['arc-course-wt','arc-course-awt'],sourceAuthorities:['synthetic-fixture']};}
function complete(d=declaration()){return{roleCount:859,retainedLinkCount:359,intentionalAbsenceCount:259,resolvedPayloadChecksum:d.resolvedPayloadChecksum,frozenIdentityMapChecksum:d.frozenIdentityMapChecksum,memberChecksumsVerified:true,ownerReadbackVerified:true,canonicalCoursesVerified:true,evidenceVerified:true,conflictsAbsent:true,backupRecoveryVerified:true};}
function fixture(){let storage=memory(),tick=0,repo=Packages.create({storage,actor:'o1-test',now:()=>`2026-10-02T21:00:${String(tick++).padStart(2,'0')}Z`});return{storage,repo};}
let pass=0,total=0;async function test(name,fn){total++;try{await fn();pass++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1}}
(async()=>{
await test('module is explicit and does not open storage on load',async()=>{assert.equal(typeof Packages.create,'function');assert.equal(Storage.IDB_VERSION,14);assert.equal(S.instructionalContentPackages,'instructional_content_packages');});
await test('declaration binds exact frozen contract and append-first sequence',async()=>{let f=fixture(),d=await f.repo.declarePackage({packageId:'pkg',declaration:declaration()});assert.equal(d.sequence,1);assert.equal(d.recordType,'PACKAGE_DECLARED');let p=await f.repo.getPackageProjection({packageId:'pkg'});assert.equal(p.state,'declared');assert.equal(p.declared.expectedRoleCount,859);await assert.rejects(f.repo.declarePackage({packageId:'pkg',declaration:declaration()}),e=>e.code==='PACKAGE_ALREADY_DECLARED');});
await test('invalid frozen counts and transitions are refused',async()=>{let f=fixture(),bad=declaration();bad.expectedRoleCount=858;await assert.rejects(f.repo.declarePackage({packageId:'bad',declaration:bad}),e=>e.code==='PACKAGE_CONTRACT_MISMATCH');await assert.rejects(f.repo.markAvailable({packageId:'missing',reason:'no'}),e=>e.code==='INVALID_PACKAGE_TRANSITION');});
await test('attempt phase failure and retry preserve complete history',async()=>{let f=fixture();await f.repo.declarePackage({packageId:'pkg',declaration:declaration()});await f.repo.startAttempt({packageId:'pkg',attemptId:'a1',expectedSequence:1});await f.repo.appendPhaseVerification({packageId:'pkg',attemptId:'a1',phase:'standards',memberCount:1,checksum:'d'.repeat(64),readbackVerified:true,expectedSequence:2});await f.repo.appendAttemptFailure({packageId:'pkg',attemptId:'a1',code:'INJECTED',reason:'synthetic failure',expectedSequence:3});await f.repo.startAttempt({packageId:'pkg',attemptId:'a2',expectedSequence:4});let h=await f.repo.getPackageHistory({packageId:'pkg'});assert.deepEqual(h.map(x=>x.sequence),[1,2,3,4,5]);assert.equal(h[2].recordType,'PHASE_VERIFIED');assert.equal((await f.repo.getPackageProjection({packageId:'pkg'})).state,'assembling');});
await test('stale sequence active attempt and duplicate attempt are refused',async()=>{let f=fixture();await f.repo.declarePackage({packageId:'pkg',declaration:declaration()});await f.repo.startAttempt({packageId:'pkg',attemptId:'a1',expectedSequence:1});await assert.rejects(f.repo.startAttempt({packageId:'pkg',attemptId:'a2',expectedSequence:2}),e=>e.code==='ATTEMPT_ALREADY_ACTIVE');await assert.rejects(f.repo.appendPhaseVerification({packageId:'pkg',attemptId:'a1',phase:'x',memberCount:1,checksum:'x',readbackVerified:true,expectedSequence:1}),e=>e.code==='WRITE_CONFLICT');});
await test('completion requires every frozen readback criterion',async()=>{let f=fixture(),d=declaration();await f.repo.declarePackage({packageId:'pkg',declaration:d});await f.repo.startAttempt({packageId:'pkg',attemptId:'a1'});let bad=complete(d);bad.conflictsAbsent=false;await assert.rejects(f.repo.markVerifiedComplete({packageId:'pkg',attemptId:'a1',completionEvidence:bad}),e=>e.code==='COMPLETION_CONTRACT_FAILED');assert.equal((await f.repo.getPackageProjection({packageId:'pkg'})).state,'assembling');await f.repo.markVerifiedComplete({packageId:'pkg',attemptId:'a1',completionEvidence:complete(d)});assert.equal((await f.repo.getPackageProjection({packageId:'pkg'})).state,'verified_complete');});
await test('ordinary read stays closed until available while audit is explicit',async()=>{let f=fixture(),d=declaration();await f.repo.declarePackage({packageId:'pkg',declaration:d});await f.repo.startAttempt({packageId:'pkg',attemptId:'a1'});await f.repo.assertWriteGate({packageId:'pkg',attemptId:'a1'});await assert.rejects(f.repo.assertOrdinaryReadGate({packageId:'pkg'}),e=>e.code==='PACKAGE_READ_GATE_CLOSED');await assert.rejects(f.repo.assertAuditReadGate({packageId:'pkg'}),e=>e.code==='AUDIT_AUTHORIZATION_REQUIRED');await f.repo.assertAuditReadGate({packageId:'pkg',auditAuthorized:true});await f.repo.markVerifiedComplete({packageId:'pkg',attemptId:'a1',completionEvidence:complete(d)});await assert.rejects(f.repo.assertOrdinaryReadGate({packageId:'pkg'}),e=>e.code==='PACKAGE_READ_GATE_CLOSED');await f.repo.markAvailable({packageId:'pkg',reason:'synthetic verified release'});assert.equal((await f.repo.assertOrdinaryReadGate({packageId:'pkg'})).state,'available');});
await test('supersession is append-first and preserves old events',async()=>{let f=fixture(),d=declaration();await f.repo.declarePackage({packageId:'pkg',declaration:d});await f.repo.startAttempt({packageId:'pkg',attemptId:'a1'});await f.repo.markVerifiedComplete({packageId:'pkg',attemptId:'a1',completionEvidence:complete(d)});await f.repo.markAvailable({packageId:'pkg',reason:'available'});let before=await f.repo.getPackageHistory({packageId:'pkg'});await f.repo.supersedePackage({packageId:'pkg',reason:'replacement reviewed',supersededByPackageId:'pkg-2'});let after=await f.repo.getPackageHistory({packageId:'pkg'});assert.equal(after.length,before.length+1);assert.deepEqual(after.slice(0,before.length),before);assert.equal((await f.repo.getPackageProjection({packageId:'pkg'})).state,'superseded');});
if(!process.exitCode)console.log(`\n${pass}/${total} ARC v8 Instructional Content Package tests passed.`);
})();
