const assert=require('assert'),fs=require('fs'),Adapter=require('../src/arc_schedule_authority_adapter');
let pass=0,total=0;async function test(name,fn){total++;try{await fn();pass++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1}}
(async()=>{
await test('V7_ONLY invokes exactly one accepted legacy mutation and never v8',async()=>{let calls=0,a=Adapter.create({authorityState:'V7_ONLY'}),result=a.runLegacy('bell-time',{period:1},p=>{calls++;return p.period+1});assert.equal(result,2);assert.equal(calls,1);assert.equal(a.dualWrite,false);assert.equal(a.isAuthoritativeV8,false);await assert.rejects(a.runIsolated('summary',{}),e=>e.code==='V8_AUTHORITY_BLOCKED');});
await test('isolated v8 adapter is hard-bound and cannot call legacy authority',async()=>{let admin={summary:async()=>({ok:true})};assert.throws(()=>Adapter.create({authorityState:'V8_ISOLATED_VERIFICATION',databaseName:'arc_classroom_v8',admin}),e=>e.code==='ISOLATED_AUTHORITY_REQUIRED');let a=Adapter.create({authorityState:'V8_ISOLATED_VERIFICATION',databaseName:Adapter.isolatedDatabaseName,admin});assert.deepEqual(await a.runIsolated('summary',{}),{ok:true});assert.throws(()=>a.runLegacy('x',{},()=>{}),e=>e.code==='LEGACY_AUTHORITY_BLOCKED');});
await test('isolated actions delegate to the same P2 API shape without a second implementation',async()=>{let calls=[],admin={createBellSchedule:async x=>(calls.push(['bell',x]),x),createScheduleMode:async x=>(calls.push(['mode',x]),x),createCalendarDay:async x=>(calls.push(['day',x]),x),createDateOverride:async x=>(calls.push(['override',x]),x),createCalendarEvent:async x=>(calls.push(['event',x]),x),createSectionPlacement:async x=>(calls.push(['placement',x]),x),correctAuthority:async(...x)=>(calls.push(['correct',x]),x),previewSemesterTransition:async x=>(calls.push(['preview',x]),{ready:true}),applySemesterTransition:async(...x)=>(calls.push(['apply',x]),{applied:true}),summary:async()=>({})},a=Adapter.create({authorityState:'V8_ISOLATED_VERIFICATION',databaseName:Adapter.isolatedDatabaseName,admin});await a.runIsolated('bell-create',{name:'Regular'});await a.runIsolated('calendar-range',{items:[{schoolDate:'2027-01-01'},{schoolDate:'2027-01-02'}]});await a.runIsolated('semester-preview',{choices:[]});await a.runIsolated('semester-apply',{input:{choices:[]},recoveryToken:'r'});assert.deepEqual(calls.map(x=>x[0]),['bell','override','override','preview','apply']);});
await test('normal ARC keeps accepted function names and routes every bounded mutation through V7_ONLY adapter',()=>{let html=fs.readFileSync('index.html','utf8');assert(html.includes('ArcScheduleAuthorityAdapter.create({ authorityState: "V7_ONLY" })'));for(const action of ['bell-time','calendar-day','calendar-day-clear','calendar-event','calendar-event-delete','calendar-range','semester-transition','planning-period','section-period'])assert(html.includes(`runLegacy("${action}"`),action);for(const fn of ['renderScheduleSetup','showCalendar','saveCalendarDay','addCalendarEvent','applySelectedCalendarDays','showSemesterTransition','applySemesterTransition','movePlanningPeriod','moveSectionPeriod'])assert(html.includes('function '+fn+'('),fn);assert(!html.includes('V8_ISOLATED_VERIFICATION'));});
await test('P3 assets are loaded and cached without changing Schema 7 or visual/navigation authority',()=>{let html=fs.readFileSync('index.html','utf8'),sw=fs.readFileSync('sw.js','utf8'),build=fs.readFileSync('app-build.js','utf8');for(const asset of ['src/arc_v8_academic_administration.js','src/arc_schedule_authority_adapter.js']){assert(html.includes(`<script src="${asset}"></script>`));assert(sw.includes(`./${asset}`));}assert(html.includes('const CURRENT_SCHEMA_VERSION = 7;'));assert(build.includes('parity-p3-schedule-adapter-1'));assert(!/arc_schedule_authority_adapter/.test(fs.readFileSync('src/arc_titanium_shell.js','utf8')));});
await test('adapter contains no production database Student Enrollment ScheduleAssignment or UI implementation',()=>{let source=fs.readFileSync('src/arc_schedule_authority_adapter.js','utf8');assert(source.includes('arc_classroom_v8_p3_verification'));assert(!/['"]arc_classroom_v8['"]|createStudent|createEnrollment|createScheduleAssignment|document\.|innerHTML|weld_v013/.test(source));});
if(!process.exitCode)console.log(`\n${pass}/${total} ARC Stage 14 P3 Schedule authority adapter tests passed.`);
})();
