const assert=require('assert');
const crypto=require('crypto').webcrypto;
const Storage=require('../src/arc_v8_storage');
const Packages=require('../src/arc_v8_instructional_content_packages');
const Coordinator=require('../src/arc_v8_instructional_import_coordinator');
const DB=Coordinator.DATABASE_NAME;
function clone(x){return x==null?x:structuredClone(x)}
function memory(name=DB){const stores=new Map();for(const s of Object.values(Storage.STORES))stores.set(s,new Map());let n=1;function keyFor(store,row){const spec=Object.values(Coordinator.ROLE_CONTRACTS).find(x=>x.store===store);return spec?row[spec.key]:row.instructionalContentPackageRecordId}function view(target){return{get:async(s,id)=>clone(target.get(s).get(id)),add:async(s,row)=>{const k=keyFor(s,row);if(target.get(s).has(k))throw new Storage.StorageError('REQUEST_FAILED','duplicate');target.get(s).set(k,clone(row));return clone(row)},put:async(s,row)=>{target.get(s).set(keyFor(s,row),clone(row));return clone(row)},clear:async s=>target.get(s).clear(),query:async(s,index,value)=>Array.from(target.get(s).values()).filter(row=>!index?true:index==='by_package'?row.packageId===value:index==='by_package_sequence'?row.packageId===value[0]&&row.sequence===value[1]:index==='by_package_type'?row.packageId===value[0]&&row.recordType===value[1]:true).map(clone)}}return{constants:{databaseName:name},generateId:()=>`00000000-0000-4000-8000-${String(n++).padStart(12,'0')}`,read:(s,k)=>view(stores).get(s,k),query:(s,i,k)=>view(stores).query(s,i,k),async transaction(names,fn){const work=new Map(Array.from(stores,([s,m])=>[s,new Map(Array.from(m,([k,v])=>[k,clone(v)]))]));const out=await fn(view(work));for(const [s,m] of work)stores.set(s,m);return out},_stores:stores};}
function owner(db,packages,owned){return{async importPackageRecord(input){await packages.assertWriteGate(input);const spec=Coordinator.ROLE_CONTRACTS[input.roleType];if(!owned.includes(spec.owner))throw new Storage.StorageError('INVALID_PACKAGE_ROLE','owner');const row=clone(input.record);row.importPackageId=input.packageId;if(input.roleType==='COMPETENCY_VERSION'||input.roleType==='LESSON_VERSION')row.immutableContent=true;await db.transaction(spec.store,tx=>tx.add(spec.store,row));return clone(row)},async getImportedReference(input){await packages.assertAuditReadGate({packageId:input.packageId,auditAuthorized:input.auditAuthorized});const spec=Coordinator.ROLE_CONTRACTS[input.roleType],row=await db.read(spec.store,input.id);if(!row||row.importPackageId!==input.packageId)throw new Storage.StorageError('REFERENCE_NOT_FOUND','missing');return row}}}
function role(type,id='00000000-0000-4000-8000-000000000001',extra={}){const s=Coordinator.ROLE_CONTRACTS[type],fields={[s.key]:id,sourceRecordKey:`source-${id}`,...extra};if(type.endsWith('_LINK')){delete fields.sourceRecordKey;fields.sourceRelationshipIdentity=`relationship-${id}`}if(type==='LESSON_VERSION')Object.assign(fields,{instructionalAvailability:'reference_only',instructionalAcceptanceRef:null,preservationState:'preserved',ordinarySchedulingEligible:false,autoBuildEligible:false});return{reviewRecordKey:`${type}|${id}`,course:'wt',roleType:type,targetRepresentation:{targetIdentity:id,targetIdField:s.key,owner:s.owner==='curriculum'?'ArcV8CurriculumPacing':s.owner==='evidence'?'ArcV8Evidence':'ArcV8LessonPlans',method:'fixture',store:s.store,fields,targetContentHash:'a'.repeat(64)}}}
function declared(){return{contractVersion:'r2-pr1',resolvedPayloadChecksum:Coordinator.PAYLOAD_SHA256,frozenIdentityMapChecksum:Coordinator.IDENTITY_SHA256,evidenceChecksum:'e'.repeat(64),evidenceReference:'fixture',expectedRoleCount:859,expectedRetainedLinkCount:359,expectedIntentionalAbsenceCount:259,canonicalCourseContexts:['arc-course-wt','arc-course-awt'],sourceAuthorities:['fixture']}}
async function fixture(){const db=memory(),packages=Packages.create({storage:db}),curriculum=owner(db,packages,['curriculum']),evidence=owner(db,packages,['evidence']),lessons=owner(db,packages,['lessons']),coordinator=Coordinator.create({storage:db,packages,curriculum,evidence,lessons,crypto,databaseName:DB});await packages.declarePackage({packageId:'pkg',declaration:declared()});await packages.startAttempt({packageId:'pkg',attemptId:'attempt'});return{db,packages,coordinator};}
function fullModel(){const counts={STANDARD_CATALOG:2,STANDARD_CATALOG_VERSION:2,STANDARD_DEFINITION:29,STANDARD_VERSION:29,COMPETENCY_DEFINITION:60,COMPETENCY_VERSION:60,ESSENTIAL_STANDARD_DESIGNATION:10,CURRICULUM_MAP:2,CURRICULUM_MAP_VERSION:2,CURRICULUM_MAP_ITEM:56,CURRICULUM_STANDARD_LINK:80,LESSON_DEFINITION:124,LESSON_VERSION:124,LESSON_STANDARD_LINK:228,LESSON_COMPETENCY_LINK:51},roles=[];let n=1;for(const [type,count] of Object.entries(counts))for(let i=0;i<count;i++)roles.push(role(type,`00000000-0000-4000-8000-${String(n++).padStart(12,'0')}`));return{format:Coordinator.FORMAT,compilerRevision:Coordinator.COMPILER,status:'PROPOSED_UNPERSISTED',readiness:'READY_FOR_OWNER_IMPLEMENTATION',academicAuthority:'V7_ONLY',counts:{roles:859,retainedLinks:359,optionalRelationshipsAbsent:259,legacyLessonVersions:124,wtLessonCompetencyLinks:51,awtLessonCompetencyLinks:0},roles,membership:roles.map(r=>({reviewRecordKey:r.reviewRecordKey,targetIdentity:r.targetRepresentation.targetIdentity,targetStore:r.targetRepresentation.store,targetContentHash:r.targetRepresentation.targetContentHash})),nonblockingExclusions:Array.from({length:259},(_,i)=>({status:'SETTLED_OPTIONAL_RELATIONSHIP_ABSENT',i})),packageEvidence:{fixture:true}}}
function identity(payload){return{entries:payload.roles.map(r=>({reviewRecordKey:r.reviewRecordKey,targetIdentity:r.targetRepresentation.targetIdentity}))}}
let pass=0,total=0;async function test(name,fn){total++;try{await fn();pass++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1}}
(async()=>{
await test('requiring coordinator is explicit and does not open storage',async()=>{assert.equal(typeof Coordinator.create,'function');assert.equal(Coordinator.DATABASE_NAME,DB)});
await test('wrong database identity is refused',async()=>{const db=memory('arc_classroom_v8');assert.throws(()=>Coordinator.create({storage:db,packages:{},curriculum:{},evidence:{},lessons:{},crypto,databaseName:'arc_classroom_v8'}),e=>e.code==='REHEARSAL_DATABASE_REQUIRED')});
await test('wrong payload bytes refuse before storage access',async()=>{await assert.rejects(Coordinator.preflight({payloadText:'{}',identityMapText:'{}',crypto}),e=>e.code==='PAYLOAD_CHECKSUM_MISMATCH')});
await test('pure model validation accepts exact accounting and deterministic phases',async()=>{const p=fullModel(),m=await Coordinator.validateModel(p,identity(p),crypto);assert.equal(m.roles.length,859);assert.deepEqual(m.phases.map(x=>x.count),[62,120,10,60,80,248,228,51])});
await test('wrong accounting duplicate key and UUID are refused',async()=>{let p=fullModel();p.counts.roles=858;await assert.rejects(Coordinator.validateModel(p,identity(p),crypto),e=>e.code==='PACKAGE_CONTRACT_MISMATCH');p=fullModel();p.roles[1].reviewRecordKey=p.roles[0].reviewRecordKey;await assert.rejects(Coordinator.validateModel(p,identity(p),crypto),e=>e.code==='DUPLICATE_PACKAGE_IDENTITY');p=fullModel();p.roles[1].targetRepresentation.targetIdentity=p.roles[0].targetRepresentation.targetIdentity;await assert.rejects(Coordinator.validateModel(p,identity(p),crypto),e=>e.code==='DUPLICATE_PACKAGE_IDENTITY')});
await test('target primary key and unknown role/store/owner routes refuse',async()=>{for(const mutate of [p=>p.roles[0].targetRepresentation.fields.standardCatalogId='bad',p=>p.roles[0].roleType='UNKNOWN',p=>p.roles[0].targetRepresentation.store='students',p=>p.roles[0].targetRepresentation.owner='Other']){const p=fullModel();mutate(p);await assert.rejects(Coordinator.validateModel(p,identity(p),crypto))}});
await test('relaxed legacy Lesson policy and fabricated teachingGuide refuse',async()=>{for(const change of [f=>f.autoBuildEligible=true,f=>f.teachingGuide={fake:true}]){const p=fullModel(),lesson=p.roles.find(x=>x.roleType==='LESSON_VERSION');change(lesson.targetRepresentation.fields);await assert.rejects(Coordinator.validateModel(p,identity(p),crypto),e=>e.code==='LEGACY_LESSON_POLICY_VIOLATION')}});
await test('phase import has exact readback and idempotent retry',async()=>{const f=await fixture(),r=role('STANDARD_CATALOG'),model={roles:[r]};let first=await f.coordinator.runPhase({model,phase:'STANDARDS',packageId:'pkg',attemptId:'attempt'});assert.deepEqual([first.created,first.equivalent],[1,0]);let second=await f.coordinator.runPhase({model,phase:'STANDARDS',packageId:'pkg',attemptId:'attempt'});assert.deepEqual([second.created,second.equivalent],[0,1]);assert.equal(first.checksum,second.checksum)});
await test('same ID different content refuses without overwrite',async()=>{const f=await fixture(),r=role('STANDARD_CATALOG');await f.coordinator.runPhase({model:{roles:[r]},phase:'STANDARDS',packageId:'pkg',attemptId:'attempt'});r.targetRepresentation.fields.title='changed';await assert.rejects(f.coordinator.runPhase({model:{roles:[r]},phase:'STANDARDS',packageId:'pkg',attemptId:'attempt'}),e=>e.code==='PACKAGE_ROW_CONFLICT');assert.equal((await f.db.read('standard_catalogs',r.targetRepresentation.targetIdentity)).title,undefined)});
await test('same source different ID refuses',async()=>{const f=await fixture(),a=role('STANDARD_CATALOG','00000000-0000-4000-8000-000000000001'),b=role('STANDARD_CATALOG','00000000-0000-4000-8000-000000000002');b.targetRepresentation.fields.sourceRecordKey=a.targetRepresentation.fields.sourceRecordKey;await f.coordinator.runPhase({model:{roles:[a]},phase:'STANDARDS',packageId:'pkg',attemptId:'attempt'});await assert.rejects(f.coordinator.runPhase({model:{roles:[b]},phase:'STANDARDS',packageId:'pkg',attemptId:'attempt'}),e=>e.code==='SOURCE_IDENTITY_CONFLICT')});
await test('wrong package binding is a hard conflict',async()=>{const f=await fixture(),r=role('STANDARD_CATALOG');r.targetRepresentation.fields.importPackageId='other';await assert.rejects(f.coordinator.runPhase({model:{roles:[r]},phase:'STANDARDS',packageId:'pkg',attemptId:'attempt'}),e=>e.code==='PACKAGE_BINDING_MISMATCH')});
await test('phase checksum is deterministic independent of model order',async()=>{const f=await fixture(),a=role('STANDARD_CATALOG','00000000-0000-4000-8000-000000000002'),b=role('STANDARD_CATALOG','00000000-0000-4000-8000-000000000001');let x=await f.coordinator.runPhase({model:{roles:[a,b]},phase:'STANDARDS',packageId:'pkg',attemptId:'attempt'}),y=await f.coordinator.runPhase({model:{roles:[b,a]},phase:'STANDARDS',packageId:'pkg',attemptId:'attempt'});assert.equal(x.checksum,y.checksum)});
await test('controlled conflict probe proves checksum equality',async()=>{const f=await fixture(),r=role('STANDARD_CATALOG');await f.coordinator.runPhase({model:{roles:[r]},phase:'STANDARDS',packageId:'pkg',attemptId:'attempt'});const result=await f.coordinator.controlledConflictProbe({role:r,packageId:'pkg',attemptId:'attempt'});assert(result.refused);assert.equal(result.beforeChecksum,result.afterChecksum)});
await test('completion evidence requires all verified phases and exclusions',async()=>{const f=await fixture(),verification={roleCount:859,retainedLinkCount:359,intentionalAbsenceCount:259,exclusionsVerified:true,checksum:'x'},phaseSummaries=Coordinator.PHASES.map(x=>({phase:x.name,memberCount:x.count,checksum:'x',readbackVerified:true}));const e=f.coordinator.completionEvidence({verification,phaseSummaries,canonicalCoursesVerified:true,evidenceVerified:true,conflictsAbsent:true,backupRecoveryVerified:true});assert.equal(e.roleCount,859);phaseSummaries.pop();assert.throws(()=>f.coordinator.completionEvidence({verification,phaseSummaries}),x=>x.code==='COMPLETION_MODEL_INCOMPLETE')});
await test('259 exclusions never become writes and production names are not accepted',async()=>{assert.equal(Coordinator.DATABASE_NAME,DB);assert(![Storage.DATABASE_NAME,'arc_classroom_v8_engineering_verification','weld_v013','WeldingClassroomPhotoStore'].includes(Coordinator.DATABASE_NAME));const source=require('fs').readFileSync(require('path').join(__dirname,'../src/arc_v8_instructional_import_coordinator.js'),'utf8');assert(!source.includes("databaseName||Storage.DATABASE_NAME"));assert.equal(fullModel().nonblockingExclusions.length,259)});
if(!process.exitCode)console.log(`\n${pass}/${total} ARC P10D-PR1 Instructional Import Coordinator tests passed.`);
})();
