const assert=require('assert'),Storage=require('../src/arc_v8_storage'),Project=require('../src/arc_v8_project');

function memory(){
  const maps={};Object.values(Storage.STORES).forEach(s=>maps[s]=new Map());let id=1;
  const keys={students:'studentId',courses:'courseId',school_years:'schoolYearId',semesters:'semesterId',grading_periods:'gradingPeriodId',sections:'sectionId',course_enrollments:'enrollmentId',enrollment_schedule_assignments:'scheduleAssignmentId',activity_definitions:'definitionId',activity_versions:'versionId',activity_evidence_declarations:'declarationId',activity_assignments:'assignmentId',student_activities:'studentActivityId',activity_attempts:'attemptId',project_instances:'projectId',project_build_attempts:'buildId',project_checkpoint_events:'eventId',project_manual_need_events:'needEventId',project_rubric_assessments:'rubricAssessmentId'};
  const paths={project_instances:{by_student_activity:'studentActivityId',by_student:'studentId',by_enrollment:'enrollmentId',by_workflow:'workflowState'},project_build_attempts:{by_project:'projectId',by_project_sequence:['projectId','sequence'],by_state:'state'},project_checkpoint_events:{by_project:'projectId',by_build:'buildId',by_checkpoint:'checkpointCode',by_occurred_at:'occurredAt'},project_manual_need_events:{by_project:'projectId',by_occurred_at:'occurredAt'},project_rubric_assessments:{by_project:'projectId',by_lifecycle:'lifecycle',by_rubric_version:'rubricVersion'}};
  const clone=x=>x===undefined?undefined:structuredClone(x),match=(v,p,k)=>JSON.stringify(Array.isArray(p)?p.map(x=>v[x]):v[p])===JSON.stringify(k);
  function api(work){return{get:async(s,k)=>clone(work[s].get(k)),add:async(s,v)=>{let k=v[keys[s]];if(work[s].has(k))throw Error('duplicate');if(paths[s])for(const def of Object.values(paths[s]))if(Array.isArray(def)&&Array.from(work[s].values()).some(x=>match(x,def,def.map(p=>v[p]))))throw Error('duplicate index');work[s].set(k,clone(v));},put:async(s,v)=>work[s].set(v[keys[s]],clone(v)),query:async(s,i,k)=>Array.from(work[s].values()).filter(v=>!i||k===undefined||match(v,paths[s][i],k)).map(clone)}}
  return{generateId:()=>`00000000-0000-4000-8000-${(id++).toString(16).padStart(12,'0')}`,read:async(s,k)=>clone(maps[s].get(k)),add:async(s,v)=>api(maps).add(s,v),query:async(s,i,k)=>api(maps).query(s,i,k),async transaction(stores,fn){stores=Array.isArray(stores)?stores:[stores];let work={};Object.keys(maps).forEach(s=>work[s]=new Map(Array.from(maps[s]).map(([k,v])=>[k,clone(v)])));let result=await fn(api(work));stores.forEach(s=>maps[s]=work[s]);return result;},_maps:maps};
}
function fixture(){
  const storage=memory();let tick=0;const repo=Project.create({storage,actor:'instructor',now:()=>`2026-09-27T12:${String(Math.floor(tick/60)).padStart(2,'0')}:${String(tick++%60).padStart(2,'0')}Z`});
  const put=(s,x)=>storage._maps[s].set(x[Object.keys(x).find(k=>/Id$/.test(k))],x),S=Storage.STORES;
  put(S.students,{studentId:'taylor',lifecycle:'active'});put(S.students,{studentId:'alex',lifecycle:'active'});put(S.enrollments,{enrollmentId:'en-taylor',studentId:'taylor',courseId:'wt',schoolYearId:'y',lifecycle:'active'});put(S.enrollments,{enrollmentId:'en-alex',studentId:'alex',courseId:'wt',schoolYearId:'y',lifecycle:'active'});
  put(S.activityDefinitions,{definitionId:'coupon',type:'Project',title:'Welding Coupon Holder'});put(S.activityVersions,{versionId:'coupon-v1',definitionId:'coupon',versionNumber:1,projectCheckpoints:[{code:'material',name:'Material Preparation',order:1,enabled:true},{code:'fit-up',name:'Fit-Up',order:2,enabled:true,requiresInstructorReview:true},{code:'tack',name:'Tack & Pre-Weld Check',order:3,enabled:true,requiresInstructorReview:true}]});
  put(S.activityDefinitions,{definitionId:'practice',type:'Practice',title:'Practice'});put(S.activityVersions,{versionId:'practice-v1',definitionId:'practice',versionNumber:1});
  put(S.studentActivities,{studentActivityId:'sa-taylor',studentId:'taylor',enrollmentId:'en-taylor',versionId:'coupon-v1'});put(S.studentActivities,{studentActivityId:'sa-taylor-2',studentId:'taylor',enrollmentId:'en-taylor',versionId:'coupon-v1'});put(S.studentActivities,{studentActivityId:'sa-alex',studentId:'alex',enrollmentId:'en-alex',versionId:'coupon-v1'});put(S.studentActivities,{studentActivityId:'sa-practice',studentId:'alex',enrollmentId:'en-alex',versionId:'practice-v1'});
  return{repo,storage,S};
}
const rubric=(projectId,extra={})=>Object.assign({projectId,rubricVersion:'project-v1',criteria:[{criterionCode:'measurement_accuracy',score:80},{criterionCode:'fit_up_fabrication',score:90},{criterionCode:'welding_quality',score:100},{criterionCode:'workmanship_finished_quality',score:70}]},extra);
let passed=0,total=0;async function test(name,fn){total++;try{await fn();passed++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1}}
(async()=>{
await test('Project prerequisite, one-per-activity, exact Version checkpoints, and integrity',async()=>{let{repo}=fixture();await assert.rejects(repo.createProject({studentActivityId:'missing'}),e=>e.code==='REFERENCE_NOT_FOUND');await assert.rejects(repo.createProject({studentActivityId:'sa-practice'}),e=>e.code==='NOT_PROJECT_ACTIVITY');let x=await repo.createProject({studentActivityId:'sa-taylor'});assert.equal(x.build.sequence,1);assert.equal(x.needEvent.need,'Ready to Work');await assert.rejects(repo.createProject({studentActivityId:'sa-taylor'}),e=>e.code==='DUPLICATE_PROJECT');await assert.rejects(repo.appendCheckpointEvent({projectId:x.project.projectId,buildId:x.build.buildId,checkpointCode:'missing',eventType:'Started'}),e=>e.code==='INVALID_CHECKPOINT');await assert.rejects(repo.appendCheckpointEvent({projectId:x.project.projectId,buildId:'wrong',checkpointCode:'material',eventType:'Started'}),e=>e.code==='INTEGRITY_MISMATCH');});
await test('Taylor lifecycle derives review and restores preserved Ready to Work',async()=>{let{repo,storage,S}=fixture(),x=await repo.createProject({studentActivityId:'sa-taylor'}),base={projectId:x.project.projectId,buildId:x.build.buildId};for(const e of [['material','Started'],['material','Verified'],['fit-up','Started']])await repo.appendCheckpointEvent({...base,checkpointCode:e[0],eventType:e[1]});let p=await repo.operationalState(base.projectId);assert.equal(p.displayNeed,'Ready to Work');assert.equal(p.currentCheckpoint.name,'Fit-Up');await repo.appendCheckpointEvent({...base,checkpointCode:'fit-up',eventType:'Ready for Review'});p=await repo.operationalState(base.projectId);assert.equal(p.displayNeed,'Instructor Review — Fit-Up');assert.equal(p.manualNeed,'Ready to Work');await repo.appendCheckpointEvent({...base,checkpointCode:'fit-up',eventType:'Verified'});p=await repo.operationalState(base.projectId);assert.equal(p.displayNeed,'Ready to Work');assert.equal(p.upNext.name,'Tack & Pre-Weld Check');assert.equal((await storage.query(S.projectInstances)).length,1);assert.deepEqual((await repo.operationalState(base.projectId)).checkpointStates,p.checkpointStates);});
await test('Needs More Work removes derived review and keeps append-first history',async()=>{let{repo,storage,S}=fixture(),x=await repo.createProject({studentActivityId:'sa-taylor'}),base={projectId:x.project.projectId,buildId:x.build.buildId,checkpointCode:'fit-up'};await repo.appendCheckpointEvent({...base,eventType:'Started'});await repo.appendCheckpointEvent({...base,eventType:'Ready for Review'});await repo.appendCheckpointEvent({...base,eventType:'Needs More Work'});let p=await repo.operationalState(base.projectId);assert.equal(p.waitingForReview,false);assert.equal(p.checkpointStates['fit-up'].status,'in_progress');assert.equal(p.displayNeed,'Ready to Work');assert.equal((await storage.query(S.projectCheckpointEvents,'by_project',base.projectId)).length,3);});
await test('active Project rule and authorized exception',async()=>{let{repo}=fixture();await repo.createProject({studentActivityId:'sa-taylor'});await assert.rejects(repo.createProject({studentActivityId:'sa-taylor-2'}),e=>e.code==='ACTIVE_PROJECT_EXISTS');assert((await repo.createProject({studentActivityId:'sa-taylor-2',authorizeAdditionalActive:true})).project);});
await test('authorized restart is atomic, preserves history and creates no ActivityAttempt',async()=>{let{repo,storage,S}=fixture(),x=await repo.createProject({studentActivityId:'sa-taylor'});await repo.appendCheckpointEvent({projectId:x.project.projectId,buildId:x.build.buildId,checkpointCode:'material',eventType:'Verified'});await assert.rejects(repo.restartBuild({projectId:x.project.projectId,expectedProjectRevision:1,expectedBuildRevision:1,reason:'scrap'}),e=>e.code==='UNAUTHORIZED_RESTART');let r=await repo.restartBuild({projectId:x.project.projectId,expectedProjectRevision:1,expectedBuildRevision:1,authorized:true,reason:'fabrication failure'});assert.equal(r.created.sequence,2);assert.equal((await storage.query(S.projectCheckpointEvents,'by_build',r.ended.buildId)).length,1);assert.equal((await storage.query(S.projectCheckpointEvents,'by_build',r.created.buildId)).length,0);assert.equal((await storage.query(S.activityAttempts)).length,0);await assert.rejects(repo.restartBuild({projectId:x.project.projectId,expectedProjectRevision:1,expectedBuildRevision:1,authorized:true}),e=>e.code==='WRITE_CONFLICT');assert.equal((await storage.query(S.projectBuilds,'by_project',x.project.projectId)).length,2);});
await test('manual need and workflow writes use optimistic revisions and valid transitions',async()=>{let{repo}=fixture(),x=await repo.createProject({studentActivityId:'sa-taylor'});let n=await repo.setManualNeed({projectId:x.project.projectId,expectedProjectRevision:1,need:'Material needed'});assert.equal(n.projectRevision,2);await assert.rejects(repo.setManualNeed({projectId:x.project.projectId,expectedProjectRevision:1,need:'stale'}),e=>e.code==='WRITE_CONFLICT');let p=await repo.transitionProject(x.project.projectId,2,'In Progress');await assert.rejects(repo.transitionProject(x.project.projectId,2,'Paused — Completion Opportunity Preserved'),e=>e.code==='WRITE_CONFLICT');await assert.rejects(repo.transitionProject(x.project.projectId,p.revision,'Finalized'),e=>e.code==='INVALID_PROJECT_TRANSITION');p=await repo.transitionProject(x.project.projectId,p.revision,'Paused — Completion Opportunity Preserved',{reason:'quarter boundary'});assert.equal(p.pauseContext.reason,'quarter boundary');p=await repo.transitionProject(x.project.projectId,p.revision,'In Progress');assert.equal(p.workflowState,'In Progress');});
await test('rubric weighting, N/A redistribution, validation and append-first correction',async()=>{let{repo,storage,S}=fixture(),x=await repo.createProject({studentActivityId:'sa-taylor'});let r=await repo.recordRubric(rubric(x.project.projectId));assert.equal(r.derivedPercent,85);let na=rubric(x.project.projectId);na.criteria[3]={criterionCode:'workmanship_finished_quality',applicable:false};let r2=await repo.recordRubric(na);assert.equal(r2.derivedPercent,90);await assert.rejects(repo.recordRubric({projectId:x.project.projectId,criteria:[]}),e=>e.code==='INVALID_RUBRIC');let corrected=await repo.recordRubric(rubric(x.project.projectId,{supersedesRubricAssessmentId:r.rubricAssessmentId,correctionReason:'entry correction'}));assert.equal(corrected.supersedesRubricAssessmentId,r.rubricAssessmentId);assert.equal((await storage.query(S.projectRubrics,'by_project',x.project.projectId)).length,3);});
await test('finalization requires workflow and rubric, closes Build, and blocks restart',async()=>{let{repo}=fixture(),x=await repo.createProject({studentActivityId:'sa-taylor'});await assert.rejects(repo.finalizeProject({projectId:x.project.projectId,expectedProjectRevision:1}),e=>e.code==='INVALID_PROJECT_WORKFLOW');let p=await repo.transitionProject(x.project.projectId,1,'In Progress');p=await repo.transitionProject(x.project.projectId,p.revision,'Ready for Final Assessment');await assert.rejects(repo.finalizeProject({projectId:x.project.projectId,expectedProjectRevision:p.revision}),e=>e.code==='RUBRIC_REQUIRED');await repo.recordRubric(rubric(x.project.projectId));let done=await repo.finalizeProject({projectId:x.project.projectId,expectedProjectRevision:p.revision});assert.equal(done.project.workflowState,'Finalized');assert.equal(done.build.state,'Completed');await assert.rejects(repo.restartBuild({projectId:x.project.projectId,expectedProjectRevision:done.project.revision,expectedBuildRevision:done.build.revision,authorized:true}),e=>e.code==='PROJECT_FINALIZED');});
await test('insufficient evidence closure creates no fake rubric',async()=>{let{repo,storage,S}=fixture(),x=await repo.createProject({studentActivityId:'sa-taylor'}),p=await repo.transitionProject(x.project.projectId,1,'Closed — Insufficient Project Evidence',{reason:'insufficient work'});assert.equal(p.lifecycle,'closed');assert.equal((await storage.query(S.projectRubrics,'by_project',x.project.projectId)).length,0);});
await test('current store boundary excludes unauthorized later runtime domains',async()=>{for(const name of Object.values(Storage.STORES)){assert(!/photo/i.test(name),name)}});
if(!process.exitCode)console.log(`\n${passed}/${total} ARC v8 Project Runtime tests passed.`);
})();
