const assert=require('assert'),fs=require('fs'),Adapter=require('../src/arc_attendance_authority_adapter');
let pass=0,total=0;async function test(name,fn){total++;try{await fn();pass++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1}}
function harness(){let calls=[],scope={studentId:'student-1',enrollmentId:'enrollment-1',scheduleAssignmentId:'assignment-1',sectionId:'section-1',courseId:'course-wt',schoolYearId:'year-1',semesterId:'semester-1'},attendance={
  currentAttendance:async x=>(calls.push(['current',x]),null),recordAttendance:async x=>(calls.push(['record',x]),x),correctAttendance:async x=>(calls.push(['correct',x]),x),attendancePassProjection:async x=>(calls.push(['projection',x]),{attendance:[],passes:[]}),createPassEvent:async x=>(calls.push(['pass-start',x]),x),closePassEvent:async(...x)=>(calls.push(['pass-return',...x]),x),deriveAttendanceGradeReviews:async x=>(calls.push(['review',x]),[]),confirmAttendanceGradeDecision:async x=>(calls.push(['confirm',x]),x)
},projection={fromV8:async()=>({scopeForStudent:id=>id==='student-1'?scope:null,contextForStudent:()=>({currentSection:{period:'4'}})})},adapter=Adapter.create({authorityState:Adapter.states.V8_ISOLATED_VERIFICATION,databaseName:Adapter.isolatedDatabaseName,attendance,projection,storage:{}});return{adapter,attendance,scope,calls};}
(async()=>{
await test('P5 authority is exclusive, isolated, and never dual-write',async()=>{assert.throws(()=>Adapter.create({authorityState:'V8_AUTHORITATIVE'}),e=>e.code==='AUTHORITY_STATE_BLOCKED');assert.throws(()=>Adapter.create({authorityState:Adapter.states.V8_ISOLATED_VERIFICATION,databaseName:'arc_classroom_v8',attendance:{},projection:{},storage:{}}),e=>e.code==='ISOLATED_AUTHORITY_REQUIRED');let n=0,v7=Adapter.create({authorityState:'V7_ONLY'});assert.equal(v7.runLegacy('attendance-set',{},()=>++n),1);assert.equal(n,1);await assert.rejects(v7.runIsolated('attendance-set',{}),e=>e.code==='V8_AUTHORITY_BLOCKED');assert.equal(v7.dualWrite,false);});
await test('all Attendance states use the single P4 stable academic scope',async()=>{for(const status of ['Present','Unexcused Absence','Excused Absence','Tardy','School Activity','Left Early','No Class']){let h=harness(),row=await h.adapter.runIsolated('attendance-set',{studentId:'student-1',sectionId:'section-1',schoolDate:'2026-10-05',status});assert.equal(row.enrollmentId,'enrollment-1');assert.equal(row.scheduleAssignmentId,'assignment-1');assert.equal(row.scheduledSessionId,'4');assert.equal(row.status,status)}});
await test('corrections are current-record and stale-revision aware',async()=>{let h=harness();h.attendance.currentAttendance=async()=>({attendanceRecordId:'attendance-1',revision:7,status:'Tardy'});await h.adapter.runIsolated('attendance-set',{studentId:'student-1',sectionId:'section-1',schoolDate:'2026-10-05',status:'Excused Absence',reason:'office correction'});let c=h.calls.find(x=>x[0]==='correct')[1];assert.equal(c.supersedesAttendanceRecordId,'attendance-1');assert.equal(c.expectedAttendanceRevision,7);assert.equal(c.reason,'office correction');});
await test('Pass start return history and Student profile projection share P4 scope',async()=>{let h=harness();await h.adapter.runIsolated('pass-start',{studentId:'student-1',sectionId:'section-1',schoolDate:'2026-10-05',reasonCode:'nurse',leftAt:'2026-10-05T10:00:00Z'});await h.adapter.runIsolated('pass-return',{studentId:'student-1',sectionId:'section-1',schoolDate:'2026-10-05',passEventId:'pass-1',expectedRevision:1,returnedAt:'2026-10-05T10:09:00Z'});await h.adapter.runIsolated('attendance-pass-projection',{studentId:'student-1',sectionId:'section-1',schoolDate:'2026-10-05'});assert.equal(h.calls.find(x=>x[0]==='pass-start')[1].enrollmentId,'enrollment-1');assert.deepEqual(h.calls.find(x=>x[0]==='pass-return').slice(1),['pass-1',1,'2026-10-05T10:09:00Z']);assert.equal(h.calls.find(x=>x[0]==='projection')[1].sectionId,'section-1');});
await test('duplicate names cannot substitute identity and moved Section mismatch is refused',async()=>{let h=harness();await assert.rejects(h.adapter.runIsolated('attendance-set',{studentId:'same-name-other-id',sectionId:'section-1',schoolDate:'2026-10-05',status:'Present'}),e=>e.code==='ACADEMIC_SCOPE_REQUIRED');await assert.rejects(h.adapter.runIsolated('attendance-set',{studentId:'student-1',sectionId:'old-section',schoolDate:'2026-10-05',status:'Present'}),e=>e.code==='ACADEMIC_SCOPE_MISMATCH');});
await test('Attendance-linked grade decisions remain review-only until explicit confirmation',async()=>{let h=harness();await h.adapter.runIsolated('grade-review',{studentId:'student-1',sectionId:'section-1',schoolDate:'2026-10-05',attendanceRecordId:'a1'});assert.equal(h.calls.filter(x=>x[0]==='confirm').length,0);await assert.rejects(h.adapter.runIsolated('grade-confirm',{studentId:'student-1',sectionId:'section-1',schoolDate:'2026-10-05',instructorConfirmed:false}),e=>e.code==='INSTRUCTOR_CONFIRMATION_REQUIRED');await h.adapter.runIsolated('grade-confirm',{studentId:'student-1',sectionId:'section-1',schoolDate:'2026-10-05',instructorConfirmed:true});assert.equal(h.calls.filter(x=>x[0]==='confirm').length,1);});
await test('normal ARC preserves UI behavior through one V7 mutation boundary',()=>{let html=fs.readFileSync('index.html','utf8');assert(html.includes('ArcAttendanceAuthorityAdapter.create({ authorityState: "V7_ONLY" })'));for(const action of ['attendance-set','attendance-mark-all-present','pass-start','pass-return'])assert(html.includes(`attendanceAuthorityAdapter.runLegacy("${action}"`),action);assert(html.includes('attendance-linked grade consequences require teacher confirmation'));});
await test('P5 adds no store or structural version and is publication-integrated',()=>{let adapter=fs.readFileSync('src/arc_attendance_authority_adapter.js','utf8'),storage=fs.readFileSync('src/arc_v8_storage.js','utf8'),sw=fs.readFileSync('sw.js','utf8'),html=fs.readFileSync('index.html','utf8');assert(storage.includes('var IDB_VERSION=12'));assert(!adapter.includes('createObjectStore'));assert(!adapter.includes("arc_classroom_v8'"));assert(sw.includes('./src/arc_attendance_authority_adapter.js'));assert(html.includes('src/arc_attendance_authority_adapter.js'));assert(fs.readFileSync('app-build.js','utf8').includes('parity-p5-attendance-pass-1-parity-p6-project-technical-1-parity-p7-competency-evidence-open-shop-1-parity-p8a-behavior-structural-foundation-1-parity-p8-workplace-safety-behavior-1-parity-p9-gradebook-authority-1-parity-p10a-unified-student-history-1'));});
if(!process.exitCode)console.log(`\n${pass}/${total} ARC Stage 14 P5 Attendance/Pass adapter tests passed.`);
})();
