const assert=require('assert'),fs=require('fs'),Storage=require('../src/arc_v8_storage'),C=require('../parity/stage14_v7_v8_parity_contract');
const doc=fs.readFileSync('docs/ARC_STAGE_14_V7_V8_NO_REGRESSION_PARITY_P10C_A1.md','utf8'),index=fs.readFileSync('index.html','utf8'),build=fs.readFileSync('app-build.js','utf8'),sw=fs.readFileSync('sw.js','utf8');
let pass=0,total=0;function test(name,fn){total++;try{fn();pass++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1}}
test('design starts from exact P10B-UI authority and structural implementation preserves Schema 8',()=>{assert(doc.includes('cb1c07b075e3852abae08f82a5f5d22dd2dea950'));assert(doc.includes('f72e0f64647e43dd536098a10cfbd3983b375c54'));assert.equal(Storage.SCHEMA_VERSION,8);assert.equal(Storage.IDB_VERSION,13);assert.equal(Object.values(Storage.STORES).length,73);assert(index.includes('const CURRENT_SCHEMA_VERSION = 7;'));});
test('existing Lesson inventory and fields are recorded exactly',()=>{for(const value of ['WT | 47 | 4 | 51','AWT | 67 | 6 | 73','`learningTargets`','`criteria`','`strategies`','`assessment`'])assert(doc.includes(value),value);for(const fn of ['renderLessonBank','scheduleLessonFromBank','confirmScheduleLesson','showAutoBuildPacing','confirmAutoBuildPacing'])assert(index.includes('function '+fn),fn);});
test('six-store normalized target and exact structural target are frozen',()=>{for(const store of ['lesson_definitions','lesson_versions','lesson_version_standard_links','lesson_version_competency_links','lesson_version_curriculum_links','lesson_version_activity_links'])assert(doc.includes('`'+store+'`'),store);assert(doc.includes('IndexedDB 13 / 73 stores'));assert(doc.includes('12 → 13'));for(const store of ['lesson_definitions','lesson_versions','lesson_version_standard_links','lesson_version_competency_links','lesson_version_curriculum_links','lesson_version_activity_links'])assert(Object.values(Storage.STORES).includes(store),store);});
test('P10B owns placement and Lesson authority cannot duplicate it',()=>{for(const value of ['`section_pacing_plans`','`section_pacing_events`','`section_pacing_snapshots`','No new Lesson-placement store'])assert(doc.includes(value),value);assert(doc.includes('Future Semester placement remains absent'));});
test('relationships reference P10B P7 and P6 versions without copied authority',()=>{for(const value of ['`standardVersionId`','`competencyVersionId`','`curriculumMapItemId`','`activityVersionId`','`declarationId`'])assert(doc.includes(value),value);assert(doc.includes('No Lesson record creates Evidence'));});
test('Auto Build is previewed instructor-controlled and commits only P10B authority',()=>{for(const value of ['`previewLessonAutoBuild`','`commitLessonAutoBuild`','preview fingerprint','Completed pacing items and actual history cannot be removed'])assert(doc.includes(value),value);assert(doc.includes('creates no Lesson definition/version/link'));});
test('reconciliation and unresolved boundaries remain explicit',()=>{for(const state of ['`RECONCILE_AND_PORT`','`REBUILD_IN_V8`','`DISCARD`','`RETAIN_OUTSIDE_V8`','`UNRESOLVED`'])assert(doc.includes(state),state);assert(doc.includes('Resources | `UNRESOLVED`'));assert(doc.includes('No Lesson approval workflow is frozen'));});
test('structural stage makes no build cache service-worker or Lesson service runtime change',()=>{assert(build.includes('parity-p10b-ui-1'));assert(!build.includes('p10c'));assert(!sw.includes('lesson_plan'));assert(!index.includes('ArcV8Lesson'));assert.equal(C.authorityState,'V7_ONLY');let row=C.rows.find(x=>x.id==='lesson-plans');assert.equal(row.status,'service-ready');assert(row.evidence.automated.includes('arc_lesson_plan_design_authority.test.js'));assert.equal(row.evidence.samsung.length,0);});
if(!process.exitCode)console.log(`\n${pass}/${total} ARC P10C-A1 Lesson Plan design-authority tests passed.`);
