const assert=require('assert'),fs=require('fs'),crypto=require('crypto').webcrypto;
const Storage=require('../src/arc_v8_storage'),Backup=require('../src/arc_v8_backup_recovery'),Physical=require('../src/arc_instructional_reference_physical_verification');
let passed=0,failed=0;async function test(name,fn){try{await fn();passed++;console.log('PASS',name)}catch(error){failed++;console.error('FAIL',name,error)}}
const DB=Physical.DATABASE_NAME,PKG=Physical.PACKAGE_ID,stores=Backup.EXPECTED_STORES.slice();
const roleCounts={standard_catalogs:2,standard_catalog_versions:2,standard_definitions:29,standard_versions:29,essential_standard_designations:10,competency_definitions:60,competency_versions:60,curriculum_maps:2,curriculum_map_versions:2,curriculum_map_items:56,curriculum_item_standard_links:80,lesson_definitions:124,lesson_versions:124,lesson_version_standard_links:228,lesson_version_competency_links:51};
const baseCounts={metadata:1,migration_log:14,infrastructure_records:3,courses:2,instructional_content_packages:12};
function clone(value){return structuredClone(value)}
function packageFixture(change){let rows={};stores.forEach(name=>rows[name]=[]);rows.metadata=[{key:'database',schemaFamily:'arc-classroom',schemaVersion:8,indexedDbVersion:14,initializationState:'ready'}];rows.migration_log=Array.from({length:14},(_,i)=>({id:'migration-'+i}));rows.infrastructure_records=[{id:'production-v8-initialization-manifest',authorityState:'V7_ONLY',classroomAuthorityTransferred:false,realStudentDataAuthorized:false},{id:'production-v8-reconciliation-manifest'},{id:'database-protection',mode:'Production/Classroom Protected'}];rows.courses=[{courseId:'arc-course-wt'},{courseId:'arc-course-awt'}];rows.instructional_content_packages=Array.from({length:12},(_,i)=>({instructionalContentPackageRecordId:'p'+(i+1)}));Object.keys(roleCounts).forEach(name=>{if(name==='lesson_versions')rows[name]=Array.from({length:124},(_,i)=>({lessonVersionId:'lesson-v'+i,importPackageId:PKG,instructionalAvailability:'reference_only',ordinarySchedulingEligible:false,autoBuildEligible:false,teachingGuide:null}));else rows[name]=Array.from({length:roleCounts[name]},(_,i)=>({id:name+'-'+i,importPackageId:PKG}));});let manifest={databaseName:DB,schemaVersion:8,indexedDbVersion:14,storeInventory:stores.slice(),totalRecordCount:891,stores:{},packageIntegrity:{checksum:'package-checksum'}};stores.forEach(name=>manifest.stores[name]={recordCount:rows[name].length,checksum:name+'-checksum'});if(change)change({rows,manifest});return{manifest,stores:rows}}
function history(){return Array.from({length:12},(_,i)=>({packageId:PKG,sequence:i+1,recordType:i===11?'PACKAGE_AVAILABLE':'EVENT_'+(i+1)}))}
function boundary(){return{getStandards:async({course})=>({standards:Array.from({length:course==='WT'?9:20})}),getEssentialStandards:async({course})=>({designations:Array.from({length:course==='WT'?4:6})}),getCurriculumMap:async({course})=>({items:Array.from({length:course==='WT'?29:27},(_,i)=>({curriculumMapItemId:course.toLowerCase()+'-item-'+i}))}),getCurriculumItem:async({curriculumMapItemId})=>({curriculumMapItemId}),getCurriculumCoverage:async()=>({covered:true})}}
function environment(options={}){let inspectCalls=0,storageCalls=0,closed=0,exports=0,gateCalls=0;let pre=packageFixture(),post=options.mutatePost?packageFixture(x=>x.manifest.stores.courses.checksum='changed'):clone(pre);let backup={exportBackup:async()=>{exports++;let pkg=exports===1?pre:post;return{text:exports===1?'pre-backup':'post-backup',package:clone(pkg),audit:{healthy:true,errorCount:0,warningCount:0}}},verifyPackage:async raw=>({verified:true,package:clone(raw==='post-backup'?post:pre),recordCount:891}),auditDatabase:async()=>({healthy:true,errorCount:0,warningCount:0})};let services={packages:{assertOrdinaryReadGate:async()=>{gateCalls++},getPackageHistory:async()=>history()},curriculum:{},lessons:{getCourseLessons:async()=>[],getAutoBuildEligibleLessons:async()=>[],getLessonVersion:async()=>{throw new Storage.StorageError('LESSON_REFERENCE_ONLY','reference only')}},backup};let inspected=options.inspection||{databaseName:DB,indexedDbVersion:14,storeNames:stores,connection:{close(){closed++}}};let api=Physical.create({crypto,inspector:{inspect:async()=>{inspectCalls++;return inspected}},services,storageFactory:()=>{storageCalls++;throw Error('must not open')},boundaryFactory:()=>boundary()});return{api,get inspectCalls(){return inspectCalls},get storageCalls(){return storageCalls},get closed(){return closed},get gateCalls(){return gateCalls}}}
;(async()=>{
await test('construction is inert and exposes only four read-only operations',async()=>{let e=environment();assert.equal(e.inspectCalls,0);assert.deepEqual(Object.keys(e.api).sort(),['capturePostBackupAndVerify','capturePreBackup','constants','inspectExactStructure','runReferenceVerification'].sort());for(const banned of ['write','put','delete','reset','restore','upgrade','import','markAvailable','Student','pacing'])assert(!Object.keys(e.api).join(' ').includes(banned))});
await test('exact structure holds inspection until same-version services are established',async()=>{let e=environment(),x=await e.api.inspectExactStructure();assert.equal(x.indexedDbVersion,14);assert.equal(x.storeCount,74);assert.equal(e.inspectCalls,1);assert.equal(e.closed,0);await e.api.capturePreBackup();assert.equal(e.closed,1);assert.equal(e.storageCalls,0)});
for(const [label,inspection] of [['older',{databaseName:DB,indexedDbVersion:13,storeNames:stores,connection:{close(){}}}],['newer',{databaseName:DB,indexedDbVersion:15,storeNames:stores,connection:{close(){}}}],['missing store',{databaseName:DB,indexedDbVersion:14,storeNames:stores.slice(1),connection:{close(){}}}],['extra store',{databaseName:DB,indexedDbVersion:14,storeNames:stores.concat('extra'),connection:{close(){}}}],['wrong database',{databaseName:'other',indexedDbVersion:14,storeNames:stores,connection:{close(){}}}]]){
  await test(label+' structure fails before versioned owner factory',async()=>{let e=environment({inspection});await assert.rejects(e.api.inspectExactStructure(),error=>error.code==='REFERENCE_STRUCTURE_MISMATCH');assert.equal(e.storageCalls,0)});
}
await test('exact PA2-shaped state verifies owner counts package and Lesson safeguards',async()=>{let e=environment();await e.api.inspectExactStructure();let pre=await e.api.capturePreBackup();assert(pre.verified);assert.equal(pre.recordCount,891);let result=await e.api.runReferenceVerification();assert.deepEqual(result.counts,{wt:{standards:9,essential:4,curriculumItems:29},awt:{standards:20,essential:6,curriculumItems:27}});assert.equal(result.packageEvents,12);assert(result.noEvent13);assert(result.courseSeparation);assert(result.ordinaryReadGateConsulted);assert.deepEqual(result.legacyLessons,{preserved:124,ordinaryWT:0,ordinaryAWT:0,autoBuildWT:0,autoBuildAWT:0,directReadCode:'LESSON_REFERENCE_ONLY'});assert(e.gateCalls>=1)});
await test('PRE backup is mandatory before owner verification',async()=>{let e=environment();await assert.rejects(e.api.runReferenceVerification(),error=>error.code==='REFERENCE_PRE_BACKUP_REQUIRED')});
await test('POST capture proves all canonical stores and migration log unchanged',async()=>{let e=environment();await e.api.capturePreBackup();await e.api.runReferenceVerification();let result=await e.api.capturePostBackupAndVerify();assert(result.verified&&result.nonmutating);assert.equal(result.indexedDbVersion,14);assert.equal(result.storeCount,74);assert.equal(result.recordCount,891);assert.equal(result.packageEvents,12);assert(result.migrationLogUnchanged);assert.deepEqual(result.audit,{healthy:true,errorCount:0,warningCount:0})});
await test('canonical store checksum change fails nonmutation proof',async()=>{let e=environment({mutatePost:true});await e.api.capturePreBackup();await e.api.runReferenceVerification();await assert.rejects(e.api.capturePostBackupAndVerify(),error=>error.code==='REFERENCE_NONMUTATION_FAILED')});
await test('engineering page is explicit read-only and load remains inert',async()=>{let html=fs.readFileSync('engineering/arc_instructional_reference_verification.html','utf8'),page=fs.readFileSync('engineering/arc_instructional_reference_verification_page.js','utf8');assert(html.includes('ENGINEERING / READ-ONLY PHYSICAL VERIFICATION'));assert(html.includes('No real Student data'));assert(html.includes('V7_ONLY'));for(const id of ['inspectStructure','capturePre','runReference','capturePost'])assert(html.includes(`id="${id}"`));for(const forbidden of ['markAvailable','restoreBackup','resetDevelopmentDatabase','enableProtectedMode','upgradeProtectedProduction'])assert(!html.includes(forbidden)&&!page.includes(forbidden));assert(page.includes('download(value.postBackup||value)'));assert(!/\.inspectExactStructure\(\)|\.capturePreBackup\(\)|\.runReferenceVerification\(\)|\.capturePostBackupAndVerify\(\)/.test(page.split("addEventListener('click'")[0]))});
await test('service worker gives engineering navigation its own cache target',async()=>{let sw=fs.readFileSync('sw.js','utf8');assert(sw.includes("./engineering/arc_instructional_reference_verification.html"));assert(sw.includes("url.pathname.endsWith('/engineering/arc_instructional_reference_verification.html')?'./engineering/arc_instructional_reference_verification.html':'./index.html'"))});
await test('normal ARC remains Schema 7 and does not load boundary or verifier',async()=>{let index=fs.readFileSync('index.html','utf8');assert(index.includes('CURRENT_SCHEMA_VERSION = 7'));assert(index.includes('V7_ONLY'));assert(!index.includes('arc_instructional_reference_boundary'));assert(!index.includes('arc_instructional_reference_physical_verification'));assert(!index.includes('arc_instructional_reference_verification'))});
await test('future Pages gate pins verification assets and normal-ARC exclusions',async()=>{let workflow=fs.readFileSync('.github/workflows/pages-live-verification.yml','utf8');for(const path of ['src/arc_instructional_reference_boundary.js','src/arc_instructional_reference_physical_verification.js','engineering/arc_instructional_reference_verification.html','engineering/arc_instructional_reference_verification_page.js'])assert(workflow.includes(path),path);assert(workflow.includes('Normal ARC must not load the instructional-reference physical verification helper.'))});
console.log(`RESULT ${passed}/${passed+failed}`);if(failed)process.exit(1);
})().catch(error=>{console.error(error);process.exit(1)});
