const assert=require('assert'),fs=require('fs'),Coordinator=require('../src/arc_v8_production_academic_configuration'),Capture=require('../src/arc_v7_schedule_configuration_capture');
const fixture=JSON.parse(fs.readFileSync('tests/fixtures/arc_current_editable_school_config_parity_fixture_20261004.json','utf8')).currentStateExample;
function config(){return{schoolYear:{key:'2026-27',label:'2026-27',startDate:'2026-08-03',endDate:'2027-07-30'},semesters:[{key:'s1',code:'S1',label:'Semester 1',startDate:'2026-08-03',endDate:'2026-12-31',order:1,gradingPeriods:[{key:'q1',code:'Q1',label:'Quarter 1',startDate:'2026-08-03',endDate:'2026-10-14',order:1}]}],currentSemesterKey:'s1',scheduleSnapshot:structuredClone(fixture)};}
function liveState(){let c=config();return Object.assign({},structuredClone(fixture),{academicYear:c.schoolYear.label,semester:c.semesters[0].label,academicStructure:{version:1,schoolYear:c.schoolYear,semesters:c.semesters,currentSemesterKey:c.currentSemesterKey},students:[{id:'private'}],academicStructureHistory:[{reason:'private audit'}]});}
let pass=0,total=0;function test(name,fn){total++;try{fn();pass++;console.log('PASS',name);}catch(e){console.error('FAIL',name,e);process.exitCode=1;}}
test('review composes canonical Courses structured boundaries and migration evidence',()=>{let r=Coordinator.review(config());assert.equal(r.academic.courseManifest[0].courseId,'arc-course-wt');assert.equal(r.migrationPlan.planVersion,'schedule-configuration-migration-plan-1');assert(r.readyForApply);});
test('review requires explicit current Semester authority',()=>{let c=config();delete c.currentSemesterKey;assert.throws(()=>Coordinator.review(c),x=>x.code==='CURRENT_SEMESTER_REQUIRED');});
test('review requires explicit schedule snapshot',()=>{let c=config();delete c.scheduleSnapshot;assert.throws(()=>Coordinator.review(c),x=>x.code==='SCHEDULE_SNAPSHOT_REQUIRED');});
test('capture reads weld_v013 only',()=>{let keys=[],r=Capture.capture({getItem:k=>(keys.push(k),JSON.stringify(fixture))});assert.deepEqual(keys,['weld_v013']);assert.equal(r.sourceKey,'weld_v013');});
test('capture strips nonconfiguration families',()=>{let state={...fixture,students:[{id:'private'}],attendance:[{id:'private'}]},r=Capture.capture({getItem:()=>JSON.stringify(state)});assert(!('students'in r.snapshot));assert(!('attendance'in r.snapshot));});
test('captured Academic Structure composes directly with captured schedule for review',()=>{let captured=Capture.capture({getItem:()=>JSON.stringify(liveState())}),input=Object.assign({},captured.snapshot.academicStructure,{scheduleSnapshot:captured.snapshot}),reviewed=Coordinator.review(input);assert(reviewed.readyForApply);assert.equal(reviewed.academic.currentSemesterKey,'s1');assert.equal(reviewed.migrationPlan.sectionPlacementIntents.length,6);assert(!('students'in captured.snapshot));assert(!('academicStructureHistory'in captured.snapshot));});
test('malformed present Academic Structure fails closed while absence remains an honest capture',()=>{let absent=Capture.capture({getItem:()=>JSON.stringify(fixture)});assert(!('academicStructure'in absent.snapshot));let state=liveState();state.academicStructure.currentSemesterKey='missing';assert.throws(()=>Capture.capture({getItem:()=>JSON.stringify(state)}),x=>x.code==='LIVE_ACADEMIC_STRUCTURE_INVALID');});
test('engineering surface is isolated and query keyed',()=>{let html=fs.readFileSync('engineering/arc_v8_production_academic_configuration.html','utf8'),index=fs.readFileSync('index.html','utf8');assert(html.includes('arc_v8_production_academic_configuration.js?v=stage2-production-academic-configuration-closure-1'));assert(html.includes('arc_v7_schedule_configuration_capture.js?v=academic-structure-operational-truth-1-repair-1'));assert(html.includes('arc_v8_production_academic_configuration_page.js?v=academic-structure-operational-truth-1-repair-1'));assert(!index.includes('arc_v8_production_academic_configuration'));});
test('service worker and Pages verification include repaired assets',()=>{let sw=fs.readFileSync('sw.js','utf8'),workflow=fs.readFileSync('.github/workflows/pages-live-verification.yml','utf8');assert(sw.includes('arc_v7_schedule_configuration_capture.js?v=academic-structure-operational-truth-1-repair-1'));assert(sw.includes('arc_v8_production_academic_configuration_page.js?v=academic-structure-operational-truth-1-repair-1'));assert(workflow.includes('academic-structure-operational-truth-1-repair-1'));assert(workflow.includes("stage2-production-academic-configuration-closure-1"));});
test('public contract exposes no Student writer or activation API',()=>{let source=fs.readFileSync('src/arc_v8_production_academic_configuration.js','utf8');assert(!/createStudent|createEnrollment|assignSection|activateProductionAcademic|PACKAGE_AVAILABLE/.test(source));assert.equal(Coordinator.RUNTIME_REVISION,'stage2-production-academic-configuration-closure-1');});
if(!process.exitCode)console.log('\n'+pass+'/'+total+' production academic configuration tests passed.');
