const assert=require('assert');
const Booth=require('../src/booth_assignment_lifecycle');

let passed=0;
function test(name,fn){try{fn();passed++;console.log('PASS',name)}catch(error){console.error('FAIL',name,error.stack||error.message);process.exitCode=1}}
function base(){return {assignments:[],student:{id:'taylor',name:'Taylor Reed',projects:[{id:'coupon',name:'Welding Coupon Holder',currentStageName:'Fit-Up',currentNeed:'Ready to Work'}],ratings:{'WT-F2':3}},booths:[{id:'b1',name:'Booth 1',removedAt:null},{id:'b4',name:'Booth 4',removedAt:null},{id:'old',name:'Booth 9',removedAt:'2026-09-18T12:00:00Z'}]};}
function input(boothId,startedAt='2026-09-18T20:00:00Z'){return {id:'a-'+boothId,studentId:'taylor',boothId,sectionId:'sec4',period:4,academicYear:'2026-27',semester:'Semester 1',date:'2026-09-18',startedAt,source:'instructor'};}

test('assign commits one authoritative active record visible to roster and manager',()=>{let x=base(),r=Booth.assign(x.assignments,input('b4'));assert.equal(r.changed,true);assert.equal(Booth.active(x.assignments,'taylor','sec4','2026-09-18').boothId,'b4');assert.deepEqual(Booth.occupants(x.assignments,'b4','sec4','2026-09-18',''),['taylor'])});
test('assignment survives JSON persistence and reload',()=>{let x=base();Booth.assign(x.assignments,input('b4'));let restored=JSON.parse(JSON.stringify(x));assert.equal(Booth.active(restored.assignments,'taylor','sec4','2026-09-18').boothId,'b4')});
test('move closes Booth A history and activates Booth B',()=>{let x=base();Booth.assign(x.assignments,input('b1','2026-09-18T17:00:00Z'));let r=Booth.assign(x.assignments,input('b4','2026-09-18T17:10:00Z'));assert.equal(r.prior.boothId,'b1');assert.equal(r.prior.endReason,'reassigned');assert.equal(r.prior.endedAt,'2026-09-18T17:10:00Z');assert.deepEqual(Booth.occupants(x.assignments,'b1','sec4','2026-09-18',''),[]);assert.deepEqual(Booth.occupants(x.assignments,'b4','sec4','2026-09-18',''),['taylor'])});
test('manual unassign ends active record and survives reload',()=>{let x=base();Booth.assign(x.assignments,input('b4'));let r=Booth.end(x.assignments,'taylor','sec4','2026-09-18','2026-09-18T20:05:00Z');assert.equal(r.changed,true);assert.equal(r.assignment.endReason,'instructor_ended');assert.equal(Booth.active(JSON.parse(JSON.stringify(x.assignments)),'taylor','sec4','2026-09-18'),null)});
test('shared booth occupancy is intentionally preserved per student',()=>{let x=base();Booth.assign(x.assignments,input('b4'));Booth.assign(x.assignments,Object.assign({},input('b4','2026-09-18T20:01:00Z'),{id:'a-riley',studentId:'riley'}));assert.deepEqual(Booth.occupants(x.assignments,'b4','sec4','2026-09-18','').sort(),['riley','taylor']);assert.equal(x.assignments.length,2)});
test('soft-removed booths are excluded from assignment choices',()=>{let x=base();assert.deepEqual(Booth.assignableBooths(x.booths).map(b=>b.id),['b1','b4'])});
test('assignment created before period end closes at the cutoff',()=>{let x=base();Booth.assign(x.assignments,input('b4','2026-09-18T17:00:00Z'));let now=new Date('2026-09-18T18:00:00Z'),end=new Date('2026-09-18T17:30:00Z');assert.equal(Booth.closeExpired(x.assignments,now,'2026-09-18',()=>end),true);assert.equal(x.assignments[0].endedAt,end.toISOString());assert.equal(x.assignments[0].endReason,'period_end')});
test('assignment created after period end is not immediately erased',()=>{let x=base();Booth.assign(x.assignments,input('b4','2026-09-18T20:00:00Z'));let now=new Date('2026-09-18T20:01:00Z'),end=new Date('2026-09-18T17:30:00Z');assert.equal(Booth.closeExpired(x.assignments,now,'2026-09-18',()=>end),false);assert.equal(Booth.active(x.assignments,'taylor','sec4','2026-09-18').boothId,'b4')});
test('post-period assignment closes on the next day',()=>{let x=base();Booth.assign(x.assignments,input('b4','2026-09-18T20:00:00Z'));assert.equal(Booth.closeExpired(x.assignments,new Date('2026-09-19T12:00:00Z'),'2026-09-19',()=>new Date('2026-09-18T17:30:00Z')),true);assert.equal(x.assignments[0].endReason,'period_end')});
test('temporary pass data does not mutate booth assignment',()=>{let x=base();Booth.assign(x.assignments,input('b4'));let before=JSON.stringify(x.assignments),pass={studentId:'taylor',reason:'bathroom',returnedAt:null};assert(pass);assert.equal(JSON.stringify(x.assignments),before);assert.equal(Booth.active(x.assignments,'taylor','sec4','2026-09-18').boothId,'b4')});
test('booth operations do not mutate unrelated student project or competency data',()=>{let x=base(),before=JSON.stringify(x.student);Booth.assign(x.assignments,input('b4'));Booth.assign(x.assignments,input('b1','2026-09-18T20:05:00Z'));Booth.end(x.assignments,'taylor','sec4','2026-09-18','2026-09-18T20:10:00Z');assert.equal(JSON.stringify(x.student),before)});

if(!process.exitCode)console.log('PASS '+passed+' booth assignment lifecycle tests');
