const assert=require('assert');
const fs=require('fs');
const html=fs.readFileSync('index.html','utf8');
const has=text=>html.includes(text);
assert(has('const CURRENT_SCHEMA_VERSION = 6'),'additive schema migration required');
assert(has('Schema 6 adds booth resources, assignment history, and resolvable shop issues'),'migration contract missing');
['booths','boothAssignments','boothIssues'].forEach(name=>assert(has('x.'+name),name+' migration missing'));
assert(has('function commitBoothAssignment'),'assignment command missing');
assert(has('prior.endedAt = now; prior.endReason = "reassigned"'),'reassignment must close prior history');
assert(has('state.boothAssignments.push'),'assignment must append history');
['studentId, boothId, sectionId','period: sec.period','startedAt: now','endedAt: null','source'].forEach(c=>assert(has(c),'assignment field missing: '+c));
assert(has('function endBoothAssignment'),'End Assignment missing');
assert(has('a.endReason = "instructor_ended"'),'manual end audit reason missing');
assert(has('function closeExpiredBoothAssignments'),'period-end lifecycle missing');
assert(has('a.endReason = "period_end"'),'automatic closure reason missing');
assert(has('a.date !== today'),'prior-day assignment must close');
assert(has('boothBadgeHtml(st, sec)'),'Fast Roster booth rendering missing');
assert(has('ASSIGN BOOTH'),'Assign Booth target missing');
assert(has('class="booth-badge'),'booth touch target missing');
assert(has('showBoothSelector'),'reassignment selector missing');
assert(has('function boothOccupants'),'shared booth lookup missing');
assert(has('Shared booth:'),'shared assignment confirmation missing');
assert(has('Assign Anyway'),'override missing');
assert(has('studentId !== exceptStudentId'),'student assignment independence missing');
assert(has('scope: resource ? "resource" : "booth"'),'issue scope distinction missing');
assert(has('An equipment issue does not automatically make the whole booth unusable'),'equipment issue usability guidance missing');
assert(has('booth.status === "unavailable"'),'Unavailable warning missing');
assert(has('booth.status === "review_needed"'),'Review Needed warning missing');
assert(has('resolvedAt: null'),'unresolved issue state missing');
assert(has('i.resolvedAt = new Date().toISOString()'),'resolution history missing');
assert(has('Assignments are evidence of booth use, not automatic blame'),'evidence-not-blame principle missing');
assert(has('Assignment history ('),'booth history UI missing');
assert(!/function attendanceRosterPriority\([^]*?if \(hasPass\)/.test(html),'pass must not reorder roster');
assert(has('installOverscrollGuard()'),'overscroll stabilization missing');
assert(has('attendance-choices'),'direct attendance controls missing');
assert(has('student-profile-nav'),'sticky student navigation missing');
assert(has('FICTIONAL STUDENT DATA ONLY'),'privacy warning missing');
console.log('PASS Booth Manager v1 foundation contracts');
