const assert=require('assert');
const M=require('../src/material_inventory');
let pass=0,total=0;function test(name,fn){total++;try{fn();pass++;console.log('PASS',name);}catch(e){console.error('FAIL',name,e);process.exitCode=1;}}
const opts=(ids)=>({timestamp:'2026-09-19T09:00:00.000Z',academicYear:'2026-27',ids});
function base(){let m=M.addDefinition({}, {id:'angle',name:'1 in Angle',kind:'linear',minimumRetainedInches:18,location:'Rack A'},opts({definition:'angle'}));m=M.addDefinition(m,{id:'plate',name:'1/8 in Plate',kind:'plate'},opts({definition:'plate'}));return m;}
test('ten identical sticks group visually but retain stable IDs',()=>{let m=M.receive(base(),'angle',{quantity:10,lengthInches:240},opts({pieces:Array.from({length:10},(_,i)=>'p'+i),ledger:'r1'})),g=M.groups(m)[0];assert.equal(g.count,10);assert.equal(new Set(g.pieceIds).size,10);assert.equal(g.lengthInches,240);});
test('six foot eight cut leaves nine full sticks plus one 13 foot 4 remainder',()=>{let m=M.receive(base(),'angle',{quantity:10,lengthInches:240},opts({pieces:Array.from({length:10},(_,i)=>'p'+i),ledger:'r1'}));m=M.useLinear(m,'p0',{usedLengthInches:80,purpose:'Shop/School Project'},opts({remainder:'rem',ledger:'u1'}));let groups=M.groups(m);assert.equal(groups.find(g=>g.lengthInches===240).count,9);assert.equal(groups.find(g=>g.lengthInches===160).count,1);assert.equal(M.totals(m,'angle').totalLinearInches,2320);});
test('aggregate length never substitutes for continuous-piece availability',()=>{let m=base();m=M.receive(m,'angle',{quantity:4,lengthInches:24},opts({pieces:['a','b','c','d'],ledger:'r'}));assert.equal(M.totals(m,'angle').totalLinearInches,96);assert.equal(M.canSupplyLinear(m,'angle',72,1),false);m=M.receive(m,'angle',{quantity:1,lengthInches:96},opts({pieces:['long'],ledger:'r2'}));assert.equal(M.canSupplyLinear(m,'angle',72,1),true);});
test('minimum retained drop scraps below threshold, retains above, and permits override',()=>{let m=base();m=M.receive(m,'angle',{quantity:3,lengthInches:100},opts({pieces:['a','b','c'],ledger:'r'}));m=M.useLinear(m,'a',{usedLengthInches:90,purpose:'Waste/Scrap'},opts({remainder:'ra',ledger:'a'}));assert(!m.pieces.some(p=>p.id==='ra'));assert.equal(m.ledger[0].remainder.scrapped,true);m=M.useLinear(m,'b',{usedLengthInches:80,purpose:'Skill Practice'},opts({remainder:'rb',ledger:'b'}));assert.equal(m.pieces.find(p=>p.id==='rb').lengthInches,20);m=M.useLinear(m,'c',{usedLengthInches:90,purpose:'Other Department',department:'Ag',retainRemainder:true},opts({remainder:'rc',ledger:'c'}));assert.equal(m.pieces.find(p=>p.id==='rc').lengthInches,10);});
test('receipt and all use purposes create contextual append-only ledger rows',()=>{let m=base();m=M.receive(m,'angle',{quantity:4,lengthInches:100},opts({pieces:['s','p','o','w'],ledger:'receipt'}));m=M.useLinear(m,'s',{usedLengthInches:20,purpose:'Student Project',studentId:'student',studentName:'Taylor',projectId:'project',projectName:'Holder'},opts({remainder:'sr',ledger:'student-use'}));m=M.useLinear(m,'p',{usedLengthInches:20,purpose:'Skill Practice'},opts({remainder:'pr',ledger:'practice'}));m=M.useLinear(m,'o',{usedLengthInches:20,purpose:'Other Department',department:'Ag'},opts({remainder:'or',ledger:'other'}));m=M.useLinear(m,'w',{usedLengthInches:100,purpose:'Waste/Scrap',note:'Miscut'},opts({ledger:'waste'}));assert.equal(m.ledger.length,5);assert.equal(m.ledger.find(x=>x.id==='student-use').studentId,'student');assert.equal(m.ledger.find(x=>x.id==='practice').projectId,'');assert.equal(m.ledger.find(x=>x.id==='other').studentId,'');assert.equal(m.ledger.find(x=>x.id==='waste').type,'Waste/Scrap');});
test('plate dimensions validate and preserve deterministic rectangular remnants',()=>{let m=base();m=M.receive(m,'plate',{quantity:1,lengthInches:48,widthInches:96,thicknessInches:.125},opts({pieces:['sheet'],ledger:'r'}));assert.throws(()=>M.usePlate(m,'sheet',{usedLengthInches:49,usedWidthInches:10,purpose:'Shop/School Project'}),/fit/);let n=M.usePlate(m,'sheet',{usedLengthInches:12,usedWidthInches:20,purpose:'Shop/School Project'},opts({remainders:['right','top'],ledger:'u'}));assert.equal(n.pieces[0].status,'consumed');assert.deepEqual(n.pieces.filter(p=>p.status==='available').map(p=>[p.lengthInches,p.widthInches]),[[36,96],[12,76]]);assert.equal(n.ledger[0].dimensions.usedWidthInches,20);});
test('adjustments require reasons and preserve prior ledger',()=>{let m=base();m=M.receive(m,'angle',{quantity:1,lengthInches:100},opts({pieces:['p'],ledger:'r'}));assert.throws(()=>M.adjust(m,'p',{lengthInches:99}),/reason/);let n=M.adjust(m,'p',{lengthInches:99,reason:'Physical recount'},opts({ledger:'a'}));assert.equal(n.ledger.length,2);assert.equal(n.ledger[0].purpose,'Adjustment');assert.equal(n.pieces[0].lengthInches,99);});
test('invalid and stale operations are atomic',()=>{let m=base();m=M.receive(m,'angle',{quantity:1,lengthInches:50},opts({pieces:['p'],ledger:'r'})),before=JSON.stringify(m);assert.throws(()=>M.useLinear(m,'p',{usedLengthInches:60,purpose:'Skill Practice'}),/exceeds/);assert.equal(JSON.stringify(m),before);let n=M.useLinear(m,'p',{usedLengthInches:20,purpose:'Skill Practice'},opts({remainder:'r',ledger:'u'}));assert.throws(()=>M.useLinear(n,'p',{usedLengthInches:1,purpose:'Skill Practice'}),/no longer available/);});
test('serialization reload preserves exact physical records and summaries',()=>{let m=M.receive(base(),'angle',{quantity:2,lengthInches:120},opts({pieces:['p1','p2'],ledger:'r'}));let reload=M.normalize(JSON.parse(JSON.stringify(m)));assert.deepEqual(reload,m);assert.equal(M.groups(reload)[0].count,2);});
test('stock summaries distinguish healthy low and zero without losing definitions',()=>{let m=M.addDefinition(base(),{id:'zero',name:'Zero',kind:'linear',lowStockPieceCount:1},opts({definition:'zero'}));m=M.updateDefinition(m,'angle',{lowStockPieceCount:1},opts({}));m=M.receive(m,'angle',{quantity:2,lengthInches:120},opts({pieces:['p1','p2'],ledger:'r'}));let s=M.stockSummary(m);assert.equal(s.find(x=>x.definition.id==='angle').status,'healthy');assert.equal(s.find(x=>x.definition.id==='plate').status,'zero');assert.equal(s.find(x=>x.definition.id==='zero').status,'zero');m=M.useLinear(m,'p1',{usedLengthInches:120,purpose:'Skill Practice'},opts({ledger:'u'}));assert.equal(M.stockSummary(m).find(x=>x.definition.id==='angle').status,'low');});
test('student/project data is read-only context and never mutated',()=>{let student={id:'s',name:'Taylor',ratings:{x:3},work:{rating:4},projects:[{id:'j',name:'Holder',checkpoints:[{id:'fit',status:'in_progress'}]}]},before=JSON.stringify(student),m=M.receive(base(),'angle',{quantity:1,lengthInches:100},opts({pieces:['p'],ledger:'r'}));M.useLinear(m,'p',{usedLengthInches:20,purpose:'Student Project',studentId:student.id,studentName:student.name,projectId:student.projects[0].id,projectName:student.projects[0].name},opts({remainder:'rem',ledger:'u'}));assert.equal(JSON.stringify(student),before);});
if(!process.exitCode)console.log(`\n${pass}/${total} Material Inventory v1 tests passed.`);
