const assert=require('assert');
const A=require('../src/needs_attention_arc_adapter');
const E=require('../src/needs_attention_engine');
let pass=0,total=0;function test(name,fn){total++;try{fn();pass++;console.log('PASS',name);}catch(e){console.error('FAIL',name,e.message);process.exitCode=1;}}
function state(){return {academicYear:'2026-27',semester:'Semester 1',activeSectionId:'sec1',sections:[{id:'sec1',course:'wt',period:2}],classes:{wt:[{id:'s1',name:'Alex',enrollments:[{year:'2026-27',semester:'Semester 1',sectionId:'sec1',period:2,course:'wt',active:true}],ratings:{'WT-S1':2},ratingScopes:{'WT-S1':{academicYear:'2026-27',semester:'Semester 1',sectionId:'sec1',course:'wt'}},projects:[],tech:[],workplacePoints:{}}],awt:[]},lessonBank:{wt:[],awt:[]},pacingPlans:{},attendanceRecords:{},technicalLibrary:{wt:[],awt:[]}};}
function defs(){return {wt:[{code:'WT-S1',name:'PPE',standard:'WT 1.1'}],awt:[]};}
function addPacing(s,status,standards,actualDates){s.lessonBank.wt=[{id:'lesson1',title:'Safety',standards:standards||['WT 1.1']}];s.pacingPlans.sec1={sectionId:'sec1',items:[{id:'pace1',lessonId:'lesson1',status:status,actualDates:actualDates||[]}]};return s;}
function attendance(s,date,status){s.attendanceRecords['sec1::'+date]={sectionId:'sec1',date:date,students:{s1:{status:status}}};return s;}
function addTechnical(s,status,date,sectionIds){s.technicalLibrary.wt=[{id:'t1',title:'Safety Quiz',date:date||'2026-09-14',sectionIds:sectionIds===undefined?['sec1']:sectionIds,course:'wt',academicYear:'2026-27',semester:'Semester 1',daySpecific:true}];s.classes.wt[0].tech=[{templateId:'t1',name:'Safety Quiz',status:status||'makeup',date:date||'2026-09-14',sectionId:'sec1',course:'wt',academicYear:'2026-27',semester:'Semester 1'}];return s;}
function addWork(s,weekKey,day,points,scope){let w={sectionId:'sec1',course:'wt',academicYear:'2026-27',semester:'Semester 1',days:{},weeklyPercent:80};Object.assign(w,scope||{});w.days[day]={status:'present',deductions:[{id:'wd1',ruleId:points===3?'serioussafety':'repeatppe',label:'Shop concern',occurrence:1,points:points,sectionId:'sec1'}]};s.classes.wt[0].workplacePoints[weekKey]=w;return s;}
function addProject(s,checkpointStatus){s.classes.wt[0].projects=[{templateId:'p1',name:'Welding Table',status:'in_progress',rubric:{},checkpoints:[{id:'plan',enabled:true,status:checkpointStatus||'in_progress',updatedAt:'2026-09-15T14:00:00.000Z'}]}];return s;}
test('current enrollment only',()=>assert.equal(A.adapt(state(),{sectionId:'sec1'}).students.length,1));
test('inactive excluded',()=>{let s=state();s.classes.wt[0].enrollments[0].active=false;assert.equal(A.adapt(s,{sectionId:'sec1'}).students.length,0);});
test('wrong semester excluded',()=>{let s=state();s.classes.wt[0].enrollments[0].semester='Semester 2';assert.equal(A.adapt(s,{sectionId:'sec1'}).students.length,0);});
test('current scoped rating preserved',()=>assert.equal(A.adapt(state(),{sectionId:'sec1'}).students[0].competencies[0].rating,2));
test('legacy rating excluded',()=>{let s=state();s.classes.wt[0].ratingScopes={};assert.equal(A.adapt(s,{sectionId:'sec1'}).students[0].competencies[0].rating,0);});
test('prior rating scope excluded',()=>{let s=state();s.classes.wt[0].ratingScopes['WT-S1'].semester='Semester 2';assert.equal(A.adapt(s,{sectionId:'sec1'}).students[0].competencies[0].rating,0);});
test('opportunity defaults false',()=>assert.equal(A.adapt(state(),{sectionId:'sec1'}).students[0].competencies[0].opportunityConfirmed,false));
test('explicit essential opportunity flags',()=>assert.equal(E.generate(A.adapt(state(),{today:'2026-09-15',sectionId:'sec1',essentialCodes:{'WT-S1':true},competencyOpportunities:{s1:{'WT-S1':true}}}))[0].ruleId,'essential_competency_risk'));
test('reassessment maps',()=>assert.equal(E.generate(A.adapt(state(),{sectionId:'sec1',essentialCodes:{'WT-S1':true},competencyOpportunities:{s1:{'WT-S1':true}},readyForReassessment:{s1:{'WT-S1':true}}}))[0].ruleId,'ready_for_review'));
test('adapter no mutation',()=>{let s=state(),b=JSON.stringify(s);A.adapt(s,{sectionId:'sec1'});assert.equal(JSON.stringify(s),b);});
test('definitions include unrated',()=>{let s=state();s.classes.wt[0].ratings={};s.classes.wt[0].ratingScopes={};assert.equal(A.adapt(s,{sectionId:'sec1',competencyDefinitions:defs()}).students[0].competencies[0].id,'WT-S1');});
test('completed pacing confirms',()=>{let s=addPacing(state(),'completed',['WT 1.1'],['2026-09-14']);assert.equal(A.adapt(s,{sectionId:'sec1',competencyDefinitions:defs()}).students[0].competencies[0].opportunityConfirmed,true);});
test('forecast does not confirm',()=>{let s=addPacing(state(),'forecasted',['WT 1.1'],[]);assert.equal(A.adapt(s,{sectionId:'sec1',competencyDefinitions:defs()}).students[0].competencies[0].opportunityConfirmed,false);});
test('partial does not confirm',()=>{let s=addPacing(state(),'partial',['WT 1.1'],['2026-09-14']);assert.equal(A.adapt(s,{sectionId:'sec1',competencyDefinitions:defs()}).students[0].competencies[0].opportunityConfirmed,false);});
test('unrelated standard does not confirm',()=>{let s=addPacing(state(),'completed',['WT 2.2'],['2026-09-14']);assert.equal(A.adapt(s,{sectionId:'sec1',competencyDefinitions:defs()}).students[0].competencies[0].opportunityConfirmed,false);});
['excused','activity','noclass'].forEach(x=>test(x+' blocks pacing',()=>{let s=attendance(addPacing(state(),'completed',['WT 1.1'],['2026-09-14']),'2026-09-14',x);assert.equal(A.adapt(s,{sectionId:'sec1',competencyDefinitions:defs()}).students[0].competencies[0].opportunityConfirmed,false);}));
['present','tardy','left_early','unexcused'].forEach(x=>test(x+' retains pacing',()=>{let s=attendance(addPacing(state(),'completed',['WT 1.1'],['2026-09-14']),'2026-09-14',x);assert.equal(A.adapt(s,{sectionId:'sec1',competencyDefinitions:defs()}).students[0].competencies[0].opportunityConfirmed,true);}));
test('due ARC tech record flags',()=>{let x=A.adapt(addTechnical(state(),'makeup'),{today:'2026-09-15',sectionId:'sec1'});assert.equal(x.students[0].technical.length,1);assert.equal(E.generate(x)[0].ruleId,'technical_evidence_missing');});
test('legacy technical alias is ignored',()=>{let s=state();s.classes.wt[0].technical=[{templateId:'t1'}];assert.equal(A.adapt(s,{today:'2026-09-15',sectionId:'sec1'}).students[0].technical.length,0);});
test('future tech not due',()=>assert.equal(E.generate(A.adapt(addTechnical(state(),'makeup','2026-09-20'),{today:'2026-09-15',sectionId:'sec1'})).length,0));
test('completed tech no flag',()=>assert.equal(E.generate(A.adapt(addTechnical(state(),'completed'),{today:'2026-09-15',sectionId:'sec1'})).length,0));
test('excused tech no flag',()=>assert.equal(E.generate(A.adapt(addTechnical(state(),'excused'),{today:'2026-09-15',sectionId:'sec1'})).length,0));
['excused','activity','noclass'].forEach(x=>test(x+' blocks tech',()=>{let s=attendance(addTechnical(state(),'makeup'),'2026-09-14',x);assert.equal(E.generate(A.adapt(s,{today:'2026-09-15',sectionId:'sec1'})).length,0);}));
['present','tardy','left_early','unexcused'].forEach(x=>test(x+' retains tech opportunity',()=>{let s=attendance(addTechnical(state(),'makeup'),'2026-09-14',x);assert.equal(A.adapt(s,{today:'2026-09-15',sectionId:'sec1'}).students[0].technical[0].opportunityConfirmed,true);}));
test('other section tech excluded',()=>assert.equal(A.adapt(addTechnical(state(),'makeup','2026-09-14',['sec2']),{today:'2026-09-15',sectionId:'sec1'}).students[0].technical.length,0));
test('prior semester tech excluded',()=>{let s=addTechnical(state(),'makeup');s.technicalLibrary.wt[0].semester='Semester 2';assert.equal(A.adapt(s,{today:'2026-09-15',sectionId:'sec1'}).students[0].technical.length,0);});
test('checkpoint Ready for Review maps to project P1',()=>{let x=A.adapt(addProject(state(),'ready_for_review'),{today:'2026-09-15',sectionId:'sec1'}),y=E.generate(x);assert.equal(x.students[0].projects.length,1);assert.equal(y[0].ruleId,'ready_for_review');assert.equal(y[0].actionTarget,'project');assert.equal(y[0].priority,'P1');});
test('in-progress checkpoint does not create project alert',()=>assert.equal(A.adapt(addProject(state(),'in_progress'),{today:'2026-09-15',sectionId:'sec1'}).students[0].projects.length,0));
test('legacy project without checkpoints does not create alert',()=>{let s=state();s.classes.wt[0].projects=[{templateId:'p1',name:'Old Project',status:'ready',rubric:{}}];assert.equal(A.adapt(s,{today:'2026-09-15',sectionId:'sec1'}).students[0].projects.length,0);});
test('disabled Ready for Review checkpoint does not create alert',()=>{let s=addProject(state(),'ready_for_review');s.classes.wt[0].projects[0].checkpoints[0].enabled=false;assert.equal(A.adapt(s,{today:'2026-09-15',sectionId:'sec1'}).students[0].projects.length,0);});
test('project adapter does not enable stalled signal',()=>{let x=A.adapt(addProject(state(),'ready_for_review'),{today:'2026-09-30',sectionId:'sec1'}).students[0].projects[0];assert.equal(x.opportunityConfirmed,false);assert.equal(x.eligibleOpportunities,0);});
test('serious Workplace deduction maps to P1',()=>{let x=A.adapt(addWork(state(),'2026-09-14','mon',3),{today:'2026-09-15',sectionId:'sec1'}),y=E.generate(x);assert.equal(x.students[0].workplace[0].date,'2026-09-14');assert.equal(y[0].ruleId,'serious_shop_followup');assert.equal(y[0].priority,'P1');});
test('two significant Workplace deductions map to P2',()=>{let s=addWork(state(),'2026-09-14','mon',2);s.classes.wt[0].workplacePoints['2026-09-14'].days.tue={status:'present',deductions:[{id:'wd2',points:2,label:'Second concern',sectionId:'sec1'}]};assert.equal(E.generate(A.adapt(s,{today:'2026-09-15',sectionId:'sec1'}))[0].ruleId,'repeated_workplace_concern');});
test('single significant Workplace deduction does not flag',()=>assert.equal(E.generate(A.adapt(addWork(state(),'2026-09-14','mon',2),{today:'2026-09-15',sectionId:'sec1'})).length,0));
test('routine Workplace deduction does not flag',()=>assert.equal(E.generate(A.adapt(addWork(state(),'2026-09-14','mon',1),{today:'2026-09-15',sectionId:'sec1'})).length,0));
test('old Workplace deduction ignored by engine',()=>assert.equal(E.generate(A.adapt(addWork(state(),'2026-08-24','mon',3),{today:'2026-09-15',sectionId:'sec1'})).length,0));
test('other-term Workplace week excluded',()=>{let s=addWork(state(),'2026-09-14','mon',3,{semester:'Semester 2'});assert.equal(A.adapt(s,{today:'2026-09-15',sectionId:'sec1'}).students[0].workplace.length,0);});
test('legacy unscoped Workplace week excluded conservatively',()=>{let s=addWork(state(),'2026-09-14','mon',3);delete s.classes.wt[0].workplacePoints['2026-09-14'].semester;assert.equal(A.adapt(s,{today:'2026-09-15',sectionId:'sec1'}).students[0].workplace.length,0);});
test('excluded Workplace day contributes no event',()=>{let s=addWork(state(),'2026-09-14','mon',3);s.classes.wt[0].workplacePoints['2026-09-14'].days.mon.status='excused';assert.equal(A.adapt(s,{today:'2026-09-15',sectionId:'sec1'}).students[0].workplace.length,0);});
test('Workplace adapter no mutation',()=>{let s=addWork(state(),'2026-09-14','mon',3),b=JSON.stringify(s);A.adapt(s,{today:'2026-09-15',sectionId:'sec1'});assert.equal(JSON.stringify(s),b);});
if(!process.exitCode)console.log('\n'+pass+'/'+total+' ARC adapter tests passed.');
