const assert=require('assert');
const A=require('../src/needs_attention_arc_adapter');
const E=require('../src/needs_attention_engine');
let pass=0;function test(name,fn){try{fn();pass++;console.log('PASS',name);}catch(e){console.error('FAIL',name,e.message);process.exitCode=1;}}
function state(){return {academicYear:'2026-27',semester:'Semester 1',activeSectionId:'sec1',sections:[{id:'sec1',course:'wt',period:2}],classes:{wt:[{id:'s1',name:'Alex',enrollments:[{year:'2026-27',semester:'Semester 1',sectionId:'sec1',period:2,course:'wt',active:true}],ratings:{'WT-S1':2},ratingScopes:{'WT-S1':{academicYear:'2026-27',semester:'Semester 1',sectionId:'sec1',course:'wt'}},technical:[]}],awt:[]},lessonBank:{wt:[],awt:[]},pacingPlans:{},attendanceRecords:{},technicalLibrary:{wt:[],awt:[]}};}
function defs(){return {wt:[{code:'WT-S1',name:'PPE',standard:'WT 1.1'}],awt:[]};}
function addPacing(s,status,standards,actualDates){s.lessonBank.wt=[{id:'lesson1',title:'Safety',standards:standards||['WT 1.1']}];s.pacingPlans.sec1={sectionId:'sec1',items:[{id:'pace1',lessonId:'lesson1',status:status,actualDates:actualDates||[]}]};return s;}
function attendance(s,date,status){s.attendanceRecords['sec1::'+date]={sectionId:'sec1',date:date,students:{s1:{status:status}}};return s;}
function addTechnical(s,status,date,sectionIds){s.technicalLibrary.wt=[{id:'t1',title:'Safety Quiz',date:date||'2026-09-14',sectionIds:sectionIds===undefined?['sec1']:sectionIds,course:'wt',academicYear:'2026-27',semester:'Semester 1',daySpecific:true}];s.classes.wt[0].technical=[{templateId:'t1',name:'Safety Quiz',status:status||'assigned',date:date||'2026-09-14'}];return s;}
test('adapts only current active section enrollment',()=>{let x=A.adapt(state(),{sectionId:'sec1'});assert.equal(x.students.length,1);assert.equal(x.students[0].sectionId,'sec1');});
test('inactive enrollment is excluded',()=>{let s=state();s.classes.wt[0].enrollments[0].active=false;assert.equal(A.adapt(s,{sectionId:'sec1'}).students.length,0);});
test('wrong semester enrollment is excluded',()=>{let s=state();s.classes.wt[0].enrollments[0].semester='Semester 2';assert.equal(A.adapt(s,{sectionId:'sec1'}).students.length,0);});
test('current scoped rating is preserved',()=>{let x=A.adapt(state(),{sectionId:'sec1'});assert.equal(x.students[0].competencies[0].rating,2);});
test('legacy unscoped rating is not silently current-term evidence',()=>{let s=state();s.classes.wt[0].ratingScopes={};assert.equal(A.adapt(s,{sectionId:'sec1'}).students[0].competencies[0].rating,0);});
test('prior semester scope is not current-term evidence',()=>{let s=state();s.classes.wt[0].ratingScopes['WT-S1'].semester='Semester 2';assert.equal(A.adapt(s,{sectionId:'sec1'}).students[0].competencies[0].rating,0);});
test('opportunity defaults false',()=>{let x=A.adapt(state(),{sectionId:'sec1',essentialCodes:{'WT-S1':true}});assert.equal(x.students[0].competencies[0].opportunityConfirmed,false);assert.equal(E.generate(x).length,0);});
test('explicit opportunity can trigger essential risk',()=>{let x=A.adapt(state(),{today:'2026-09-15',sectionId:'sec1',essentialCodes:{'WT-S1':true},competencyOpportunities:{s1:{'WT-S1':true}}});assert.equal(E.generate(x)[0].ruleId,'essential_competency_risk');});
test('nonessential competency does not become risk',()=>{let x=A.adapt(state(),{sectionId:'sec1',competencyOpportunities:{s1:{'WT-S1':true}}});assert.equal(E.generate(x).length,0);});
test('reassessment signal maps without mutating rating',()=>{let s=state(),before=JSON.stringify(s);let x=A.adapt(s,{sectionId:'sec1',essentialCodes:{'WT-S1':true},competencyOpportunities:{s1:{'WT-S1':true}},readyForReassessment:{s1:{'WT-S1':true}}});assert.equal(E.generate(x)[0].ruleId,'ready_for_review');assert.equal(JSON.stringify(s),before);});
test('adapter does not mutate ARC state',()=>{let s=state(),before=JSON.stringify(s);A.adapt(s,{sectionId:'sec1'});assert.equal(JSON.stringify(s),before);});
test('competency definitions include unrated skills',()=>{let s=state();s.classes.wt[0].ratings={};s.classes.wt[0].ratingScopes={};let x=A.adapt(s,{sectionId:'sec1',competencyDefinitions:defs()});assert.equal(x.students[0].competencies[0].id,'WT-S1');});
test('completed pacing lesson confirms matching competency opportunity',()=>{let s=addPacing(state(),'completed',['WT 1.1'],['2026-09-14']);let x=A.adapt(s,{today:'2026-09-15',sectionId:'sec1',competencyDefinitions:defs(),essentialCodes:{'WT-S1':true}});assert.equal(x.students[0].competencies[0].opportunityConfirmed,true);assert.equal(x.students[0].competencies[0].evidenceDate,'2026-09-14');});
test('forecasted lesson does not confirm opportunity',()=>{let s=addPacing(state(),'forecasted',['WT 1.1'],[]);assert.equal(A.adapt(s,{sectionId:'sec1',competencyDefinitions:defs()}).students[0].competencies[0].opportunityConfirmed,false);});
test('partial lesson does not yet confirm opportunity',()=>{let s=addPacing(state(),'partial',['WT 1.1'],['2026-09-14']);assert.equal(A.adapt(s,{sectionId:'sec1',competencyDefinitions:defs()}).students[0].competencies[0].opportunityConfirmed,false);});
test('completed unrelated standard does not confirm opportunity',()=>{let s=addPacing(state(),'completed',['WT 2.2'],['2026-09-14']);assert.equal(A.adapt(s,{sectionId:'sec1',competencyDefinitions:defs()}).students[0].competencies[0].opportunityConfirmed,false);});
test('multi-standard competency matches either listed standard',()=>{let s=state(),d={wt:[{code:'WT-M2',name:'Layout',standard:'WT 2.1; WT 4.2'}],awt:[]};s.classes.wt[0].ratings={};s.classes.wt[0].ratingScopes={};s=addPacing(s,'completed',['WT 4.2'],['2026-09-12']);assert.equal(A.adapt(s,{sectionId:'sec1',competencyDefinitions:d}).students[0].competencies[0].opportunityConfirmed,true);});
test('completed pacing inference does not mutate ARC state',()=>{let s=addPacing(state(),'completed',['WT 1.1'],['2026-09-14']),before=JSON.stringify(s);A.adapt(s,{sectionId:'sec1',competencyDefinitions:defs()});assert.equal(JSON.stringify(s),before);});
['excused','activity','noclass'].forEach(status=>test(status+' attendance blocks pacing opportunity',()=>{let s=attendance(addPacing(state(),'completed',['WT 1.1'],['2026-09-14']),'2026-09-14',status);assert.equal(A.adapt(s,{sectionId:'sec1',competencyDefinitions:defs()}).students[0].competencies[0].opportunityConfirmed,false);}));
['present','tardy','left_early','unexcused'].forEach(status=>test(status+' attendance retains pacing opportunity',()=>{let s=attendance(addPacing(state(),'completed',['WT 1.1'],['2026-09-14']),'2026-09-14',status);assert.equal(A.adapt(s,{sectionId:'sec1',competencyDefinitions:defs()}).students[0].competencies[0].opportunityConfirmed,true);}));
test('later eligible actual date confirms opportunity after earlier excused date',()=>{let s=addPacing(state(),'completed',['WT 1.1'],['2026-09-10','2026-09-12']);attendance(s,'2026-09-10','excused');attendance(s,'2026-09-12','present');let x=A.adapt(s,{sectionId:'sec1',competencyDefinitions:defs()});assert.equal(x.students[0].competencies[0].evidenceDate,'2026-09-12');});
test('missing attendance record defaults to present like ARC attendanceStatus',()=>{let s=addPacing(state(),'completed',['WT 1.1'],['2026-09-14']);assert.equal(A.attendanceStatus(s,'s1','sec1','2026-09-14'),'present');});
test('due assigned Technical assessment creates missing-evidence item',()=>{let s=addTechnical(state(),'assigned');let x=A.adapt(s,{today:'2026-09-15',sectionId:'sec1'}),y=E.generate(x);assert.equal(x.students[0].technical.length,1);assert.equal(y.length,1);assert.equal(y[0].ruleId,'technical_evidence_missing');});
test('future Technical assessment is not due',()=>{let s=addTechnical(state(),'assigned','2026-09-20');let x=A.adapt(s,{today:'2026-09-15',sectionId:'sec1'});assert.equal(x.students[0].technical[0].due,false);assert.equal(E.generate(x).length,0);});
test('completed Technical assessment does not flag',()=>{let s=addTechnical(state(),'completed');assert.equal(E.generate(A.adapt(s,{today:'2026-09-15',sectionId:'sec1'})).length,0);});
test('excused Technical assessment does not flag',()=>{let s=addTechnical(state(),'excused');assert.equal(E.generate(A.adapt(s,{today:'2026-09-15',sectionId:'sec1'})).length,0);});
['excused','activity','noclass'].forEach(status=>test(status+' attendance blocks Technical opportunity',()=>{let s=attendance(addTechnical(state(),'assigned'),'2026-09-14',status);let x=A.adapt(s,{today:'2026-09-15',sectionId:'sec1'});assert.equal(x.students[0].technical[0].opportunityConfirmed,false);assert.equal(E.generate(x).length,0);}));
['present','tardy','left_early','unexcused'].forEach(status=>test(status+' attendance retains Technical opportunity',()=>{let s=attendance(addTechnical(state(),'assigned'),'2026-09-14',status);assert.equal(A.adapt(s,{today:'2026-09-15',sectionId:'sec1'}).students[0].technical[0].opportunityConfirmed,true);}));
test('Technical template from another section is excluded',()=>{let s=addTechnical(state(),'assigned','2026-09-14',['sec2']);assert.equal(A.adapt(s,{today:'2026-09-15',sectionId:'sec1'}).students[0].technical.length,0);});
test('Technical template from prior semester is excluded',()=>{let s=addTechnical(state(),'assigned');s.technicalLibrary.wt[0].semester='Semester 2';assert.equal(A.adapt(s,{today:'2026-09-15',sectionId:'sec1'}).students[0].technical.length,0);});
test('Technical adapter does not mutate ARC state',()=>{let s=addTechnical(state(),'assigned'),before=JSON.stringify(s);A.adapt(s,{today:'2026-09-15',sectionId:'sec1'});assert.equal(JSON.stringify(s),before);});
if(!process.exitCode)console.log('\n'+pass+'/42 ARC adapter tests passed.');
