const assert=require('assert'),fs=require('fs'),crypto=require('crypto'),cp=require('child_process');
const manifestPath='reconciliation/p10d/instructional-content-manifest.json',sourceQueuePath='reconciliation/p10d/human-review-queue.json',queuePath='reconciliation/p10d/consolidated-review-queue.json',mapPath='reconciliation/p10d/original-item-resolution-map.json';
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])]));return v;}
function hash(v){return crypto.createHash('sha256').update(JSON.stringify(stable(v))).digest('hex');}
let pass=0,total=0;function test(name,fn){total++;try{fn();pass++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1}}
const manifestBefore=fs.readFileSync(manifestPath,'utf8'),sourceBefore=fs.readFileSync(sourceQueuePath,'utf8'),queueBefore=fs.readFileSync(queuePath,'utf8'),mapBefore=fs.readFileSync(mapPath,'utf8');cp.execFileSync(process.execPath,['scripts/consolidate_p10d_review_queue.js'],{stdio:'pipe'});const M=JSON.parse(fs.readFileSync(manifestPath)),S=JSON.parse(fs.readFileSync(sourceQueuePath)),Q=JSON.parse(fs.readFileSync(queuePath)),R=JSON.parse(fs.readFileSync(mapPath));
test('consolidation is byte reproducible and leaves P10D authority unchanged',()=>{assert.equal(fs.readFileSync(manifestPath,'utf8'),manifestBefore);assert.equal(fs.readFileSync(sourceQueuePath,'utf8'),sourceBefore);assert.equal(fs.readFileSync(queuePath,'utf8'),queueBefore);assert.equal(fs.readFileSync(mapPath,'utf8'),mapBefore);assert.equal(M.manifestHash,'960dc548c984c0f6aed591f40856cb2947491928e31d71e3a8d65b0fbca501a2');});
test('every original item maps once with deterministic fingerprint and back-reference',()=>{assert.equal(S.count,408);assert.equal(R.mappings.length,408);assert.equal(new Set(R.mappings.map(x=>x.originalQueueIndex)).size,408);assert.equal(new Set(R.mappings.map(x=>x.originalItemFingerprint)).size,408);for(const [i,x] of S.items.entries()){let r=R.mappings.find(y=>y.originalQueueIndex===i);assert(r);assert.equal(r.originalItemFingerprint,hash(x));assert.equal(r.course,x.course);assert.equal(r.family,x.family);}});
test('smallest defensible consolidated set separates decisions and statuses',()=>{assert.deepEqual(Q.counts,{consolidatedEntries:8,trueInstructorDecisions:0,sourceVerificationDecisions:2,mechanicalFollowOnGroups:2,safeUnresolvedGroups:4,originalItems:408,originalItemsMapped:408,originalItemsMechanical:149,originalItemsSafeUnresolved:259,originalItemsBlockingImport:0});assert.equal(Q.decisions.length,8);assert.equal(Q.trueInstructorDecisionPresentation.length,0);});
test('all required categories are represented',()=>{let categories=Q.decisions.map(x=>x.category).join(' | ');for(const value of ['Standard-reference interpretation','Curriculum → Standard relationship','Curriculum → Competency relationship','Lesson → Standard relationship','Lesson → Competency relationship','Lesson → Curriculum relationship','Activity/Evidence relationship','external authoritative-source verification'])assert(categories.includes(value),value);});
test('candidate-only relationships safely remain absent',()=>{for(const family of ['curriculumItemCompetencyLinks','lessonVersionCompetencyLinks','lessonVersionCurriculumLinks','lessonVersionActivityLinks'])for(const row of R.mappings.filter(x=>x.family===family)){assert.equal(row.classification,'safe unresolved relationship');assert.equal(row.status,'SAFE_TO_REMAIN_ABSENT');assert.equal(row.blocksImport,false);}});
test('ambiguous parent rows become mechanical content relationship separation',()=>{for(const family of ['curriculumMapItems','lessonDefinitions','lessonVersions'])for(const row of R.mappings.filter(x=>x.family===family)){assert.equal(row.classification,'mechanical follow-on mapping');assert.equal(row.blocksImport,false);}});
test('only two external source gates block their scoped Standard authority',()=>{assert.equal(Q.importBlockers.length,2);assert.deepEqual(Q.importBlockers.map(x=>x.decisionId),['SV-WT-STANDARDS-SOURCE','SV-AWT-STANDARDS-SOURCE']);assert(Q.decisions.filter(x=>x.decisionClass==='source-verification decision').every(x=>x.choices.length===3));assert.equal(R.mappings.filter(x=>x.blocksImport).length,0);});
test('no runtime build cache schema database or parity state changes',()=>{for(const file of ['index.html','app-build.js','sw.js','src/arc_v8_storage.js']){let current=fs.readFileSync(file,'utf8').replace(/\r\n/g,'\n'),accepted=cp.execFileSync('git',['show','cddeac773caa917b405f30c2f2e4c8f090c65e91:'+file],{encoding:'utf8'}).replace(/\r\n/g,'\n');assert.equal(current,accepted,file);}const C=require('../parity/stage14_v7_v8_parity_contract');assert.equal(C.authorityState,'V7_ONLY');assert.equal(C.rows.filter(x=>x.status==='service-ready').length,40);assert.equal(C.rows.filter(x=>x.status==='not-started').length,4);assert.equal(C.rows.filter(x=>x.status==='accepted').length,3);});
if(!process.exitCode)console.log(`\n${pass}/${total} P10D-R1A queue consolidation tests passed.`);
