const assert=require('assert'),fs=require('fs'),crypto=require('crypto'),cp=require('child_process'),os=require('os'),path=require('path');
const output='reconciliation/p10d/r1b-source-disposition-freeze.json',start='16f7e186051d2778a6e8e0afb0fad4dfc72787d4';
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])]));return v;}
const hash=v=>crypto.createHash('sha256').update(typeof v==='string'||Buffer.isBuffer(v)?v:JSON.stringify(stable(v))).digest('hex');
const {validateRelationships}=require('../scripts/generate_p10d_r1b_source_disposition_freeze.js');
let pass=0,total=0;function test(name,fn){total++;try{fn();pass++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1}}
function isolatedFixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'arc-p10d-r1b-f1-'));fs.mkdirSync(path.join(root,'scripts'),{recursive:true});fs.mkdirSync(path.join(root,'reconciliation'),{recursive:true});fs.mkdirSync(path.join(root,'source_authority'),{recursive:true});fs.copyFileSync('scripts/generate_p10d_r1b_source_disposition_freeze.js',path.join(root,'scripts','generate_p10d_r1b_source_disposition_freeze.js'));fs.cpSync('reconciliation/p10d',path.join(root,'reconciliation','p10d'),{recursive:true});fs.cpSync('source_authority/recovered_2026-09-29',path.join(root,'source_authority','recovered_2026-09-29'),{recursive:true});return root;}
function json(root,relative,mutate){const file=path.join(root,relative),value=JSON.parse(fs.readFileSync(file,'utf8'));mutate(value);fs.writeFileSync(file,JSON.stringify(value,null,2)+'\n');}
function rejectedWithoutOutput(root,mutate,{absent=false}={}){const out=path.join(root,output);if(absent)fs.unlinkSync(out);else fs.writeFileSync(out,'SENTINEL');mutate(root);const result=cp.spawnSync(process.execPath,[path.join(root,'scripts','generate_p10d_r1b_source_disposition_freeze.js')],{encoding:'utf8'});assert.notEqual(result.status,0,`invalid fixture unexpectedly succeeded: ${result.stdout}`);if(absent)assert.equal(fs.existsSync(out),false,'invalid input created output');else assert.equal(fs.readFileSync(out,'utf8'),'SENTINEL','invalid input overwrote output');}
function isolatedTest(name,mutate,options){test(name,()=>{const root=isolatedFixture();try{rejectedWithoutOutput(root,mutate,options);}finally{fs.rmSync(root,{recursive:true,force:true});}});}
const protectedFiles=['index.html','app-build.js','app.webmanifest','sw.js','src/arc_v8_storage.js','parity/stage14_v7_v8_parity_contract.js','reconciliation/p10d/instructional-content-manifest.json','reconciliation/p10d/human-review-queue.json','reconciliation/p10d/consolidated-review-queue.json','reconciliation/p10d/original-item-resolution-map.json','source_authority/recovered_2026-09-29/source-manifest.json','source_authority/recovered_2026-09-29/standards-comparison.json','source_authority/recovered_2026-09-29/transcriptions/south-dakota-welding-standards.json'];
const before=Object.fromEntries(protectedFiles.map(f=>[f,fs.readFileSync(f)]));cp.execFileSync(process.execPath,['scripts/generate_p10d_r1b_source_disposition_freeze.js'],{stdio:'pipe'});const first=fs.readFileSync(output,'utf8');cp.execFileSync(process.execPath,['scripts/generate_p10d_r1b_source_disposition_freeze.js'],{stdio:'pipe'});const second=fs.readFileSync(output,'utf8'),A=JSON.parse(second);
test('generation is byte deterministic and artifact hash is valid',()=>{assert.equal(first,second);let clone=structuredClone(A);delete clone.artifactHash;assert.equal(A.artifactHash,hash(clone));});
test('two source gates resolve independently to exact preserved sources',()=>{assert.deepEqual(A.sourceResolutions.map(x=>x.decisionId),['SV-WT-STANDARDS-SOURCE','SV-AWT-STANDARDS-SOURCE']);for(const x of A.sourceResolutions){assert.equal(x.gateStatus,'RESOLVED_SOURCE_VERIFIED');assert.equal(x.importAuthorized,false);assert.equal(x.controllingSources.length,1);let s=x.controllingSources[0];assert.equal(hash(fs.readFileSync(s.path)),s.sha256);}});
test('official comparison covers 29 ordered codes and exactly two abbreviation differences',()=>{assert.equal(A.sourceResolutions.reduce((n,x)=>n+x.comparison.standardCount,0),29);let d=A.sourceResolutions.flatMap(x=>x.comparison.wordingDifferences);assert.deepEqual(d.map(x=>x.code),['WT 2.2','AWT 2.2']);for(const x of d){assert(x.officialWording.includes('American National Standards Institute (ANSI)/American Welding Society (AWS)'));assert(x.repositoryWording.includes('ANSI/AWS'));assert.equal(x.controllingWording,'official');}});
test('ten instructor-selected Essentials retain three-part provenance',()=>{assert.deepEqual(A.essentialProvenance[0].selections,['WT 1.1','WT 2.1','WT 3.3','WT 4.3']);assert.deepEqual(A.essentialProvenance[1].selections,['AWT 1.1','AWT 3.2','AWT 5.3','AWT 6.1','AWT 7.3','AWT 9.1']);for(const x of A.essentialProvenance){assert.equal(x.provenance.length,3);assert.equal(x.newSelectionCreated,false);assert(x.designationAuthority.includes('not South Dakota DOE'));}});
test('all 408 historical items are accounted for once as 149 content and 259 absent optional relationships',()=>{let d=A.effectiveDispositions;assert.equal(d.length,408);assert.equal(new Set(d.map(x=>x.originalQueueIndex)).size,408);assert.equal(new Set(d.map(x=>x.originalItemFingerprint)).size,408);assert.equal(d.filter(x=>x.effectiveDisposition==='PRESERVE_EXACT_CONTENT').length,149);assert.equal(d.filter(x=>x.effectiveDisposition==='LEAVE_OPTIONAL_RELATIONSHIP_ABSENT').length,259);assert(d.every(x=>!x.blocksContentPreservation&&!x.authorizesImport));});
test('51 explicit WT Lesson competency links are preserved and no AWT mapping is invented',()=>{assert.equal(A.preservedApprovedRelationships.explicitWtLessonCompetencyLinks.length,51);assert.equal(A.preservedApprovedRelationships.awtLessonCompetencyLinksCreated,0);assert.equal(new Set(A.preservedApprovedRelationships.explicitWtLessonCompetencyLinks.map(x=>x.lessonCompetencyLinkId)).size,51);});
test('overlay authorizes no import, database path, schema/store change, or parity advance',()=>{assert.deepEqual(A.importAuthorization,{authorized:false,dryRunAuthorized:false,databaseMutationAuthorized:false,nextPossibleStep:'Separately scoped reviewed import/dry-run planning after R1B acceptance.'});assert.equal(A.startingAuthority.academicAuthority,'V7_ONLY');const source=fs.readFileSync('scripts/generate_p10d_r1b_source_disposition_freeze.js','utf8');for(const forbidden of ['indexedDB.open','openDatabase(','arc_classroom_v8'])assert(!source.includes(forbidden),forbidden);const C=require('../parity/stage14_v7_v8_parity_contract');assert.equal(C.authorityState,'V7_ONLY');assert.equal(C.rows.filter(x=>x.status==='service-ready').length,40);assert.equal(C.rows.filter(x=>x.status==='not-started').length,4);assert.equal(C.rows.filter(x=>x.status==='accepted').length,3);});
test('runtime, parity, historical reconciliation, and preserved source authority remain byte unchanged',()=>{for(const [file,bytes] of Object.entries(before)){assert(fs.readFileSync(file).equals(bytes),file);if(file==='src/arc_v8_storage.js')continue;let accepted=cp.execFileSync('git',['show',`${start}:${file}`],{encoding:'utf8',maxBuffer:8*1024*1024}).replace(/\r\n/g,'\n'),current=bytes.toString('utf8').replace(/\r\n/g,'\n');assert.equal(current,accepted,file);}});
test('R1B documentation preserves boundaries and later import gate',()=>{let d=fs.readFileSync('docs/ARC_STAGE_14_V7_V8_NO_REGRESSION_PARITY_P10D_R1B.md','utf8');for(const x of ['V7_ONLY','WT 2.2','AWT 2.2','149','259','51','no content import','no parity advance','Classroom Ready'])assert(d.includes(x),x);});
isolatedTest('rejects stale and recomputed manifest self-digests before output',root=>json(root,'reconciliation/p10d/instructional-content-manifest.json',value=>{value.courses.wt.summary.standardCount++;delete value.manifestHash;value.manifestHash=hash(value);}));
isolatedTest('rejects altered queue-only input and creates no output',root=>json(root,'reconciliation/p10d/human-review-queue.json',value=>{value.items[0].reasons=['altered queue reason'];}),{absent:true});
isolatedTest('rejects altered transcription and findings inputs before output',root=>{json(root,'source_authority/recovered_2026-09-29/transcriptions/south-dakota-welding-standards.json',value=>{value.adopted='altered';});fs.appendFileSync(path.join(root,'source_authority/recovered_2026-09-29/SOURCE_AUTHORITY_FINDINGS.md'),'\naltered\n');});
isolatedTest('rejects unknown classifications and decisions without overwriting output',root=>json(root,'reconciliation/p10d/original-item-resolution-map.json',value=>{value.mappings[0].classification='unknown classification';value.mappings[0].decisionId='NONEXISTENT-DECISION';}));
isolatedTest('rejects duplicate, missing and out-of-range queue mapping coverage',root=>json(root,'reconciliation/p10d/original-item-resolution-map.json',value=>{value.mappings[1].originalQueueIndex=value.mappings[0].originalQueueIndex;value.mappings.pop();value.mappings[2].originalQueueIndex=999;}));
isolatedTest('rejects mismatched manifest identities, fingerprints and course routes',root=>json(root,'reconciliation/p10d/original-item-resolution-map.json',value=>{value.mappings[0].manifestRecordId='missing-record';value.mappings[1].originalItemFingerprint='0'.repeat(64);value.mappings[2].course='awt';}));
isolatedTest('rejects contradictory consolidated decision authority',root=>json(root,'reconciliation/p10d/consolidated-review-queue.json',value=>{const d=value.decisions.find(x=>x.decisionId==='MF-CURRICULUM-CONTENT-SEPARATION');d.decisionClass='safe unresolved relationship';d.course='awt';}));
isolatedTest('rejects altered preserved source bytes without overwriting output',root=>{const file=path.join(root,'source_authority/recovered_2026-09-29/source_material/13207-WeldingTech.pdf');fs.appendFileSync(file,Buffer.from([0]));});
test('pure relationship validation explicitly rejects unknown classification and decision',()=>{const M=require('../reconciliation/p10d/instructional-content-manifest.json'),Q=require('../reconciliation/p10d/human-review-queue.json'),C=require('../reconciliation/p10d/consolidated-review-queue.json'),R=structuredClone(require('../reconciliation/p10d/original-item-resolution-map.json'));R.mappings[0].classification='unknown classification';R.mappings[0].decisionId='NONEXISTENT-DECISION';assert.throws(()=>validateRelationships(M,Q,C,R),/decision route|classification|Unknown decision/);});
test('pure relationship validation explicitly rejects bad identity and fingerprint',()=>{const M=require('../reconciliation/p10d/instructional-content-manifest.json'),Q=require('../reconciliation/p10d/human-review-queue.json'),C=require('../reconciliation/p10d/consolidated-review-queue.json'),R=structuredClone(require('../reconciliation/p10d/original-item-resolution-map.json'));R.mappings[0].originalItemFingerprint='0'.repeat(64);assert.throws(()=>validateRelationships(M,Q,C,R),/fingerprint/);R.mappings[0].originalItemFingerprint=hash(Q.items[0]);R.mappings[0].manifestRecordId='missing-record';assert.throws(()=>validateRelationships(M,Q,C,R),/manifest identity|manifest record/);});
test('pure relationship validation explicitly rejects duplicate and out-of-range indexes',()=>{const M=require('../reconciliation/p10d/instructional-content-manifest.json'),Q=require('../reconciliation/p10d/human-review-queue.json'),C=require('../reconciliation/p10d/consolidated-review-queue.json'),R=structuredClone(require('../reconciliation/p10d/original-item-resolution-map.json'));R.mappings[1].originalQueueIndex=R.mappings[0].originalQueueIndex;assert.throws(()=>validateRelationships(M,Q,C,R),/Duplicate queue index/);R.mappings[1].originalQueueIndex=999;assert.throws(()=>validateRelationships(M,Q,C,R),/Invalid queue index/);});
if(!process.exitCode)console.log(`\n${pass}/${total} P10D-R1B source disposition tests passed.`);
