const assert=require('assert'),fs=require('fs'),crypto=require('crypto'),cp=require('child_process');
const manifestPath='reconciliation/p10d/instructional-content-manifest.json',queuePath='reconciliation/p10d/human-review-queue.json';
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])]));return v;}
function hash(v){return crypto.createHash('sha256').update(typeof v==='string'?v:JSON.stringify(stable(v))).digest('hex');}
let pass=0,total=0;function test(name,fn){total++;try{fn();pass++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1}}
const beforeManifest=fs.readFileSync(manifestPath,'utf8'),beforeQueue=fs.readFileSync(queuePath,'utf8');cp.execFileSync(process.execPath,['scripts/generate_p10d_instructional_manifest.js'],{stdio:'pipe'});const afterManifest=fs.readFileSync(manifestPath,'utf8'),afterQueue=fs.readFileSync(queuePath,'utf8'),M=JSON.parse(afterManifest),Q=JSON.parse(afterQueue);
test('generation is byte reproducible with stable manifest hash',()=>{assert.equal(afterManifest,beforeManifest);assert.equal(afterQueue,beforeQueue);let clone=structuredClone(M);delete clone.manifestHash;assert.equal(M.manifestHash,hash(clone));assert.equal(Q.manifestHash,M.manifestHash);});
test('complete WT and AWT source inventory remains separate',()=>{assert.deepEqual(M.courses.wt.summary,{standards:9,essentialDesignations:4,competencies:26,curriculumMaps:1,curriculumMapVersions:1,curriculumItems:29,lessons:51});assert.deepEqual(M.courses.awt.summary,{standards:20,essentialDesignations:6,competencies:34,curriculumMaps:1,curriculumMapVersions:1,curriculumItems:27,lessons:73});for(const course of ['wt','awt'])for(const family of Object.values(M.courses[course]).filter(Array.isArray))for(const row of family)if(row.courseId)assert.equal(row.courseId,course);});
test('IDs use approved identity inputs and never display title alone',()=>{assert.equal(M.idRule.algorithm,'lowercase ASCII slug plus first 12 lowercase hex characters of SHA-256(kind|course|approved source identity)');for(const course of ['wt','awt']){let c=M.courses[course];assert.equal(new Set(c.standards.map(x=>x.standardId)).size,c.standards.length);assert.equal(new Set(c.lessonDefinitions.map(x=>x.lessonId)).size,c.lessonDefinitions.length);assert(c.lessonDefinitions.every(x=>x.lessonId.includes('-'+course+'-')));}});
test('source hashes cover every proposed source record',()=>{for(const course of ['wt','awt'])for(const family of Object.values(M.courses[course]).filter(Array.isArray))for(const row of family)if(row.source)assert.match(row.source.sourceHash||row.sourceHash,/^[a-f0-9]{64}$/);});
test('no duplicate is silently merged and all source Lesson codes remain',()=>{for(const course of ['wt','awt']){let defs=M.courses[course].lessonDefinitions,versions=M.courses[course].lessonVersions;assert.equal(defs.length,versions.length);assert.equal(new Set(defs.map(x=>x.lessonCode)).size,defs.length);assert(defs.every(x=>x.duplicate&&typeof x.duplicate.exact==='boolean'));}});
test('approved links are referentially consistent and relationship ambiguity is explicit',()=>{for(const course of ['wt','awt']){let c=M.courses[course],standards=new Set(c.standards.map(x=>x.standardVersionId)),competencies=new Set(c.competencies.map(x=>x.competencyVersionId)),lessons=new Set(c.lessonVersions.map(x=>x.lessonVersionId)),items=new Set(c.curriculumMapItems.map(x=>x.curriculumMapItemId));for(const x of c.curriculumItemStandardLinks.filter(x=>x.disposition==='APPROVE_AS_IS'))assert(standards.has(x.standardVersionId)&&items.has(x.curriculumMapItemId));for(const x of c.lessonVersionStandardLinks.filter(x=>x.disposition==='APPROVE_AS_IS'))assert(standards.has(x.standardVersionId)&&lessons.has(x.lessonVersionId));for(const x of c.lessonVersionCompetencyLinks.filter(x=>x.disposition==='APPROVE_AS_IS'))assert(competencies.has(x.competencyVersionId)&&lessons.has(x.lessonVersionId));for(const family of [c.curriculumItemCompetencyLinks,c.lessonVersionCompetencyLinks,c.lessonVersionCurriculumLinks,c.lessonVersionActivityLinks])for(const x of family.filter(x=>x.disposition==='REVIEW_REQUIRED'))assert(x.basis&&x.relationshipType==='REVIEW_REQUIRED');}});
test('sentence-stem findings preserve source and report every nonconformance',()=>{for(const course of ['wt','awt']){let failures=M.courses[course].lessonDefinitions.filter(x=>!x.validation.learningTargetStemConforming||!x.validation.successCriteriaStemConforming);assert.equal(failures.length,0);}});
test('transactional pilot and fictional history are exclusions only',()=>{assert.deepEqual(M.exclusions.map(x=>x.disposition),Array(5).fill('EXCLUDE_TRANSACTIONAL'));let content=JSON.stringify(M.courses);for(const token of ['sectionCurriculumProgress','pacingHistorySnapshots','sectionArchives'])assert(!content.includes(token));});
test('manifest tooling changes no runtime build cache schema or database authority',()=>{for(const file of ['index.html','app-build.js','sw.js','src/arc_v8_storage.js']){let current=fs.readFileSync(file,'utf8').replace(/\r\n/g,'\n'),accepted=cp.execFileSync('git',['show','d8ac2b0935896d814c721ba48bab8f75c5020828:'+file],{encoding:'utf8'}).replace(/\r\n/g,'\n');assert.equal(current,accepted,file);}assert.equal(M.databaseMutation,false);assert.equal(M.schemaVersion,8);assert.equal(M.idbVersionObserved,13);});
if(!process.exitCode)console.log(`\n${pass}/${total} P10D instructional reconciliation tests passed.`);
