const assert=require('assert'),fs=require('fs'),crypto=require('crypto'),cp=require('child_process');
const output='reconciliation/p10d/r1b-source-disposition-freeze.json',start='16f7e186051d2778a6e8e0afb0fad4dfc72787d4';
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])]));return v;}
const hash=v=>crypto.createHash('sha256').update(typeof v==='string'||Buffer.isBuffer(v)?v:JSON.stringify(stable(v))).digest('hex');
let pass=0,total=0;function test(name,fn){total++;try{fn();pass++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1}}
const protectedFiles=['index.html','app-build.js','app.webmanifest','sw.js','src/arc_v8_storage.js','parity/stage14_v7_v8_parity_contract.js','reconciliation/p10d/instructional-content-manifest.json','reconciliation/p10d/human-review-queue.json','reconciliation/p10d/consolidated-review-queue.json','reconciliation/p10d/original-item-resolution-map.json','source_authority/recovered_2026-09-29/source-manifest.json','source_authority/recovered_2026-09-29/standards-comparison.json','source_authority/recovered_2026-09-29/transcriptions/south-dakota-welding-standards.json'];
const before=Object.fromEntries(protectedFiles.map(f=>[f,fs.readFileSync(f)]));cp.execFileSync(process.execPath,['scripts/generate_p10d_r1b_source_disposition_freeze.js'],{stdio:'pipe'});const first=fs.readFileSync(output,'utf8');cp.execFileSync(process.execPath,['scripts/generate_p10d_r1b_source_disposition_freeze.js'],{stdio:'pipe'});const second=fs.readFileSync(output,'utf8'),A=JSON.parse(second);
test('generation is byte deterministic and artifact hash is valid',()=>{assert.equal(first,second);let clone=structuredClone(A);delete clone.artifactHash;assert.equal(A.artifactHash,hash(clone));});
test('two source gates resolve independently to exact preserved sources',()=>{assert.deepEqual(A.sourceResolutions.map(x=>x.decisionId),['SV-WT-STANDARDS-SOURCE','SV-AWT-STANDARDS-SOURCE']);for(const x of A.sourceResolutions){assert.equal(x.gateStatus,'RESOLVED_SOURCE_VERIFIED');assert.equal(x.importAuthorized,false);assert.equal(x.controllingSources.length,1);let s=x.controllingSources[0];assert.equal(hash(fs.readFileSync(s.path)),s.sha256);}});
test('official comparison covers 29 ordered codes and exactly two abbreviation differences',()=>{assert.equal(A.sourceResolutions.reduce((n,x)=>n+x.comparison.standardCount,0),29);let d=A.sourceResolutions.flatMap(x=>x.comparison.wordingDifferences);assert.deepEqual(d.map(x=>x.code),['WT 2.2','AWT 2.2']);for(const x of d){assert(x.officialWording.includes('American National Standards Institute (ANSI)/American Welding Society (AWS)'));assert(x.repositoryWording.includes('ANSI/AWS'));assert.equal(x.controllingWording,'official');}});
test('ten instructor-selected Essentials retain three-part provenance',()=>{assert.deepEqual(A.essentialProvenance[0].selections,['WT 1.1','WT 2.1','WT 3.3','WT 4.3']);assert.deepEqual(A.essentialProvenance[1].selections,['AWT 1.1','AWT 3.2','AWT 5.3','AWT 6.1','AWT 7.3','AWT 9.1']);for(const x of A.essentialProvenance){assert.equal(x.provenance.length,3);assert.equal(x.newSelectionCreated,false);assert(x.designationAuthority.includes('not South Dakota DOE'));}});
test('all 408 historical items are accounted for once as 149 content and 259 absent optional relationships',()=>{let d=A.effectiveDispositions;assert.equal(d.length,408);assert.equal(new Set(d.map(x=>x.originalQueueIndex)).size,408);assert.equal(new Set(d.map(x=>x.originalItemFingerprint)).size,408);assert.equal(d.filter(x=>x.effectiveDisposition==='PRESERVE_EXACT_CONTENT').length,149);assert.equal(d.filter(x=>x.effectiveDisposition==='LEAVE_OPTIONAL_RELATIONSHIP_ABSENT').length,259);assert(d.every(x=>!x.blocksContentPreservation&&!x.authorizesImport));});
test('51 explicit WT Lesson competency links are preserved and no AWT mapping is invented',()=>{assert.equal(A.preservedApprovedRelationships.explicitWtLessonCompetencyLinks.length,51);assert.equal(A.preservedApprovedRelationships.awtLessonCompetencyLinksCreated,0);assert.equal(new Set(A.preservedApprovedRelationships.explicitWtLessonCompetencyLinks.map(x=>x.lessonCompetencyLinkId)).size,51);});
test('overlay authorizes no import, database path, schema/store change, or parity advance',()=>{assert.deepEqual(A.importAuthorization,{authorized:false,dryRunAuthorized:false,databaseMutationAuthorized:false,nextPossibleStep:'Separately scoped reviewed import/dry-run planning after R1B acceptance.'});assert.equal(A.startingAuthority.academicAuthority,'V7_ONLY');const source=fs.readFileSync('scripts/generate_p10d_r1b_source_disposition_freeze.js','utf8');for(const forbidden of ['indexedDB.open','openDatabase(','arc_classroom_v8'])assert(!source.includes(forbidden),forbidden);const C=require('../parity/stage14_v7_v8_parity_contract');assert.equal(C.authorityState,'V7_ONLY');assert.equal(C.rows.filter(x=>x.status==='service-ready').length,40);assert.equal(C.rows.filter(x=>x.status==='not-started').length,4);assert.equal(C.rows.filter(x=>x.status==='accepted').length,3);});
test('runtime, parity, historical reconciliation, and preserved source authority remain byte unchanged',()=>{for(const [file,bytes] of Object.entries(before)){assert(fs.readFileSync(file).equals(bytes),file);let accepted=cp.execFileSync('git',['show',`${start}:${file}`],{encoding:'utf8',maxBuffer:8*1024*1024}).replace(/\r\n/g,'\n'),current=bytes.toString('utf8').replace(/\r\n/g,'\n');assert.equal(current,accepted,file);}});
test('R1B documentation preserves boundaries and later import gate',()=>{let d=fs.readFileSync('docs/ARC_STAGE_14_V7_V8_NO_REGRESSION_PARITY_P10D_R1B.md','utf8');for(const x of ['V7_ONLY','WT 2.2','AWT 2.2','149','259','51','no content import','no parity advance','Classroom Ready'])assert(d.includes(x),x);});
if(!process.exitCode)console.log(`\n${pass}/${total} P10D-R1B source disposition tests passed.`);
