const assert=require('assert');
const P=require('../src/project_bank');
let passed=0;
function test(name,fn){try{fn();passed++;console.log('PASS',name)}catch(error){console.error('FAIL',name,error.message);process.exitCode=1}}
function definition(){return P.normalizeDefinition({id:'rack',title:'Helmet Rack',studentTitle:'Build a Helmet Rack',type:'Build Project',difficulty:3,applicability:{wt:true,awt:false},recommendedReadiness:'Basic layout and fit-up',minimumClearance:2,materials:['Flat bar'],equipmentRequirements:['SMAW machine'],processRequirements:['SMAW'],linkedStandards:['WT 3.1'],linkedCompetencies:['WT-F2'],stages:[{id:'assigned',name:'Assigned'},{id:'fit',name:'Fit-Up',requiresInstructorCheck:true},{id:'complete',name:'Complete'}],instructorCheckpoints:[{id:'fit_check',name:'Fit-up approval',stageId:'fit'}]});}
test('normalizes complete reusable definition separately from assignments',()=>{let d=definition();assert.equal(d.id,'rack');assert.equal(d.studentTitle,'Build a Helmet Rack');assert.equal(d.difficulty,3);assert.deepEqual(d.applicability,{wt:true,awt:false});assert.equal(d.materials[0].name,'Flat bar');assert.equal(d.linkedCompetencies[0],'WT-F2')});
test('difficulty and course applicability remain separate',()=>{let d=definition();assert.equal(d.difficulty,3);assert.equal(d.applicability.awt,false);d.applicability.awt=true;assert.equal(d.difficulty,3)});
test('assignment receives independent stage need and history records',()=>{let d=definition(),a=P.assignment(d,{assignmentId:'a1',sectionId:'sec1',course:'wt',timestamp:'2026-09-18T14:00:00Z',isPrimary:true});assert.equal(a.templateId,'rack');assert.equal(a.currentStageId,'assigned');assert.equal(a.currentNeed,'Ready to Work');assert.equal(a.stageHistory.length,1);assert.equal(a.needHistory.length,1);assert.notStrictEqual(a.stages,d.stages)});
test('multiple assignments can coexist and only one is primary',()=>{let d=definition(),a=P.assignment(d,{assignmentId:'a1'}),b=P.assignment(d,{assignmentId:'a2'}),list=P.setPrimary([a,b],'a2');assert.equal(list[0].isPrimary,false);assert.equal(list[1].isPrimary,true);assert.equal(P.primary(list).id,'a2')});
test('stage advancement appends history and does not create ratings',()=>{let a=P.assignment(definition(),{assignmentId:'a1',timestamp:'2026-09-18T14:00:00Z'}),next=P.setStage(a,'fit',{timestamp:'2026-09-18T15:00:00Z'});assert.equal(next.currentStageId,'fit');assert.equal(next.stageHistory.length,2);assert.equal(next.currentNeed,'Needs Instructor Check');assert.equal(next.ratings,undefined);assert.equal(a.currentStageId,'assigned')});
test('current need is operational and preserves source history',()=>{let a=P.assignment(definition(),{assignmentId:'a1'}),next=P.setNeed(a,'Needs Material',{source:'Instructor',timestamp:'2026-09-18T15:00:00Z'});assert.equal(next.currentNeed,'Needs Material');assert.equal(next.needHistory.at(-1).source,'Instructor');assert.equal(next.score,null)});
test('clearance review warns without blocking assignment',()=>{let d=definition(),review=P.clearanceReview(d,1),a=P.assignment(d,{assignmentId:'override'});assert.equal(review.review,true);assert(review.reason.includes('stored clearance is 1'));assert.equal(a.templateId,d.id)});
test('missing clearance gets review workflow',()=>assert.equal(P.clearanceReview(definition(),null).review,true));
test('legacy libraries migrate without deleting templates and starters seed once',()=>{let x=P.mergeDefinitions([],{wt:[{id:'old',title:'Old Project'}],awt:[]}),again=P.mergeDefinitions(x,{wt:[],awt:[]});assert(x.some(d=>d.id==='old'));assert(x.some(d=>d.id==='pb_wt_coupon_holder'));assert.equal(new Set(again.map(d=>d.id)).size,again.length)});
test('archived definitions remain data records',()=>{let d=P.normalizeDefinition({id:'old',title:'Old',archived:true});assert.equal(d.archived,true);assert.equal(d.title,'Old')});
test('starter projects are WT Level 1-2 with kid-friendly text',()=>P.starterDefinitions().forEach(d=>{assert.equal(d.applicability.wt,true);assert.equal(d.applicability.awt,false);assert(d.difficulty>=1&&d.difficulty<=2);assert(d.studentDescription);assert(d.studentInstructions)}));
if(!process.exitCode)console.log('PASS '+passed+' Project Bank v1 tests');
