const assert=require('assert');
const X=require('../src/project_checkpoint_persistence');
const K=require('../src/project_checkpoint_controller');
let pass=0,total=0;function test(name,fn){total++;try{fn();pass++;console.log('PASS',name);}catch(e){console.error('FAIL',name,e.message);process.exitCode=1;}}
function state(){return {academicYear:'2026-27',semester:'Semester 1',activeSectionId:'sec1'};}
function student(){return {id:'s1',name:'Alex',enrollments:[{year:'2026-27',semester:'Semester 1',sectionId:'sec1',active:true}],projects:[K.initialize({templateId:'p1',name:'Welding Table',status:'in_progress'})]};}
test('transaction returns updated student and history entry',()=>{let r=X.transact(state(),student(),'p1','start','plan',{timestamp:'2026-09-16T14:00:00',historyId:'h1'});assert.equal(r.changed,true);assert.equal(r.project.checkpoints[0].status,'in_progress');assert.equal(r.historyEntry.type,'project_checkpoint');assert.equal(r.historyEntry.label,'Checkpoint started');});
test('history preserves academic scope',()=>{let r=X.transact(state(),student(),'p1','ready','plan',{timestamp:'2026-09-16T14:00:00',historyId:'h1'});assert.equal(r.historyEntry.academicYear,'2026-27');assert.equal(r.historyEntry.semester,'Semester 1');assert.equal(r.historyEntry.sectionId,'sec1');});
test('verification history records instructor and status change',()=>{let r=X.transact(state(),student(),'p1','verify','plan',{timestamp:'2026-09-16T14:00:00',verifiedBy:'teacher',historyId:'h1'});assert.equal(r.historyEntry.fromStatus,'not_started');assert.equal(r.historyEntry.toStatus,'verified');assert.equal(r.historyEntry.verifiedBy,'teacher');});
test('transaction leaves source student untouched',()=>{let s=student(),before=JSON.stringify(s);X.transact(state(),s,'p1','start','plan',{timestamp:'2026-09-16T14:00:00'});assert.equal(JSON.stringify(s),before);});
test('unknown action produces no history',()=>{let s=student(),r=X.transact(state(),s,'p1','mystery','plan',{});assert.equal(r.changed,false);assert.equal(r.historyEntry,null);assert.strictEqual(r.student,s);});
test('unknown project produces no transaction',()=>{let s=student(),r=X.transact(state(),s,'missing','start','plan',{});assert.equal(r.changed,false);assert.equal(r.historyEntry,null);});
test('undo restores exact previous project snapshot',()=>{let s=student(),before=JSON.stringify(s.projects[0]),r=X.transact(state(),s,'p1','verify','plan',{timestamp:'2026-09-16T14:00:00',verifiedBy:'teacher',historyId:'h1'}),u=X.applyUndo(r.student,r.undo);assert.equal(u.changed,true);assert.equal(JSON.stringify(u.student.projects[0]),before);});
test('undo does not mutate updated student',()=>{let r=X.transact(state(),student(),'p1','start','plan',{timestamp:'2026-09-16T14:00:00'}),before=JSON.stringify(r.student);X.applyUndo(r.student,r.undo);assert.equal(JSON.stringify(r.student),before);});
test('undo for another student is rejected',()=>{let r=X.transact(state(),student(),'p1','start','plan',{timestamp:'2026-09-16T14:00:00'}),other=Object.assign({},r.student,{id:'s2'}),u=X.applyUndo(other,r.undo);assert.equal(u.changed,false);});
test('append history is immutable',()=>{let h=[{id:'old'}],r=X.transact(state(),student(),'p1','start','plan',{timestamp:'2026-09-16T14:00:00',historyId:'new'}),next=X.appendHistory(h,r.historyEntry);assert.equal(h.length,1);assert.equal(next.length,2);assert.equal(next[1].id,'new');});
test('history entry contains project and checkpoint names',()=>{let r=X.transact(state(),student(),'p1','start','plan',{timestamp:'2026-09-16T14:00:00'});assert.equal(r.historyEntry.projectName,'Welding Table');assert.equal(r.historyEntry.checkpointName,'Plan & Understand');});
test('checkpoint speed is never written as grade evidence',()=>{let r=X.transact(state(),student(),'p1','verify','plan',{timestamp:'2026-09-16T14:00:00',verifiedBy:'teacher'});assert.equal(Object.prototype.hasOwnProperty.call(r.historyEntry,'grade'),false);assert.equal(Object.prototype.hasOwnProperty.call(r.historyEntry,'score'),false);});
if(!process.exitCode)console.log('\n'+pass+'/'+total+' Project Checkpoint Persistence tests passed.');