const assert=require('assert');
const A=require('../src/needs_attention_arc_adapter');
const E=require('../src/needs_attention_engine');
const C=require('../src/project_checkpoints');
const K=require('../src/project_checkpoint_controller');
let pass=0,total=0;function test(name,fn){total++;try{fn();pass++;console.log('PASS',name);}catch(e){console.error('FAIL',name,e.message);process.exitCode=1;}}
function state(){return {academicYear:'2026-27',semester:'Semester 1',activeSectionId:'sec1',sections:[{id:'sec1',course:'wt',period:2}],classes:{wt:[{id:'s1',name:'Alex',enrollments:[{year:'2026-27',semester:'Semester 1',sectionId:'sec1',period:2,course:'wt',active:true}],ratings:{},ratingScopes:{},projects:[{templateId:'p1',name:'Welding Table',status:'in_progress',checkpoints:[{id:'plan',enabled:true,status:'in_progress',updatedAt:'2026-09-01T14:00:00'}],checkpointActivity:[]}],tech:[],workplacePoints:{}}],awt:[]},lessonBank:{wt:[],awt:[]},pacingPlans:{},attendanceRecords:{},technicalLibrary:{wt:[],awt:[]}};}
function activity(s,type,date,opts){let p=s.classes.wt[0].projects[0],x={id:'a'+(p.checkpointActivity.length+1),checkpointId:'plan',type,date,academicYear:'2026-27',semester:'Semester 1',sectionId:'sec1'};Object.assign(x,opts||{});p.checkpointActivity.push(x);return s;}
function adaptProject(s,today){return A.adapt(s,{today:today||'2026-09-15',sectionId:'sec1'}).students[0].projects[0];}
function alerts(s,today){return E.generate(A.adapt(s,{today:today||'2026-09-15',sectionId:'sec1'}));}
test('activityRecord preserves academic scope',()=>{let r=C.activityRecord({type:'progress',date:'2026-09-01',academicYear:'2026-27',semester:'Semester 1',sectionId:'sec1'});assert.equal(r.academicYear,'2026-27');assert.equal(r.semester,'Semester 1');assert.equal(r.sectionId,'sec1');});
test('controller transition writes academic scope',()=>{let p=K.start({name:'Table'},'plan',{date:'2026-09-01',academicYear:'2026-27',semester:'Semester 1',sectionId:'sec1'}),r=p.checkpointActivity[0];assert.equal(r.academicYear,'2026-27');assert.equal(r.semester,'Semester 1');assert.equal(r.sectionId,'sec1');});
test('controller opportunity writes academic scope',()=>{let p=K.recordOpportunity({name:'Table'},'plan',{date:'2026-09-02',academicYear:'2026-27',semester:'Semester 1',sectionId:'sec1',opportunityConfirmed:true}),r=p.checkpointActivity[0];assert.equal(r.academicYear,'2026-27');assert.equal(r.semester,'Semester 1');assert.equal(r.sectionId,'sec1');});
test('three scoped opportunities after progress can flag stalled',()=>{let s=state();activity(s,'progress','2026-09-01',{meaningfulProgress:true});['2026-09-10','2026-09-11','2026-09-12'].forEach(d=>activity(s,'opportunity',d,{opportunityConfirmed:true}));let y=alerts(s);assert.equal(y.length,1);assert.equal(y[0].ruleId,'project_stalled');});
test('three opportunities before later progress do not remain stalled opportunities',()=>{let s=state();['2026-09-01','2026-09-02','2026-09-03'].forEach(d=>activity(s,'opportunity',d,{opportunityConfirmed:true}));activity(s,'progress','2026-09-05',{meaningfulProgress:true});let p=adaptProject(s,'2026-09-15');assert.equal(p.eligibleOpportunities,0);assert.equal(alerts(s,'2026-09-15').length,0);});
test('same-day opportunity does not count after progress without time ordering',()=>{let s=state();activity(s,'progress','2026-09-01',{meaningfulProgress:true});activity(s,'opportunity','2026-09-01',{opportunityConfirmed:true});let p=adaptProject(s);assert.equal(p.eligibleOpportunities,0);});
test('other section activity is ignored',()=>{let s=state();activity(s,'progress','2026-09-01',{meaningfulProgress:true});['2026-09-10','2026-09-11','2026-09-12'].forEach(d=>activity(s,'opportunity',d,{opportunityConfirmed:true,sectionId:'sec2'}));let p=adaptProject(s);assert.equal(p.eligibleOpportunities,0);});
test('other semester activity is ignored',()=>{let s=state();activity(s,'progress','2026-09-01',{meaningfulProgress:true});['2026-09-10','2026-09-11','2026-09-12'].forEach(d=>activity(s,'opportunity',d,{opportunityConfirmed:true,semester:'Semester 2'}));let p=adaptProject(s);assert.equal(p.eligibleOpportunities,0);});
test('other academic year activity is ignored',()=>{let s=state();activity(s,'progress','2026-09-01',{meaningfulProgress:true});['2026-09-10','2026-09-11','2026-09-12'].forEach(d=>activity(s,'opportunity',d,{opportunityConfirmed:true,academicYear:'2025-26'}));let p=adaptProject(s);assert.equal(p.eligibleOpportunities,0);});
test('legacy unscoped activity cannot activate stalled logic',()=>{let s=state(),p=s.classes.wt[0].projects[0];p.checkpointActivity=[{type:'progress',date:'2026-09-01',meaningfulProgress:true},{type:'opportunity',date:'2026-09-10',opportunityConfirmed:true},{type:'opportunity',date:'2026-09-11',opportunityConfirmed:true},{type:'opportunity',date:'2026-09-12',opportunityConfirmed:true}];assert.equal(A.adapt(s,{today:'2026-09-15',sectionId:'sec1'}).students[0].projects.length,0);assert.equal(alerts(s).length,0);});
['excused','activity','noclass'].forEach(status=>test(status+' excludes scoped opportunity',()=>{let s=state();activity(s,'progress','2026-09-01',{meaningfulProgress:true});['2026-09-10','2026-09-11'].forEach(d=>activity(s,'opportunity',d,{opportunityConfirmed:true}));activity(s,'opportunity','2026-09-12',{opportunityConfirmed:true});s.attendanceRecords['sec1::2026-09-12']={students:{s1:{status}}};assert.equal(adaptProject(s).eligibleOpportunities,2);assert.equal(alerts(s).length,0);}));
test('ready for review remains independent of scoped activity',()=>{let s=state(),p=s.classes.wt[0].projects[0];p.checkpoints[0].status='ready_for_review';p.checkpointActivity=[];let y=alerts(s);assert.equal(y.length,1);assert.equal(y[0].ruleId,'ready_for_review');assert.equal(y[0].priority,'P1');});
['completed','NE','absent'].forEach(status=>test(status+' project does not flag stalled',()=>{let s=state(),p=s.classes.wt[0].projects[0];p.status=status;activity(s,'progress','2026-09-01',{meaningfulProgress:true});['2026-09-10','2026-09-11','2026-09-12'].forEach(d=>activity(s,'opportunity',d,{opportunityConfirmed:true}));assert.equal(alerts(s).length,0);}));
if(!process.exitCode)console.log('\n'+pass+'/'+total+' Project Activity Scope tests passed.');
