const assert=require('assert');
const fs=require('fs');
const html=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('sw.js','utf8');
function has(text){return html.includes(text)}
assert(has('src/project_bank.js'),'host must load Project Bank model');
assert(sw.includes('./src/project_bank.js'),'offline shell must cache Project Bank model');
assert(has('const CURRENT_SCHEMA_VERSION = 7'),'Project Bank must use additive schema 7');
assert(has('Schema 7 creates reusable Project Bank definitions and independent operational assignment state'),'migration contract missing');
assert(has('x.projectBank = ArcProjectBank.mergeDefinitions'),'legacy reusable templates must migrate');
assert(has('ArcProjectBank.normalizeAssignment(project, definition'),'existing assignments must migrate without deletion');
assert(has('function projectDefinitionForm'),'Project Bank editor must exist');
['pbTitle','pbStudentTitle','pbDescription','pbInstructions','pbType','pbDifficulty','pbWT','pbAWT','pbTime','pbNotes','pbMaterials','pbEquipment','pbProcesses','pbStandards','pbCompetencies','pbReadiness','pbStages','pbCheckpoints'].forEach(id=>assert(has('id="'+id+'"'),'editor field missing '+id));
assert(has('function showEditClassProject'),'definition editing must exist');
assert(has('function showCopyClassProject'),'definition copying must exist');
assert(has('function confirmDeleteClassProject'),'definition archiving must exist');
assert(has('definition.archived = true'),'archive must preserve definition history');
assert(has('function showAssignProjectStudents'),'class selected-student assignment must exist');
assert(has('function showProjectAssigner'),'individual assignment must remain');
assert(has('Independent assignment ${assignment.id} created from Project Bank.'),'assignment history must identify independent records');
assert(has('function setStudentProjectStage'),'stage workflow must exist');
assert(has('function setStudentProjectNeed'),'current-need workflow must exist');
assert(has('Operational stage only; no competency rating or project grade changed.'),'stage changes must state grading boundary');
assert(has('Operational information only; not negative evidence and no grade changed.'),'needs must remain non-judgmental');
assert(has('function setStudentPrimaryProject'),'multiple assignments must support a primary/current designation');
assert(has('function requestProjectAssignments'),'readiness review workflow must exist');
assert(has('Assign Anyway'),'instructor override must remain explicit');
assert(has('fastRosterProjectHtml(st)'),'Fast Roster must show project and stage');
assert(has('fastRosterNeedHtml(st)'),'Fast Roster must show current need');
assert(has('Where are they? What are they doing? What do they need?'),'Fast Roster purpose must remain explicit');
assert(!/function attendanceRosterPriority\([^]*?if \(hasPass\)/.test(html),'Project Bank must not regress stable pass ordering');
assert(has('installOverscrollGuard()'),'Project Bank must preserve Samsung overscroll protection');
assert(has('function boothBadgeHtml'),'Project Bank must preserve Booth Manager');
assert(has('FICTIONAL STUDENT DATA ONLY'),'privacy warning must remain');
console.log('PASS Project Bank host integration contracts');
