const fs=require('fs'),assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const count=(html.match(/function\s+renderModal\s*\(/g)||[]).length;
assert.equal(count,1,'index.html must contain exactly one authoritative renderModal definition');
const active=html.slice(html.indexOf('function renderModal()'),html.indexOf('function compCard'));
assert(active.includes('if (tab === "projects")'),'authoritative renderer must retain Projects tab');
assert(active.includes('showProjectAssigner()'),'Projects tab must retain assignment workflow');
assert(active.includes('renderProjectCheckpointCards(s)'),'Projects tab must render checkpoint cards through the host adapter');
assert(html.includes('projectRow(student.projects[i], i)'),'Projects tab must retain existing rubric/project grading rows');
assert(html.includes('ArcProjectCheckpointHostBridge.execute'),'checkpoint actions must use the transactional host bridge');
assert(html.indexOf('replaceStudent: replaceCheckpointStudent')<html.indexOf('save: save'),'host must replace student state before autosave');
console.log('PASS single authoritative renderModal');
console.log('PASS Projects checkpoint and grading workflows retained');
console.log('\n2/2 Render Modal Authority tests passed.');
