const assert=require('assert'),fs=require('fs'),cp=require('child_process');
const doc=fs.readFileSync('docs/ARC_REPOSITORY_CONTINUITY_SOURCE_AUTHORITY_INVENTORY.md','utf8');
let pass=0,total=0;function test(name,fn){total++;try{fn();pass++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1}}
test('inventory records the exact accepted starting authority and bounded status',()=>{for(const text of ['fee5f0d5a0461e32fb2e613b1bc40a88b60bbb6e','0f305308a560e64c026e530f9138205ab431d2ea','rollback/pre-stage-14-continuity-source-inventory','V7_ONLY','P10D-R1B has not begun'])assert(doc.includes(text),text);});
test('priority continuity sources and authority classes are present',()=>{for(const text of ['ARC_MASTER_PLAN.md','ARC_CONTINUITY_LOG.md','ARC_CONTINUATION_HANDOFF.md','ARC_CAPABILITY_REGISTRY.md','controlling source evidence','governing accepted design','accepted implementation evidence','continuity / roadmap','engineering history'])assert(doc.includes(text),text);});
test('standards source conclusion preserves the external evidence gate',()=>{for(const text of ['course `13207`','course `13208`','adopted May 2022','do **not** exist','Orange-highlight meaning remains','SV-WT-STANDARDS-SOURCE','SV-AWT-STANDARDS-SOURCE'])assert(doc.includes(text),text);});
test('SLO findings distinguish architecture from absent source packet',()=>{for(const text of ['No SLO specification','must not create parallel evidence','missing authoritative packet'])assert(doc.includes(text),text);});
test('roadmap inventory preserves deliberately deferred ecosystem',()=>{for(const text of ['ARC Student','Advanced Welding Competition','Community Project Bank','AI Weld Coach','OneDrive/cloud sync','Administrator documentation/reporting','Growth Milestones'])assert(doc.includes(text),text);});
test('parity audit preserves exact inventory and flags superseded proficiency statement',()=>{for(const text of ['exactly 47 rows','40 `service-ready`','four `not-started`','three `accepted`','Level 3 Proficient 90%','Level 4 Advanced 100%','Teaching Tips'])assert(doc.includes(text),text);});
test('runtime remains V7_ONLY and historical reconciliation authorities remain byte identical to R1A',()=>{for(const file of ['reconciliation/p10d/instructional-content-manifest.json','reconciliation/p10d/human-review-queue.json','reconciliation/p10d/consolidated-review-queue.json','reconciliation/p10d/original-item-resolution-map.json','parity/stage14_v7_v8_parity_contract.js']){let current=fs.readFileSync(file,'utf8').replace(/\r\n/g,'\n'),accepted=cp.execFileSync('git',['show','fee5f0d5a0461e32fb2e613b1bc40a88b60bbb6e:'+file],{encoding:'utf8',maxBuffer:8*1024*1024}).replace(/\r\n/g,'\n');assert.equal(current,accepted,file);}const index=fs.readFileSync('index.html','utf8'),sw=fs.readFileSync('sw.js','utf8'),C=require('../parity/stage14_v7_v8_parity_contract');assert(index.includes('const CURRENT_SCHEMA_VERSION = 7;'));assert.equal(C.authorityState,'V7_ONLY');for(const token of ['instructional-content-manifest.json','human-review-queue.json','consolidated-review-queue.json','original-item-resolution-map.json','stage14_v7_v8_parity_contract.js']){assert(!index.includes(token),`index.html ${token}`);assert(!sw.includes(token),`sw.js ${token}`);}});
if(!process.exitCode)console.log(`\n${pass}/${total} repository continuity/source inventory tests passed.`);
