const assert=require('assert');
const Simulation=require('../src/simulation_foundation');
const Deployment=require('../src/deployment_readiness');
function storage(failKey){const data={};return {data,getItem:key=>Object.prototype.hasOwnProperty.call(data,key)?data[key]:null,setItem:(key,value)=>{if(key===failKey)return false;data[key]=String(value);return true;},removeItem:key=>{delete data[key];return true;}};}
function state(label){return {schemaVersion:7,classes:{wt:[{id:'s1',name:label,projects:[]}],awt:[]},sections:[],academicYear:'2026-27',semester:'Semester 1',projectBank:[]};}
function manager(store,clock){return Simulation.create({storage:store,integrity:Deployment.stateIntegrity,verifyIntegrity:Deployment.verifyStateIntegrity,validateState:x=>assert.equal(x.schemaVersion,7),canonicalState:id=>state('canonical-'+id),now:()=>clock.value});}
let pass=0,total=0;function test(name,fn){total++;try{fn();pass++;console.log('PASS',name);}catch(e){console.error('FAIL',name,e);process.exitCode=1;}}
test('entry requires verified live safety snapshot and isolates state',()=>{let store=storage(),clock={value:'2026-09-19T10:00:00Z'},m=manager(store,clock),live=state('live'),r=m.enter('presentation',live,{view:'roster'});assert.equal(r.snapshot.integrity.value,Deployment.stateIntegrity(live).value);r.state.classes.wt[0].name='changed';m.saveActive(r.state);assert.equal(live.classes.wt[0].name,'live');assert.equal(JSON.parse(store.data.weld_v013||'null'),null);});
test('failed safety snapshot leaves no active simulation',()=>{let store=storage(Simulation.create({storage:storage(),integrity:Deployment.stateIntegrity,verifyIntegrity:Deployment.verifyStateIntegrity,canonicalState:()=>state('x')}).keys.snapshots),clock={value:'2026-09-19T10:01:00Z'},m=manager(store,clock);assert.throws(()=>m.enter('test-1',state('live'),{}),/rejected/);assert.equal(m.active(),null);});
test('leave persists simulation and restores exact live state and navigation',()=>{let store=storage(),clock={value:'2026-09-19T10:02:00Z'},m=manager(store,clock),live=state('live'),r=m.enter('test-1',live,{view:'booths',sectionId:'sec6'});r.state.classes.wt[0].name='persisted';let left=m.leave(r.state);assert.deepEqual(left.state,live);assert.equal(left.navigation.view,'booths');assert.equal(m.active(),null);assert.equal(m.loadScenario('test-1').classes.wt[0].name,'persisted');});
test('restart resumes active simulation',()=>{let store=storage(),clock={value:'2026-09-19T10:03:00Z'},m=manager(store,clock),r=m.enter('test-2',state('live'),{});r.state.classes.wt[0].name='resume-me';m.saveActive(r.state);let resumed=manager(store,clock).resume();assert.equal(resumed.definition.id,'test-2');assert.equal(resumed.state.classes.wt[0].name,'resume-me');});
test('scenario saves are mutually isolated',()=>{let store=storage(),clock={value:'2026-09-19T10:04:00Z'},m=manager(store,clock),r=m.enter('test-1',state('live'),{});r.state.classes.wt[0].name='one';m.leave(r.state);clock.value='2026-09-19T10:05:00Z';r=m.enter('test-2',state('live-two'),{});r.state.classes.wt[0].name='two';m.leave(r.state);assert.equal(m.loadScenario('test-1').classes.wt[0].name,'one');assert.equal(m.loadScenario('test-2').classes.wt[0].name,'two');});
test('reset changes only active simulation and preserves live snapshots',()=>{let store=storage(),clock={value:'2026-09-19T10:06:00Z'},m=manager(store,clock),r=m.enter('test-3',state('live'),{}),snapshotCount=m.snapshots().length;r.state.classes.wt[0].name='dirty';m.saveActive(r.state);let reset=m.reset();assert.equal(reset.state.classes.wt[0].name,'canonical-test-3');assert.equal(m.snapshots().length,snapshotCount);assert.equal(m.active().scenarioId,'test-3');});
test('safety snapshots retain latest five',()=>{let store=storage(),clock={value:''},m=manager(store,clock);for(let i=0;i<7;i++){clock.value='2026-09-19T10:0'+i+':00Z';let r=m.enter('test-4',state('live-'+i),{});m.leave(r.state);}assert.equal(m.snapshots().length,5);assert.equal(m.snapshots()[0].state.classes.wt[0].name,'live-6');});
if(!process.exitCode)console.log('\n'+pass+'/'+total+' Simulation Foundation tests passed.');
