const assert=require('assert'),fs=require('fs'),crypto=require('crypto'),C=require('../parity/stage14_v7_v8_parity_contract');
const required=['academic-year-semester','grading-periods','sections','schedule-setup','school-calendar','bell-schedules','planning-period','section-period-placement','semester-transition','student-records','student-directory-search','roster-management','student-movement','dashboard-class-context','fast-roster','attendance','passes','attendance-pass-history','curriculum-standards','lesson-plans','pacing','class-forecast','notifications','project-library','project-assignment','project-checkpoints','project-rubric','competency-catalog','competency-assessment','reassessment','technical-assessments','open-shop','workplace','safety','behavior-incidents','gradebook','manual-posting','photo-capture','student-work-library','student-history','booth-manager','general-inventory','material-inventory','backup-restore','app-update-pwa','navigation-shell','simulation-isolation'];
let pass=0,total=0;async function test(name,fn){total++;try{await fn();pass++;console.log('PASS',name)}catch(e){console.error('FAIL',name,e);process.exitCode=1}}
(async()=>{
await test('contract is exact P1 V7_ONLY authority with mutation and dual write prohibited',()=>{assert.equal(C.contractId,'arc-stage14-v7-v8-no-regression-parity-p1');assert.equal(C.authorityState,'V7_ONLY');assert.equal(C.productionMutationAuthorized,false);assert.equal(C.dualWriteAllowed,false);assert.equal(C.realStudentDataAuthorized,false);assert(C.acceptedApplicationIsProduct);assert.equal(C.governingCommit,'991cbdb6ad1b13f897ce08cc96f88e9d725bfb43');assert.equal(C.governingTree,'99c95af65fe3c8d37136dd3b5be378ac4e758bac');});
await test('registry contains every frozen production-critical audit capability exactly once',()=>{assert.deepEqual(C.rows.map(x=>x.id),required);assert.equal(new Set(C.rows.map(x=>x.id)).size,C.rows.length);assert(C.rows.every(x=>x.productionCritical));});
await test('every row records the full deterministic no-regression contract',()=>{for(const r of C.rows){for(const k of ['id','domain','capability','status','allowedIntentionalDifferences','historyAndCorrection','recoveryExpectation','samsungPhysicalRequirement'])assert.notEqual(r[k],undefined,r.id+' '+k);for(const k of ['source','entryPoint','instructorAction','observableResult','persistentState'])assert(r.v7[k],r.id+' v7.'+k);assert(Array.isArray(r.v7.anchors)&&r.v7.anchors.length,r.id);assert(Array.isArray(r.v7.crossViewConsumers)&&r.v7.crossViewConsumers.length,r.id);assert(r.v8.requiredAuthority&&r.v8.requiredProjectionOrAdapter,r.id);assert.equal(r.retirement.status,'retained',r.id);assert(r.evidence&&Array.isArray(r.evidence.automated)&&Array.isArray(r.evidence.samsung)&&Array.isArray(r.evidence.acceptance),r.id);}});
await test('all lifecycle states and only forward deterministic transitions are frozen',()=>{assert.deepEqual(C.states,['not-started','service-ready','ui-connected','behaviorally-verified','samsung-verified','accepted','retired-by-instructor']);for(const r of C.rows)assert(C.states.includes(r.status),r.id);for(const [from,to] of Object.entries(C.transitions)){assert(C.states.includes(from));for(const next of to)assert(C.states.indexOf(next)>C.states.indexOf(from)||next==='retired-by-instructor',from+' '+next);}});
await test('service existence cannot mark a row accepted and retirement requires instructor authority',()=>{for(const r of C.rows){if(r.status==='accepted'){assert(r.evidence.automated.length,r.id);assert(r.evidence.samsung.length,r.id);assert(r.evidence.acceptance.length,r.id);}if(r.status==='retired-by-instructor'){assert.equal(r.retirement.status,'retired-by-instructor');assert(r.retirement.approvedBy&&r.retirement.approvedAt&&r.retirement.reason);}}assert(C.rows.some(r=>r.status==='service-ready'));assert(C.rows.some(r=>r.status==='not-started'));});
await test('every cited source and anchor exists in the accepted repository',()=>{for(const r of C.rows){assert(fs.existsSync(r.v7.source),r.id+' '+r.v7.source);let source=fs.readFileSync(r.v7.source,'utf8');for(const anchor of r.v7.anchors)assert(source.includes(anchor),r.id+' missing anchor '+anchor);}});
await test('normal ARC remains schema 7 and does not load the P1 registry as runtime code',()=>{let index=fs.readFileSync('index.html','utf8'),sw=fs.readFileSync('sw.js','utf8');assert(index.includes('const CURRENT_SCHEMA_VERSION = 7;'));assert(!index.includes('stage14_v7_v8_parity_contract'));assert(!sw.includes('stage14_v7_v8_parity_contract'));});
await test('P3 records bounded adapter evidence without claiming authoritative UI or Samsung acceptance',()=>{for(const id of ['academic-year-semester','grading-periods','schedule-setup','school-calendar','bell-schedules','planning-period','section-period-placement','semester-transition']){let r=C.rows.find(x=>x.id===id);assert.equal(r.status,'service-ready',id);assert(r.evidence.automated.includes('arc_v8_academic_administration.test.js'),id);assert(r.evidence.automated.includes('arc_schedule_authority_adapter.test.js'),id);assert.equal(r.evidence.samsung.length,0,id);}assert(!C.rows.some(x=>x.status==='ui-connected'));assert.equal(C.authorityState,'V7_ONLY');});
await test('contract is deeply frozen and matches the accepted canonical fingerprint',()=>{assert(Object.isFrozen(C)&&Object.isFrozen(C.rows)&&C.rows.every(Object.isFrozen));let canonical=JSON.stringify(C);assert.equal(crypto.createHash('sha256').update(canonical).digest('hex'),'8e2d77aab9313150d01b41e2566b45fcd2658592b56ff756653946489a9e59cf');assert.throws(()=>{C.rows.push({});},TypeError);});
if(!process.exitCode)console.log(`\n${pass}/${total} Stage 14 P1 parity-contract tests passed.`);
})();
