const fs=require('fs');
const assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('src/arc_visual_foundation.css','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const build=fs.readFileSync('app-build.js','utf8');
const shell=fs.readFileSync('src/arc_titanium_shell.js','utf8');

assert(html.includes('src/arc_titanium_shell.js'));
assert(html.includes('id="arcSidebar"'));
assert(html.includes('id="arcPrimaryNavigation"'));
assert(html.includes('id="arcSidebarToggle"'));
assert(html.includes('Advanced Welding Classroom'));
assert(html.includes('Advanced Readiness Classroom'));
assert(html.includes('More Than Welding. A Brighter Future.'));
assert(html.includes('Skills Today.<br>Stronger Tomorrow.'));
assert(html.includes('function initializeArcShell()'));
assert(html.includes('function renderActiveCurriculum()'));
assert(html.includes('function runArcNavigation(action)'));
assert(html.includes('updateArcActiveRoute()'));
assert(html.includes('function handleArcPopState()'));
assert(html.includes("pushArcTransientHistory(\"student\")"));
assert(html.includes("pushArcTransientHistory('navigation')"));
assert(html.includes('window.addEventListener("popstate", handleArcPopState)'));
assert(html.includes('onclick="navBack()"'));
assert(html.includes('onclick="toggleClassMenu(event)"'));
assert(html.includes('onclick="showQuickAdd()"'));
assert(html.includes('onclick="leaveSimulation()"'));
assert(shell.includes("Today's Focus"));
assert(shell.includes("id:'today-focus'")&&shell.includes('future:true'));
assert(!html.includes('Presentation Mode'));

assert(css.includes('.arc-sidebar{position:fixed'));
assert(css.includes('.arc-titanium-shell.arc-sidebar-collapsed'));
assert(css.includes('@media (max-width:900px)'));
assert(css.includes('@media (max-width:620px)'));
assert(css.includes('env(safe-area-inset-top)'));
assert(css.includes('.arc-titanium-shell .modal{left:var(--arc-sidebar-width);z-index:120}'));
assert(css.includes('.arc-sidebar{')&&css.includes('z-index:180'));
assert(sw.includes("'./src/arc_titanium_shell.js'"));
assert(build.includes("build:'titanium-foundation-repair-1'"));
assert(html.includes('const CURRENT_SCHEMA_VERSION = 7;'));
console.log('Titanium Foundation integration tests passed.');
