/* P10D-R1A deterministic consolidation. Does not alter the P10D manifest or source queue. */
'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=path.resolve(__dirname,'..'),DIR=path.join(ROOT,'reconciliation','p10d');
const manifest=JSON.parse(fs.readFileSync(path.join(DIR,'instructional-content-manifest.json'),'utf8'));
const original=JSON.parse(fs.readFileSync(path.join(DIR,'human-review-queue.json'),'utf8'));
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])]));return v;}
function hash(v){return crypto.createHash('sha256').update(JSON.stringify(stable(v))).digest('hex');}
if(original.manifestHash!==manifest.manifestHash)throw Error('Queue and manifest authority differ.');
const decisions=[
  {decisionId:'SV-WT-STANDARDS-SOURCE',category:'external authoritative-source verification',decisionClass:'source-verification decision',course:'wt',blocks:['authoritative WT Standard catalog/version import','WT Essential designation import','normalized WT Standard links'],doesNotBlock:['exact WT Curriculum raw content','exact WT Lesson raw content','P7 Competency preservation'],explanation:'Repository wording cannot be preferred over an unavailable authoritative WT source document.',choices:[{id:'SUPPLY_SOURCE',label:'Supply authoritative WT source',effect:'Compare exact codes, wording, ordering and essential designations.'},{id:'CONFIRM_REPOSITORY_COPY',label:'Confirm repository copy as authority',effect:'A separate disposition-freeze stage may approve the repository catalog.'},{id:'DEFER',label:'Defer verification',effect:'Keep WT Standards and dependent normalized links blocked; preserve independent raw content only.'}],originalItems:[]},
  {decisionId:'SV-AWT-STANDARDS-SOURCE',category:'external authoritative-source verification',decisionClass:'source-verification decision',course:'awt',blocks:['authoritative AWT Standard catalog/version import','AWT Essential designation import','normalized AWT Standard links'],doesNotBlock:['exact AWT Curriculum raw content','exact AWT Lesson raw content','P7 Competency preservation'],explanation:'Repository wording cannot be preferred over an unavailable authoritative AWT source document.',choices:[{id:'SUPPLY_SOURCE',label:'Supply authoritative AWT source',effect:'Compare exact codes, wording, ordering and essential designations.'},{id:'CONFIRM_REPOSITORY_COPY',label:'Confirm repository copy as authority',effect:'A separate disposition-freeze stage may approve the repository catalog.'},{id:'DEFER',label:'Defer verification',effect:'Keep AWT Standards and dependent normalized links blocked; preserve independent raw content only.'}],originalItems:[]},
  {decisionId:'MF-CURRICULUM-CONTENT-SEPARATION',category:'Standard-reference interpretation / Curriculum → Standard relationship',decisionClass:'mechanical follow-on mapping',course:'both',blocks:[],doesNotBlock:['Curriculum item preservation/import'],explanation:'A Curriculum item can preserve exact rawStandardsText while only exact unambiguous Standard codes become links. Ranges, course-wide references and contextual prose remain source text, not mandatory normalized links.',choices:[],originalItems:[]},
  {decisionId:'MF-LESSON-CONTENT-SEPARATION',category:'Standard-reference interpretation / Lesson → Standard relationship',decisionClass:'mechanical follow-on mapping',course:'both',blocks:[],doesNotBlock:['Lesson definition/version preservation/import'],explanation:'A Lesson can preserve exact sourceStandardsText while only exact unambiguous Standard codes become links. Contextual instructor-selection language remains source text.',choices:[],originalItems:[]},
  {decisionId:'SU-CURRICULUM-COMPETENCY-CANDIDATES',category:'Curriculum → Competency relationship',decisionClass:'safe unresolved relationship',course:'both',blocks:[],doesNotBlock:['Curriculum preservation/import','Competency preservation/import'],explanation:'Shared Standard codes do not assert Curriculum-to-Competency relationships. Candidate links remain absent unless later accepted authority explicitly selects them.',choices:[],originalItems:[]},
  {decisionId:'SU-LESSON-COMPETENCY-CANDIDATES',category:'Lesson → Competency relationship',decisionClass:'safe unresolved relationship',course:'both',blocks:[],doesNotBlock:['Lesson preservation/import','Competency preservation/import'],explanation:'Shared Standard codes do not assert Lesson-to-Competency relationships. Exact WT competency-code links already approved by P10D are unaffected; no AWT mapping is invented.',choices:[],originalItems:[]},
  {decisionId:'SU-LESSON-CURRICULUM-CANDIDATES',category:'Lesson → Curriculum relationship',decisionClass:'safe unresolved relationship',course:'both',blocks:[],doesNotBlock:['Lesson preservation/import','Curriculum preservation/import'],explanation:'Shared Standard codes do not identify one authoritative Curriculum item. Optional candidate links remain absent.',choices:[],originalItems:[]},
  {decisionId:'SU-ACTIVITY-EVIDENCE-IDENTITIES',category:'Activity/Evidence relationship',decisionClass:'safe unresolved relationship',course:'awt',blocks:[],doesNotBlock:['Lesson preservation/import'],explanation:'Two Lessons imply assessment activity, but no exact P6 Activity Version or Evidence Declaration identity exists. The links remain absent without fabricating identity.',choices:[],originalItems:[]}
];
const byId=new Map(decisions.map(x=>[x.decisionId,x]));
function route(item){
  if(item.family==='curriculumMapItems')return'MF-CURRICULUM-CONTENT-SEPARATION';
  if(item.family==='lessonDefinitions'||item.family==='lessonVersions')return'MF-LESSON-CONTENT-SEPARATION';
  if(item.family==='curriculumItemCompetencyLinks')return'SU-CURRICULUM-COMPETENCY-CANDIDATES';
  if(item.family==='lessonVersionCompetencyLinks')return'SU-LESSON-COMPETENCY-CANDIDATES';
  if(item.family==='lessonVersionCurriculumLinks')return'SU-LESSON-CURRICULUM-CANDIDATES';
  if(item.family==='lessonVersionActivityLinks')return'SU-ACTIVITY-EVIDENCE-IDENTITIES';
  throw Error(`Unclassified original item: ${item.family}`);
}
const mappings=original.items.map((item,index)=>{let decisionId=route(item),decision=byId.get(decisionId),fingerprint=hash(item),classification=decision.decisionClass,status=classification==='mechanical follow-on mapping'?'MECHANICAL_AFTER_CONTENT_RELATIONSHIP_SPLIT':'SAFE_TO_REMAIN_ABSENT';let ref={originalQueueIndex:index,originalItemFingerprint:fingerprint,course:item.course,family:item.family,manifestRecordId:item.id,originalDisposition:item.disposition,originalReasons:item.reasons,decisionId,classification,status,blocksImport:false};decision.originalItems.push({originalQueueIndex:index,originalItemFingerprint:fingerprint,course:item.course,family:item.family,manifestRecordId:item.id});return ref;});
for(const d of decisions){d.affectedOriginalItemCount=d.originalItems.length;d.backReferences={artifact:'original-item-resolution-map.json',matchField:'decisionId',matchValue:d.decisionId};delete d.originalItems;}
const counts={consolidatedEntries:decisions.length,trueInstructorDecisions:decisions.filter(x=>x.decisionClass==='true instructor decision').length,sourceVerificationDecisions:decisions.filter(x=>x.decisionClass==='source-verification decision').length,mechanicalFollowOnGroups:decisions.filter(x=>x.decisionClass==='mechanical follow-on mapping').length,safeUnresolvedGroups:decisions.filter(x=>x.decisionClass==='safe unresolved relationship').length,originalItems:original.count,originalItemsMapped:mappings.length,originalItemsMechanical:mappings.filter(x=>x.classification==='mechanical follow-on mapping').length,originalItemsSafeUnresolved:mappings.filter(x=>x.classification==='safe unresolved relationship').length,originalItemsBlockingImport:mappings.filter(x=>x.blocksImport).length};
const queue={artifactId:'arc-p10d-r1a-consolidated-review-queue-v1',sourceManifestHash:manifest.manifestHash,sourceQueueCount:original.count,principle:'Preserve exact source content independently from optional normalized relationships.',counts,importBlockers:[{decisionId:'SV-WT-STANDARDS-SOURCE',scope:'WT Standards, Essential designations and dependent normalized Standard links only'},{decisionId:'SV-AWT-STANDARDS-SOURCE',scope:'AWT Standards, Essential designations and dependent normalized Standard links only'}],trueInstructorDecisionPresentation:[],recommendedReviewOrder:['Obtain or explicitly identify the authoritative WT and AWT Standards source documents.','Resolve the two source-verification entries.','In a later disposition-freeze stage, mechanically separate exact Curriculum/Lesson content approval from optional relationship approval.','Preserve candidate-only Curriculum/Competency, Lesson/Competency, Lesson/Curriculum and Activity/Evidence links as absent.','Only open new pedagogical mapping decisions when explicit accepted authority is supplied.'],decisions};
queue.artifactHash=hash({...queue,artifactHash:undefined});
const mapArtifact={artifactId:'arc-p10d-r1a-original-item-map-v1',sourceManifestHash:manifest.manifestHash,sourceQueueCount:original.count,consolidatedQueueHash:queue.artifactHash,mappings};mapArtifact.artifactHash=hash({...mapArtifact,artifactHash:undefined});
fs.writeFileSync(path.join(DIR,'consolidated-review-queue.json'),JSON.stringify(queue,null,2)+'\n');
fs.writeFileSync(path.join(DIR,'original-item-resolution-map.json'),JSON.stringify(mapArtifact,null,2)+'\n');
console.log(JSON.stringify({counts,consolidatedQueueHash:queue.artifactHash,resolutionMapHash:mapArtifact.artifactHash},null,2));
