/* Deterministic source-authority preservation manifest. No runtime/database access. */
'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=path.resolve(__dirname,'..'),BASE=path.join(ROOT,'source_authority','recovered_2026-09-29'),SRC=path.join(BASE,'source_material');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const meta={
'1000012641.jpg':['AWT official standards photograph, page 1','external/institutional authority + historical/reference evidence','South Dakota DOE printed standards; instructor-supplied photograph','May 2022','AWT course metadata and prerequisite','visual source preserved; PDF is exact-text authority','source verified; no disposition freeze'],
'1000012642.jpg':['AWT official standards highlighted photograph, page 2','external/institutional authority + instructor design/selection authority','South Dakota DOE printed standards; instructor orange highlighting','May 2022','AWT Standards, Webb levels, Essential selections','visually reviewed; exact text transcribed from PDF','source verified; Essential provenance frozen'],
'1000012643.jpg':['AWT official standards highlighted photograph, page 3','external/institutional authority + instructor design/selection authority','South Dakota DOE printed standards; instructor orange highlighting','May 2022','AWT Standards, Webb levels, Essential selections','visually reviewed; exact text transcribed from PDF','source verified; Essential provenance frozen'],
'1000012647.jpg':['WT official standards photograph, page 1','external/institutional authority + historical/reference evidence','South Dakota DOE printed standards; instructor-supplied photograph','May 2022','WT course metadata','visual source preserved; PDF is exact-text authority','source verified; no disposition freeze'],
'1000012648.jpg':['WT official standards highlighted photograph, page 2','external/institutional authority + instructor design/selection authority','South Dakota DOE printed standards; instructor orange highlighting','May 2022','WT Standards, Webb levels, Essential selections','visually reviewed; exact text transcribed from PDF','source verified; Essential provenance frozen'],
'13207-WeldingTech.pdf':['Official Welding Technology standards, 2 pages','external/institutional authority','South Dakota Department of Education','Adopted May 2022','WT course 13207 metadata, wording, Webb levels','faithfully transcribed and visually checked','source verified; P10D dispositions unchanged'],
'13208-Adv-Welding.pdf':['Official Advanced Welding Technology standards, 3 pages','external/institutional authority','South Dakota Department of Education','Adopted May 2022','AWT course 13208 metadata, prerequisite, wording, Webb levels','faithfully transcribed and visually checked','source verified; P10D dispositions unchanged'],
'1505.jpg':['WT curriculum-map Essential Standards photograph','instructor design/selection authority + historical/reference evidence','Instructor-authored curriculum map printout','recovered 2026-09-29','WT Essential selections and competency scale','visually reviewed; DOCX is full content authority','corroborated; no content import'],
'1506.jpg':['AWT curriculum-map Essential Standards photograph','instructor design/selection authority + historical/reference evidence','Instructor-authored curriculum map printout','recovered 2026-09-29','AWT Essential selections and competency scale','visually reviewed; DOCX is full content authority','corroborated; no content import'],
'450.jpg':['Lesson Plan Review Rubric photograph, page 1 of 2','external/institutional authority','Oelrichs School administrative rubric','recovered 2026-09-29','Lesson planning: Essential Standards, targets, success criteria','faithfully transcribed','source preserved; future generator constraint'],
'451.jpg':['Lesson Plan Review Rubric photograph, page 2 of 2','external/institutional authority','Oelrichs School administrative rubric','recovered 2026-09-29','Lesson planning: engagement, assessment, submission','faithfully transcribed','source preserved; future generator constraint'],
'452.jpg':['Instructional Walk-through Rubric photograph, page 1 of 4','external/institutional authority','Oelrichs School administrative rubric','recovered 2026-09-29','Learning targets and success criteria','faithfully transcribed','source preserved; design-validation input'],
'453.jpg':['Instructional Walk-through Rubric photograph, page 2 of 4','external/institutional authority','Oelrichs School administrative rubric','recovered 2026-09-29','Teacher practices and student engagement/ownership','faithfully transcribed','source preserved; design-validation input'],
'454.jpg':['Instructional Walk-through Rubric photograph, page 3 of 4','external/institutional authority','Oelrichs School administrative rubric','recovered 2026-09-29','Assessment, culture, management','faithfully transcribed','source preserved; design-validation input'],
'455.jpg':['Instructional Walk-through Rubric photograph, page 4 of 4','external/institutional authority','Oelrichs School administrative rubric','recovered 2026-09-29','Evidence Observed checklist','faithfully transcribed','source preserved; design-validation input'],
'AWT Weekly Lesson Plan Sep28-Oct2 2026.docx':['AWT weekly-plan example; 18 paragraphs, 3 tables, 11 table rows','administration-accepted output example','Instructor-produced plan accepted for administration use','Week of 2026-09-28','Future Administrative Weekly Lesson Plan output structure','structurally extracted/reviewed; not transcribed as policy','preserve as template example; not institutional policy'],
'Advanced Welding Technology Competencies Printable.docx':['AWT competency guide; 34 competencies plus header row','instructor design/selection authority','Instructor-approved AWT competency guide','recovered 2026-09-29','AWT competency identity, descriptions, Standards, 0-4 scale','structurally extracted/reviewed','source authority preserved; no import'],
'Advanced Welding Technology Curriculum Map.docx':['AWT curriculum map; 60 paragraphs, 9 tables, 57 table rows','instructor design/selection authority','Instructor-authored AWT curriculum map','recovered 2026-09-29','AWT sequencing, Essential/Supporting Standards, differentiation and pacing','structurally extracted/reviewed','source authority preserved; no import'],
'FERPA Statement Updated 2024.pdf':['Oelrichs School District FERPA notice, 2 pages','external/institutional authority','Oelrichs School District','Updated 2024','Privacy for all student education records and disclosures','text extracted and visually checked; no legal reinterpretation','source authority preserved; later privacy review required'],
'WT Weekly Lesson Plan Sep28-Oct2 2026.docx':['WT weekly-plan example; 18 paragraphs, 3 tables, 11 table rows','administration-accepted output example','Instructor-produced plan accepted for administration use','Week of 2026-09-28','Future Administrative Weekly Lesson Plan output structure','structurally extracted/reviewed; not transcribed as policy','preserve as template example; not institutional policy'],
'Welding Technology Competencies Printable.docx':['WT competency guide; 26 competencies plus header row','instructor design/selection authority','Instructor-approved WT competency guide','recovered 2026-09-29','WT competency identity, descriptions, Standards, 0-4 scale','structurally extracted/reviewed','source authority preserved; no import'],
'Welding Technology Curriculum Map Revised.docx':['WT curriculum map; 30 paragraphs, 9 tables, 52 table rows','instructor design/selection authority','Instructor-authored revised WT curriculum map','recovered 2026-09-29','WT sequencing, Essential/Supporting Standards, differentiation and pacing','structurally extracted/reviewed','source authority preserved; no import'],
'd3d5c621-d41f-4dd5-a44c-03479810b3c7-1_all_15092.jpg':['Oelrichs Data Cycles / SLO photograph, page 3 of 3','external/institutional authority','Oelrichs School data-cycle form','recovered 2026-09-29','SLO reflection and final principal approval','faithfully transcribed','source preserved; future Administrative generator constraint'],
'd3d5c621-d41f-4dd5-a44c-03479810b3c7-1_all_15093.jpg':['Oelrichs Data Cycles / SLO photograph, page 2 of 3','external/institutional authority','Oelrichs School data-cycle form','recovered 2026-09-29','SLO strategies, initial approval, post assessment, next steps','faithfully transcribed','source preserved; future Administrative generator constraint'],
'd3d5c621-d41f-4dd5-a44c-03479810b3c7-1_all_15094.jpg':['Oelrichs Data Cycles / SLO photograph, page 1 of 3','external/institutional authority','Oelrichs School data-cycle form','recovered 2026-09-29','SLO baseline, target, population, timeframe and growth goal','faithfully transcribed','source preserved; future Administrative generator constraint']};
const names=fs.readdirSync(SRC).sort((a,b)=>a.localeCompare(b,'en'));
if(names.length!==25||names.some(n=>!meta[n])||Object.keys(meta).some(n=>!names.includes(n)))throw Error('Source inventory differs from the exact 25-file handoff.');
const sources=names.map(originalFilename=>{const bytes=fs.readFileSync(path.join(SRC,originalFilename)),hash=sha(bytes),m=meta[originalFilename];return{sourceId:`arc-source-${hash.slice(0,16)}`,originalFilename,repositoryPath:`source_authority/recovered_2026-09-29/source_material/${originalFilename}`,sha256:hash,byteLength:bytes.length,sourceInventory:m[0],authorityClassification:m[1],provenance:m[2],dateOrVersion:m[3],arcCapabilitiesConstrained:m[4],transcriptionStatus:m[5],reconciliationStatus:m[6],supersessionStatus:'active source evidence; does not silently supersede accepted runtime or P10D dispositions'};});
const manifest={manifestId:'arc-source-authority-recovered-2026-09-29',generatedBy:'scripts/generate_source_authority_manifest.js',sourceCount:sources.length,preservationRule:'Original files are immutable byte-preserved evidence. Derived transcriptions and comparisons never replace originals.',sources};
manifest.manifestSha256=sha(Buffer.from(JSON.stringify(manifest)));
fs.writeFileSync(path.join(BASE,'source-manifest.json'),JSON.stringify(manifest,null,2)+'\n');
console.log(JSON.stringify({sourceCount:sources.length,manifestSha256:manifest.manifestSha256},null,2));
