/* ARC P10D-PA1 protected production instructional-package availability bridge.
   Engineering-only and explicit: loading this module never opens IndexedDB. */
(function(root,factory){
  var api=factory(
    root.ArcV8Storage||(typeof require==='function'?require('./arc_v8_storage'):null),
    root.ArcV8BackupRecovery||(typeof require==='function'?require('./arc_v8_backup_recovery'):null),
    root.ArcV8InstructionalContentPackages||(typeof require==='function'?require('./arc_v8_instructional_content_packages'):null),
    root.ArcV8CurriculumPacing||(typeof require==='function'?require('./arc_v8_curriculum_pacing'):null),
    root.ArcV8Evidence||(typeof require==='function'?require('./arc_v8_evidence'):null),
    root.ArcV8LessonPlans||(typeof require==='function'?require('./arc_v8_lesson_plans'):null)
  );
  if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcV8InstructionalPackageAvailabilityPhysical=api;
}(this,function(Storage,BackupRecovery,Packages,Curriculum,Evidence,Lessons){
  'use strict';
  var DB='arc_classroom_v8',RUNTIME='p10d-pa1-production-instructional-package-availability-bridge-1',AUTHORITY='V7_ONLY';
  var CONFIRMATION='MAKE VERIFIED INSTRUCTIONAL PACKAGE AVAILABLE UNDER V7_ONLY';
  var PACKAGE_ID='ae06a3f8-cd1b-4a2a-943f-2f3d4e1f3f3b',ATTEMPT_ID='f13897b2-e4a3-4f76-9826-9a6b17282285';
  var BASELINE_FILE_SHA256='db34dd5f0285d4dc1622765d94c30579cce74c916936e7234ffbd07dbefebbfc',BASELINE_PACKAGE_SHA256='51c1270cbe3b5f06d0ba26c81aef151ff80ca4cbd59cee4feba06ca428e756f7';
  var PAYLOAD_SHA256='f1f7756242c1ef685ef4ce061507d03b8fc6834e0e448cde7510fc8e2ade79b1',IDENTITY_SHA256='7ba2956022875c03cc1bea1ee9ffa205fa78c204bfdc967c06c66fc5b1c3b750',EVIDENCE_SHA256='81d23b6fa9ee5daefd41a99ee5e3e49de67c1c948598659fad5d224efd45448a';
  var PROTECTION='Production/Classroom Protected',INIT='production-v8-initialization-manifest',RECON='production-v8-reconciliation-manifest',PROTECT='database-protection';
  var PACKAGE_STORE=Storage.STORES.instructionalContentPackages,COURSE_STORE=Storage.STORES.courses,CURRENT_STORES=Object.freeze(BackupRecovery.EXPECTED_STORES.slice());
  var ROLE_COUNTS=Object.freeze({standard_catalogs:2,standard_catalog_versions:2,standard_definitions:29,standard_versions:29,essential_standard_designations:10,competency_definitions:60,competency_versions:60,curriculum_maps:2,curriculum_map_versions:2,curriculum_map_items:56,curriculum_item_standard_links:80,lesson_definitions:124,lesson_versions:124,lesson_version_standard_links:228,lesson_version_competency_links:51});
  var ROLE_STORES=Object.freeze(Object.keys(ROLE_COUNTS)),BASE_STORES=Object.freeze(['metadata','migration_log','infrastructure_records']);
  var EMPTY_STORES=Object.freeze(CURRENT_STORES.filter(function(name){return BASE_STORES.indexOf(name)<0&&name!==COURSE_STORE&&name!==PACKAGE_STORE&&ROLE_STORES.indexOf(name)<0;}));
  var PHASES=Object.freeze([
    {sequence:3,phase:'STANDARDS',memberCount:62,checksum:'b46500a170e4f3223fd1107766471f72c1c03e161651b93858dee8f8e6fc79d3'},
    {sequence:4,phase:'COMPETENCIES',memberCount:120,checksum:'0373bba0713fd871e4e8d91f4ee70e989347188a89fdee1cb0463a5bbc01ed82'},
    {sequence:5,phase:'ESSENTIALS',memberCount:10,checksum:'3f05ac1ae0f57be1ec2a26b0d175489f886bf034242d768471b2ff175eb06c98'},
    {sequence:6,phase:'CURRICULUM_CORE',memberCount:60,checksum:'a49d80768229c62713fd470d64ebe568aa5bb76b0f47138a8973fed6361b2e93'},
    {sequence:7,phase:'CURRICULUM_STANDARD_LINKS',memberCount:80,checksum:'a104bed403f6bef74c7bb235bc8e4090c65e821d29af82d4af4740142c598267'},
    {sequence:8,phase:'LESSON_CORE',memberCount:248,checksum:'36a06016ff9048b185b7e9499091a4f01ea812150411cadd8750f69cda87628d'},
    {sequence:9,phase:'LESSON_STANDARD_LINKS',memberCount:228,checksum:'c120f902c1ce96b735f20228017e38320ac0011115d5052c458ad27605e901b3'},
    {sequence:10,phase:'LESSON_COMPETENCY_LINKS',memberCount:51,checksum:'1584621cd0a0381af5f9b91c0198ffa7ccc2db8aaa165aa91bae80af54f7a9d0'}
  ]);
  function fail(code,message,context,cause){throw new Storage.StorageError(code,message,context||{},cause);}
  function copy(value){return value===undefined?undefined:structuredClone(value);}
  function text(value){return String(value==null?'':value).trim();}
  function canonical(value){if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return'['+value.map(canonical).join(',')+']';return'{'+Object.keys(value).sort().filter(function(k){return value[k]!==undefined;}).map(function(k){return JSON.stringify(k)+':'+canonical(value[k]);}).join(',')+'}';}
  function sameList(a,b){return canonical((a||[]).slice().sort())===canonical((b||[]).slice().sort());}
  function one(rows,id){return(rows||[]).find(function(row){return row.id===id;})||null;}
  function total(counts){return Object.keys(counts||{}).reduce(function(n,k){return n+Number(counts[k]||0);},0);}
  function request(req){return new Promise(function(resolve,reject){req.onsuccess=function(){resolve(req.result);};req.onerror=function(){reject(req.error||new Error('IndexedDB request failed.'));};});}
  function done(tx){return new Promise(function(resolve,reject){tx.oncomplete=resolve;tx.onerror=function(){reject(tx.error||new Error('IndexedDB transaction failed.'));};tx.onabort=function(){reject(tx.error||new Error('IndexedDB transaction aborted.'));};});}
  function create(options){
    options=options||{};var databaseName=text(options.databaseName||DB),idb=options.indexedDB||(typeof indexedDB!=='undefined'?indexedDB:null),cryptoApi=options.crypto||(typeof crypto!=='undefined'?crypto:null),build=options.build||{},clock=options.now||function(){return new Date().toISOString();};
    var expectedCommit=text(options.expectedPublicationCommit),expectedTree=text(options.expectedPublicationTree),inspector=options.inspector||null,services=options.services||null,inspection=null,acceptedBaseline=null,verifiedPreBackup=null,lastResult=null;
    if(databaseName!==DB)fail('PRODUCTION_IDENTITY_REQUIRED','Package availability accepts only exact protected production identity.',{actual:databaseName,expected:DB});
    if(!cryptoApi||!cryptoApi.subtle)throw Error('Package availability requires Web Crypto SHA-256.');
    async function sha256(value){var bytes=typeof value==='string'?new TextEncoder().encode(value):value,hash=await cryptoApi.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(hash),function(x){return x.toString(16).padStart(2,'0');}).join('');}
    async function openUnversioned(){if(!idb)fail('INDEXEDDB_UNAVAILABLE','IndexedDB is required.');return new Promise(function(resolve,reject){var req=idb.open(DB),created=false;req.onupgradeneeded=function(){created=true;try{req.transaction.abort();}catch(ignore){}};req.onerror=function(){reject(created?new Storage.StorageError('PRODUCTION_DATABASE_REQUIRED','Protected production database does not exist.'):req.error||new Error('Production inspection failed.'));};req.onsuccess=function(){if(created){req.result.close();reject(new Storage.StorageError('PRODUCTION_DATABASE_REQUIRED','Protected production database does not exist.'));return;}resolve(req.result);};});}
    async function nativeInspect(){var db=await openUnversioned();try{var names=Array.from(db.objectStoreNames),tx=db.transaction(names,'readonly'),finished=done(tx),values=await Promise.all(names.map(function(name){return request(tx.objectStore(name).getAll());})),stores={};await finished;names.forEach(function(name,index){stores[name]=values[index];});return{exists:true,databaseName:DB,indexedDbVersion:db.version,storeNames:names,counts:Object.fromEntries(names.map(function(name){return[name,stores[name].length];})),metadata:(stores.metadata||[]).find(function(x){return x.key==='database';})||null,infrastructure:stores.infrastructure_records||[],stores:stores};}finally{db.close();}}
    async function inspectRaw(){return inspector&&typeof inspector.inspect==='function'?inspector.inspect(DB):nativeInspect();}
    function validateInfrastructure(report){var init=one(report.infrastructure,INIT),recon=one(report.infrastructure,RECON),protect=one(report.infrastructure,PROTECT);if(!init||init.status!=='complete'||init.databaseName!==DB||init.schemaFamily!=='arc-classroom'||Number(init.schemaVersion)!==8||Number(init.indexedDbVersion)!==10||Number(init.expectedStoreCount)!==53||init.authorityState!==AUTHORITY||init.classroomAuthorityTransferred!==false||init.realStudentDataAuthorized!==false||init.contentImported!==false)fail('INITIALIZATION_MANIFEST_MISMATCH','Historical protected production initialization authority differs.');if(!recon||recon.status!=='complete'||Number(recon.importedRecordCount)!==0||Number(recon.excludedIdentityCount)!==0||recon.reusableAuthorityImported!==false||recon.classroomTransactionsImported!==false)fail('RECONCILIATION_MANIFEST_MISMATCH','Protected production reconciliation authority differs.');if(!protect||protect.mode!==PROTECTION)fail('PROTECTION_REQUIRED','Production database is not protected.');return{initialization:init,reconciliation:recon,protection:protect};}
    function validateDeclaration(payload){if(!payload||payload.contractVersion!=='p10d-r2-resolved-representation-repair-1'||payload.resolvedPayloadChecksum!==PAYLOAD_SHA256||payload.frozenIdentityMapChecksum!==IDENTITY_SHA256||payload.evidenceChecksum!==EVIDENCE_SHA256||Number(payload.expectedRoleCount)!==859||Number(payload.expectedRetainedLinkCount)!==359||Number(payload.expectedIntentionalAbsenceCount)!==259||!sameList(payload.canonicalCourseContexts,['arc-course-wt','arc-course-awt']))fail('PACKAGE_DECLARATION_MISMATCH','Physical package declaration differs from accepted R2 authority.');}
    function validateHistory(rows){rows=(rows||[]).slice().sort(function(a,b){return Number(a.sequence)-Number(b.sequence);});if(rows.length!==11&&rows.length!==12)fail('PACKAGE_HISTORY_MISMATCH','Package history must contain exactly 11 verified-complete or 12 available records.',{count:rows.length});rows.forEach(function(row,index){if(row.packageId!==PACKAGE_ID||Number(row.sequence)!==index+1)fail('PACKAGE_HISTORY_MISMATCH','Package identity or sequence differs.',{index:index,row:row});});var first=rows[0],second=rows[1],complete=rows[10];if(first.recordType!=='PACKAGE_DECLARED'||first.attemptId!==null)fail('PACKAGE_HISTORY_MISMATCH','Package declaration lineage differs.');validateDeclaration(first.payload);if(second.recordType!=='ATTEMPT_STARTED'||second.attemptId!==ATTEMPT_ID)fail('PACKAGE_HISTORY_MISMATCH','Package attempt lineage differs.');PHASES.forEach(function(expected){var row=rows[expected.sequence-1],p=row&&row.payload||{};if(!row||row.recordType!=='PHASE_VERIFIED'||row.attemptId!==ATTEMPT_ID||p.phase!==expected.phase||Number(p.memberCount)!==expected.memberCount||p.checksum!==expected.checksum||p.readbackVerified!==true)fail('PACKAGE_HISTORY_MISMATCH','Package phase lineage differs.',{expected:expected,actual:row});});var c=complete&&complete.payload||{};if(!complete||complete.recordType!=='PACKAGE_VERIFIED_COMPLETE'||complete.attemptId!==ATTEMPT_ID||Number(c.roleCount)!==859||Number(c.retainedLinkCount)!==359||Number(c.intentionalAbsenceCount)!==259||c.resolvedPayloadChecksum!==PAYLOAD_SHA256||c.frozenIdentityMapChecksum!==IDENTITY_SHA256||c.ownerReadbackVerified!==true||c.backupRecoveryVerified!==true)fail('PACKAGE_HISTORY_MISMATCH','Verified-complete lineage differs.');if(rows.length===12){var available=rows[11],p=available.payload||{};if(available.recordType!=='PACKAGE_AVAILABLE'||available.attemptId!==ATTEMPT_ID||p.availabilityScope!=='instructional-owner-reads'||p.normalAuthority!==AUTHORITY||p.classroomAuthorityTransferred!==false||p.realStudentDataAuthorized!==false||p.packageId!==PACKAGE_ID||p.attemptId!==ATTEMPT_ID||p.acceptedPi2BaselineFileChecksum!==BASELINE_FILE_SHA256||p.acceptedPi2BaselinePackageChecksum!==BASELINE_PACKAGE_SHA256||p.legacyLessonPolicy!=='reference_only'||!text(p.operator)||!text(p.publicationCommit)||!text(p.publicationTree)||!text(p.rollbackRef)||!text(p.preAvailabilityRecoveryFileChecksum)||!text(p.preAvailabilityRecoveryPackageChecksum))fail('PACKAGE_AVAILABLE_LINEAGE_MISMATCH','Availability event provenance differs from bounded PA1 authority.');}return rows;}
    function validateCourses(stores){var rows=(stores[COURSE_STORE]||[]).slice().sort(function(a,b){return a.courseId.localeCompare(b.courseId);});if(rows.length!==2||rows[0].courseId!=='arc-course-awt'||rows[0].code!=='AWT'||rows[0].title!=='Advanced Welding Technology'||rows[1].courseId!=='arc-course-wt'||rows[1].code!=='WT'||rows[1].title!=='Welding Technology')fail('CANONICAL_COURSE_MISMATCH','Only exact canonical WT/AWT Courses are permitted.');}
    function validateLessonPolicy(stores){var versions=stores.lesson_versions||[];if(versions.length!==124)fail('LEGACY_LESSON_POLICY_VIOLATION','Exactly 124 preserved Lesson Versions are required.');versions.forEach(function(row){if(row.importPackageId!==PACKAGE_ID||row.instructionalAvailability!=='reference_only'||row.immutableContent!==true||row.ordinarySchedulingEligible!==false||row.autoBuildEligible!==false||row.instructionalAcceptanceRef!==null||(row.teachingGuide!==undefined&&row.teachingGuide!==null))fail('LEGACY_LESSON_POLICY_VIOLATION','Legacy Lesson policy differs.',{lessonVersionId:row.lessonVersionId});});}
    function validateSnapshot(report){if(!report||report.exists!==true||report.databaseName!==DB||Number(report.indexedDbVersion)!==14||!sameList(report.storeNames,CURRENT_STORES))fail('PRODUCTION_STRUCTURE_MISMATCH','Production must be exact Schema 8 / IDB 14 / 74 stores.');var meta=report.metadata;if(!meta||meta.schemaFamily!=='arc-classroom'||Number(meta.schemaVersion)!==8||Number(meta.indexedDbVersion)!==14||meta.initializationState!=='ready')fail('METADATA_INCONSISTENT','Production metadata is not ready Schema 8 / IDB 14 authority.');var manifests=validateInfrastructure(report),stores=report.stores||{},counts=report.counts||{},migrations=stores.migration_log||[];if(migrations.length!==14||['indexeddb-10-to-11','indexeddb-11-to-12','indexeddb-12-to-13','indexeddb-13-to-14'].some(function(id){return !migrations.some(function(row){return row.id===id&&row.status==='succeeded';});}))fail('MIGRATION_HISTORY_MISMATCH','Production migration history differs from accepted authority.');if(Number(counts.metadata)!==1||Number(counts.migration_log)!==14||Number(counts.infrastructure_records)!==3||Number(counts[COURSE_STORE])!==2)fail('PRODUCTION_COUNT_MISMATCH','Protected baseline counts differ.');Object.keys(ROLE_COUNTS).forEach(function(name){if(Number(counts[name]||0)!==ROLE_COUNTS[name])fail('INSTRUCTIONAL_COUNT_MISMATCH','Instructional role count differs.',{store:name,expected:ROLE_COUNTS[name],actual:counts[name]});(stores[name]||[]).forEach(function(row){if(row.importPackageId!==PACKAGE_ID)fail('PACKAGE_BINDING_MISMATCH','Instructional row belongs to another package.',{store:name});});});var populated=EMPTY_STORES.filter(function(name){return Number(counts[name]||0)!==0;});if(populated.length)fail('UNEXPECTED_CLASSROOM_RECORDS','Student/classroom/pacing or intentionally absent stores are not empty.',{stores:populated});validateCourses(stores);validateLessonPolicy(stores);var history=validateHistory(stores[PACKAGE_STORE]),state=history.length===12?'available':'verified_complete',expectedTotal=state==='available'?891:890;if(total(counts)!==expectedTotal||Number(counts[PACKAGE_STORE])!==history.length)fail('PRODUCTION_COUNT_MISMATCH','Total or package record count differs.',{expectedTotal:expectedTotal,actualTotal:total(counts)});return{databaseName:DB,schemaVersion:8,indexedDbVersion:14,storeCount:74,totalRecords:expectedTotal,packageId:PACKAGE_ID,attemptId:ATTEMPT_ID,packageEvents:history.length,state:state,available:state==='available',roleCount:859,retainedLinkCount:359,intentionalAbsenceCount:259,legacyLessonCount:124,manifests:copy(manifests),authorityState:AUTHORITY,classroomAuthorityTransferred:false,realStudentDataAuthorized:false};}
    async function ensureServices(){if(services)return services;var controller=Storage.create({databaseName:DB,indexedDB:idb,crypto:cryptoApi,build:build,now:function(){var v=clock();return v instanceof Date?v:new Date(v);}}),db=await controller.open();db.constants=controller.constants;db.generateId=controller.generateId;var packages=Packages.create({storage:db,actor:'p10d-pa1-package-availability',now:function(){var v=clock();return v instanceof Date?v.toISOString():String(v);}}),curriculum=Curriculum.create({storage:db,packageAuthority:packages,crypto:cryptoApi,actor:'p10d-pa1-package-availability'}),evidence=Evidence.create({storage:db,packageAuthority:packages,actor:'p10d-pa1-package-availability'}),lessons=Lessons.create({storage:db,packageAuthority:packages,actor:'p10d-pa1-package-availability'}),backup=BackupRecovery.create({storage:db,crypto:cryptoApi,databaseName:DB,build:{version:'P10D-PA1',build:RUNTIME},now:function(){var v=clock();return v instanceof Date?v.toISOString():String(v);}});services={storage:db,controller:controller,packages:packages,curriculum:curriculum,evidence:evidence,lessons:lessons,backup:backup};return services;}
    function reportFromPackage(pkg){var stores=pkg.stores||{},counts={};CURRENT_STORES.forEach(function(name){counts[name]=(stores[name]||[]).length;});return{exists:true,databaseName:DB,indexedDbVersion:pkg.manifest.indexedDbVersion,storeNames:pkg.manifest.storeInventory||Object.keys(stores),counts:counts,metadata:(stores.metadata||[]).find(function(x){return x.key==='database';})||null,infrastructure:stores.infrastructure_records||[],stores:stores};}
    async function summarizeBackup(input,source,filename,expectedState){var service=await ensureServices(),raw=input&&input.text!==undefined?input.text:String(input),verified=await service.backup.verifyPackage(raw),pkg=verified.package;if(!pkg.manifest||pkg.manifest.databaseName!==DB||Number(pkg.manifest.schemaVersion)!==8||Number(pkg.manifest.indexedDbVersion)!==14)fail('BACKUP_IDENTITY_MISMATCH','Recovery package is not exact protected Schema 8 / IDB 14 authority.');var snapshot=validateSnapshot(reportFromPackage(pkg));if(snapshot.state!==expectedState)fail('BACKUP_STATE_MISMATCH','Recovery package state differs.',{expected:expectedState,actual:snapshot.state});return{text:raw,package:pkg,verified:true,source:source,fileChecksum:await sha256(raw),packageChecksum:pkg.manifest.packageIntegrity.checksum,recordCount:verified.recordCount,storeCount:74,filename:filename,mimeType:'application/json',snapshot:snapshot,authorityState:AUTHORITY};}
    function publicBackup(summary){return{verified:true,source:summary.source,fileChecksum:summary.fileChecksum,packageChecksum:summary.packageChecksum,recordCount:summary.recordCount,storeCount:summary.storeCount,filename:summary.filename,mimeType:summary.mimeType,text:summary.text,authorityState:AUTHORITY};}
    function parity(expected,actual,allowed){var diffs=[],allow=allowed||[];CURRENT_STORES.forEach(function(name){var a=expected.package.manifest.stores[name],b=actual.package.manifest.stores[name];if((a.recordCount!==b.recordCount||a.checksum!==b.checksum)&&allow.indexOf(name)<0)diffs.push({store:name,expected:a,actual:b});});if(diffs.length)fail('BASELINE_PARITY_MISMATCH','Live production differs from retained recovery authority.',{differences:diffs});return{matched:true,allowedDifferences:allow.slice()};}
    async function exportSummary(purpose,filename,state){var service=await ensureServices(),exported=await service.backup.exportBackup({purpose:purpose});return summarizeBackup(exported,'captured',filename,state);}
    async function verifyHidden(service){var code=null;try{await service.packages.assertOrdinaryReadGate({packageId:PACKAGE_ID});}catch(e){code=e.code;}if(code!=='PACKAGE_READ_GATE_CLOSED')fail('ORDINARY_READ_GATE_MISMATCH','Unavailable package must refuse ordinary reads.',{code:code});var wt=await service.curriculum.getCourseStandards({courseId:'arc-course-wt'}),awt=await service.curriculum.getCourseStandards({courseId:'arc-course-awt'}),wtLessons=await service.lessons.getCourseLessons({courseId:'arc-course-wt'}),awtLessons=await service.lessons.getCourseLessons({courseId:'arc-course-awt'});if(wt.standards.length||awt.standards.length||wtLessons.length||awtLessons.length)fail('ORDINARY_READ_EXPOSED','Unavailable package content is visible.');return{blocked:true,code:code,wtStandards:0,awtStandards:0,wtLessons:0,awtLessons:0};}
    async function verifyOwnerReads(service){await service.packages.assertOrdinaryReadGate({packageId:PACKAGE_ID});var wt=await service.curriculum.getCourseStandards({courseId:'arc-course-wt'}),awt=await service.curriculum.getCourseStandards({courseId:'arc-course-awt'});if(wt.catalogs.length!==1||wt.standards.length!==9||awt.catalogs.length!==1||awt.standards.length!==20)fail('OWNER_READ_MISMATCH','Ordinary Standard projections differ.');var wtEssential=await service.curriculum.getEssentialStandards({courseId:'arc-course-wt',catalogVersionId:wt.catalogVersions[0].standardCatalogVersionId}),awtEssential=await service.curriculum.getEssentialStandards({courseId:'arc-course-awt',catalogVersionId:awt.catalogVersions[0].standardCatalogVersionId}),wtMap=await service.curriculum.getCurriculumMap({courseId:'arc-course-wt'}),awtMap=await service.curriculum.getCurriculumMap({courseId:'arc-course-awt'});if(wtEssential.designations.length!==4||awtEssential.designations.length!==6||!wtMap||wtMap.items.length!==29||!awtMap||awtMap.items.length!==27)fail('OWNER_READ_MISMATCH','Essential or Curriculum projections differ.');var definitions=await service.storage.query(Storage.STORES.competencyDefinitions),versions=await service.storage.query(Storage.STORES.competencyVersions),wtCompetencies=definitions.filter(function(x){return(x.courseIds||[]).indexOf('arc-course-wt')>=0;}),awtCompetencies=definitions.filter(function(x){return(x.courseIds||[]).indexOf('arc-course-awt')>=0;});if(definitions.length!==60||versions.length!==60||wtCompetencies.length!==26||awtCompetencies.length!==34||definitions.some(function(x){return x.importPackageId!==PACKAGE_ID;})||versions.some(function(x){return x.importPackageId!==PACKAGE_ID;}))fail('OWNER_READ_MISMATCH','Ordinary Competency package read differs.');var wtLessons=await service.lessons.getCourseLessons({courseId:'arc-course-wt'}),awtLessons=await service.lessons.getCourseLessons({courseId:'arc-course-awt'}),wtAuto=await service.lessons.getAutoBuildEligibleLessons({courseId:'arc-course-wt'}),awtAuto=await service.lessons.getAutoBuildEligibleLessons({courseId:'arc-course-awt'}),version=(await service.storage.query(Storage.STORES.lessonVersions))[0],lessonCode=null;try{await service.lessons.getLessonVersion({lessonVersionId:version.lessonVersionId});}catch(e){lessonCode=e.code;}if(wtLessons.length||awtLessons.length||wtAuto.length||awtAuto.length||lessonCode!=='LESSON_REFERENCE_ONLY')fail('LEGACY_LESSON_EXPOSURE','Reference-only Lessons became ordinary or Auto Build content.',{directReadCode:lessonCode});return{wt:{standardCatalogs:1,standards:9,essentialStandards:4,curriculumMaps:1,curriculumItems:29,competencies:26,ordinaryLessons:0,autoBuildLessons:0},awt:{standardCatalogs:1,standards:20,essentialStandards:6,curriculumMaps:1,curriculumItems:27,competencies:34,ordinaryLessons:0,autoBuildLessons:0},legacyLessons:{referenceOnly:124,directOrdinaryReadCode:lessonCode}};}
    async function inspectReadiness(){var snapshot=validateSnapshot(await inspectRaw()),service=await ensureServices(),ownerReads=snapshot.available?await verifyOwnerReads(service):await verifyHidden(service);inspection=Object.assign({},snapshot,{ownerReads:ownerReads});return copy(inspection);}
    async function loadAcceptedBaseline(input){var raw=String(input);if(await sha256(raw)!==BASELINE_FILE_SHA256)fail('BASELINE_FILE_CHECKSUM_MISMATCH','Loaded PI2 baseline bytes differ from accepted physical authority.');acceptedBaseline=await summarizeBackup(raw,'loaded','ARC-v8-protected-post-instructional-import-schema8-idb14.json','verified_complete');if(acceptedBaseline.packageChecksum!==BASELINE_PACKAGE_SHA256||acceptedBaseline.recordCount!==890)fail('BASELINE_PACKAGE_CHECKSUM_MISMATCH','Loaded PI2 baseline package integrity differs.');return publicBackup(acceptedBaseline);}
    async function capturePreAvailabilityBackup(){var ready=await inspectReadiness();if(ready.state!=='verified_complete')fail('VERIFIED_COMPLETE_REQUIRED','Fresh pre-availability recovery requires unavailable verified-complete package authority.');if(!acceptedBaseline)fail('ACCEPTED_BASELINE_REQUIRED','Load and verify the accepted PI2 baseline first.');var current=await exportSummary('p10d-pa1-protected-pre-package-availability','ARC-v8-protected-pre-package-availability-schema8-idb14.json','verified_complete');parity(acceptedBaseline,current,[]);verifiedPreBackup=current;return publicBackup(current);}
    async function loadPreAvailabilityBackup(input){if(!acceptedBaseline)fail('ACCEPTED_BASELINE_REQUIRED','Load and verify the accepted PI2 baseline first.');var current=await summarizeBackup(typeof input==='string'?input:input.text,'loaded','ARC-v8-protected-pre-package-availability-schema8-idb14.json','verified_complete');parity(acceptedBaseline,current,[]);verifiedPreBackup=current;return publicBackup(current);}
    function requireAuthorization(input){input=input||{};if(!acceptedBaseline||!verifiedPreBackup)fail('VERIFIED_RECOVERY_REQUIRED','Accepted PI2 baseline and fresh pre-availability recovery are required.');if(text(input.confirmation)!==CONFIRMATION)fail('EXPLICIT_CONFIRMATION_REQUIRED','Exact package-availability confirmation is required.');if(!text(input.operator)||!text(input.publicationCommit)||!text(input.publicationTree)||!text(input.rollbackRef))fail('AUTHORIZATION_REQUIRED','Operator, publication commit/tree, and rollback reference are required.');if(!expectedCommit||!expectedTree)fail('PUBLICATION_IDENTITY_REQUIRED','Engineering URL must provide exact publication commit and tree.');if(text(input.publicationCommit)!==expectedCommit||text(input.publicationTree)!==expectedTree)fail('PUBLICATION_IDENTITY_MISMATCH','Entered commit/tree differs from engineering URL authority.');return input;}
    async function verifyAvailablePackage(){if(!acceptedBaseline||!verifiedPreBackup)fail('VERIFIED_RECOVERY_REQUIRED','Accepted PI2 baseline and pre-availability recovery are required for exact post verification.');var snapshot=validateSnapshot(await inspectRaw());if(snapshot.state!=='available')fail('AVAILABLE_PACKAGE_REQUIRED','Package is not in exact available state.');var service=await ensureServices(),ownerReads=await verifyOwnerReads(service),post=await exportSummary('p10d-pa1-protected-post-package-availability','ARC-v8-protected-post-package-availability-schema8-idb14.json','available'),comparison=parity(verifiedPreBackup,post,[PACKAGE_STORE]),before=verifiedPreBackup.package.manifest.stores[PACKAGE_STORE],after=post.package.manifest.stores[PACKAGE_STORE],audit=await service.backup.auditDatabase();if(before.recordCount!==11||after.recordCount!==12||before.checksum===after.checksum||post.recordCount!==891||!audit.healthy)fail('POST_AVAILABILITY_VERIFICATION_FAILED','Post-availability mutation or integrity differs from bounded authority.');lastResult=Object.assign({},snapshot,{onlyChangedStore:PACKAGE_STORE,storeParity:comparison,ownerReads:ownerReads,audit:audit,postAvailabilityBackup:publicBackup(post),preAvailabilityBackup:{fileChecksum:verifiedPreBackup.fileChecksum,packageChecksum:verifiedPreBackup.packageChecksum},acceptedBaseline:{fileChecksum:acceptedBaseline.fileChecksum,packageChecksum:acceptedBaseline.packageChecksum},normalAuthority:AUTHORITY});return copy(lastResult);}
    async function makeAvailable(input){input=requireAuthorization(input);var before=validateSnapshot(await inspectRaw()),service=await ensureServices(),live=await exportSummary('p10d-pa1-pre-availability-recheck','ARC-v8-protected-pre-package-availability-schema8-idb14.json',before.state);if(before.state==='available')return verifyAvailablePackage();if(before.state!=='verified_complete')fail('VERIFIED_COMPLETE_REQUIRED','Only exact verified-complete unavailable package can become available.');parity(acceptedBaseline,live,[]);parity(verifiedPreBackup,live,[]);await verifyHidden(service);await service.packages.markAvailable({packageId:PACKAGE_ID,attemptId:ATTEMPT_ID,expectedSequence:11,reason:'P10D-PA1 bounded package availability under continued V7_ONLY.',payload:{availabilityScope:'instructional-owner-reads',normalAuthority:AUTHORITY,classroomAuthorityTransferred:false,realStudentDataAuthorized:false,packageId:PACKAGE_ID,attemptId:ATTEMPT_ID,publicationCommit:text(input.publicationCommit),publicationTree:text(input.publicationTree),rollbackRef:text(input.rollbackRef),acceptedPi2BaselineFileChecksum:acceptedBaseline.fileChecksum,acceptedPi2BaselinePackageChecksum:acceptedBaseline.packageChecksum,preAvailabilityRecoveryFileChecksum:verifiedPreBackup.fileChecksum,preAvailabilityRecoveryPackageChecksum:verifiedPreBackup.packageChecksum,legacyLessonPolicy:'reference_only',operator:text(input.operator)}});return verifyAvailablePackage();}
    return{inspectReadiness:inspectReadiness,loadAcceptedBaseline:loadAcceptedBaseline,capturePreAvailabilityBackup:capturePreAvailabilityBackup,loadPreAvailabilityBackup:loadPreAvailabilityBackup,makeAvailable:makeAvailable,verifyAvailablePackage:verifyAvailablePackage,constants:{databaseName:DB,runtimeRevision:RUNTIME,authorityState:AUTHORITY,confirmation:CONFIRMATION,packageId:PACKAGE_ID,attemptId:ATTEMPT_ID,baselineFileChecksum:BASELINE_FILE_SHA256,baselinePackageChecksum:BASELINE_PACKAGE_SHA256,storeCount:74,beforeRecords:890,afterRecords:891,beforeEvents:11,afterEvents:12,expectedPublicationCommit:expectedCommit,expectedPublicationTree:expectedTree,roleCounts:copy(ROLE_COUNTS),emptyStores:EMPTY_STORES.slice()}};
  }
  return{create:create,DATABASE_NAME:DB,RUNTIME_REVISION:RUNTIME,CONFIRMATION:CONFIRMATION,PACKAGE_ID:PACKAGE_ID,ATTEMPT_ID:ATTEMPT_ID,BASELINE_FILE_SHA256:BASELINE_FILE_SHA256,BASELINE_PACKAGE_SHA256:BASELINE_PACKAGE_SHA256,ROLE_COUNTS:ROLE_COUNTS,EMPTY_STORES:EMPTY_STORES};
}));
