/* ARC P10D-PU2 protected-production physical upgrade bridge.
   Engineering-only and explicit: loading this module never opens IndexedDB. */
(function(root,factory){
  var api=factory(
    root.ArcV8Storage||(typeof require==='function'?require('./arc_v8_storage'):null),
    root.ArcV8BackupRecovery||(typeof require==='function'?require('./arc_v8_backup_recovery'):null),
    root.ArcV8ProductionInitialization||(typeof require==='function'?require('./arc_v8_production_initialization'):null),
    root.ArcV8ProtectedProductionUpgrade||(typeof require==='function'?require('./arc_v8_protected_production_upgrade'):null)
  );
  if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcV8ProtectedProductionUpgradePhysical=api;
}(this,function(Storage,BackupRecovery,ProductionInitialization,ProtectedUpgrade){
  'use strict';
  var DB='arc_classroom_v8',RUNTIME='p10d-pu2-protected-upgrade-bridge-1';
  var CONFIRMATION='UPGRADE PROTECTED PRODUCTION TO IDB14',AUTHORITY='V7_ONLY';
  var PROTECTION='Production/Classroom Protected',FORMAT='arc-v8-portable-backup',FORMAT_VERSION=1;
  var INIT='production-v8-initialization-manifest',RECON='production-v8-reconciliation-manifest',PROTECT='database-protection';
  var ALLOWED_DATABASES=Object.freeze([DB,'arc_classroom_v8_engineering_verification']);
  var HISTORICAL=Object.freeze(ProtectedUpgrade.HISTORICAL_STORES.slice());
  var CURRENT=Object.freeze(BackupRecovery.EXPECTED_STORES.slice());
  var NEW_STORES=Object.freeze(ProtectedUpgrade.NEW_STORES.slice());

  function fail(code,message,context,cause){throw new Storage.StorageError(code,message,context||{},cause);}
  function clone(value){return value===undefined?undefined:structuredClone(value);}
  function canonical(value){if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return'['+value.map(canonical).join(',')+']';return'{'+Object.keys(value).sort().filter(function(k){return value[k]!==undefined;}).map(function(k){return JSON.stringify(k)+':'+canonical(value[k]);}).join(',')+'}';}
  function sameList(a,b){return canonical((a||[]).slice().sort())===canonical((b||[]).slice().sort());}
  function text(value){return String(value===undefined||value===null?'':value).trim();}
  function row(rows,id){return(rows||[]).find(function(item){return item.id===id;})||null;}
  function bytes(value){if(value instanceof ArrayBuffer)return new Uint8Array(value);if(ArrayBuffer.isView(value))return new Uint8Array(value.buffer,value.byteOffset,value.byteLength);fail('INVALID_BINARY','Expected binary bytes.');}
  function b64(value){var raw=bytes(value),s='';for(var i=0;i<raw.length;i++)s+=String.fromCharCode(raw[i]);if(typeof btoa==='function')return btoa(s);if(typeof Buffer!=='undefined')return Buffer.from(raw).toString('base64');fail('BASE64_UNAVAILABLE','Base64 encoding is unavailable.');}
  function request(request){return new Promise(function(resolve,reject){request.onsuccess=function(){resolve(request.result);};request.onerror=function(){reject(request.error||new Error('IndexedDB request failed.'));};});}
  function transactionDone(tx){return new Promise(function(resolve,reject){tx.oncomplete=function(){resolve();};tx.onerror=function(){reject(tx.error||new Error('IndexedDB transaction failed.'));};tx.onabort=function(){reject(tx.error||new Error('IndexedDB transaction aborted.'));};});}

  function create(options){
    options=options||{};
    var databaseName=text(options.databaseName||DB),idb=options.indexedDB||(typeof indexedDB!=='undefined'?indexedDB:null),cryptoApi=options.crypto||(typeof crypto!=='undefined'?crypto:null);
    var clock=options.now||function(){return new Date();},build=options.build||{};
    var expectedCommit=text(options.expectedPublicationCommit),expectedTree=text(options.expectedPublicationTree);
    if(databaseName!==DB)fail('PRODUCTION_IDENTITY_REQUIRED','Physical upgrade accepts only exact protected production identity.',{actual:databaseName,expected:DB});
    if(!cryptoApi||!cryptoApi.subtle)throw Error('Physical upgrade requires Web Crypto SHA-256.');
    var inspector=options.inspector||null,verifiedBackup=null,lastUpgrade=null;
    function getInspector(){if(!inspector)inspector=ProductionInitialization.nativeInspector(idb);return inspector;}
    async function digest(value){var raw=typeof value==='string'?new TextEncoder().encode(value):bytes(value),hash=await cryptoApi.subtle.digest('SHA-256',raw);return Array.from(new Uint8Array(hash),function(x){return x.toString(16).padStart(2,'0');}).join('');}
    function validateManifests(report){var init=row(report.infrastructure,INIT),recon=row(report.infrastructure,RECON),protection=row(report.infrastructure,PROTECT);
      if(!init||init.status!=='complete'||init.databaseName!==DB||init.schemaFamily!=='arc-classroom'||Number(init.schemaVersion)!==8||Number(init.indexedDbVersion)!==10||Number(init.expectedStoreCount)!==53||!sameList(init.expectedStores,HISTORICAL)||init.authorityState!==AUTHORITY||init.classroomAuthorityTransferred!==false||init.realStudentDataAuthorized!==false||init.contentImported!==false)fail('INITIALIZATION_MANIFEST_MISMATCH','Protected production initialization authority differs.');
      if(!recon||recon.status!=='complete'||Number(recon.importedRecordCount)!==0||Number(recon.excludedIdentityCount)!==0||recon.reusableAuthorityImported!==false||recon.classroomTransactionsImported!==false)fail('RECONCILIATION_MANIFEST_MISMATCH','Protected production zero-import reconciliation differs.');
      if(!protection||protection.mode!==PROTECTION)fail('PROTECTION_REQUIRED','Production database is not protected.');
      return{initialization:init,reconciliation:recon,protection:protection};
    }
    function validateInspection(report){
      if(!report||report.exists!==true||report.databaseName!==DB||Number(report.indexedDbVersion)!==10||!sameList(report.storeNames,HISTORICAL))fail('PREUPGRADE_INSPECTION_MISMATCH','Production must be exact protected IDB 10 / 53 stores before upgrade.');
      var unknown=(report.knownDatabases||[]).filter(function(name){return ALLOWED_DATABASES.indexOf(name)<0;});if(unknown.length)fail('UNEXPECTED_PROFILE_DATABASE','Unexpected database identity is present.',{databases:unknown});
      var domain=HISTORICAL.filter(function(name){return['metadata','migration_log','infrastructure_records'].indexOf(name)<0;}),populated=domain.filter(function(name){return Number((report.counts||{})[name]||0)!==0;});if(populated.length)fail('UNEXPECTED_PRODUCTION_RECORDS','Protected production contains classroom/domain records.',{stores:populated});
      var metadata=report.metadata;if(!metadata||metadata.schemaFamily!=='arc-classroom'||Number(metadata.schemaVersion)!==8||Number(metadata.indexedDbVersion)!==10||metadata.initializationState!=='ready')fail('METADATA_INCONSISTENT','Production metadata is not exact ready Schema 8 / IDB 10 authority.');
      return{report:clone(report),manifests:clone(validateManifests(report)),authorityState:AUTHORITY,classroomAuthorityTransferred:false,realStudentDataAuthorized:false,instructionalContentImported:false};
    }
    async function inspectProtectedProduction(){return validateInspection(await getInspector().inspect(DB));}
    async function openHistorical(){
      if(!idb)fail('INDEXEDDB_UNAVAILABLE','IndexedDB is required.');
      return new Promise(function(resolve,reject){var req=idb.open(DB),upgraded=false;req.onupgradeneeded=function(){upgraded=true;try{req.transaction.abort();}catch(ignore){}};req.onerror=function(){reject(req.error||new Error('Historical database open failed.'));};req.onsuccess=function(){var db=req.result;if(upgraded){db.close();reject(new Storage.StorageError('UNVERSIONED_OPEN_UPGRADE_REFUSED','Historical snapshot refused a database creation or upgrade.'));return;}resolve(db);};});
    }
    async function snapshotHistorical(){var db=await openHistorical();try{if(Number(db.version)!==10||!sameList(Array.from(db.objectStoreNames),HISTORICAL))fail('HISTORICAL_SNAPSHOT_IDENTITY_MISMATCH','Live historical database changed before backup capture.');var tx=db.transaction(HISTORICAL,'readonly'),done=transactionDone(tx),stores={},reads=HISTORICAL.map(function(name){return request(tx.objectStore(name).getAll());}),results=await Promise.all(reads);for(var i=0;i<HISTORICAL.length;i++){var name=HISTORICAL[i];stores[name]=results[i].map(function(value){var copy=clone(value);if(name==='artifact_media_blobs'&&copy.bytes!==undefined){copy.bytesBase64=b64(copy.bytes);delete copy.bytes;}return copy;});}await done;return stores;}finally{db.close();}}
    async function packageChecksum(pkg){var copy=clone(pkg);copy.manifest.packageIntegrity.checksum='';return digest(canonical(copy));}
    async function buildHistoricalPackage(){
      var inspected=await inspectProtectedProduction(),stores=await snapshotHistorical(),storeManifest={},total=0;
      for(var name of HISTORICAL){storeManifest[name]={recordCount:stores[name].length,checksumAlgorithm:'SHA-256',checksum:await digest(canonical(stores[name]))};total+=stores[name].length;}
      var blobs=stores.artifact_media_blobs||[],mediaItems=[],mediaBytes=0;for(var blob of blobs){if(typeof blob.bytesBase64!=='string')fail('MISSING_MEDIA','Artifact media bytes are missing.',{mediaBlobId:blob.mediaBlobId});var raw=typeof atob==='function'?Uint8Array.from(atob(blob.bytesBase64),function(c){return c.charCodeAt(0);}):new Uint8Array(Buffer.from(blob.bytesBase64,'base64'));mediaBytes+=raw.byteLength;mediaItems.push({mediaBlobId:blob.mediaBlobId,artifactId:blob.artifactId,byteSize:raw.byteLength,checksumAlgorithm:'SHA-256',checksum:await digest(raw)});}
      var instant=clock(),exportedAt=instant instanceof Date?instant.toISOString():text(instant);var pkg={manifest:{format:FORMAT,formatVersion:FORMAT_VERSION,schemaFamily:'arc-classroom',schemaVersion:8,indexedDbVersion:10,databaseName:DB,applicationVersion:text(build.version),build:text(build.build),exportedAt:exportedAt,purpose:'p10d-pu2-protected-pre-upgrade-recovery',storeInventory:HISTORICAL.slice(),stores:storeManifest,totalRecordCount:total,media:{blobCount:blobs.length,totalBytes:mediaBytes,items:mediaItems},checksumAlgorithm:'SHA-256',audit:{status:'Verified Healthy',errorCount:0,warningCount:0,issues:[]},packageIntegrity:{algorithm:'SHA-256',checksum:''}},stores:stores};
      pkg.manifest.packageIntegrity.checksum=await packageChecksum(pkg);var portable=canonical(pkg),pu1=ProtectedUpgrade.create({crypto:cryptoApi,databaseName:DB}),verified=await pu1.verifyHistoricalBackup(portable);verifiedBackup={text:portable,package:verified.package,fileChecksum:verified.fileChecksum,packageChecksum:verified.packageChecksum,totalRecordCount:verified.totalRecordCount,source:'captured'};matchBackup(inspected.report,verifiedBackup.package);return summaryBackup(verifiedBackup,inspected.manifests);
    }
    function matchBackup(report,pkg){var counts=report.counts||{};for(var name of HISTORICAL)if(Number(counts[name]||0)!==pkg.stores[name].length)fail('LIVE_BACKUP_MISMATCH','Verified backup count differs from live production.',{store:name});var metadata=(pkg.stores.metadata||[]).find(function(item){return item.key==='database';});if(canonical(metadata)!==canonical(report.metadata)||canonical((pkg.stores.infrastructure_records||[]).slice().sort(function(a,b){return a.id.localeCompare(b.id);}))!==canonical((report.infrastructure||[]).slice().sort(function(a,b){return a.id.localeCompare(b.id); })))fail('LIVE_BACKUP_MISMATCH','Verified backup metadata or protected manifests differ from live production.');return true;}
    function summaryBackup(value,manifests){return{verified:true,source:value.source,fileChecksum:value.fileChecksum,packageChecksum:value.packageChecksum,storeCount:HISTORICAL.length,recordCount:value.totalRecordCount,manifests:clone(manifests||{initialization:row(value.package.stores.infrastructure_records,INIT),reconciliation:row(value.package.stores.infrastructure_records,RECON),protection:row(value.package.stores.infrastructure_records,PROTECT)}),filename:'ARC-v8-protected-pre-upgrade-schema8-idb10.json',mimeType:'application/json',text:value.text,authorityState:AUTHORITY};}
    async function loadHistoricalBackup(input){var pu1=ProtectedUpgrade.create({crypto:cryptoApi,databaseName:DB}),verified=await pu1.verifyHistoricalBackup(input);verifiedBackup={text:typeof input==='string'?input:canonical(input),package:verified.package,fileChecksum:verified.fileChecksum,packageChecksum:verified.packageChecksum,totalRecordCount:verified.totalRecordCount,source:'loaded'};return summaryBackup(verifiedBackup);}
    function requireAuthority(input){input=input||{};if(text(input.confirmation)!==CONFIRMATION)fail('EXPLICIT_CONFIRMATION_REQUIRED','Exact protected-upgrade confirmation is required.');if(!text(input.confirmedBy)||!text(input.startingCommit)||!text(input.startingTree)||!text(input.rollbackRef))fail('AUTHORIZATION_REQUIRED','Operator, deployed commit/tree, and rollback reference are required.');if(!expectedCommit||!expectedTree)fail('PUBLICATION_IDENTITY_REQUIRED','The engineering page must be opened with exact publication commit and tree identity.');if(text(input.startingCommit)!==expectedCommit||text(input.startingTree)!==expectedTree)fail('PUBLICATION_IDENTITY_MISMATCH','Entered deployed commit/tree differs from the page publication identity.',{expectedCommit:expectedCommit,expectedTree:expectedTree});return input;}
    async function upgradeProtectedProduction(input){
      requireAuthority(input);if(!verifiedBackup)fail('VERIFIED_BACKUP_REQUIRED','Capture or load and verify the historical recovery backup first.');var inspected=await inspectProtectedProduction();matchBackup(inspected.report,verifiedBackup.package);
      var filteredInspector={inspect:async function(){var fresh=await getInspector().inspect(DB);validateInspection(fresh);fresh=clone(fresh);fresh.knownDatabases=[DB];return fresh;}};
      var pu1=(options.upgradeFactory||function(){return ProtectedUpgrade.create({indexedDB:idb,crypto:cryptoApi,databaseName:DB,inspector:filteredInspector,build:build});})();
      if(!pu1||typeof pu1.executeUpgrade!=='function')fail('PU1_COORDINATOR_REQUIRED','Accepted PU1 coordinator is required.');var result=await pu1.executeUpgrade({historicalBackup:verifiedBackup.text});
      if(result.authorityState!==AUTHORITY||result.classroomAuthorityTransferred!==false||result.realStudentDataAuthorized!==false||!result.postUpgrade||Number(result.postUpgrade.indexedDbVersion)!==14||Number(result.postUpgrade.storeCount)!==74||result.postUpgrade.newStoresEmpty!==true||Number((result.postUpgrade.counts||{}).instructional_content_packages||0)!==0)fail('POSTUPGRADE_AUTHORITY_MISMATCH','PU1 result does not retain exact protected empty 14/74 authority.');
      lastUpgrade=result;return{upgraded:true,runtimeRevision:RUNTIME,operator:text(input.confirmedBy),publicationCommit:expectedCommit,publicationTree:expectedTree,rollbackRef:text(input.rollbackRef),authorityState:AUTHORITY,classroomAuthorityTransferred:false,realStudentDataAuthorized:false,instructionalContentImported:false,postUpgrade:clone(result.postUpgrade),preUpgradeBackup:summaryBackup(verifiedBackup,inspected.manifests),postUpgradeBackup:{verified:true,fileChecksum:result.postUpgradeBackup.fileChecksum,packageChecksum:result.postUpgradeBackup.packageChecksum,storeCount:74,recordCount:result.postUpgradeBackup.totalRecordCount,filename:'ARC-v8-protected-post-upgrade-schema8-idb14.json',mimeType:'application/json',text:result.postUpgradeBackup.text}};
    }
    async function verifyUpgradedProduction(){var report=await getInspector().inspect(DB);if(!report||report.exists!==true||Number(report.indexedDbVersion)!==14||!sameList(report.storeNames,CURRENT))fail('POSTUPGRADE_INSPECTION_MISMATCH','Upgraded production is not exact IDB 14 / 74 stores.');var newNonempty=NEW_STORES.filter(function(name){return Number((report.counts||{})[name]||0)!==0;});if(newNonempty.length)fail('NEW_STORE_NOT_EMPTY','A new structural store is not empty.',{stores:newNonempty});if(!lastUpgrade)fail('UPGRADE_RESULT_REQUIRED','This page session has no verified PU1 upgrade result.');return{verified:true,databaseName:DB,schemaVersion:8,indexedDbVersion:14,storeCount:74,newStoresEmpty:true,integrityStatus:lastUpgrade.postUpgrade.audit.status,protectedResetRefused:lastUpgrade.postUpgrade.protectedResetRefused,authorityState:AUTHORITY,classroomAuthorityTransferred:false,realStudentDataAuthorized:false,instructionalContentImported:false,postUpgradeBackup:{verified:true,fileChecksum:lastUpgrade.postUpgradeBackup.fileChecksum,packageChecksum:lastUpgrade.postUpgradeBackup.packageChecksum,storeCount:74,recordCount:lastUpgrade.postUpgradeBackup.totalRecordCount,filename:'ARC-v8-protected-post-upgrade-schema8-idb14.json',mimeType:'application/json',text:lastUpgrade.postUpgradeBackup.text}};}
    return{inspectProtectedProduction:inspectProtectedProduction,captureHistoricalBackup:buildHistoricalPackage,loadHistoricalBackup:loadHistoricalBackup,upgradeProtectedProduction:upgradeProtectedProduction,verifyUpgradedProduction:verifyUpgradedProduction,constants:{databaseName:DB,runtimeRevision:RUNTIME,confirmation:CONFIRMATION,authorityState:AUTHORITY,historicalStoreCount:53,currentStoreCount:74,historicalStores:HISTORICAL.slice(),currentStores:CURRENT.slice(),newStores:NEW_STORES.slice(),allowedDatabases:ALLOWED_DATABASES.slice(),expectedPublicationCommit:expectedCommit,expectedPublicationTree:expectedTree}};
  }
  return{create:create,DATABASE_NAME:DB,RUNTIME_REVISION:RUNTIME,CONFIRMATION:CONFIRMATION,HISTORICAL_STORES:HISTORICAL.slice(),NEW_STORES:NEW_STORES.slice()};
}));
