/* Stage 14 P5 Attendance and Pass authority boundary. */
(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcAttendanceAuthorityAdapter=api;}(this,function(){
  'use strict';
  var V7='V7_ONLY',ISOLATED='V8_ISOLATED_VERIFICATION',ISOLATED_DB='arc_classroom_v8_p5_verification';
  function fail(code,message,context){var e=new Error(message);e.code=code;e.context=context||{};throw e;}
  function create(options){options=options||{};var state=options.authorityState||V7,databaseName=String(options.databaseName||''),attendance=options.attendance||null,projection=options.projection||null,storage=options.storage||null;if([V7,ISOLATED].indexOf(state)<0)fail('AUTHORITY_STATE_BLOCKED','Attendance adapter refuses an unapproved authority state.');if(state===ISOLATED&&(databaseName!==ISOLATED_DB||!attendance||!projection||!storage))fail('ISOLATED_AUTHORITY_REQUIRED','v8 Attendance verification is hard-bound to the isolated P5 database.',{databaseName:databaseName});
    function legacy(action,payload,mutation){if(state!==V7)fail('LEGACY_AUTHORITY_BLOCKED','Legacy mutation is available only in V7_ONLY.',{action:action});if(typeof mutation!=='function')fail('LEGACY_MUTATION_REQUIRED','V7_ONLY requires exactly one explicit legacy mutation.',{action:action});return mutation(payload);}
    async function scoped(payload){var view=await projection.fromV8(storage,{day:payload.schoolDate||payload.day,selectedSectionId:payload.sectionId,currentPeriodCode:payload.currentPeriodCode}),scope=view.scopeForStudent(payload.studentId);if(!scope)fail('ACADEMIC_SCOPE_REQUIRED','Attendance and Pass operations require the effective P4 Student scope.');if(payload.sectionId&&scope.sectionId!==payload.sectionId)fail('ACADEMIC_SCOPE_MISMATCH','Requested Section differs from effective P4 academic scope.');return{view:view,scope:scope,input:Object.assign({},payload,scope,{scheduledSessionId:String(payload.scheduledSessionId||view.contextForStudent(payload.studentId).currentSection.period)})};}
    async function isolated(action,payload){if(state!==ISOLATED)fail('V8_AUTHORITY_BLOCKED','v8 Attendance execution is disabled while classroom authority is V7_ONLY.',{action:action});var c=await scoped(payload||{}),input=c.input,current;switch(action){case'attendance-set':current=await attendance.currentAttendance(input);if(!current)return attendance.recordAttendance(input);if(current.status===input.status)return current;return attendance.correctAttendance({supersedesAttendanceRecordId:current.attendanceRecordId,expectedAttendanceRevision:current.revision,status:input.status,reason:input.reason||'Instructor correction',recordedAt:input.recordedAt,recordedBy:input.recordedBy});case'attendance-current':return attendance.currentAttendance(input);case'attendance-pass-projection':return attendance.attendancePassProjection(input);case'pass-start':return attendance.createPassEvent(input);case'pass-return':return attendance.closePassEvent(input.passEventId,input.expectedRevision,input.returnedAt);case'grade-review':return attendance.deriveAttendanceGradeReviews(input);case'grade-confirm':if(!input.instructorConfirmed)fail('INSTRUCTOR_CONFIRMATION_REQUIRED','Attendance-linked Gradebook action requires instructor confirmation.');return attendance.confirmAttendanceGradeDecision(input);default:fail('UNSUPPORTED_ATTENDANCE_ACTION','Unknown Attendance/Pass action.',{action:action});}}
    return{authorityState:state,databaseName:state===ISOLATED?databaseName:null,runLegacy:legacy,runIsolated:isolated,isAuthoritativeV8:false,dualWrite:false};
  }
  return{create:create,states:Object.freeze({V7_ONLY:V7,V8_ISOLATED_VERIFICATION:ISOLATED}),isolatedDatabaseName:ISOLATED_DB};
}));
