/* Stage 14 P4 Student/Enrollment/Schedule Assignment authority boundary. */
(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcAcademicAuthorityAdapter=api;}(this,function(){
  'use strict';var V7='V7_ONLY',ISOLATED='V8_ISOLATED_VERIFICATION',AUTHORITATIVE='V8_AUTHORITATIVE',ISOLATED_DB='arc_classroom_v8_p4_verification',PRODUCTION_DB='arc_classroom_v8';
  function fail(code,message,context){var e=new Error(message);e.code=code;e.context=context||{};throw e;}
  function create(options){options=options||{};var state=options.authorityState||V7,databaseName=String(options.databaseName||''),academic=options.academic||null,projection=options.projection||null,storage=options.storage||null,cache=options.projectionCache||null,resolveProductContext=options.resolveProductContext||null,gate=options.activationGate,verifyGate=options.verifyActivationGate;if([V7,ISOLATED,AUTHORITATIVE].indexOf(state)<0)fail('AUTHORITY_STATE_BLOCKED','Academic adapter refuses an unapproved authority state.');if(state===ISOLATED&&(databaseName!==ISOLATED_DB||!academic||!projection||!storage))fail('ISOLATED_AUTHORITY_REQUIRED','v8 academic verification is hard-bound to the isolated P4 database.',{databaseName:databaseName});if(state===AUTHORITATIVE&&(databaseName!==PRODUCTION_DB||!academic||!projection||!storage||!cache||typeof resolveProductContext!=='function'||typeof verifyGate!=='function'||!verifyGate(gate)))fail('PRODUCTION_ACTIVATION_GATE_REQUIRED','Production academic authority requires the exact production database, verified activation gate, and deterministic product-context resolver.',{databaseName:databaseName});
    function legacy(action,payload,mutation){if(state!==V7)fail('LEGACY_AUTHORITY_BLOCKED','Legacy mutation is available only in V7_ONLY.',{action:action});if(typeof mutation!=='function')fail('LEGACY_MUTATION_REQUIRED','V7_ONLY requires exactly one explicit legacy mutation.',{action:action});return mutation(payload);}
    async function v8(action,payload){if(state!==ISOLATED&&state!==AUTHORITATIVE)fail('V8_AUTHORITY_BLOCKED','v8 academic execution is disabled while classroom authority is V7_ONLY.',{action:action});if(state===AUTHORITATIVE&&action!=='projection')payload=Object.assign({},payload,await resolveProductContext(action,payload));if(state===AUTHORITATIVE&&['create-student-placement','reenroll'].includes(action)&&gate.realStudentDataAuthorized!==true)fail('REAL_STUDENT_DATA_NOT_AUTHORIZED','Production Student creation and enrollment remain unavailable until separately authorized.',{action:action});var result;switch(action){case'create-student-placement':result=await academic.createStudentPlacement(payload);break;case'edit-student':result=await academic.updateStudent(payload.studentId,payload.expectedRevision,payload.changes);break;case'archive-student':result=await academic.archiveStudent(payload.studentId,payload.expectedRevision);break;case'drop':result=await academic.dropStudentEnrollment(payload);break;case'reenroll':result=await academic.reenrollStudent(payload);break;case'move':result=await academic.moveEnrollment(payload);break;case'move-or-reenroll':if(payload.currentAssignmentId)result=await academic.moveEnrollment(payload);else{if(gate.realStudentDataAuthorized!==true)fail('REAL_STUDENT_DATA_NOT_AUTHORIZED','Production re-enrollment remains unavailable until separately authorized.',{action:action});result=await academic.reenrollStudent(payload);}break;case'projection':return state===AUTHORITATIVE?cache.get(payload):projection.fromV8(storage,payload);default:fail('UNSUPPORTED_ACADEMIC_ACTION','Unknown academic action.',{action:action});}if(state===AUTHORITATIVE)cache.invalidate();return result;}
    return{authorityState:state,databaseName:state===V7?null:databaseName,runLegacy:legacy,runIsolated:v8,runV8:v8,isAuthoritativeV8:state===AUTHORITATIVE,dualWrite:false};}
  return{create:create,states:Object.freeze({V7_ONLY:V7,V8_ISOLATED_VERIFICATION:ISOLATED,V8_AUTHORITATIVE:AUTHORITATIVE}),isolatedDatabaseName:ISOLATED_DB,productionDatabaseName:PRODUCTION_DB};
}));
