/* ARC P10D-PI1 protected production instructional-import bridge.
   Engineering-only and explicit: loading this module never opens IndexedDB. */
(function(root,factory){
  var api=factory(
    root.ArcV8Storage||(typeof require==='function'?require('./arc_v8_storage'):null),
    root.ArcV8Academic||(typeof require==='function'?require('./arc_v8_academic'):null),
    root.ArcV8BackupRecovery||(typeof require==='function'?require('./arc_v8_backup_recovery'):null),
    root.ArcV8InstructionalContentPackages||(typeof require==='function'?require('./arc_v8_instructional_content_packages'):null),
    root.ArcV8CurriculumPacing||(typeof require==='function'?require('./arc_v8_curriculum_pacing'):null),
    root.ArcV8Evidence||(typeof require==='function'?require('./arc_v8_evidence'):null),
    root.ArcV8LessonPlans||(typeof require==='function'?require('./arc_v8_lesson_plans'):null),
    root.ArcV8InstructionalImportCoordinator||(typeof require==='function'?require('./arc_v8_instructional_import_coordinator'):null)
  );
  if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcV8InstructionalImportProductionPhysical=api;
}(this,function(Storage,Academic,BackupRecovery,Packages,Curriculum,Evidence,Lessons,Coordinator){
  'use strict';
  var DB='arc_classroom_v8',RUNTIME='p10d-pi1-production-instructional-import-bridge-1',AUTHORITY='V7_ONLY';
  var CONFIRMATION='IMPORT VERIFIED INSTRUCTIONAL PACKAGE UNDER V7_ONLY';
  var PROTECTION='Production/Classroom Protected',INIT='production-v8-initialization-manifest',RECON='production-v8-reconciliation-manifest',PROTECT='database-protection';
  var PAYLOAD_SHA256='f1f7756242c1ef685ef4ce061507d03b8fc6834e0e448cde7510fc8e2ade79b1',IDENTITY_SHA256='7ba2956022875c03cc1bea1ee9ffa205fa78c204bfdc967c06c66fc5b1c3b750';
  var PU3_FILE_SHA256='348152d43422052795af4a9475ee2ac8f5d958f3f7c9095e6dba86417184a534',PU3_PACKAGE_SHA256='6520052c9ae08067ba4074834e3ea42cb0100c9e6de36ded1ef14402c4ff2000';
  var ROLE_STORES=Object.freeze(Array.from(new Set(Object.keys(Coordinator.ROLE_CONTRACTS).map(function(k){return Coordinator.ROLE_CONTRACTS[k].store;}))));
  var BASE_STORES=Object.freeze(['metadata','migration_log','infrastructure_records']);
  var CURRENT_STORES=Object.freeze(BackupRecovery.EXPECTED_STORES.slice());
  var PACKAGE_STORE=Storage.STORES.instructionalContentPackages;
  var COURSE_STORE=Storage.STORES.courses;
  var PROTECTED_EMPTY_STORES=Object.freeze(CURRENT_STORES.filter(function(name){return BASE_STORES.indexOf(name)<0&&name!==COURSE_STORE&&name!==PACKAGE_STORE&&ROLE_STORES.indexOf(name)<0;}));

  function fail(code,message,context,cause){throw new Storage.StorageError(code,message,context||{},cause);}
  function copy(value){return value===undefined?undefined:structuredClone(value);}
  function text(value){return String(value==null?'':value).trim();}
  function canonical(value){if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return'['+value.map(canonical).join(',')+']';return'{'+Object.keys(value).sort().filter(function(k){return value[k]!==undefined;}).map(function(k){return JSON.stringify(k)+':'+canonical(value[k]);}).join(',')+'}';}
  function sameList(a,b){return canonical((a||[]).slice().sort())===canonical((b||[]).slice().sort());}
  function one(rows,id){return(rows||[]).find(function(row){return row.id===id;})||null;}
  function request(req){return new Promise(function(resolve,reject){req.onsuccess=function(){resolve(req.result);};req.onerror=function(){reject(req.error||new Error('IndexedDB request failed.'));};});}
  function done(tx){return new Promise(function(resolve,reject){tx.oncomplete=resolve;tx.onerror=function(){reject(tx.error||new Error('IndexedDB transaction failed.'));};tx.onabort=function(){reject(tx.error||new Error('IndexedDB transaction aborted.'));};});}

  function create(options){
    options=options||{};
    var databaseName=text(options.databaseName||DB),idb=options.indexedDB||(typeof indexedDB!=='undefined'?indexedDB:null),cryptoApi=options.crypto||(typeof crypto!=='undefined'?crypto:null),build=options.build||{};
    var expectedCommit=text(options.expectedPublicationCommit),expectedTree=text(options.expectedPublicationTree),clock=options.now||function(){return new Date().toISOString();};
    if(databaseName!==DB)fail('PRODUCTION_IDENTITY_REQUIRED','Instructional import accepts only exact protected production identity.',{actual:databaseName,expected:DB});
    if(!cryptoApi||!cryptoApi.subtle)throw Error('Production instructional import requires Web Crypto SHA-256.');
    var inspector=options.inspector||null,services=options.services||null,inspection=null,verifiedPreBackup=null,payloadText=null,identityText=null,model=null,lastResult=null;
    async function sha256(value){var bytes=typeof value==='string'?new TextEncoder().encode(value):value,hash=await cryptoApi.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(hash),function(x){return x.toString(16).padStart(2,'0');}).join('');}
    async function openUnversioned(){
      if(!idb)fail('INDEXEDDB_UNAVAILABLE','IndexedDB is required.');
      return new Promise(function(resolve,reject){var req=idb.open(DB),created=false;req.onupgradeneeded=function(){created=true;try{req.transaction.abort();}catch(ignore){}};req.onerror=function(){if(created)reject(new Storage.StorageError('PRODUCTION_DATABASE_REQUIRED','Protected production database does not exist.'));else reject(req.error||new Error('Production inspection failed.'));};req.onsuccess=function(){if(created){req.result.close();reject(new Storage.StorageError('PRODUCTION_DATABASE_REQUIRED','Protected production database does not exist.'));return;}resolve(req.result);};});
    }
    async function nativeInspect(){
      var known=[];if(idb&&typeof idb.databases==='function'){try{known=(await idb.databases()).map(function(x){return x.name;}).filter(Boolean);}catch(ignore){}}
      var db=await openUnversioned();try{var stores=Array.from(db.objectStoreNames),tx=db.transaction(stores,'readonly'),finished=done(tx),snap={},reads=stores.map(function(name){return request(tx.objectStore(name).getAll());}),values=await Promise.all(reads);await finished;stores.forEach(function(name,index){snap[name]=values[index];});return{exists:true,databaseName:DB,indexedDbVersion:db.version,storeNames:stores,counts:Object.fromEntries(stores.map(function(name){return[name,snap[name].length];})),metadata:(snap.metadata||[]).find(function(x){return x.key==='database';})||null,infrastructure:snap.infrastructure_records||[],stores:snap,knownDatabases:known};}finally{db.close();}
    }
    async function inspectRaw(){return inspector&&typeof inspector.inspect==='function'?inspector.inspect(DB):nativeInspect();}
    function validateInfrastructure(report){var init=one(report.infrastructure,INIT),recon=one(report.infrastructure,RECON),protect=one(report.infrastructure,PROTECT);if(!init||init.status!=='complete'||init.databaseName!==DB||init.schemaFamily!=='arc-classroom'||Number(init.schemaVersion)!==8||Number(init.indexedDbVersion)!==10||Number(init.expectedStoreCount)!==53||init.authorityState!==AUTHORITY||init.classroomAuthorityTransferred!==false||init.realStudentDataAuthorized!==false||init.contentImported!==false)fail('INITIALIZATION_MANIFEST_MISMATCH','Historical protected production initialization authority differs.');if(!recon||recon.status!=='complete'||Number(recon.importedRecordCount)!==0||Number(recon.excludedIdentityCount)!==0||recon.reusableAuthorityImported!==false||recon.classroomTransactionsImported!==false)fail('RECONCILIATION_MANIFEST_MISMATCH','Protected production reconciliation authority differs.');if(!protect||protect.mode!==PROTECTION)fail('PROTECTION_REQUIRED','Production database is not protected.');return{initialization:init,reconciliation:recon,protection:protect};}
    function validateSnapshot(report){
      if(!report||report.exists!==true||report.databaseName!==DB||Number(report.indexedDbVersion)!==14||!sameList(report.storeNames,CURRENT_STORES))fail('PRODUCTION_STRUCTURE_MISMATCH','Production must be exact Schema 8 / IDB 14 / 74 stores.');
      var meta=report.metadata;if(!meta||meta.schemaFamily!=='arc-classroom'||Number(meta.schemaVersion)!==8||Number(meta.indexedDbVersion)!==14||meta.initializationState!=='ready')fail('METADATA_INCONSISTENT','Production metadata is not ready Schema 8 / IDB 14 authority.');
      var manifests=validateInfrastructure(report),populated=PROTECTED_EMPTY_STORES.filter(function(name){return Number((report.counts||{})[name]||0)!==0;});if(populated.length)fail('UNEXPECTED_CLASSROOM_RECORDS','Protected production contains unauthorized classroom or nonpackage instructional records.',{stores:populated});
      var migrations=report.stores&&report.stores.migration_log||[];if(migrations.length!==14||['indexeddb-10-to-11','indexeddb-11-to-12','indexeddb-12-to-13','indexeddb-13-to-14'].some(function(id){return !migrations.some(function(row){return row.id===id&&row.status==='succeeded';});}))fail('MIGRATION_HISTORY_MISMATCH','Production migration history differs from accepted PU3 authority.');
      var packageRows=Number((report.counts||{})[PACKAGE_STORE]||0),courses=Number((report.counts||{})[COURSE_STORE]||0),targetCount=ROLE_STORES.reduce(function(n,name){return n+Number((report.counts||{})[name]||0);},0);
      var state=packageRows===0&&courses===0&&targetCount===0?'fresh':packageRows>0&&courses===2?'resume_candidate':'invalid';if(state==='invalid')fail('UNEXPECTED_IMPORT_STATE','Production import state is neither fresh nor an exact resumable package.',{packageRows:packageRows,courses:courses,targetRows:targetCount});
      return{databaseName:DB,schemaVersion:8,indexedDbVersion:14,storeCount:74,state:state,packageRows:packageRows,targetRows:targetCount,courseCount:courses,manifests:copy(manifests),authorityState:AUTHORITY,classroomAuthorityTransferred:false,realStudentDataAuthorized:false,pu3Baseline:{fileChecksum:PU3_FILE_SHA256,packageChecksum:PU3_PACKAGE_SHA256,recordCount:18}};
    }
    async function inspectReadiness(){inspection=validateSnapshot(await inspectRaw());return copy(inspection);}
    async function ensureServices(){
      if(services)return services;
      var storage=Storage.create({databaseName:DB,indexedDB:idb,crypto:cryptoApi,build:build,now:function(){var v=clock();return v instanceof Date?v:new Date(v);}}),db=await storage.open();db.constants=storage.constants;db.generateId=storage.generateId;
      var packages=Packages.create({storage:db,actor:'p10d-pi1-technical-import',now:function(){var v=clock();return v instanceof Date?v.toISOString():String(v);}});
      var academic=Academic.create({storage:db,actor:'p10d-pi1-technical-import',now:function(){var v=clock();return v instanceof Date?v.toISOString():String(v);}});
      var curriculum=Curriculum.create({storage:db,packageAuthority:packages,crypto:cryptoApi,actor:'p10d-pi1-technical-import',now:function(){var v=clock();return v instanceof Date?v.toISOString():String(v);}});
      var evidence=Evidence.create({storage:db,packageAuthority:packages,actor:'p10d-pi1-technical-import',now:function(){var v=clock();return v instanceof Date?v.toISOString():String(v);}});
      var lessons=Lessons.create({storage:db,packageAuthority:packages,actor:'p10d-pi1-technical-import',now:function(){var v=clock();return v instanceof Date?v.toISOString():String(v);}});
      var coordinator=Coordinator.createProduction({storage:db,packages:packages,curriculum:curriculum,evidence:evidence,lessons:lessons,crypto:cryptoApi,databaseName:DB,productionImportAuthorized:true});
      var backup=BackupRecovery.create({storage:db,crypto:cryptoApi,databaseName:DB,build:{version:'P10D-PI1',build:RUNTIME},now:function(){var v=clock();return v instanceof Date?v.toISOString():String(v);}});
      services={storage:db,controller:storage,packages:packages,academic:academic,curriculum:curriculum,evidence:evidence,lessons:lessons,coordinator:coordinator,backup:backup};return services;
    }
    function reportFromPackage(pkg){var stores=pkg.stores||{},counts={};CURRENT_STORES.forEach(function(name){counts[name]=(stores[name]||[]).length;});return{exists:true,databaseName:DB,indexedDbVersion:pkg.manifest.indexedDbVersion,storeNames:pkg.manifest.storeInventory||Object.keys(stores),counts:counts,metadata:(stores.metadata||[]).find(function(x){return x.key==='database';})||null,infrastructure:stores.infrastructure_records||[],stores:stores};}
    async function summarizeBackup(exported,source,filename){var service=await ensureServices(),verified=await service.backup.verifyPackage(exported.text||exported),pkg=verified.package;if(!pkg.manifest||pkg.manifest.databaseName!==DB||Number(pkg.manifest.schemaVersion)!==8||Number(pkg.manifest.indexedDbVersion)!==14)fail('BACKUP_IDENTITY_MISMATCH','Recovery package is not exact protected production Schema 8 / IDB 14 authority.');validateSnapshot(reportFromPackage(pkg));var raw=exported.text||String(exported),fileChecksum=await sha256(raw);return{text:raw,package:pkg,verified:true,source:source,fileChecksum:fileChecksum,packageChecksum:pkg.manifest.packageIntegrity.checksum,recordCount:verified.recordCount,storeCount:74,filename:filename,mimeType:'application/json',authorityState:AUTHORITY};}
    function publicBackup(summary){return{verified:true,source:summary.source,fileChecksum:summary.fileChecksum,packageChecksum:summary.packageChecksum,recordCount:summary.recordCount,storeCount:summary.storeCount,filename:summary.filename,mimeType:summary.mimeType,text:summary.text,authorityState:AUTHORITY};}
    async function capturePreImportBackup(){await inspectReadiness();var service=await ensureServices(),exported=await service.backup.exportBackup({purpose:'p10d-pi1-protected-pre-instructional-import'});verifiedPreBackup=await summarizeBackup(exported,'captured','ARC-v8-protected-pre-instructional-import-schema8-idb14.json');return publicBackup(verifiedPreBackup);}
    async function loadPreImportBackup(input){verifiedPreBackup=await summarizeBackup(typeof input==='string'?{text:input}:input,'loaded','ARC-v8-protected-pre-instructional-import-schema8-idb14.json');return publicBackup(verifiedPreBackup);}
    async function refreshModel(){if(payloadText===null||identityText===null)return null;model=await Coordinator.preflight({payloadText:payloadText,identityMapText:identityText,crypto:cryptoApi});return{payloadChecksum:model.payloadChecksum,identityMapChecksum:model.identityMapChecksum,evidenceChecksum:model.evidenceChecksum,roleCount:model.roles.length,retainedLinkCount:359,intentionalAbsenceCount:model.exclusions.length,legacyLessonCount:124,wtLessonCompetencyLinks:51,awtLessonCompetencyLinks:0,authorityState:AUTHORITY};}
    async function loadResolvedPayload(input){payloadText=String(input);if(await sha256(payloadText)!==PAYLOAD_SHA256){payloadText=null;model=null;fail('PAYLOAD_CHECKSUM_MISMATCH','Resolved payload bytes differ from accepted R2 authority.');}var result=await refreshModel();return result||{payloadChecksum:PAYLOAD_SHA256,pendingIdentityMap:true};}
    async function loadIdentityMap(input){identityText=String(input);if(await sha256(identityText)!==IDENTITY_SHA256){identityText=null;model=null;fail('IDENTITY_CHECKSUM_MISMATCH','Identity-map bytes differ from accepted R2 authority.');}var result=await refreshModel();return result||{identityMapChecksum:IDENTITY_SHA256,pendingResolvedPayload:true};}
    function requireModel(){if(!model)fail('FROZEN_PACKAGE_REQUIRED','Load and verify both exact frozen package files first.');return model;}
    function declarationFor(current){var p=current.payload,e=p.packageEvidence||{};return{contractVersion:p.compilerRevision,resolvedPayloadChecksum:current.payloadChecksum,frozenIdentityMapChecksum:current.identityMapChecksum,evidenceChecksum:current.evidenceChecksum,evidenceReference:e.r1bArtifact&&e.r1bArtifact.path||p.context&&p.context.path||'p10d-r2-evidence',expectedRoleCount:859,expectedRetainedLinkCount:359,expectedIntentionalAbsenceCount:259,canonicalCourseContexts:['arc-course-wt','arc-course-awt'],sourceAuthorities:(e.sourceResolutions||[]).map(function(x){return{decisionId:x.decisionId,course:x.course,selectedAuthority:x.selectedAuthority};})};}
    function assertDeclaration(projection,current){var expected=declarationFor(current),actual=projection&&projection.declared;if(!actual||canonical(actual)!==canonical(expected))fail('PACKAGE_DECLARATION_MISMATCH','Existing production package declaration differs from exact frozen authority.',{expected:expected,actual:actual});return expected;}
    async function canonicalCourses(service,allowCreate){if(allowCreate)await service.academic.initialize();var rows=await service.storage.query(COURSE_STORE),ordered=rows.slice().sort(function(a,b){return a.courseId.localeCompare(b.courseId);});if(ordered.length!==2||ordered[0].courseId!=='arc-course-awt'||ordered[0].code!=='AWT'||ordered[0].title!=='Advanced Welding Technology'||ordered[1].courseId!=='arc-course-wt'||ordered[1].code!=='WT'||ordered[1].title!=='Welding Technology')fail('CANONICAL_COURSE_MISMATCH','Only exact canonical WT/AWT Courses are permitted.',{courses:ordered});return ordered;}
    async function packageContext(service,current){var events=await service.storage.query(PACKAGE_STORE),ids=Array.from(new Set(events.map(function(x){return x.packageId;})));if(ids.length>1)fail('MULTIPLE_PRODUCTION_PACKAGES','PI1 accepts at most one exact production instructional package.');if(!ids.length)return null;var packageId=ids[0],projection=await service.packages.getPackageProjection({packageId:packageId});assertDeclaration(projection,current);if(['available','superseded'].indexOf(projection.state)>=0)fail('PACKAGE_STATE_REFUSED','PI1 refuses available or superseded package authority.',{state:projection.state});var allowed={};current.roles.forEach(function(role){allowed[role.targetRepresentation.store+'|'+role.targetRepresentation.targetIdentity]=true;});for(var store of ROLE_STORES){var key=Object.keys(Coordinator.ROLE_CONTRACTS).map(function(name){return Coordinator.ROLE_CONTRACTS[name];}).find(function(spec){return spec.store===store;}).key,rows=await service.storage.query(store);for(var row of rows)if(row.importPackageId!==packageId||!allowed[store+'|'+row[key]])fail('UNRELATED_IMPORT_OCCUPANCY','Production contains an unrelated or unbound instructional row.',{store:store,id:row[key],importPackageId:row.importPackageId});}return{packageId:packageId,projection:projection,history:await service.packages.getPackageHistory({packageId:packageId})};}
    function requireAuthorization(input){input=input||{};if(!verifiedPreBackup)fail('VERIFIED_BACKUP_REQUIRED','A verified pre-import recovery package is required.');requireModel();if(text(input.confirmation)!==CONFIRMATION)fail('EXPLICIT_CONFIRMATION_REQUIRED','Exact instructional-import confirmation is required.');if(!text(input.operator)||!text(input.publicationCommit)||!text(input.publicationTree)||!text(input.rollbackRef))fail('AUTHORIZATION_REQUIRED','Operator, publication commit/tree, and rollback reference are required.');if(!expectedCommit||!expectedTree)fail('PUBLICATION_IDENTITY_REQUIRED','Engineering URL must provide exact publication commit and tree.');if(text(input.publicationCommit)!==expectedCommit||text(input.publicationTree)!==expectedTree)fail('PUBLICATION_IDENTITY_MISMATCH','Entered commit/tree differs from engineering URL authority.');return input;}
    async function verifyOrdinaryBlocked(service,packageId){var refused=false,code=null;try{await service.packages.assertOrdinaryReadGate({packageId:packageId});}catch(e){refused=e.code==='PACKAGE_READ_GATE_CLOSED';code=e.code;}if(!refused)fail('ORDINARY_READ_EXPOSED','Completed package became visible without PACKAGE_AVAILABLE.');return{blocked:true,code:code};}
    async function verifyPackage(service,current,packageId){var context=await packageContext(service,current);if(!context||context.packageId!==packageId)fail('PACKAGE_NOT_DECLARED','Expected production package does not exist.');var verification=await service.coordinator.verifyAll({model:current,packageId:packageId}),projection=await service.packages.getPackageProjection({packageId:packageId}),courses=await canonicalCourses(service,false),ordinary=await verifyOrdinaryBlocked(service,packageId),audit=await service.backup.auditDatabase(),protectedResetRefused=false;try{await(service.controller||service.storage).resetDevelopmentDatabase();}catch(e){protectedResetRefused=e.code==='PROTECTED_DATABASE';}if(!protectedResetRefused)fail('PROTECTED_RESET_NOT_REFUSED','Protected production reset was not refused.');if(verification.roleCount!==859||verification.retainedLinkCount!==359||verification.intentionalAbsenceCount!==259||!verification.exclusionsVerified)fail('PACKAGE_ACCOUNTING_MISMATCH','Production readback differs from frozen package.');if(projection.state!=='verified_complete'||projection.available!==false)fail('PACKAGE_STATE_MISMATCH','Production package must remain verified_complete and unavailable.',{state:projection.state,available:projection.available});if(!audit.healthy)fail('INTEGRITY_ERRORS','Post-import database integrity is not healthy.',{audit:audit});return{packageId:packageId,attemptId:projection.currentAttemptId,roleCount:859,retainedLinkCount:359,intentionalAbsenceCount:259,wtLessonCompetencyLinks:51,awtLessonCompetencyLinks:0,legacyLessonCount:124,referenceOnlyLessons:124,teachingGuideFabricated:false,state:projection.state,available:false,ordinaryRead:ordinary,courses:courses,audit:audit,protectedResetRefused:true,verification:verification,authorityState:AUTHORITY,classroomAuthorityTransferred:false,realStudentDataAuthorized:false};}
    async function importVerifiedPackage(input){
      requireAuthorization(input);var current=requireModel(),freshInspection=validateSnapshot(await inspectRaw());inspection=freshInspection;var service=await ensureServices(),context=await packageContext(service,current),packageId,attemptId,projection,history=[];
      if(!context){if(freshInspection.state!=='fresh')fail('FRESH_IMPORT_STATE_REQUIRED','Fresh production import requires empty instructional stores and package history.');await canonicalCourses(service,true);packageId=(service.controller||service.storage).generateId();await service.packages.declarePackage({packageId:packageId,declaration:declarationFor(current),reason:'P10D-PI1 exact frozen production package declaration.'});projection=await service.packages.getPackageProjection({packageId:packageId});attemptId=(service.controller||service.storage).generateId();await service.packages.startAttempt({packageId:packageId,attemptId:attemptId,expectedSequence:projection.lastSequence,reason:'P10D-PI1 guarded production import attempt.'});}
      else{packageId=context.packageId;projection=context.projection;history=context.history;await canonicalCourses(service,false);if(projection.state==='verified_complete'){lastResult=await verifyPackage(service,current,packageId);return copy(lastResult);}if(projection.state!=='assembling')fail('PACKAGE_STATE_REFUSED','Only exact assembling or verified-complete package state can resume.',{state:projection.state});attemptId=projection.currentAttemptId;}
      history=await service.packages.getPackageHistory({packageId:packageId});var phaseSummaries=[];
      for(var phase of current.phases){var summary=await service.coordinator.runPhase({model:current,phase:phase.name,packageId:packageId,attemptId:attemptId}),prior=history.find(function(row){return row.recordType==='PHASE_VERIFIED'&&row.attemptId===attemptId&&row.payload&&row.payload.phase===phase.name;});if(prior){if(Number(prior.payload.memberCount)!==summary.memberCount||prior.payload.checksum!==summary.checksum||prior.payload.readbackVerified!==true)fail('PHASE_RESUME_MISMATCH','Persisted phase verification differs from exact readback.',{phase:phase.name});}else{projection=await service.packages.getPackageProjection({packageId:packageId});await service.packages.appendPhaseVerification({packageId:packageId,attemptId:attemptId,expectedSequence:projection.lastSequence,phase:phase.name,memberCount:summary.memberCount,checksum:summary.checksum,readbackVerified:true,details:{created:summary.created,equivalent:summary.equivalent}});history=await service.packages.getPackageHistory({packageId:packageId});}phaseSummaries.push(summary);}
      var verification=await service.coordinator.verifyAll({model:current,packageId:packageId}),assembled=await service.backup.exportBackup({purpose:'p10d-pi1-assembled-hidden-recovery'}),assembledVerified=await service.backup.verifyPackage(assembled.text),completion=service.coordinator.completionEvidence({verification:verification,phaseSummaries:phaseSummaries,canonicalCoursesVerified:true,evidenceVerified:true,conflictsAbsent:true,backupRecoveryVerified:assembledVerified.verified===true});projection=await service.packages.getPackageProjection({packageId:packageId});await service.packages.markVerifiedComplete({packageId:packageId,attemptId:attemptId,expectedSequence:projection.lastSequence,completionEvidence:completion,reason:'P10D-PI1 exact package readback and recovery verified.'});
      var verified=await verifyPackage(service,current,packageId),post=await service.backup.exportBackup({purpose:'p10d-pi1-protected-post-instructional-import'}),postSummary=await summarizeBackup(post,'captured','ARC-v8-protected-post-instructional-import-schema8-idb14.json');lastResult=Object.assign({},verified,{operator:text(input.operator),publicationCommit:expectedCommit,publicationTree:expectedTree,rollbackRef:text(input.rollbackRef),assembledHiddenBackup:{fileChecksum:await sha256(assembled.text),packageChecksum:assembled.package.manifest.packageIntegrity.checksum,recordCount:assembled.verification.recordCount},postImportBackup:publicBackup(postSummary)});return copy(lastResult);
    }
    async function verifyImportedPackage(){var current=requireModel(),service=await ensureServices(),context=await packageContext(service,current);if(!context)fail('PACKAGE_NOT_DECLARED','Production instructional package does not exist.');var verified=await verifyPackage(service,current,context.packageId),post=await service.backup.exportBackup({purpose:'p10d-pi1-protected-post-instructional-import-verification'}),summary=await summarizeBackup(post,'verified','ARC-v8-protected-post-instructional-import-schema8-idb14.json');lastResult=Object.assign({},verified,{postImportBackup:publicBackup(summary)});return copy(lastResult);}
    return{inspectReadiness:inspectReadiness,capturePreImportBackup:capturePreImportBackup,loadPreImportBackup:loadPreImportBackup,loadResolvedPayload:loadResolvedPayload,loadIdentityMap:loadIdentityMap,importVerifiedPackage:importVerifiedPackage,verifyImportedPackage:verifyImportedPackage,constants:{databaseName:DB,runtimeRevision:RUNTIME,confirmation:CONFIRMATION,authorityState:AUTHORITY,payloadChecksum:PAYLOAD_SHA256,identityMapChecksum:IDENTITY_SHA256,pu3BaselineFileChecksum:PU3_FILE_SHA256,pu3BaselinePackageChecksum:PU3_PACKAGE_SHA256,storeCount:74,roleCount:859,retainedLinkCount:359,intentionalAbsenceCount:259,legacyLessonCount:124,wtLessonCompetencyLinks:51,awtLessonCompetencyLinks:0,roleStores:ROLE_STORES.slice(),protectedEmptyStores:PROTECTED_EMPTY_STORES.slice(),expectedPublicationCommit:expectedCommit,expectedPublicationTree:expectedTree}};
  }
  return{create:create,DATABASE_NAME:DB,RUNTIME_REVISION:RUNTIME,CONFIRMATION:CONFIRMATION,PAYLOAD_SHA256:PAYLOAD_SHA256,IDENTITY_SHA256:IDENTITY_SHA256,PU3_FILE_SHA256:PU3_FILE_SHA256,PU3_PACKAGE_SHA256:PU3_PACKAGE_SHA256,ROLE_STORES:ROLE_STORES.slice(),PROTECTED_EMPTY_STORES:PROTECTED_EMPTY_STORES.slice()};
}));
