/* Stage 14 P7 Competency, Evidence, Reassessment, and Open Shop authority boundary. */
(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcCompetencyEvidenceAuthorityAdapter=api;}(this,function(){
  'use strict';
  var V7='V7_ONLY',ISOLATED='V8_ISOLATED_VERIFICATION',ISOLATED_DB='arc_classroom_v8_p7_verification';
  var LEVELS=Object.freeze({1:{name:'Introduced',percent:60},2:{name:'Developing',percent:75},3:{name:'Proficient',percent:90},4:{name:'Advanced',percent:100}});
  function fail(code,message,context){var e=new Error(message);e.code=code;e.context=context||{};throw e;}
  function copy(x){return x==null?x:JSON.parse(JSON.stringify(x));}
  function create(options){options=options||{};var state=options.authorityState||V7,databaseName=String(options.databaseName||''),storage=options.storage||null,projection=options.projection||null,evidence=options.evidence||null,catalog=options.catalog||null;
    if([V7,ISOLATED].indexOf(state)<0)fail('AUTHORITY_STATE_BLOCKED','Competency/Evidence adapter refuses an unapproved authority state.');
    if(state===ISOLATED&&(databaseName!==ISOLATED_DB||!storage||!projection||!evidence))fail('ISOLATED_AUTHORITY_REQUIRED','v8 Competency/Evidence verification is hard-bound to the isolated P7 database.',{databaseName:databaseName});
    function legacy(action,payload,mutation){if(state!==V7)fail('LEGACY_AUTHORITY_BLOCKED','Legacy mutation is available only in V7_ONLY.',{action:action});if(typeof mutation!=='function')fail('LEGACY_MUTATION_REQUIRED','V7_ONLY requires exactly one explicit legacy mutation.',{action:action});return mutation(payload);}
    async function scoped(input){var view=await projection.fromV8(storage,{day:input.schoolDate||input.day,selectedSectionId:input.sectionId,currentPeriodCode:input.currentPeriodCode}),scope=view.scopeForStudent(input.studentId);if(!scope)fail('ACADEMIC_SCOPE_REQUIRED','Competency operations require the effective P4 Student scope.',{studentId:input.studentId});if(input.sectionId&&scope.sectionId!==input.sectionId)fail('ACADEMIC_SCOPE_MISMATCH','Requested Section differs from effective P4 academic scope.',{studentId:input.studentId});return{view:view,studentScope:scope,evidenceScope:{enrollmentId:scope.enrollmentId,schoolYearId:scope.schoolYearId,semesterId:scope.semesterId,sectionId:scope.sectionId}};}
    function catalogProjection(input){var course=String(input.courseCode||'').toUpperCase(),items=(input.catalog||catalog&&catalog[course.toLowerCase()]||[]).map(function(c,index){return{stableKey:String(c.code),code:String(c.code),name:String(c.name),group:String(c.category||c.group||''),standard:String(c.standard||''),levels:copy(c.levels||{}),studentStatement:String(c.student||c.studentStatement||''),order:index,courseCode:course,deepLink:{studentId:input.studentId||null,competencyCode:String(c.code)}};});if(course!=='WT'&&course!=='AWT')fail('COURSE_REQUIRED','WT or AWT catalog authority is required.');if(items.some(function(x){return x.code.indexOf(course+'-')!==0;}))fail('CATALOG_COURSE_MISMATCH','Competency catalog contains a cross-course stable key.');return{courseCode:course,items:items};}
    async function resolve(input,c){return evidence.resolveCompetency({studentId:input.studentId,competencyId:input.competencyId,strategyConfigId:input.strategyConfigId,scope:c.evidenceScope,calculatedAt:input.calculatedAt});}
    async function directJudgment(input,c){if(![1,2,3,4].includes(input.level))fail('INVALID_PROFICIENCY_LEVEL','Instructor proficiency must be Level 1–4.');if(!input.reason||!String(input.reason.code||input.reason).trim())fail('INSTRUCTOR_REASON_REQUIRED','Direct instructor proficiency requires an explicit reason.');var current=await resolve(input,c);return evidence.appendInstructorOverride({studentId:input.studentId,competencyId:input.competencyId,competencyVersionId:input.competencyVersionId,scope:c.evidenceScope,strategyConfigId:input.strategyConfigId,derivationFingerprint:current.evidenceDerivedState.evidenceFingerprint,action:'Apply',authoritativeLevel:input.level,reason:typeof input.reason==='string'?{code:'instructor_judgment',detail:input.reason}:input.reason,explanation:input.explanation||'',reviewPolicy:input.reviewPolicy||{onNewEvidence:true},supersedesOverrideId:input.supersedesOverrideId||null,expectedChainRevision:input.expectedChainRevision||0});}
    async function openShop(input,c){var items=input.competencies||[],needs=[];for(var i=0;i<items.length;i++){var item=items[i],resolved=await resolve(Object.assign({},input,item),c),level=resolved.resolvedOfficialLevel;if(level===1||level===2||level===null&&item.opportunityState==='No Evidence / No Attempt')needs.push({type:'competency',competencyId:item.competencyId,competencyCode:item.competencyCode,name:item.name,level:level,displayState:level===null?'NE':LEVELS[level].name,catalogOrder:item.catalogOrder,authoritySource:resolved.authoritySource,reviewRequired:resolved.reviewRequired,deepLink:{studentId:input.studentId,competencyCode:item.competencyCode}});}
      needs.sort(function(a,b){var al=a.level===null?0:a.level,bl=b.level===null?0:b.level;return al-bl||a.catalogOrder-b.catalogOrder||a.competencyCode.localeCompare(b.competencyCode);});var projects=(input.projectRecommendations||[]).map(function(p){return{type:'project',projectId:p.projectId,name:p.name,priority:p.priority,reason:p.reason,deepLink:{studentId:input.studentId,projectId:p.projectId}};}).sort(function(a,b){return a.priority-b.priority||a.projectId.localeCompare(b.projectId);});return{studentScope:c.studentScope,priorityCompetencies:needs.slice(0,input.competencyLimit||3),priorityProjects:projects,readOnly:true,persistedRecommendation:false};}
    async function isolated(action,input){if(state!==ISOLATED)fail('V8_AUTHORITY_BLOCKED','v8 Competency/Evidence execution is disabled while classroom authority is V7_ONLY.',{action:action});input=input||{};if(action==='catalog-projection')return catalogProjection(input);var c=await scoped(input);switch(action){case'resolve':return resolve(input,c);case'instructor-proficiency':return directJudgment(input,c);case'override-revoke':return evidence.appendInstructorOverride({studentId:input.studentId,competencyId:input.competencyId,scope:c.evidenceScope,action:'Revoke',reason:input.reason||{code:'instructor_review'},supersedesOverrideId:input.supersedesOverrideId,expectedChainRevision:input.expectedChainRevision});case'evidence-source':return evidence.createEvidenceSource(Object.assign({},input.source,{studentId:input.studentId,enrollmentId:c.studentScope.enrollmentId,academicScope:{schoolYearId:c.studentScope.schoolYearId,semesterId:c.studentScope.semesterId,sectionId:c.studentScope.sectionId}}));case'evidence-record':return evidence.createEvidenceRecord(input.record);case'evidence-correct':return evidence.correctEvidenceRecord(input.correction);case'evidence-source-correct':return evidence.correctEvidenceSource(input.correction);case'open-shop':return openShop(input,c);default:fail('UNSUPPORTED_COMPETENCY_ACTION','Unknown Competency/Evidence action.',{action:action});}}
    return{authorityState:state,databaseName:state===ISOLATED?databaseName:null,runLegacy:legacy,runIsolated:isolated,levelAuthority:LEVELS,isAuthoritativeV8:false,dualWrite:false};
  }
  return{create:create,states:Object.freeze({V7_ONLY:V7,V8_ISOLATED_VERIFICATION:ISOLATED}),isolatedDatabaseName:ISOLATED_DB,levels:LEVELS};
}));
