/* ARC Schema 8 Behavior/Incident authority. Private documentation; no grading effects. */
(function(root,factory){var api=factory(root.ArcV8Storage||(typeof require==='function'?require('./arc_v8_storage'):null));if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcV8Behavior=api;}(this,function(Storage){
  'use strict';var S=Storage.STORES;
  function fail(code,message,context){throw new Storage.StorageError(code,message,context||{});}
  function clone(x){return x==null?x:JSON.parse(JSON.stringify(x));}
  function create(options){options=options||{};var db=options.storage,now=options.now||function(){return new Date().toISOString();},actor=options.actor||'system';if(!db)throw Error('Behavior repository requires storage.');
    function stamp(value,id,lifecycle){var at=now();return Object.assign({},value,{behaviorEventId:id,lifecycle:lifecycle||'active',revision:1,createdAt:at,createdBy:actor,updatedAt:at,updatedBy:actor});}
    async function validate(tx,input){var student=await tx.get(S.students,input.studentId),enrollment=await tx.get(S.enrollments,input.enrollmentId);if(!student||!enrollment||enrollment.studentId!==student.studentId)fail('INTEGRITY_MISMATCH','BehaviorEvent requires matching Student and Enrollment authority.');if(input.sectionId){var section=await tx.get(S.sections,input.sectionId);if(!section)fail('REFERENCE_NOT_FOUND','BehaviorEvent Section does not exist.');}if(input.relatedWorkplaceEventId){var workplace=await tx.get(S.workplaceEvents,input.relatedWorkplaceEventId);if(!workplace||workplace.studentId!==input.studentId||workplace.enrollmentId!==input.enrollmentId)fail('INTEGRITY_MISMATCH','BehaviorEvent Workplace link is invalid.');}if(input.relatedSafetyEventId){var safety=await tx.get(S.safetyEvents,input.relatedSafetyEventId);if(!safety||safety.studentId!==input.studentId||safety.enrollmentId!==input.enrollmentId)fail('INTEGRITY_MISMATCH','BehaviorEvent Safety link is invalid.');}}
    function fields(input){if(!input.studentId||!input.enrollmentId||!input.occurredAt||!input.schoolDate||!String(input.category||'').trim()||!String(input.severity||'').trim()||!String(input.action||'').trim()||!String(input.description||'').trim())fail('INVALID_BEHAVIOR_EVENT','Student, Enrollment, occurrence, category, severity, action, and objective description are required.');return{studentId:input.studentId,enrollmentId:input.enrollmentId,sectionId:input.sectionId||null,schoolDate:String(input.schoolDate),occurredAt:String(input.occurredAt),recordedAt:input.recordedAt||now(),recordedBy:input.recordedBy||actor,category:String(input.category),severity:String(input.severity),action:String(input.action),description:String(input.description),followUp:String(input.followUp||''),privateInstructorDocumentation:true,relatedWorkplaceEventId:input.relatedWorkplaceEventId||null,relatedSafetyEventId:input.relatedSafetyEventId||null,context:clone(input.context||{}),supersedesBehaviorEventId:input.supersedesBehaviorEventId||null,correctionReason:String(input.correctionReason||''),gradeEffect:'none'};}
    async function record(input){var value=fields(input);return db.transaction([S.students,S.enrollments,S.sections,S.workplaceEvents,S.safetyEvents,S.behaviorEvents],async function(tx){await validate(tx,value);var row=stamp(value,db.generateId(),'active');await tx.add(S.behaviorEvents,row);return row;});}
    async function correct(input){return db.transaction([S.students,S.enrollments,S.sections,S.workplaceEvents,S.safetyEvents,S.behaviorEvents],async function(tx){var prior=await tx.get(S.behaviorEvents,input.supersedesBehaviorEventId);if(!prior)fail('REFERENCE_NOT_FOUND','BehaviorEvent does not exist.');if(prior.revision!==input.expectedRevision)fail('WRITE_CONFLICT','BehaviorEvent changed after it was read.');if(prior.lifecycle!=='active')fail('EVENT_NOT_CURRENT','Only the current active BehaviorEvent may be corrected or voided.');if(!String(input.reason||'').trim())fail('CORRECTION_REASON_REQUIRED','BehaviorEvent correction or void requires a reason.');var replacement=fields(Object.assign({},prior,input.replacement||{},{studentId:prior.studentId,enrollmentId:prior.enrollmentId,supersedesBehaviorEventId:prior.behaviorEventId,correctionReason:String(input.reason)}));await validate(tx,replacement);var row=stamp(replacement,db.generateId(),input.void?'voided':'active'),revised=Object.assign({},prior,{lifecycle:'superseded',revision:prior.revision+1,updatedAt:now(),updatedBy:actor});await tx.put(S.behaviorEvents,revised);await tx.add(S.behaviorEvents,row);return{event:row,prior:revised};});}
    function currentRows(rows){var next={};rows.forEach(function(x){if(x.supersedesBehaviorEventId)next[x.supersedesBehaviorEventId]=x;});return rows.filter(function(x){var y=x,seen={};while(next[y.behaviorEventId]&&!seen[y.behaviorEventId]){seen[y.behaviorEventId]=true;y=next[y.behaviorEventId];}return y.behaviorEventId===x.behaviorEventId&&y.lifecycle==='active';});}
    async function studentProjection(input){var rows=await db.query(S.behaviorEvents,'by_student',input.studentId),current=currentRows(rows).filter(function(x){return !input.enrollmentId||x.enrollmentId===input.enrollmentId;}).sort(function(a,b){return b.occurredAt.localeCompare(a.occurredAt)||b.behaviorEventId.localeCompare(a.behaviorEventId);});return{studentId:input.studentId,enrollmentId:input.enrollmentId||null,current:clone(current),history:clone(rows.slice().sort(function(a,b){return a.createdAt.localeCompare(b.createdAt)||a.behaviorEventId.localeCompare(b.behaviorEventId);})),privateInstructorDocumentation:true,automaticGradeEffect:false};}
    async function classProjection(input){var rows=await db.query(S.behaviorEvents,'by_section',input.sectionId),current=currentRows(rows).filter(function(x){return !input.schoolDate||x.schoolDate===input.schoolDate;}).sort(function(a,b){return b.occurredAt.localeCompare(a.occurredAt)||a.studentId.localeCompare(b.studentId);});return{sectionId:input.sectionId,schoolDate:input.schoolDate||null,current:clone(current),privateInstructorDocumentation:true,automaticGradeEffect:false};}
    return{recordBehaviorEvent:record,correctBehaviorEvent:correct,studentProjection:studentProjection,classProjection:classProjection};
  }
  return{create:create};
}));
