/* Stage 14 P8 Workplace, Safety, and Behavior/Incident exclusive authority boundary. */
(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcWorkplaceSafetyBehaviorAuthorityAdapter=api;}(this,function(){
  'use strict';
  var V7='V7_ONLY',ISOLATED='V8_ISOLATED_VERIFICATION',ISOLATED_DB='arc_classroom_v8_p8_verification';
  var LEGACY_EVENT_MAP=Object.freeze({attire:'IMPROPER_ATTIRE',ppe:'MISSING_PPE',preparedness:'UNPREPARED',offtask:'OFF_TASK',cleanup:'FAILED_CLEANUP',toolcare:'POOR_TOOL_CARE',procedure:'PROCEDURE',repeatppe:'REPEATED_PPE',horseplay:'HORSEPLAY',misuse:'KNOWING_MISUSE',refusal:'REFUSED_INSTRUCTION',disruption:'SIGNIFICANT_DISRUPTION',serioussafety:'SERIOUS_SAFETY',endangerment:'INTENTIONAL_ENDANGERMENT',severemisuse:'SEVERE_MISUSE',fullperiodrefusal:'FULL_PERIOD_REFUSAL'});
  function fail(code,message,context){var e=new Error(message);e.code=code;e.context=context||{};throw e;}
  function copy(x){return x==null?x:JSON.parse(JSON.stringify(x));}
  function create(options){options=options||{};var state=options.authorityState||V7,databaseName=String(options.databaseName||''),storage=options.storage||null,projection=options.projection||null,workplace=options.workplace||null,behavior=options.behavior||null,competencyAdapter=options.competencyAdapter||null;
    if([V7,ISOLATED].indexOf(state)<0)fail('AUTHORITY_STATE_BLOCKED','Workplace/Safety/Behavior adapter refuses an unapproved authority state.');
    if(state===ISOLATED&&(databaseName!==ISOLATED_DB||!storage||!projection||!workplace||!behavior||!competencyAdapter))fail('ISOLATED_AUTHORITY_REQUIRED','P8 verification is hard-bound to its isolated IndexedDB authority.',{databaseName:databaseName});
    function legacy(action,payload,mutation){if(state!==V7)fail('LEGACY_AUTHORITY_BLOCKED','Schema 7 mutation is available only in V7_ONLY.',{action:action});if(typeof mutation!=='function')fail('LEGACY_MUTATION_REQUIRED','V7_ONLY requires exactly one explicit legacy mutation.',{action:action});return mutation(payload);}
    async function scoped(input){var view=await projection.fromV8(storage,{day:input.schoolDate||input.day,selectedSectionId:input.sectionId,currentPeriodCode:input.currentPeriodCode}),scope=view.scopeForStudent(input.studentId);if(!scope)fail('ACADEMIC_SCOPE_REQUIRED','P8 operations require the effective P4 Student scope.',{studentId:input.studentId});if(input.sectionId&&scope.sectionId!==input.sectionId)fail('ACADEMIC_SCOPE_MISMATCH','Requested Section differs from effective P4 academic scope.',{studentId:input.studentId,requested:input.sectionId,effective:scope.sectionId});return{view:view,scope:scope};}
    async function dayFor(input,c){var rows=await storage.query('workplace_days','by_student_enrollment_date',[input.studentId,c.scope.enrollmentId,input.schoolDate]),day=rows.find(function(x){return x.lifecycle==='active';});if(day)return day;return workplace.createWorkplaceDay({studentId:input.studentId,enrollmentId:c.scope.enrollmentId,schoolDate:input.schoolDate,applicabilityState:input.applicabilityState||'Applicable',applicabilitySource:input.applicabilitySource||'Explicit Instructor Authority',applicabilityContext:input.applicabilityContext||{sectionId:c.scope.sectionId}});}
    function eventType(input){var code=input.eventTypeCode||LEGACY_EVENT_MAP[input.legacyDeductionId];if(!code)fail('WORKPLACE_EVENT_TYPE_REQUIRED','A recognized Workplace event authority is required.');return code;}
    async function safetyEvidence(input,c){if(!input.qualification||!input.qualificationReason)fail('SAFETY_EVIDENCE_POLICY_REQUIRED','Safety Evidence requires explicit accepted qualification and reason authority.');var safety=await storage.read('safety_events',input.safetyEventId);if(!safety||safety.lifecycle!=='active'||safety.studentId!==input.studentId||safety.enrollmentId!==c.scope.enrollmentId)fail('SAFETY_AUTHORITY_REQUIRED','Active Safety authority does not match the P4 scope.');var source=await competencyAdapter.runIsolated('evidence-source',{studentId:input.studentId,schoolDate:input.schoolDate,sectionId:c.scope.sectionId,source:{sourceType:'Continuous Safety',occurredAt:safety.occurredAt,recordedAt:safety.recordedAt,recordedBy:safety.recordedBy,context:{safetyEventId:safety.safetyEventId,eventTypeCode:safety.eventTypeCode,severity:safety.severity}}});var record=await competencyAdapter.runIsolated('evidence-record',{studentId:input.studentId,schoolDate:input.schoolDate,sectionId:c.scope.sectionId,record:{sourceId:source.sourceId,competencyId:input.competencyId,competencyVersionId:input.competencyVersionId,strategyConfigId:input.strategyConfigId,demonstratedLevel:null,qualification:input.qualification,evidenceMode:'Habit/Continuous',qualificationReason:copy(input.qualificationReason),context:{safetyEventId:safety.safetyEventId}}});return{source:source,record:record,safetyEventId:safety.safetyEventId};}
    async function history(input,c){var values=await Promise.all([storage.query('workplace_days','by_student',input.studentId),storage.query('safety_events','by_student',input.studentId),behavior.studentProjection({studentId:input.studentId,enrollmentId:c.scope.enrollmentId})]),days=values[0].filter(function(x){return x.enrollmentId===c.scope.enrollmentId;}),safety=values[1].filter(function(x){return x.enrollmentId===c.scope.enrollmentId;}).sort(function(a,b){return String(b.occurredAt).localeCompare(String(a.occurredAt))||b.safetyEventId.localeCompare(a.safetyEventId);}),work=[];for(var i=0;i<days.length;i++)work.push({day:days[i],result:await workplace.deriveDailyWorkplace(days[i].workplaceDayId)});work.sort(function(a,b){return b.day.schoolDate.localeCompare(a.day.schoolDate);});return{studentScope:copy(c.scope),workplace:work,safety:copy(safety),behavior:values[2],unifiedStudentHistoryComplete:false,privateBehaviorDocumentation:true};}
    async function isolated(action,input){if(state!==ISOLATED)fail('V8_AUTHORITY_BLOCKED','v8 P8 execution is disabled while classroom authority is V7_ONLY.',{action:action});input=input||{};var c=await scoped(input),day,result;switch(action){
      case'workplace-status':day=await dayFor(input,c);return workplace.updateApplicability(day.workplaceDayId,day.revision,input.status==='present'?'Applicable':'Nonapplicable',input.reason||'Explicit instructor status',Object.assign({},input.context||{},{legacyStatus:input.status,sectionId:c.scope.sectionId}));
      case'workplace-event':day=await dayFor(input,c);return workplace.recordWorkplaceEvent({workplaceDayId:day.workplaceDayId,eventTypeCode:eventType(input),expectedDayRevision:day.revision,legitimateRepeat:input.legitimateRepeat===true,incidentKey:input.incidentKey||null,occurredAt:input.occurredAt,recordedAt:input.recordedAt,recordedBy:input.recordedBy,physicalContext:Object.assign({},input.physicalContext||{},{sectionId:c.scope.sectionId}),note:input.note});
      case'workplace-event-correct':return workplace.correctWorkplaceEvent(input.correction);
      case'workplace-positive':day=await dayFor(input,c);return workplace.addPositiveObservation({workplaceDayId:day.workplaceDayId,dimensionCode:input.dimensionCode,expectedDayRevision:day.revision,occurredAt:input.occurredAt,recordedAt:input.recordedAt,recordedBy:input.recordedBy,physicalContext:Object.assign({},input.physicalContext||{},{sectionId:c.scope.sectionId}),note:input.note});
      case'workplace-positive-correct':return workplace.correctPositiveObservation(input.correction);
      case'workplace-week':return workplace.deriveLiveWeek({studentId:input.studentId,enrollmentId:c.scope.enrollmentId,startDate:input.startDate,endDate:input.endDate});
      case'workplace-finalize':return workplace.finalizeWeek(Object.assign({},input,{enrollmentId:c.scope.enrollmentId}));
      case'workplace-gradebook-handoff':result=await storage.query('workplace_week_finalizations','by_student_week',[input.studentId,c.scope.enrollmentId,input.instructionalWeekId]);result=result.sort(function(a,b){return (b.chainRevision||0)-(a.chainRevision||0);})[0]||null;return{studentScope:copy(c.scope),weekFinalization:copy(result),gradebookWritePerformed:false,requiresLaterGradebookAuthority:true};
      case'safety-record':return workplace.recordSafetyEvent(Object.assign({},input,{enrollmentId:c.scope.enrollmentId}));
      case'safety-correct':return workplace.correctSafetyEvent(input.correction);
      case'safety-evidence':return safetyEvidence(input,c);
      case'behavior-record':return behavior.recordBehaviorEvent(Object.assign({},input,{enrollmentId:c.scope.enrollmentId,sectionId:c.scope.sectionId}));
      case'behavior-correct':return behavior.correctBehaviorEvent(input.correction);
      case'student-history':return history(input,c);
      default:fail('UNSUPPORTED_P8_ACTION','Unknown Workplace/Safety/Behavior action.',{action:action});
    }}
    return{authorityState:state,databaseName:state===ISOLATED?databaseName:null,runLegacy:legacy,runIsolated:isolated,eventTypeMap:LEGACY_EVENT_MAP,isAuthoritativeV8:false,dualWrite:false};
  }
  return{create:create,states:Object.freeze({V7_ONLY:V7,V8_ISOLATED_VERIFICATION:ISOLATED}),isolatedDatabaseName:ISOLATED_DB,eventTypeMap:LEGACY_EVENT_MAP};
}));
