/* Stage 14 P4 Student/Enrollment/Schedule Assignment authority boundary. */
(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcAcademicAuthorityAdapter=api;}(this,function(){
  'use strict';var V7='V7_ONLY',ISOLATED='V8_ISOLATED_VERIFICATION',ISOLATED_DB='arc_classroom_v8_p4_verification';
  function fail(code,message,context){var e=new Error(message);e.code=code;e.context=context||{};throw e;}
  function create(options){options=options||{};var state=options.authorityState||V7,databaseName=String(options.databaseName||''),academic=options.academic||null,projection=options.projection||null,storage=options.storage||null;if([V7,ISOLATED].indexOf(state)<0)fail('AUTHORITY_STATE_BLOCKED','Academic adapter refuses an unapproved authority state.');if(state===ISOLATED&&(databaseName!==ISOLATED_DB||!academic||!projection||!storage))fail('ISOLATED_AUTHORITY_REQUIRED','v8 academic verification is hard-bound to the isolated P4 database.',{databaseName:databaseName});
    function legacy(action,payload,mutation){if(state!==V7)fail('LEGACY_AUTHORITY_BLOCKED','Legacy mutation is available only in V7_ONLY.',{action:action});if(typeof mutation!=='function')fail('LEGACY_MUTATION_REQUIRED','V7_ONLY requires exactly one explicit legacy mutation.',{action:action});return mutation(payload);}
    async function isolated(action,payload){if(state!==ISOLATED)fail('V8_AUTHORITY_BLOCKED','v8 academic execution is disabled while classroom authority is V7_ONLY.',{action:action});switch(action){case'create-student-placement':return academic.createStudentPlacement(payload);case'edit-student':return academic.updateStudent(payload.studentId,payload.expectedRevision,payload.changes);case'archive-student':return academic.archiveStudent(payload.studentId,payload.expectedRevision);case'drop':return academic.dropStudentEnrollment(payload);case'reenroll':return academic.reenrollStudent(payload);case'move':return academic.moveEnrollment(payload);case'projection':return projection.fromV8(storage,payload);default:fail('UNSUPPORTED_ACADEMIC_ACTION','Unknown academic action.',{action:action});}}
    return{authorityState:state,databaseName:state===ISOLATED?databaseName:null,runLegacy:legacy,runIsolated:isolated,isAuthoritativeV8:false,dualWrite:false};}
  return{create:create,states:Object.freeze({V7_ONLY:V7,V8_ISOLATED_VERIFICATION:ISOLATED}),isolatedDatabaseName:ISOLATED_DB};
}));
