/* Stage 14 P6 Project, Activity, and Technical authority boundary. */
(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcProjectTechnicalAuthorityAdapter=api;}(this,function(){
  'use strict';
  var V7='V7_ONLY',ISOLATED='V8_ISOLATED_VERIFICATION',ISOLATED_DB='arc_classroom_v8_p6_verification';
  function fail(code,message,context){var e=new Error(message);e.code=code;e.context=context||{};throw e;}
  function create(options){options=options||{};var state=options.authorityState||V7,databaseName=String(options.databaseName||''),storage=options.storage||null,projection=options.projection||null,activity=options.activity||null,project=options.project||null,assessment=options.assessment||null;if([V7,ISOLATED].indexOf(state)<0)fail('AUTHORITY_STATE_BLOCKED','Project/Technical adapter refuses an unapproved authority state.');if(state===ISOLATED&&(databaseName!==ISOLATED_DB||!storage||!projection||!activity||!project||!assessment))fail('ISOLATED_AUTHORITY_REQUIRED','v8 Project/Technical verification is hard-bound to the isolated P6 database.',{databaseName:databaseName});
    function legacy(action,payload,mutation){if(state!==V7)fail('LEGACY_AUTHORITY_BLOCKED','Legacy mutation is available only in V7_ONLY.',{action:action});if(typeof mutation!=='function')fail('LEGACY_MUTATION_REQUIRED','V7_ONLY requires exactly one explicit legacy mutation.',{action:action});return mutation(payload);}
    async function view(payload){return projection.fromV8(storage,{day:payload.schoolDate||payload.assignedDate||payload.day,selectedSectionId:payload.sectionId,currentPeriodCode:payload.currentPeriodCode});}
    async function scopes(payload){var v=await view(payload),ids=payload.studentIds||[payload.studentId],out=ids.map(function(id){var s=v.scopeForStudent(id);if(!s)fail('ACADEMIC_SCOPE_REQUIRED','Project and Technical operations require the effective P4 Student scope.',{studentId:id});if(payload.sectionId&&s.sectionId!==payload.sectionId)fail('ACADEMIC_SCOPE_MISMATCH','Requested Section differs from effective P4 academic scope.',{studentId:id});return s;});return{view:v,scopes:out};}
    async function assign(input,isProject){var x=await scopes(input),result=await activity.assign({versionId:input.versionId,sectionId:input.sectionId||x.scopes[0].sectionId,assignedDate:input.assignedDate,assignedAt:input.assignedAt,assignedBy:input.assignedBy,origin:input.origin||((x.scopes.length>1)?'Selected Students':'Individual'),recipients:x.scopes.map(function(s){return{studentId:s.studentId,enrollmentId:s.enrollmentId};}),academicContext:{schoolYearId:x.scopes[0].schoolYearId,semesterId:x.scopes[0].semesterId,sectionId:input.sectionId||x.scopes[0].sectionId}}),projects=[];if(isProject){for(var i=0;i<result.studentActivities.length;i++)projects.push(await project.createProject({studentActivityId:result.studentActivities[i].studentActivityId,authorizeAdditionalActive:!!input.authorizeAdditionalActive,startedAt:input.startedAt,authorizedBy:input.assignedBy,pacingMetadata:input.pacingMetadata||{}}));}return{assignment:result.assignment,studentActivities:result.studentActivities,projects:projects,academicScopes:x.scopes};}
    async function projectProjection(input){var x=await scopes(input),op=await project.operationalState(input.projectId),scope=x.scopes[0],shared={studentScope:scope,project:op.project,activeBuild:op.activeBuild,checkpointStates:op.checkpointStates,currentCheckpoint:op.currentCheckpoint,waitingForReview:op.waitingForReview,manualNeed:op.manualNeed,displayNeed:op.displayNeed,eventCount:op.eventCount};return{studentProject:shared,fastRoster:shared,classForecast:shared,boothProjectContext:shared};}
    async function isolated(action,input){if(state!==ISOLATED)fail('V8_AUTHORITY_BLOCKED','v8 Project/Technical execution is disabled while classroom authority is V7_ONLY.',{action:action});input=input||{};switch(action){case'project-definition-create':{var pd=await activity.createDefinition({type:'Project',title:input.title,courseIds:input.courseIds});var pv=await activity.createVersion(Object.assign({},input.version,{definitionId:pd.definitionId}));return{definition:pd,version:pv};}case'technical-definition-create':{var type=input.activityType==='Test'?'Test':'Technical Assignment',td=await activity.createDefinition({type:type,title:input.title,courseIds:input.courseIds});var tv=await activity.createVersion(Object.assign({},input.version,{definitionId:td.definitionId,pointsPossible:input.pointsPossible}));return{definition:td,version:tv};}case'project-assign':return assign(input,true);case'technical-assign':return assign(input,false);case'attempt-start':await scopes(input);return activity.createAttempt(input);case'activity-transition':await scopes(input);return activity.transitionStudentActivity(input.studentActivityId,input.expectedRevision,input.workflowState);case'project-checkpoint':await scopes(input);return project.appendCheckpointEvent(input);case'project-need':await scopes(input);return project.setManualNeed(input);case'project-workflow':await scopes(input);return project.transitionProject(input.projectId,input.expectedRevision,input.workflowState,input.context);case'project-rubric':await scopes(input);return project.recordRubric(input);case'project-finalize':await scopes(input);return project.finalizeProject(input);case'project-projection':return projectProjection(input);case'technical-finalize-assessment':await scopes(input);return assessment.finalizeActivityAssessment(input);case'technical-gradebook-handoff':await scopes(input);return assessment.createAssessmentResultFromActivity(input);case'project-gradebook-handoff':await scopes(input);return assessment.createAssessmentResultFromProject(input);default:fail('UNSUPPORTED_PROJECT_TECHNICAL_ACTION','Unknown Project/Technical action.',{action:action});}}
    return{authorityState:state,databaseName:state===ISOLATED?databaseName:null,runLegacy:legacy,runIsolated:isolated,isAuthoritativeV8:false,dualWrite:false};
  }
  return{create:create,states:Object.freeze({V7_ONLY:V7,V8_ISOLATED_VERIFICATION:ISOLATED}),isolatedDatabaseName:ISOLATED_DB};
}));
