/* ARC Stage 14 P2 academic-administration authority. No UI or Schema v7 access. */
(function(root,factory){
  var req=typeof require==='function'?require:null;
  var api=factory(root.ArcV8Storage||(req&&req('./arc_v8_storage')),
    root.ArcV8BackupRecovery||(req&&req('./arc_v8_backup_recovery')));
  if(typeof module==='object'&&module.exports)module.exports=api;
  else root.ArcV8AcademicAdministration=api;
}(this,function(Storage,Backup){
  'use strict';
  var S=Storage.STORES;
  var PREFIX='academic-admin:';
  var KINDS=Object.freeze({
    bell:'bell-schedule',mode:'weekly-schedule-mode',day:'calendar-day',
    event:'calendar-event',override:'date-override',placement:'section-placement',audit:'audit'
  });
  var DAYS=Object.freeze(['sunday','monday','tuesday','wednesday','thursday','friday','saturday']);
  function fail(code,message,context){throw new Storage.StorageError(code,message,context||{});}
  function clone(value){return value==null?value:structuredClone(value);}
  function text(value){return String(value==null?'':value).trim();}
  function date(value,field,nullable){value=text(value);if(nullable&&!value)return null;var parsed=new Date(value+'T00:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(value)||isNaN(parsed.getTime())||parsed.toISOString().slice(0,10)!==value)fail('INVALID_DATE','Invalid academic-administration date.',{field:field,value:value});return value;}
  function time(value,field){value=text(value);if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(value))fail('INVALID_TIME','Time must use 24-hour HH:MM.',{field:field,value:value});return value;}
  function range(from,to,prefix){from=date(from,prefix+'From');to=date(to,prefix+'To',true);if(to&&to<from)fail('INVALID_DATE_RANGE','End date precedes start date.',{from:from,to:to});return{from:from,to:to};}
  function overlaps(a,b){return a.effectiveFrom<=(b.effectiveTo||'9999-12-31')&&b.effectiveFrom<=(a.effectiveTo||'9999-12-31');}
  function activeOn(row,day){return row.lifecycle==='active'&&row.effectiveFrom<=day&&(!row.effectiveTo||row.effectiveTo>=day);}
  function sortBy(fields){return function(a,b){for(var i=0;i<fields.length;i++){var x=String(a[fields[i]]==null?'':a[fields[i]]),y=String(b[fields[i]]==null?'':b[fields[i]]);if(x!==y)return x.localeCompare(y);}return String(a.id).localeCompare(String(b.id));};}
  function create(options){
    options=options||{};
    var storage=options.storage,actor=text(options.actor),now=options.now||function(){return new Date().toISOString();};
    var backup=options.backup||null,preparedRecovery=null;
    if(!storage||!actor)throw Error('Academic Administration requires storage and operator authority.');
    function id(kind){return PREFIX+kind+':'+storage.generateId();}
    function stamp(kind,input){var at=now();return Object.assign({},clone(input),{id:id(kind),authorityType:kind,lifecycle:'active',revision:1,createdAt:at,createdBy:actor,updatedAt:at,updatedBy:actor});}
    async function rows(kind,tx){var all=await (tx||storage).query(S.infrastructure);return all.filter(function(x){return x.authorityType===kind;});}
    function requireReason(reason){reason=text(reason);if(!reason)fail('REASON_REQUIRED','A correction reason is required.');return reason;}
    async function audit(tx,operation,target,before,after,reason,recovery){var at=now(),row={id:id(KINDS.audit),authorityType:KINDS.audit,operation:operation,targetType:target.authorityType||target.recordType,targetId:target.id||target.schoolYearId||target.semesterId||target.gradingPeriodId||target.sectionId,before:clone(before),after:clone(after),reason:reason,operator:actor,occurredAt:at,recovery:recovery?clone(recovery):null,lifecycle:'active',revision:1,createdAt:at,createdBy:actor,updatedAt:at,updatedBy:actor};await tx.add(S.infrastructure,row);return row;}
    async function prepareRecovery(){if(!backup||typeof backup.exportBackup!=='function')fail('RECOVERY_SERVICE_REQUIRED','A complete v8 backup service is required before correction.');var result=await backup.exportBackup();if(!result.verification||!result.verification.verified)fail('RECOVERY_VERIFICATION_FAILED','Academic correction recovery package did not verify.',{verification:result.verification||null});preparedRecovery={token:storage.generateId(),filename:result.filename,checksum:result.package.manifest.packageIntegrity.checksum,verified:true,preparedAt:now(),text:result.text};return{token:preparedRecovery.token,filename:preparedRecovery.filename,checksum:preparedRecovery.checksum,verified:true,preparedAt:preparedRecovery.preparedAt,recoveryPackage:{filename:preparedRecovery.filename,mimeType:'application/json',text:preparedRecovery.text}};}
    function consumeRecovery(token){if(!preparedRecovery||token!==preparedRecovery.token)fail('VERIFIED_RECOVERY_REQUIRED','Use the exact unconsumed verified recovery token for this correction.');var evidence={filename:preparedRecovery.filename,checksum:preparedRecovery.checksum,verified:true,preparedAt:preparedRecovery.preparedAt};preparedRecovery=null;return evidence;}
    function normalizePeriods(input){var seen={},periods=(Array.isArray(input)?input:[]).map(function(p,i){var code=text(p.code),kind=text(p.kind)||'Instructional',start=time(p.startTime,'periods['+i+'].startTime'),end=time(p.endTime,'periods['+i+'].endTime');if(!code||seen[code]||!['Instructional','Planning'].includes(kind)||end<=start)fail('INVALID_BELL_SCHEDULE','Bell periods require unique codes, ordered times, and Instructional or Planning kind.',{index:i,code:code});seen[code]=true;return{code:code,label:text(p.label)||code,startTime:start,endTime:end,kind:kind,order:Number.isFinite(Number(p.order))?Number(p.order):i};}).sort(sortBy(['startTime','order','code']));for(var i=1;i<periods.length;i++)if(periods[i].startTime<periods[i-1].endTime)fail('OVERLAPPING_BELL_PERIOD','Bell periods cannot overlap.',{prior:periods[i-1].code,current:periods[i].code});if(!periods.length)fail('INVALID_BELL_SCHEDULE','At least one bell period is required.');return periods;}
    async function createBellSchedule(input){var record=stamp(KINDS.bell,{name:text(input.name),periods:normalizePeriods(input.periods)});if(!record.name)fail('INVALID_BELL_SCHEDULE','Bell schedule name is required.');await storage.add(S.infrastructure,record);return record;}
    async function createScheduleMode(input){var r=range(input.effectiveFrom,input.effectiveTo,'effective'),map={};for(var d of DAYS){var value=input.week&&input.week[d];if(value!=null&&value!==''){var bell=await storage.read(S.infrastructure,value);if(!bell||bell.authorityType!==KINDS.bell||bell.lifecycle!=='active')fail('REFERENCE_NOT_FOUND','Weekly schedule mode references an unavailable Bell Schedule.',{day:d,bellScheduleId:value});map[d]=value;}else map[d]=null;}var record=stamp(KINDS.mode,{name:text(input.name),effectiveFrom:r.from,effectiveTo:r.to,week:map,isDefault:input.isDefault!==false});if(!record.name)fail('INVALID_SCHEDULE_MODE','Schedule mode name is required.');await storage.transaction(S.infrastructure,async function(tx){var existing=await rows(KINDS.mode,tx);if(record.isDefault&&existing.some(function(x){return x.id!==record.id&&x.lifecycle==='active'&&x.isDefault&&overlaps(x,record);}))fail('OVERLAPPING_DEFAULT_MODE','Default weekly schedule modes cannot overlap.',{});await tx.add(S.infrastructure,record);});return record;}
    async function createCalendarDay(input){var schoolDate=date(input.schoolDate,'schoolDate'),type=text(input.dayType);if(!['Instructional','Noninstructional'].includes(type))fail('INVALID_CALENDAR_DAY','Calendar day must be Instructional or Noninstructional.');var record=stamp(KINDS.day,{schoolDate:schoolDate,dayType:type,label:text(input.label),reason:text(input.reason)});await storage.transaction(S.infrastructure,async function(tx){if((await rows(KINDS.day,tx)).some(function(x){return x.lifecycle==='active'&&x.schoolDate===schoolDate;}))fail('DUPLICATE_CALENDAR_DAY','Only one active calendar authority may exist per date.',{schoolDate:schoolDate});await tx.add(S.infrastructure,record);});return record;}
    async function createCalendarEvent(input){var r=range(input.startDate,input.endDate,'event'),record=stamp(KINDS.event,{label:text(input.label),startDate:r.from,endDate:r.to||r.from,eventType:text(input.eventType)||'Information',note:text(input.note)});if(!record.label)fail('INVALID_CALENDAR_EVENT','Calendar event label is required.');await storage.add(S.infrastructure,record);return record;}
    async function createDateOverride(input){var schoolDate=date(input.schoolDate,'schoolDate'),bellId=input.bellScheduleId||null,modeId=input.scheduleModeId||null;if(!text(input.reason))fail('REASON_REQUIRED','Date override reason is required.');if(bellId){var bell=await storage.read(S.infrastructure,bellId);if(!bell||bell.authorityType!==KINDS.bell||bell.lifecycle!=='active')fail('REFERENCE_NOT_FOUND','Date override Bell Schedule does not exist.');}if(modeId){var mode=await storage.read(S.infrastructure,modeId);if(!mode||mode.authorityType!==KINDS.mode||mode.lifecycle!=='active')fail('REFERENCE_NOT_FOUND','Date override Schedule Mode does not exist.');}var type=input.dayType==null?null:text(input.dayType);if(type&&!['Instructional','Noninstructional'].includes(type))fail('INVALID_CALENDAR_DAY','Override day type is invalid.');var record=stamp(KINDS.override,{schoolDate:schoolDate,bellScheduleId:bellId,scheduleModeId:modeId,dayType:type,label:text(input.label),reason:text(input.reason)});await storage.transaction(S.infrastructure,async function(tx){if((await rows(KINDS.override,tx)).some(function(x){return x.lifecycle==='active'&&x.schoolDate===schoolDate;}))fail('DUPLICATE_DATE_OVERRIDE','Only one active override may exist per date.',{schoolDate:schoolDate});await tx.add(S.infrastructure,record);});return record;}
    async function createSectionPlacement(input){var section=await storage.read(S.sections,input.sectionId);if(!section)fail('REFERENCE_NOT_FOUND','Section does not exist.',{sectionId:input.sectionId});var r=range(input.effectiveFrom,input.effectiveTo,'effective'),semesterId=input.semesterId||null,semester=semesterId&&await storage.read(S.semesters,semesterId);if(semesterId&&(!semester||semester.schoolYearId!==section.schoolYearId))fail('ACADEMIC_SCOPE_MISMATCH','Placement Semester and Section School Year disagree.');var year=await storage.read(S.schoolYears,section.schoolYearId);if(!year||r.from<year.startDate||(r.to&&r.to>year.endDate)||(semester&&(r.from<semester.startDate||(r.to&&r.to>semester.endDate))))fail('ACADEMIC_DATE_OUT_OF_RANGE','Section placement dates must remain in their academic scope.');var bell=await storage.read(S.infrastructure,input.bellScheduleId);if(!bell||bell.authorityType!==KINDS.bell||bell.lifecycle!=='active'||!bell.periods.some(function(x){return x.code===text(input.periodCode);}))fail('REFERENCE_NOT_FOUND','Placement requires an active Bell Schedule and existing period code.');var record=stamp(KINDS.placement,{sectionId:section.sectionId,schoolYearId:section.schoolYearId,semesterId:semesterId,effectiveFrom:r.from,effectiveTo:r.to,bellScheduleId:bell.id,periodCode:text(input.periodCode),scheduleContext:input.scheduleContext&&typeof input.scheduleContext==='object'?clone(input.scheduleContext):null,reason:text(input.reason)});await storage.transaction(S.infrastructure,async function(tx){var existing=await rows(KINDS.placement,tx);if(existing.some(function(x){return x.lifecycle==='active'&&x.sectionId===section.sectionId&&overlaps(x,record);}))fail('OVERLAPPING_SECTION_PLACEMENT','A Section cannot have overlapping effective placements.');await tx.add(S.infrastructure,record);});return record;}
    async function validateAuthorityCorrection(tx,current,next){var all=await rows(current.authorityType,tx),authorityRows=await tx.query(S.infrastructure);if(current.authorityType===KINDS.bell){next.name=text(next.name);next.periods=normalizePeriods(next.periods);if(!next.name)fail('INVALID_BELL_SCHEDULE','Bell schedule name is required.');var referencedPlacements=authorityRows.filter(function(x){return x.authorityType===KINDS.placement&&x.lifecycle==='active'&&x.bellScheduleId===next.id;}),referencedModes=authorityRows.filter(function(x){return x.authorityType===KINDS.mode&&x.lifecycle==='active'&&Object.values(x.week||{}).includes(next.id);});if(next.lifecycle!=='active'&&(referencedPlacements.length||referencedModes.length))fail('AUTHORITY_IN_USE','An active schedule or placement still references this Bell Schedule.');if((referencedPlacements.length||referencedModes.length)&&JSON.stringify(next.periods)!==JSON.stringify(current.periods))fail('HISTORICAL_AUTHORITY_IMMUTABLE','Create a new Bell Schedule and effective mode/placement instead of rewriting used period truth.');}
      if(current.authorityType===KINDS.mode){var mr=range(next.effectiveFrom,next.effectiveTo,'effective');next.name=text(next.name);next.effectiveFrom=mr.from;next.effectiveTo=mr.to;if(!next.name)fail('INVALID_SCHEDULE_MODE','Schedule mode name is required.');for(var d of DAYS){var bellId=next.week&&next.week[d];if(bellId){var bell=await tx.get(S.infrastructure,bellId);if(!bell||bell.authorityType!==KINDS.bell||bell.lifecycle!=='active')fail('REFERENCE_NOT_FOUND','Weekly schedule mode references an unavailable Bell Schedule.',{day:d,bellScheduleId:bellId});}}if(next.isDefault&&all.some(function(x){return x.id!==next.id&&x.lifecycle==='active'&&x.isDefault&&overlaps(x,next);}))fail('OVERLAPPING_DEFAULT_MODE','Default weekly schedule modes cannot overlap.');}
      if(current.authorityType===KINDS.day){next.schoolDate=date(next.schoolDate,'schoolDate');if(!['Instructional','Noninstructional'].includes(next.dayType))fail('INVALID_CALENDAR_DAY','Calendar day must be Instructional or Noninstructional.');if(all.some(function(x){return x.id!==next.id&&x.lifecycle==='active'&&x.schoolDate===next.schoolDate;}))fail('DUPLICATE_CALENDAR_DAY','Only one active calendar authority may exist per date.');}
      if(current.authorityType===KINDS.event){var er=range(next.startDate,next.endDate,'event');next.startDate=er.from;next.endDate=er.to||er.from;next.label=text(next.label);if(!next.label)fail('INVALID_CALENDAR_EVENT','Calendar event label is required.');}
      if(current.authorityType===KINDS.override){next.schoolDate=date(next.schoolDate,'schoolDate');requireReason(next.reason);if(next.dayType&&!['Instructional','Noninstructional'].includes(next.dayType))fail('INVALID_CALENDAR_DAY','Override day type is invalid.');for(var ref of [[next.bellScheduleId,KINDS.bell],[next.scheduleModeId,KINDS.mode]])if(ref[0]){var authority=await tx.get(S.infrastructure,ref[0]);if(!authority||authority.authorityType!==ref[1]||authority.lifecycle!=='active')fail('REFERENCE_NOT_FOUND','Date override references unavailable schedule authority.');}if(all.some(function(x){return x.id!==next.id&&x.lifecycle==='active'&&x.schoolDate===next.schoolDate;}))fail('DUPLICATE_DATE_OVERRIDE','Only one active override may exist per date.');}
      if(current.authorityType===KINDS.placement){var section=await tx.get(S.sections,next.sectionId),year=section&&await tx.get(S.schoolYears,section.schoolYearId),semester=next.semesterId&&await tx.get(S.semesters,next.semesterId),pr=range(next.effectiveFrom,next.effectiveTo,'effective'),bellRow=await tx.get(S.infrastructure,next.bellScheduleId);if(!section||!year||next.schoolYearId!==section.schoolYearId||(next.semesterId&&(!semester||semester.schoolYearId!==section.schoolYearId)))fail('ACADEMIC_SCOPE_MISMATCH','Section placement academic scope is invalid.');if(pr.from<year.startDate||(pr.to&&pr.to>year.endDate)||(semester&&(pr.from<semester.startDate||(pr.to&&pr.to>semester.endDate))))fail('ACADEMIC_DATE_OUT_OF_RANGE','Section placement dates must remain in their academic scope.');if(!bellRow||bellRow.authorityType!==KINDS.bell||bellRow.lifecycle!=='active'||!bellRow.periods.some(function(x){return x.code===text(next.periodCode);}))fail('REFERENCE_NOT_FOUND','Placement period must exist in an active Bell Schedule.');next.effectiveFrom=pr.from;next.effectiveTo=pr.to;if(all.some(function(x){return x.id!==next.id&&x.lifecycle==='active'&&x.sectionId===next.sectionId&&overlaps(x,next);}))fail('OVERLAPPING_SECTION_PLACEMENT','A Section cannot have overlapping effective placements.');}
      return next;}
    async function reviseAuthority(idValue,expectedRevision,changes,reason,recoveryToken){var recovery=consumeRecovery(recoveryToken),allowed=['name','periods','week','effectiveFrom','effectiveTo','isDefault','schoolDate','dayType','label','eventType','note','reason','bellScheduleId','scheduleModeId','periodCode','scheduleContext','lifecycle'];for(var requested of Object.keys(changes||{}))if(!allowed.includes(requested))fail('INVALID_CORRECTION_FIELD','Correction attempted to change an unsupported or immutable field.',{field:requested});return storage.transaction([S.infrastructure,S.sections,S.schoolYears,S.semesters],async function(tx){var current=await tx.get(S.infrastructure,idValue);if(!current||!Object.values(KINDS).includes(current.authorityType)||current.authorityType===KINDS.audit)fail('NOT_FOUND','Academic-administration authority was not found.');if(current.revision!==expectedRevision)fail('WRITE_CONFLICT','Academic-administration authority changed after it was read.',{expectedRevision:expectedRevision,actualRevision:current.revision});var next=clone(current);for(var key of allowed)if(Object.prototype.hasOwnProperty.call(changes,key))next[key]=clone(changes[key]);next=await validateAuthorityCorrection(tx,current,next);next.revision=current.revision+1;next.updatedAt=now();next.updatedBy=actor;await tx.put(S.infrastructure,next);var event=await audit(tx,'correct',current,current,next,requireReason(reason),recovery);return{record:next,audit:event};});}
    async function correctAcademic(store,idField,idValue,expectedRevision,changes,reason,recoveryToken){var recovery=consumeRecovery(recoveryToken),reasonText=requireReason(reason),allowed=store===S.schoolYears?['label','startDate','endDate','lifecycle']:['code','label','startDate','endDate','order','lifecycle'];for(var requested of Object.keys(changes||{}))if(!allowed.includes(requested))fail('INVALID_CORRECTION_FIELD','Correction attempted to change an unsupported or immutable field.',{field:requested});return storage.transaction([S.schoolYears,S.semesters,S.gradingPeriods,S.infrastructure],async function(tx){var current=await tx.get(store,idValue);if(!current)fail('NOT_FOUND','Academic record was not found.',{store:store,id:idValue});if(current.revision!==expectedRevision)fail('WRITE_CONFLICT','Academic record changed after it was read.',{expectedRevision:expectedRevision,actualRevision:current.revision});var next=Object.assign({},current,clone(changes));if(store===S.schoolYears){var yr=range(next.startDate,next.endDate,'schoolYear'),semesters=await tx.query(S.semesters,'by_school_year',idValue);if(!yr.to)fail('INVALID_DATE','School Year end date is required.');next.startDate=yr.from;next.endDate=yr.to;if(semesters.some(function(x){return x.lifecycle==='active'&&(x.startDate<yr.from||x.endDate>yr.to);}))fail('ACADEMIC_DATE_OUT_OF_RANGE','School Year correction would invalidate a Semester.');}if(store===S.semesters){var year=await tx.get(S.schoolYears,next.schoolYearId),sr=range(next.startDate,next.endDate,'semester'),periods=await tx.query(S.gradingPeriods,'by_semester',idValue);if(!sr.to||!year||sr.from<year.startDate||sr.to>year.endDate||periods.some(function(x){return x.lifecycle==='active'&&(x.startDate<sr.from||x.endDate>sr.to);}))fail('ACADEMIC_DATE_OUT_OF_RANGE','Semester correction would invalidate its School Year or Grading Periods.');next.startDate=sr.from;next.endDate=sr.to;}if(store===S.gradingPeriods){var semester=await tx.get(S.semesters,next.semesterId),pr=range(next.startDate,next.endDate,'gradingPeriod');if(!pr.to||!semester||next.schoolYearId!==semester.schoolYearId||pr.from<semester.startDate||pr.to>semester.endDate)fail('ACADEMIC_DATE_OUT_OF_RANGE','Grading Period correction must remain in its Semester.');next.startDate=pr.from;next.endDate=pr.to;}next.revision=current.revision+1;next.updatedAt=now();next.updatedBy=actor;await tx.put(store,next);var event=await audit(tx,'correct',{recordType:store,[idField]:idValue},current,next,reasonText,recovery);return{record:next,audit:event};});}
    async function scheduleForDate(day){day=date(day,'date');var all=await storage.query(S.infrastructure),active=all.filter(function(x){return x.lifecycle==='active';}),calendar=active.find(function(x){return x.authorityType===KINDS.day&&x.schoolDate===day;})||null,override=active.find(function(x){return x.authorityType===KINDS.override&&x.schoolDate===day;})||null,modes=active.filter(function(x){return x.authorityType===KINDS.mode&&x.isDefault&&activeOn(x,day);}).sort(sortBy(['effectiveFrom','id'])),mode=null;if(override&&override.scheduleModeId)mode=active.find(function(x){return x.id===override.scheduleModeId;})||null;else mode=modes[modes.length-1]||null;var weekday=DAYS[new Date(day+'T00:00:00Z').getUTCDay()],bellId=override&&override.bellScheduleId||(mode&&mode.week[weekday])||null,bell=bellId&&active.find(function(x){return x.id===bellId;})||null,dayType=override&&override.dayType||calendar&&calendar.dayType||(bell?'Instructional':'Noninstructional'),events=active.filter(function(x){return x.authorityType===KINDS.event&&x.startDate<=day&&x.endDate>=day;}).sort(sortBy(['startDate','label']));return{schoolDate:day,dayType:dayType,calendarDay:calendar,dateOverride:override,scheduleMode:mode,bellSchedule:dayType==='Noninstructional'?null:bell,periods:dayType==='Noninstructional'||!bell?[]:clone(bell.periods),events:events};}
    async function placementForSection(sectionId,day){day=date(day,'date');var matches=(await rows(KINDS.placement)).filter(function(x){return x.sectionId===sectionId&&activeOn(x,day);}).sort(sortBy(['effectiveFrom','id']));return matches[matches.length-1]||null;}
    async function summary(){var all=await storage.query(S.infrastructure),out={bellSchedules:[],scheduleModes:[],calendarDays:[],calendarEvents:[],dateOverrides:[],sectionPlacements:[],audit:[]};var map={[KINDS.bell]:'bellSchedules',[KINDS.mode]:'scheduleModes',[KINDS.day]:'calendarDays',[KINDS.event]:'calendarEvents',[KINDS.override]:'dateOverrides',[KINDS.placement]:'sectionPlacements',[KINDS.audit]:'audit'};for(var row of all)if(map[row.authorityType])out[map[row.authorityType]].push(row);for(var key of Object.keys(out))out[key].sort(sortBy(['schoolDate','effectiveFrom','startDate','name','label','occurredAt','id']));return clone(out);}
    return{prepareRecovery:prepareRecovery,createBellSchedule:createBellSchedule,createScheduleMode:createScheduleMode,createCalendarDay:createCalendarDay,createCalendarEvent:createCalendarEvent,createDateOverride:createDateOverride,createSectionPlacement:createSectionPlacement,correctAuthority:reviseAuthority,correctSchoolYear:function(idValue,revision,changes,reason,token){return correctAcademic(S.schoolYears,'schoolYearId',idValue,revision,changes,reason,token);},correctSemester:function(idValue,revision,changes,reason,token){return correctAcademic(S.semesters,'semesterId',idValue,revision,changes,reason,token);},correctGradingPeriod:function(idValue,revision,changes,reason,token){return correctAcademic(S.gradingPeriods,'gradingPeriodId',idValue,revision,changes,reason,token);},scheduleForDate:scheduleForDate,placementForSection:placementForSection,summary:summary,kinds:KINDS,days:DAYS};
  }
  return{create:create,KINDS:KINDS,DAYS:DAYS};
}));
