/* Shared read-only effective Section context. Section static period/Semester fields are bootstrap metadata only. */
(function(root,factory){var api=factory(root.ArcV8Storage||(typeof require==='function'?require('./arc_v8_storage'):null));if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcEffectiveSectionContext=api;}(this,function(Storage){
  'use strict';
  var S=Storage.STORES,PLACEMENT='section-placement';
  function fail(code,message,context){if(Storage&&Storage.StorageError)throw new Storage.StorageError(code,message,context||{});var e=new Error(message);e.code=code;e.context=context||{};throw e;}
  function active(row,day){return row&&row.lifecycle==='active'&&row.effectiveFrom<=day&&(!row.effectiveTo||row.effectiveTo>=day);}
  function copy(x){return x==null?x:JSON.parse(JSON.stringify(x));}
  function scopeFailure(section,placement,reason){fail('SECTION_PLACEMENT_SCOPE_MISMATCH','Effective Section placement disagrees with academic authority.',{sectionId:section&&section.sectionId||placement.sectionId,placementId:placement.id,reason:reason});}
  function validateScope(section,placement,years,semesters,periodAuthority,currentDate){var year=(years||[]).find(function(x){return x.schoolYearId===placement.schoolYearId;})||null,semester=placement.semesterId?(semesters||[]).find(function(x){return x.semesterId===placement.semesterId;})||null:null,periodCode=String(placement.periodCode==null?'':placement.periodCode).trim();if(!year)scopeFailure(section,placement,'MISSING_SCHOOL_YEAR');if(placement.schoolYearId!==section.schoolYearId)scopeFailure(section,placement,'SECTION_SCHOOL_YEAR_MISMATCH');if(placement.semesterId&&!semester)scopeFailure(section,placement,'MISSING_SEMESTER');if(semester&&semester.schoolYearId!==placement.schoolYearId)scopeFailure(section,placement,'SEMESTER_SCHOOL_YEAR_MISMATCH');if(!placement.effectiveFrom||!placement.effectiveTo||placement.effectiveTo<placement.effectiveFrom||placement.effectiveFrom<year.startDate||placement.effectiveTo>year.endDate)scopeFailure(section,placement,'PLACEMENT_OUTSIDE_SCHOOL_YEAR');if(semester&&(placement.effectiveFrom<semester.startDate||placement.effectiveTo>semester.endDate))scopeFailure(section,placement,'PLACEMENT_OUTSIDE_SEMESTER');if(!periodCode)scopeFailure(section,placement,'MISSING_PERIOD_CODE');var codes=periodAuthority&&(placement.effectiveTo<currentDate?periodAuthority.retained:periodAuthority.active);if(codes&&codes.indexOf(periodCode)<0)scopeFailure(section,placement,'UNKNOWN_PERIOD_CODE');return{year:year,semester:semester,periodCode:periodCode};}
  function resolve(input){input=input||{};var sectionId=String(input.sectionId||''),day=String(input.schoolDate||input.day||''),currentDate=String(input.currentDate||new Date().toISOString().slice(0,10)),sections=input.sections||[],placements=(input.sectionPlacements||[]).filter(function(x){return x.authorityType===PLACEMENT&&x.sectionId===sectionId&&active(x,day);}),section=sections.find(function(x){return x.sectionId===sectionId;})||input.section||null,periodAuthority=input.periodAuthority||input.knownPeriodCodes&&{active:input.knownPeriodCodes,retained:input.knownPeriodCodes}||null;if(!section)return null;if(placements.length>1)fail('AMBIGUOUS_SECTION_PLACEMENT','More than one effective Section placement exists for the requested date.',{sectionId:sectionId,schoolDate:day,placementIds:placements.map(function(x){return x.id;})});if(!placements.length)return null;var placement=placements[0],scope=validateScope(section,placement,input.schoolYears||[],input.semesters||[],periodAuthority,currentDate);return{section:copy(section),sectionId:section.sectionId,courseId:section.courseId,schoolYearId:placement.schoolYearId,semesterId:placement.semesterId||null,periodCode:scope.periodCode,placementId:placement.id,effectiveFrom:placement.effectiveFrom,effectiveTo:placement.effectiveTo};}
  async function read(reader,store,key){return reader.get?reader.get(store,key):reader.read(store,key);}
  async function fromReader(reader,input){var section=await read(reader,S.sections,input.sectionId);if(!section)return null;var rows=await reader.query(S.infrastructure),placementRows=rows.filter(function(x){return x.authorityType===PLACEMENT&&x.sectionId===input.sectionId;}),activePeriodCodes=[],retainedPeriodCodes=[];rows.filter(function(x){return x.authorityType==='bell-schedule';}).forEach(function(bell){(Array.isArray(bell.periods)?bell.periods:[]).forEach(function(period){var code=String(period&&period.code!=null?period.code:'').trim();if(code&&retainedPeriodCodes.indexOf(code)<0)retainedPeriodCodes.push(code);if(code&&bell.lifecycle==='active'&&activePeriodCodes.indexOf(code)<0)activePeriodCodes.push(code);});});var semesters=await reader.query(S.semesters),years=await reader.query(S.schoolYears);return resolve({sectionId:input.sectionId,schoolDate:input.schoolDate||input.day,currentDate:input.currentDate,section:section,sections:[section],sectionPlacements:placementRows,semesters:semesters,schoolYears:years,periodAuthority:{active:activePeriodCodes,retained:retainedPeriodCodes}});}
  function placementsForSemester(input){input=input||{};var semester=input.semester,section=input.section,years=input.schoolYears||[],semesters=input.semesters||[],rows=(input.sectionPlacements||[]).filter(function(x){return x.authorityType===PLACEMENT&&x.lifecycle==='active'&&x.sectionId===section.sectionId&&x.semesterId===semester.semesterId&&x.effectiveFrom<=semester.endDate&&(!x.effectiveTo||x.effectiveTo>=semester.startDate);});for(var row of rows)validateScope(section,row,years,semesters);return rows.slice().sort(function(a,b){return a.effectiveFrom.localeCompare(b.effectiveFrom)||a.id.localeCompare(b.id);});}
  async function forSemester(reader,input){var section=await read(reader,S.sections,input.sectionId),semester=await read(reader,S.semesters,input.semesterId);if(!section||!semester)return[];var rows=await reader.query(S.infrastructure),years=await reader.query(S.schoolYears),semesters=await reader.query(S.semesters);return placementsForSemester({section:section,semester:semester,sectionPlacements:rows,schoolYears:years,semesters:semesters});}
  return{resolve:resolve,fromReader:fromReader,placementsForSemester:placementsForSemester,forSemester:forSemester,authorityType:PLACEMENT};
}));
