/* Daily Teaching First Slice 1 renderer. Plain text only; no domain mutation capability. */
(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcDailyTeachingUI=api;}(this,function(){
  'use strict';
  function el(tag,cls,text){var n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=String(text);return n;}
  function list(values,cls){var ul=el('ul',cls);(values||[]).forEach(function(x){ul.appendChild(el('li','',x));});return ul;}
  function create(options){options=options||{};var root=options.root,read=options.read,onBack=options.onBack||function(){},state=options.state||{};if(!root||typeof read!=='function')throw new Error('Daily Teaching UI requires a root and read callback.');var token=0;
    function message(title,body){root.replaceChildren(el('h2','',title),el('p','arc-dt-muted',body));}
    async function show(input){var mine=++token;message('Loading teaching focus…','Reading the selected sample class.');try{var view=await read(input);if(mine!==token)return;if(view.status!=='ready'){var labels={no_section:['Choose a sample class','Select a class to view today’s focus.'],schedule_unknown:['Schedule unavailable','No configured schedule authority exists for this sample date.'],no_class:['No Class','This sample date is explicitly noninstructional.'],pacing_not_configured:['Pacing not configured','This Section has no pacing plan for the Semester.'],no_focus:['No focus recorded','No teaching focus has been recorded for this class today.'],unavailable_reference:['Planned reference unavailable','The recorded focus remains in history, but its pacing item is unavailable.'],invalid_reference:['Invalid planned reference','The focus cannot be resolved to its exact Lesson authority.'],no_guide:['Teaching guidance unavailable','Teaching guidance has not been reviewed for this lesson.']};var m=labels[view.status]||['Unable to load','The checked teaching projection could not be displayed.'];message(m[0],m[1]);return;}render(view);}catch(e){if(mine===token)message('Unable to load',e.message||String(e));}}
    function render(v){var section=el('section','arc-dt-view'),back=el('button','arc-dt-button','← Sample classes');back.type='button';back.onclick=onBack;section.append(back,el('p','arc-dt-kicker','DAILY TEACHING REVIEW — SAMPLE CLASSES — NOT LIVE CLASSROOM'),el('h1','',v.section.displayName||v.section.sectionId),el('p','arc-dt-muted',v.schoolDate+' • '+v.focusLabel));if(v.planningNote)section.appendChild(el('p','',v.planningNote));var shared=el('section','arc-dt-panel');shared.append(el('h2','',v.mode==='brief'?'Continuation reminder':'Shared instruction'),el('p','',v.guide.sharedInstruction.summary),list(v.guide.sharedInstruction.safetyPrompts,'arc-dt-safety'));if(v.mode==='full')shared.append(el('h3','','Demonstration'),list(v.guide.sharedInstruction.demonstrationSteps));section.appendChild(shared);var targets=el('section','arc-dt-panel');targets.append(el('h2','','Targets and success'),list(v.lesson.learningTargets),list(v.lesson.successCriteria));section.appendChild(targets);section.appendChild(el('p','arc-dt-note','Teaching options only — student connections are not recorded here yet.'));var cards=el('div','arc-dt-cards');v.guide.pathways.forEach(function(p){var d=el('details','arc-dt-card'),s=el('summary','',p.title),body=el('div','arc-dt-card-body');s.appendChild(el('span','arc-dt-use',p.useWhen));body.append(el('h3','','Task'),el('p','',p.task),el('h3','','Instructor focus'),el('p','',p.instructorFocus),el('h3','','Ask'),list(p.questions),el('h3','','Look for'),list(p.lookFors),el('h3','','Safety'),list(p.safetyPrompts,'arc-dt-safety'));p.helpSections.forEach(function(h){body.append(el('h3','',h.title),list(h.body));});d.append(s,body);d.addEventListener('toggle',function(){if(d.open){Array.from(cards.querySelectorAll('details')).forEach(function(other){if(other!==d)other.open=false;});state.expanded=p.pathwayKey;}});cards.appendChild(d);});section.appendChild(cards);root.replaceChildren(section);if(state.expanded){var match=v.guide.pathways.findIndex(function(x){return x.pathwayKey===state.expanded;});if(match>=0)cards.children[match].open=true;}if(Number.isFinite(state.scrollY))window.scrollTo(0,state.scrollY);}
    return{show:show,capture:function(){state.scrollY=window.scrollY;return state;},cancel:function(){token++;}};
  }
  return{create:create};
}));
