/* Stage 14 academic cutover authority. Explicit tooling/adapters only until
   protected production initialization and Samsung acceptance are complete. */
(function(root,factory){var api=factory(root.ArcV8Storage||(typeof require==='function'?require('./arc_v8_storage'):null),root.ArcV8Academic||(typeof require==='function'?require('./arc_v8_academic'):null),root.ArcV8BackupRecovery||(typeof require==='function'?require('./arc_v8_backup_recovery'):null));if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcV8AcademicCutover=api;}(this,function(Storage,Academic,Backup){
'use strict';var S=Storage.STORES,ACADEMIC=[S.students,S.courses,S.schoolYears,S.semesters,S.gradingPeriods,S.sections,S.enrollments,S.scheduleAssignments],INFRA=[S.metadata,S.migrations,S.infrastructure],LATER=Backup.EXPECTED_STORES.filter(function(x){return ACADEMIC.indexOf(x)<0&&INFRA.indexOf(x)<0;}),MANIFEST='academic-authority-cutover-manifest';
function fail(code,message,context){throw new Storage.StorageError(code,message,context||{});}function row(rows,id){return rows.find(function(x){return x.id===id;});}
function create(options){options=options||{};var storage=options.storage,backup=options.backup,actor=String(options.actor||''),now=options.now||function(){return new Date().toISOString();},environment=options.environment||'production',realData=options.realStudentDataAuthorized===true;if(!storage||!backup||!actor)throw Error('Academic cutover requires storage, backup, and actor authority.');var academic=Academic.create({storage:storage,actor:actor,now:now});
async function prerequisites(){if(storage.constants.databaseName!==Storage.DATABASE_NAME||storage.constants.schemaVersion!==8||storage.constants.indexedDbVersion!==10)fail('PRODUCTION_IDENTITY_REQUIRED','Academic cutover requires exact protected production v8 authority.',{constants:storage.constants});var db=await storage.open(),infra=await db.query(S.infrastructure),init=row(infra,'production-v8-initialization-manifest'),recon=row(infra,'production-v8-reconciliation-manifest'),protection=row(infra,'database-protection');if(!init||init.status!=='complete'||init.authorityState!=='V7_ONLY'||init.classroomAuthorityTransferred!==false)fail('STAGE1_PREREQUISITE_MISSING','Stage 1 initialization manifest is missing or incompatible.');if(!recon||recon.importedRecordCount!==0)fail('STAGE1_PREREQUISITE_MISSING','Stage 1 reconciliation manifest is missing or incompatible.');if(!protection||protection.mode!=='Production/Classroom Protected')fail('PROTECTION_REQUIRED','Protected production authority is required.');for(var store of LATER)if((await db.query(store)).length)fail('LATER_DOMAIN_RECORDS_PRESENT','Later-domain records block bounded academic cutover.',{store:store});var audit=await backup.auditDatabase();if(!audit.healthy)fail('DATABASE_INTEGRITY_FAILED','Database integrity audit failed.',{audit:audit});var recovery=await backup.exportBackup({purpose:'pre-academic-cutover-recovery'});if(!recovery.verification.verified)fail('RECOVERY_VERIFICATION_FAILED','Academic cutover recovery package did not verify.');return{db:db,init:init,reconciliation:recon,protection:protection,audit:audit,recovery:recovery};}
async function courseManifest(){var courses=await academic.initialize(),expected=[['arc-course-wt','WT','Welding Technology'],['arc-course-awt','AWT','Advanced Welding Technology']];expected.forEach(function(e,i){if(courses[i].courseId!==e[0]||courses[i].code!==e[1]||courses[i].title!==e[2])fail('COURSE_MANIFEST_MISMATCH','WT/AWT stable Course authority differs from approved manifest.');});return courses;}
async function setupSummary(day){var db=await storage.open(),out={courses:await db.query(S.courses),schoolYears:await db.query(S.schoolYears),semesters:await db.query(S.semesters),gradingPeriods:await db.query(S.gradingPeriods),sections:await db.query(S.sections),students:await db.query(S.students),enrollments:await db.query(S.enrollments),scheduleAssignments:await db.query(S.scheduleAssignments)};if(day){out.rosters={};for(var sec of out.sections)out.rosters[sec.sectionId]=await academic.rosterForSection(sec.sectionId,day);}return out;}
async function activate(authority){var gate=await prerequisites(),db=gate.db,courses=await courseManifest(),summary=await setupSummary();if(courses.length!==2||!summary.schoolYears.length||!summary.semesters.length||!summary.gradingPeriods.length||!summary.sections.length)fail('ACADEMIC_CONFIGURATION_INCOMPLETE','Manual academic configuration is incomplete.');if(summary.students.length||summary.enrollments.length||summary.scheduleAssignments.length)fail('REAL_DATA_NOT_AUTHORIZED','Stage 2 production activation requires an empty Student/roster authority until real-data authorization.');if(!authority||!authority.startingCommit||!authority.startingTree||!authority.rollbackRef)fail('ROLLBACK_AUTHORITY_REQUIRED','Academic cutover requires exact Git rollback authority.');var manifest={id:MANIFEST,type:'AcademicAuthorityCutoverManifest',status:'implemented-locally-physical-verification-pending',authorityState:'V7_ONLY',targetAuthorityState:'V8_AUTHORITATIVE',productionActivated:false,samsungVerified:false,v7WritesDisabled:false,realStudentDataAuthorized:false,courseIds:courses.map(function(x){return x.courseId;}),createdAt:now(),createdBy:actor,startingCommit:String(authority.startingCommit),startingTree:String(authority.startingTree),rollbackRef:String(authority.rollbackRef)};await db.put(S.infrastructure,manifest);return{manifest:manifest,recovery:gate.recovery,audit:gate.audit,summary:summary};}
function manual(){return{verifyCourses:courseManifest,createSchoolYear:academic.createSchoolYear,createSemester:academic.createSemester,createGradingPeriod:academic.createGradingPeriod,createSection:academic.createSection,archiveSection:academic.archiveSection,createStudent:function(input){if(environment==='production'&&!realData)fail('REAL_DATA_NOT_AUTHORIZED','Real student production data is not authorized.');return academic.createStudent(input);},updateStudent:academic.updateStudent,archiveStudent:academic.archiveStudent,createEnrollment:function(input){if(environment==='production'&&!realData)fail('REAL_DATA_NOT_AUTHORIZED','Real student production data is not authorized.');return academic.createEnrollment(input);},closeEnrollment:academic.closeEnrollment,assignSection:academic.createScheduleAssignment,endAssignment:academic.endScheduleAssignment,moveSection:academic.moveEnrollment,rosterForSection:academic.rosterForSection,gradingPeriodForDate:academic.gradingPeriodForDate,summary:setupSummary};}
return{preflight:prerequisites,activate:activate,manual:manual(),constants:{manifestId:MANIFEST,currentAuthorityState:'V7_ONLY',targetAuthorityState:'V8_AUTHORITATIVE',academicStores:ACADEMIC.slice(),laterStores:LATER.slice()}};}
return{create:create};
}));
