/* Stage 14 P10C-UI Lesson Bank and Auto Build presentation/orchestration boundary. */
(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcLessonPacingUI=api;}(this,function(){
  'use strict';
  function fail(code,message,context){var e=new Error(message);e.code=code;e.context=context||{};throw e;}
  function copy(value){return value==null?value:JSON.parse(JSON.stringify(value));}
  function required(value,name){if(value===undefined||value===null||String(value).trim()==='')fail('REQUIRED_FIELD',name+' is required.',{field:name});return value;}
  function create(options){options=options||{};var lessons=options.lessonAdapter,pacing=options.pacingAdapter,calendar=options.calendarProjection||{preview:async function(){return{dates:[],source:'unconfigured-preview'};}},idFactory=options.idFactory||function(){return 'pace-'+Date.now()+'-'+Math.random().toString(36).slice(2,8);};if(!lessons||!pacing)fail('ADAPTER_REQUIRED','Lesson/Pacing UI requires exclusive P10C and P10B adapters.');
    function lessonRead(action,payload){return lessons.runIsolated(action,payload||{});}function pacingRead(action,payload){return pacing.runIsolated(action,payload||{});}
    async function lessonBank(input){var rows=await lessonRead('getCourseLessons',{courseId:input.courseId,lifecycle:input.lifecycle||'active',reusableKind:input.filter==='numbered'||input.filter==='reusable'?input.filter:null,search:input.search||''}),cards=[];for(var row of rows){var detail=await lessonRead('getLessonPlanbookProjection',{lessonVersionId:row.currentVersion.lessonVersionId});cards.push({lessonId:row.definition.lessonId,lessonVersionId:row.currentVersion.lessonVersionId,lessonCode:row.definition.lessonCode,reusableKind:row.definition.reusableKind,title:detail.title,standards:detail.relationships.standards,competencies:detail.relationships.competencies,curriculum:detail.relationships.curriculum,activities:detail.relationships.activities,learningTargets:detail.learningTargets,successCriteria:detail.successCriteria,engagementStrategies:detail.engagementStrategies,assessment:detail.assessment});}return{courseId:input.courseId,filter:input.filter||'all',search:input.search||'',numbered:cards.filter(function(x){return x.reusableKind==='numbered';}).length,reusable:cards.filter(function(x){return x.reusableKind==='reusable';}).length,total:cards.length,cards:cards};}
    function durationFor(lesson,model,fallback,history,latestAcademicYear){var relevant=(history||[]).filter(function(x){return x.completed!==false&&(x.lessonVersionId===lesson.lessonVersionId||x.lessonId===lesson.lessonId)&&Number(x.periods)>0;}),selected=relevant;if(model==='latest'&&relevant.length){var latestRows=relevant.filter(function(x){return String(x.academicYear||'')===latestAcademicYear;});selected=latestRows.length?latestRows:relevant;}if(model==='uniform'||!selected.length)return{periods:fallback,source:model==='uniform'?'uniform':'fallback',observations:0,average:null,range:null};var values=selected.map(function(x){return Number(x.periods);}),average=values.reduce(function(a,b){return a+b;},0)/values.length,periods=model==='conservative'?Math.ceil(average):Math.round(average);return{periods:Math.max(1,periods),source:model,observations:values.length,average:average,range:[Math.min.apply(null,values),Math.max.apply(null,values)]};}
    async function plan(input){var projection=await pacingRead('getSectionPacing',{sectionId:input.sectionId,semesterId:input.semesterId});if(!projection.configured)fail('PACING_NOT_CONFIGURED','Future or unconfigured Semester pacing remains unknown; Auto Build cannot fabricate a plan.',{sectionId:input.sectionId,semesterId:input.semesterId});if(projection.plan.courseId!==input.courseId)fail('PACING_SCOPE_MISMATCH','Lesson Course differs from Section pacing authority.');return projection;}
    async function previewCommands(input,commands,projection,summary){var request={sectionPacingPlanId:projection.plan.sectionPacingPlanId,expectedRevision:projection.plan.revision,expectedSequence:projection.plan.lastSequence,reason:input.reason||'Instructor Lesson pacing preview',commands:commands},batch=await pacingRead('previewPacingBatch',request),forecast=await calendar.preview({sectionId:input.sectionId,semesterId:input.semesterId,anchorDate:projection.current.anchorDate,includeOpenShop:projection.current.includeOpenShop,items:batch.after.current.items});return Object.assign({courseId:input.courseId,sectionId:input.sectionId,semesterId:input.semesterId,request:request,forecast:forecast,write:false},summary||{},batch);}
    async function previewScheduleLesson(input){required(input.lessonVersionId,'lessonVersionId');var projection=await plan(input),version=await lessonRead('getLessonVersion',{lessonVersionId:input.lessonVersionId}),definition=await lessonRead('getLessonDefinition',{lessonId:version.lessonId});if(definition.courseId!==input.courseId||version.lifecycle!=='active')fail('LESSON_SCOPE_MISMATCH','Scheduling requires an active Lesson Version in the Section Course.');var periods=Math.max(1,Number(input.periods)||1),command={eventType:'ITEM_ADDED',pacingItemId:input.pacingItemId||idFactory(),lessonPlanVersionId:version.lessonVersionId,payload:{order:projection.current.items.length,plannedDuration:periods,durationModel:'manual',durationSource:'instructor'},reason:input.reason||'Instructor scheduled Lesson'};return previewCommands(input,[command],projection,{mode:'individual',lessonId:definition.lessonId,lessonVersionId:version.lessonVersionId,plannedDuration:periods});}
    async function commitPreview(preview){if(!preview||!preview.previewFingerprint||!preview.request)fail('ACCEPTED_PREVIEW_REQUIRED','Commit requires the exact accepted preview.');var request=Object.assign({},copy(preview.request),{previewFingerprint:preview.previewFingerprint}),result=await pacingRead('appendPacingBatch',request);return{committed:true,atomic:result.atomic,events:result.events,projection:result.projection,previewFingerprint:result.previewFingerprint};}
    async function previewAutoBuild(input){var projection=await plan(input),eligible=await lessonRead('getAutoBuildEligibleLessons',{courseId:input.courseId}),start=Number(required(input.startLesson,'startLesson')),end=Number(required(input.endLesson,'endLesson'));if(start>end)fail('INVALID_LESSON_RANGE','Ending Lesson must be the same as or later than starting Lesson.');var selected=eligible.filter(function(x){var code=Number(x.lessonCode);return code>=start&&code<=end;}),fallback=Math.max(1,Number(input.fallbackPeriods)||1),model=input.durationModel||'uniform',latestAcademicYear=(input.historyObservations||[]).map(function(x){return String(x.academicYear||'');}).sort().slice(-1)[0]||'';if(['uniform','historical','latest','conservative'].indexOf(model)<0)fail('INVALID_DURATION_MODEL','Duration model is outside the accepted workflow.');var commands=[],removed=[],retained=projection.current.items.slice(),completed=retained.filter(function(x){return x.status==='completed';});if(input.replaceUnfinished){retained.filter(function(x){return x.status!=='completed';}).forEach(function(x){commands.push({eventType:'ITEM_REMOVED',pacingItemId:x.pacingItemId,reason:input.reason||'Instructor replaced unfinished Auto Build items'});removed.push(x.pacingItemId);});retained=completed.slice();}var existing={};retained.forEach(function(x){if(x.lessonPlanVersionId)existing[x.lessonPlanVersionId]=true;});var added=[],skipped=[],durationEvidence=[];selected.forEach(function(lesson){if(existing[lesson.lessonVersionId]){skipped.push(lesson.lessonVersionId);return;}var duration=durationFor(lesson,model,fallback,input.historyObservations,latestAcademicYear);durationEvidence.push({lessonVersionId:lesson.lessonVersionId,choice:duration});var pacingItemId=idFactory();commands.push({eventType:'ITEM_ADDED',pacingItemId:pacingItemId,lessonPlanVersionId:lesson.lessonVersionId,payload:{order:retained.length+added.length,plannedDuration:duration.periods,durationModel:model,durationSource:duration.source,historicalSampleCount:duration.observations,historicalAverage:duration.average,historicalRange:duration.range},reason:input.reason||'Instructor accepted Auto Build preview'});added.push({pacingItemId:pacingItemId,lessonId:lesson.lessonId,lessonVersionId:lesson.lessonVersionId,lessonCode:lesson.lessonCode,title:lesson.title,plannedDuration:duration.periods});existing[lesson.lessonVersionId]=true;});if(!commands.length)fail('NO_PACING_CHANGES','Auto Build preview contains no pacing changes.');return previewCommands(input,commands,projection,{mode:'auto-build',choices:{startLesson:start,endLesson:end,durationModel:model,fallbackPeriods:fallback,replaceUnfinished:!!input.replaceUnfinished},added:added,removed:removed,skipped:skipped,completedProtected:completed.map(function(x){return x.pacingItemId;}),durationEvidence:durationEvidence});}
    return{lessonBank:lessonBank,previewScheduleLesson:previewScheduleLesson,commitScheduleLesson:commitPreview,previewAutoBuild:previewAutoBuild,commitAutoBuild:commitPreview,placementAuthority:'P10B_SECTION_PACING',persistedAutoBuildTruth:false};
  }
  return{create:create};
}));
