/* ARC P10D-PU1 protected production structural-upgrade coordinator.
   Explicit engineering tooling only: loading this module never opens IndexedDB. */
(function(root,factory){
  var api=factory(
    root.ArcV8Storage||(typeof require==='function'?require('./arc_v8_storage'):null),
    root.ArcV8BackupRecovery||(typeof require==='function'?require('./arc_v8_backup_recovery'):null),
    root.ArcV8ProductionInitialization||(typeof require==='function'?require('./arc_v8_production_initialization'):null)
  );
  if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcV8ProtectedProductionUpgrade=api;
}(this,function(Storage,BackupRecovery,ProductionInitialization){
  'use strict';
  var DATABASE_NAME='arc_classroom_v8',FORMAT='arc-v8-portable-backup',FORMAT_VERSION=1;
  var AUTHORITY_STATE='V7_ONLY',PROTECTED_MODE='Production/Classroom Protected';
  var INIT_ID='production-v8-initialization-manifest',RECON_ID='production-v8-reconciliation-manifest',PROTECTION_ID='database-protection';
  var HISTORICAL_COMMIT='52b7d1b3ed920c0e889e211e41ea34b6e0395bbd',HISTORICAL_TREE='521e44fa1254e3f70b47b91d99d5749f7dabdcc0',HISTORICAL_ROLLBACK='rollback/pre-stage-14-stage-2-production-v8-initialization',HISTORICAL_OPERATOR='stage14-instructor-production-initialization';
  var NEW_STORES=Object.freeze(['behavior_events','standard_catalogs','standard_catalog_versions','standard_definitions','standard_versions','essential_standard_designations','curriculum_maps','curriculum_map_versions','curriculum_map_items','curriculum_item_standard_links','curriculum_item_competency_links','section_pacing_plans','section_pacing_events','section_pacing_snapshots','lesson_definitions','lesson_versions','lesson_version_standard_links','lesson_version_competency_links','lesson_version_curriculum_links','lesson_version_activity_links','instructional_content_packages']);
  var HISTORICAL_STORES=Object.freeze(BackupRecovery.EXPECTED_STORES.filter(function(name){return NEW_STORES.indexOf(name)<0;}));
  var MIGRATION_STEPS=Object.freeze([
    {id:'indexeddb-10-to-11',fromIndexedDbVersion:10,toIndexedDbVersion:11,storesAdded:['behavior_events']},
    {id:'indexeddb-11-to-12',fromIndexedDbVersion:11,toIndexedDbVersion:12,storesAdded:['standard_catalogs','standard_catalog_versions','standard_definitions','standard_versions','essential_standard_designations','curriculum_maps','curriculum_map_versions','curriculum_map_items','curriculum_item_standard_links','curriculum_item_competency_links','section_pacing_plans','section_pacing_events','section_pacing_snapshots']},
    {id:'indexeddb-12-to-13',fromIndexedDbVersion:12,toIndexedDbVersion:13,storesAdded:['lesson_definitions','lesson_versions','lesson_version_standard_links','lesson_version_competency_links','lesson_version_curriculum_links','lesson_version_activity_links']},
    {id:'indexeddb-13-to-14',fromIndexedDbVersion:13,toIndexedDbVersion:14,storesAdded:['instructional_content_packages']}
  ]);
  var KEYS={metadata:'key',migration_log:'id',infrastructure_records:'id',students:'studentId',courses:'courseId',school_years:'schoolYearId',semesters:'semesterId',grading_periods:'gradingPeriodId',sections:'sectionId',course_enrollments:'enrollmentId',enrollment_schedule_assignments:'scheduleAssignmentId',activity_definitions:'definitionId',activity_versions:'versionId',activity_evidence_declarations:'declarationId',activity_assignments:'assignmentId',student_activities:'studentActivityId',activity_attempts:'attemptId',project_instances:'projectId',project_build_attempts:'buildId',project_checkpoint_events:'eventId',project_manual_need_events:'needEventId',project_rubric_assessments:'rubricAssessmentId',competency_definitions:'competencyId',competency_versions:'competencyVersionId',competency_strategy_configurations:'strategyConfigId',evidence_sources:'sourceId',evidence_records:'evidenceRecordId',instructor_overrides:'overrideId',workplace_days:'workplaceDayId',workplace_events:'workplaceEventId',positive_workplace_observations:'observationId',safety_events:'safetyEventId',workplace_week_finalizations:'weekFinalizationId',activity_assessment_finalizations:'activityAssessmentFinalizationId',assessment_results:'assessmentResultId',gradebook_policy_versions:'gradebookPolicyVersionId',gradebook_entries:'gradebookEntryId',gradebook_entry_revisions:'gradebookEntryRevisionId',gradebook_posting_instances:'postingInstanceId',gradebook_posting_memberships:'postingMembershipId',gradebook_posting_events:'postingEventId',quarter_grade_snapshots:'quarterGradeSnapshotId',attendance_records:'attendanceRecordId',pass_events:'passEventId',supplemental_shop_sessions:'supplementalSessionId',attendance_grade_decisions:'attendanceGradeDecisionId',artifacts:'artifactId',artifact_media_blobs:'mediaBlobId',artifact_links:'artifactLinkId',booth_definitions:'boothId',booth_resources:'boothResourceId',booth_assignments:'boothAssignmentId',booth_issues:'boothIssueId'};
  var INFRASTRUCTURE=Object.freeze(['metadata','migration_log','infrastructure_records']);
  var EXCLUDED=Object.freeze(['engineering','simulation','pilot','test','fictional-transactional']);
  function fail(code,message,context){throw new Storage.StorageError(code,message,context||{});}
  function clone(value){return value===undefined?undefined:structuredClone(value);}
  function canonical(value){if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return'['+value.map(canonical).join(',')+']';return'{'+Object.keys(value).sort().filter(function(k){return value[k]!==undefined;}).map(function(k){return JSON.stringify(k)+':'+canonical(value[k]);}).join(',')+'}';}
  function sameList(a,b){return canonical((a||[]).slice().sort())===canonical((b||[]).slice().sort());}
  function row(rows,id){return(rows||[]).find(function(x){return x.id===id;})||null;}
  function bytes(value){if(value instanceof ArrayBuffer)return new Uint8Array(value);if(ArrayBuffer.isView(value))return new Uint8Array(value.buffer,value.byteOffset,value.byteLength);fail('INVALID_BINARY','Expected binary bytes.');}
  function decode(value){var s;if(typeof atob==='function')s=atob(value);else if(typeof Buffer!=='undefined')s=Buffer.from(value,'base64').toString('binary');else fail('BASE64_UNAVAILABLE','Base64 decoding is unavailable.');var out=new Uint8Array(s.length);for(var i=0;i<s.length;i++)out[i]=s.charCodeAt(i);return out;}
  function create(options){
    options=options||{};var databaseName=String(options.databaseName||DATABASE_NAME),cryptoApi=options.crypto||(typeof crypto!=='undefined'?crypto:null);
    if(databaseName!==DATABASE_NAME)fail('PRODUCTION_IDENTITY_REQUIRED','PU1 accepts only the exact ARC production database identity.',{actual:databaseName,expected:DATABASE_NAME});
    if(!cryptoApi||!cryptoApi.subtle)throw Error('PU1 requires Web Crypto SHA-256.');
    var inspector=options.inspector||null;
    function getInspector(){if(!inspector)inspector=ProductionInitialization.nativeInspector(options.indexedDB);return inspector;}
    var storageFactory=options.storageFactory||function(){return Storage.create({indexedDB:options.indexedDB,databaseName:DATABASE_NAME,crypto:cryptoApi,now:options.now,build:options.build||{}});};
    var backupFactory=options.backupFactory||function(db){return BackupRecovery.create({storage:db,databaseName:DATABASE_NAME,crypto:cryptoApi,now:options.now,build:options.build||{}});};
    async function digest(value){var raw=typeof value==='string'?new TextEncoder().encode(value):bytes(value),hash=await cryptoApi.subtle.digest('SHA-256',raw);return Array.from(new Uint8Array(hash),function(x){return x.toString(16).padStart(2,'0');}).join('');}
    function authorityRows(pkg){var infra=pkg.stores.infrastructure_records||[],init=row(infra,INIT_ID),reconciliation=row(infra,RECON_ID),protection=row(infra,PROTECTION_ID);return{initialization:init,reconciliation:reconciliation,protection:protection};}
    function validateAuthority(manifests){var init=manifests.initialization,reconciliation=manifests.reconciliation,protection=manifests.protection;
      if(!init||init.status!=='complete'||init.databaseName!==DATABASE_NAME||init.schemaFamily!=='arc-classroom'||Number(init.schemaVersion)!==8||Number(init.indexedDbVersion)!==10||Number(init.expectedStoreCount)!==53||!sameList(init.expectedStores,HISTORICAL_STORES)||init.authorityState!==AUTHORITY_STATE||init.classroomAuthorityTransferred!==false||init.realStudentDataAuthorized!==false||init.contentImported!==false)fail('INITIALIZATION_MANIFEST_MISMATCH','Historical initialization manifest is not the accepted protected 10/53 authority.');
      if(init.startingCommit!==HISTORICAL_COMMIT||init.startingTree!==HISTORICAL_TREE||init.rollbackRef!==HISTORICAL_ROLLBACK||init.createdBy!==HISTORICAL_OPERATOR)fail('HISTORICAL_AUTHORITY_MISMATCH','Historical initialization Git/operator authority differs.');
      if(!reconciliation||reconciliation.status!=='complete'||Number(reconciliation.importedRecordCount)!==0||Number(reconciliation.excludedIdentityCount)!==0||!sameList(reconciliation.excludedDataClasses,EXCLUDED)||reconciliation.reusableAuthorityImported!==false||reconciliation.classroomTransactionsImported!==false||reconciliation.startingCommit!==HISTORICAL_COMMIT||reconciliation.startingTree!==HISTORICAL_TREE||reconciliation.rollbackRef!==HISTORICAL_ROLLBACK||reconciliation.createdBy!==HISTORICAL_OPERATOR)fail('RECONCILIATION_MANIFEST_MISMATCH','Historical zero-import reconciliation authority differs.');
      if(!protection||protection.mode!==PROTECTED_MODE||protection.protectedBy!==HISTORICAL_OPERATOR)fail('PROTECTION_REQUIRED','Historical database protection authority differs.');
    }
    async function verifyHistoricalBackup(input){var text=typeof input==='string'?input:canonical(input),pkg;try{pkg=typeof input==='string'?JSON.parse(input):clone(input);}catch(e){fail('MALFORMED_PACKAGE','Historical backup is not valid JSON.');}if(!pkg||!pkg.manifest||!pkg.stores)fail('MALFORMED_PACKAGE','Historical backup requires manifest and stores.');var m=pkg.manifest;
      if(m.format!==FORMAT||Number(m.formatVersion)!==FORMAT_VERSION)fail('UNSUPPORTED_PACKAGE_FORMAT','Historical backup format differs.');
      if(m.schemaFamily!=='arc-classroom'||Number(m.schemaVersion)!==8||Number(m.indexedDbVersion)!==10||m.databaseName!==DATABASE_NAME)fail('HISTORICAL_IDENTITY_MISMATCH','Historical backup identity differs.',{manifest:m});
      if(!sameList(Object.keys(pkg.stores),HISTORICAL_STORES)||!sameList(m.storeInventory,HISTORICAL_STORES))fail('STORE_INVENTORY_MISMATCH','Historical backup must contain exactly 53 stores.');
      var total=0;for(var store of HISTORICAL_STORES){var records=pkg.stores[store],declared=m.stores&&m.stores[store];if(!Array.isArray(records)||!declared||Number(declared.recordCount)!==records.length)fail('COUNT_MISMATCH','Historical store count differs.',{store:store});var seen={};for(var record of records){var id=record[KEYS[store]];if(id===undefined||id===null||seen[String(id)])fail('DUPLICATE_OR_MISSING_ID','Historical store has missing or duplicate primary identity.',{store:store,id:id});seen[String(id)]=true;}if(await digest(canonical(records))!==declared.checksum)fail('STORE_CHECKSUM_MISMATCH','Historical store checksum differs.',{store:store});total+=records.length;}
      var blobs=pkg.stores.artifact_media_blobs||[],media=m.media||{},items=media.items||[],mediaBytes=0;if(Number(media.blobCount)!==blobs.length||items.length!==blobs.length)fail('MEDIA_COUNT_MISMATCH','Historical media inventory differs.');for(var blob of blobs){var raw=decode(blob.bytesBase64),item=items.find(function(x){return x.mediaBlobId===blob.mediaBlobId;});mediaBytes+=raw.byteLength;if(Number(blob.byteSize)!==raw.byteLength||!item||Number(item.byteSize)!==raw.byteLength||item.artifactId!==blob.artifactId||item.checksum!==await digest(raw))fail('MEDIA_CHECKSUM_MISMATCH','Historical media differs.',{mediaBlobId:blob.mediaBlobId});}if(Number(media.totalBytes)!==mediaBytes)fail('MEDIA_COUNT_MISMATCH','Historical media byte count differs.');
      var packageCopy=clone(pkg);packageCopy.manifest.packageIntegrity.checksum='';var packageChecksum=await digest(canonical(packageCopy));if(!m.packageIntegrity||m.packageIntegrity.algorithm!=='SHA-256'||m.packageIntegrity.checksum!==packageChecksum)fail('PACKAGE_CHECKSUM_MISMATCH','Historical completed-package checksum differs.');
      var metadata=(pkg.stores.metadata||[]).find(function(x){return x.key==='database';});if(!metadata||metadata.schemaFamily!=='arc-classroom'||Number(metadata.schemaVersion)!==8||Number(metadata.indexedDbVersion)!==10||metadata.initializationState!=='ready')fail('METADATA_INCONSISTENT','Historical metadata differs.');var manifests=authorityRows(pkg);validateAuthority(manifests);
      var nonempty=HISTORICAL_STORES.filter(function(name){return INFRASTRUCTURE.indexOf(name)<0&&pkg.stores[name].length!==0;});if(nonempty.length)fail('HISTORICAL_DOMAIN_NOT_EMPTY','Historical protected foundation contains domain records.',{stores:nonempty});
      return{verified:true,fileChecksum:await digest(text),packageChecksum:packageChecksum,totalRecordCount:total,storeCount:HISTORICAL_STORES.length,metadata:clone(metadata),manifests:clone(manifests),stores:clone(pkg.stores),package:pkg};
    }
    function compareInspection(report,verified){if(!report||report.exists!==true||report.databaseName!==DATABASE_NAME||Number(report.indexedDbVersion)!==10||!sameList(report.storeNames,HISTORICAL_STORES))fail('PREUPGRADE_INSPECTION_MISMATCH','Live pre-upgrade database identity or store inventory differs.');var unexpectedKnown=(report.knownDatabases||[]).filter(function(name){return name!==DATABASE_NAME;});if(unexpectedKnown.length)fail('UNEXPECTED_PROFILE_DATABASE','The task-owned rehearsal profile contains an unexpected database.',{databases:unexpectedKnown});var unexpected=HISTORICAL_STORES.filter(function(name){return Number((report.counts||{})[name]||0)!==verified.stores[name].length;});if(unexpected.length)fail('PREUPGRADE_INSPECTION_MISMATCH','Live pre-upgrade counts differ from verified backup.',{stores:unexpected});if(canonical(report.metadata)!==canonical(verified.metadata)||canonical((report.infrastructure||[]).slice().sort(function(a,b){return a.id.localeCompare(b.id);}))!==canonical(Object.values(verified.manifests).slice().sort(function(a,b){return a.id.localeCompare(b.id); })))fail('PREUPGRADE_INSPECTION_MISMATCH','Live metadata or protection manifests differ from verified backup.');return{matched:true,databaseName:DATABASE_NAME,indexedDbVersion:10,storeCount:53,counts:clone(report.counts),metadata:clone(report.metadata),infrastructure:clone(report.infrastructure),knownDatabases:clone(report.knownDatabases||[])};}
    async function inspectPreUpgrade(verified){var report=await getInspector().inspect(DATABASE_NAME);return compareInspection(report,verified);}
    async function executeUpgrade(input){var historical=await verifyHistoricalBackup(input.historicalBackup),pre=await inspectPreUpgrade(historical),controller=storageFactory(),db,backup;
      try{db=await controller.open();backup=backupFactory(db);if(Number(controller.constants.indexedDbVersion)!==14||!sameList(db.storeNames,BackupRecovery.EXPECTED_STORES))fail('POSTUPGRADE_INVENTORY_MISMATCH','Current storage did not reach exact 14/74 authority.');var counts={},rows={};for(var store of BackupRecovery.EXPECTED_STORES){rows[store]=await db.query(store);counts[store]=rows[store].length;}var newNonempty=NEW_STORES.filter(function(name){return counts[name]!==0;});if(newNonempty.length)fail('NEW_STORE_NOT_EMPTY','A newly added structural store is not empty.',{stores:newNonempty});var oldDomainChanged=HISTORICAL_STORES.filter(function(name){return INFRASTRUCTURE.indexOf(name)<0&&canonical(rows[name])!==canonical(historical.stores[name]);});if(oldDomainChanged.length)fail('HISTORICAL_DOMAIN_CHANGED','Historical domain stores changed during upgrade.',{stores:oldDomainChanged});if(canonical(rows.infrastructure_records)!==canonical(historical.stores.infrastructure_records))fail('PROTECTION_MANIFEST_CHANGED','Historical infrastructure manifests changed during upgrade.');
        var prefix=historical.stores.migration_log||[],migrations=rows.migration_log||[];for(var historicalMigration of prefix){var preserved=migrations.find(function(item){return item.id===historicalMigration.id;});if(!preserved||canonical(preserved)!==canonical(historicalMigration))fail('MIGRATION_PREFIX_CHANGED','Historical migration prefix changed.',{migrationId:historicalMigration.id});}var added=MIGRATION_STEPS.map(function(step){return migrations.find(function(item){return item.id===step.id;});});if(migrations.length!==prefix.length+4||added.some(function(item){return !item;}))fail('MIGRATION_SEQUENCE_MISMATCH','Expected exactly four new migration records.',{actual:migrations.filter(function(item){return !prefix.some(function(old){return old.id===item.id;});})});for(var i=0;i<MIGRATION_STEPS.length;i++){var expected=MIGRATION_STEPS[i],actual=added[i];if(!actual||actual.id!==expected.id||Number(actual.fromIndexedDbVersion)!==expected.fromIndexedDbVersion||Number(actual.toIndexedDbVersion)!==expected.toIndexedDbVersion||actual.status!=='succeeded'||!sameList(actual.storesAdded,expected.storesAdded))fail('MIGRATION_SEQUENCE_MISMATCH','Ordered migration record differs.',{expected:expected,actual:actual||null});}
        var metadata=rows.metadata.find(function(x){return x.key==='database';});if(!metadata||metadata.schemaFamily!=='arc-classroom'||Number(metadata.schemaVersion)!==8||Number(metadata.indexedDbVersion)!==14||metadata.initializationState!=='ready')fail('METADATA_INCONSISTENT','Post-upgrade metadata differs.');validateAuthority(authorityRows({stores:rows}));var audit=await backup.auditDatabase();if(!audit.healthy)fail('POSTUPGRADE_INTEGRITY_FAILED','Post-upgrade database integrity is not healthy.',{audit:audit});var resetRefused=false;try{await controller.resetDevelopmentDatabase();}catch(e){if(e&&e.code==='PROTECTED_DATABASE')resetRefused=true;else throw e;}if(!resetRefused)fail('PROTECTED_RESET_REFUSAL_FAILED','Protected reset was not refused.');var exported=await backup.exportBackup({purpose:'p10d-pu1-post-upgrade-recovery'}),readback=await backup.verifyPackage(exported.text);if(!exported.verification.verified||!readback.verified||Number(exported.package.manifest.indexedDbVersion)!==14||exported.package.manifest.storeInventory.length!==74)fail('POSTUPGRADE_BACKUP_FAILED','Current 74-store backup did not verify.');return{databaseName:DATABASE_NAME,authorityState:AUTHORITY_STATE,classroomAuthorityTransferred:false,realStudentDataAuthorized:false,preUpgrade:pre,historicalBackup:{fileChecksum:historical.fileChecksum,packageChecksum:historical.packageChecksum,totalRecordCount:historical.totalRecordCount},postUpgrade:{schemaVersion:8,indexedDbVersion:14,storeCount:74,newStores:NEW_STORES.slice(),newStoresEmpty:true,historicalDomainPreserved:true,infrastructurePreserved:true,migrationPrefixCount:prefix.length,migrations:clone(added),metadata:clone(metadata),counts:counts,audit:audit,protectedResetRefused:true},postUpgradeBackup:{text:exported.text,fileChecksum:await digest(exported.text),packageChecksum:readback.checksum,totalRecordCount:readback.recordCount,verification:readback}};
      }finally{if(db&&typeof db.close==='function')db.close();}
    }
    return{verifyHistoricalBackup:verifyHistoricalBackup,inspectPreUpgrade:inspectPreUpgrade,executeUpgrade:executeUpgrade,constants:{databaseName:DATABASE_NAME,authorityState:AUTHORITY_STATE,historicalStores:HISTORICAL_STORES.slice(),currentStores:BackupRecovery.EXPECTED_STORES.slice(),newStores:NEW_STORES.slice(),migrationSteps:clone(MIGRATION_STEPS),historicalAuthority:{commit:HISTORICAL_COMMIT,tree:HISTORICAL_TREE,rollback:HISTORICAL_ROLLBACK,operator:HISTORICAL_OPERATOR}}};
  }
  return{create:create,DATABASE_NAME:DATABASE_NAME,HISTORICAL_STORES:HISTORICAL_STORES.slice(),NEW_STORES:NEW_STORES.slice(),MIGRATION_STEPS:clone(MIGRATION_STEPS)};
}));
