/* ARC P10D-PR1 exact frozen instructional-package import coordinator.
   Engineering infrastructure only: loading this module never opens IndexedDB. */
(function(root,factory){
  var api=factory(root.ArcV8Storage||(typeof require==='function'?require('./arc_v8_storage'):null));
  if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcV8InstructionalImportCoordinator=api;
}(this,function(Storage){
  'use strict';
  var DATABASE_NAME='arc_classroom_v8_p10d_persisted_rehearsal_1';
  var PAYLOAD_SHA256='f1f7756242c1ef685ef4ce061507d03b8fc6834e0e448cde7510fc8e2ade79b1';
  var IDENTITY_SHA256='7ba2956022875c03cc1bea1ee9ffa205fa78c204bfdc967c06c66fc5b1c3b750';
  var FORMAT='arc-p10d-resolved-instructional-payload-v1';
  var COMPILER='p10d-r2-resolved-representation-repair-1';
  var PHASES=Object.freeze([
    {name:'STANDARDS',types:['STANDARD_CATALOG','STANDARD_CATALOG_VERSION','STANDARD_DEFINITION','STANDARD_VERSION'],count:62},
    {name:'COMPETENCIES',types:['COMPETENCY_DEFINITION','COMPETENCY_VERSION'],count:120},
    {name:'ESSENTIALS',types:['ESSENTIAL_STANDARD_DESIGNATION'],count:10},
    {name:'CURRICULUM_CORE',types:['CURRICULUM_MAP','CURRICULUM_MAP_VERSION','CURRICULUM_MAP_ITEM'],count:60},
    {name:'CURRICULUM_STANDARD_LINKS',types:['CURRICULUM_STANDARD_LINK'],count:80},
    {name:'LESSON_CORE',types:['LESSON_DEFINITION','LESSON_VERSION'],count:248},
    {name:'LESSON_STANDARD_LINKS',types:['LESSON_STANDARD_LINK'],count:228},
    {name:'LESSON_COMPETENCY_LINKS',types:['LESSON_COMPETENCY_LINK'],count:51}
  ]);
  var ROLES=Object.freeze({
    STANDARD_CATALOG:{owner:'curriculum',store:'standard_catalogs',key:'standardCatalogId',phase:'STANDARDS'},
    STANDARD_CATALOG_VERSION:{owner:'curriculum',store:'standard_catalog_versions',key:'standardCatalogVersionId',phase:'STANDARDS'},
    STANDARD_DEFINITION:{owner:'curriculum',store:'standard_definitions',key:'standardId',phase:'STANDARDS'},
    STANDARD_VERSION:{owner:'curriculum',store:'standard_versions',key:'standardVersionId',phase:'STANDARDS'},
    COMPETENCY_DEFINITION:{owner:'evidence',store:'competency_definitions',key:'competencyId',phase:'COMPETENCIES'},
    COMPETENCY_VERSION:{owner:'evidence',store:'competency_versions',key:'competencyVersionId',phase:'COMPETENCIES'},
    ESSENTIAL_STANDARD_DESIGNATION:{owner:'curriculum',store:'essential_standard_designations',key:'essentialStandardDesignationId',phase:'ESSENTIALS'},
    CURRICULUM_MAP:{owner:'curriculum',store:'curriculum_maps',key:'curriculumMapId',phase:'CURRICULUM_CORE'},
    CURRICULUM_MAP_VERSION:{owner:'curriculum',store:'curriculum_map_versions',key:'curriculumMapVersionId',phase:'CURRICULUM_CORE'},
    CURRICULUM_MAP_ITEM:{owner:'curriculum',store:'curriculum_map_items',key:'curriculumMapItemId',phase:'CURRICULUM_CORE'},
    CURRICULUM_STANDARD_LINK:{owner:'curriculum',store:'curriculum_item_standard_links',key:'curriculumItemStandardLinkId',phase:'CURRICULUM_STANDARD_LINKS'},
    LESSON_DEFINITION:{owner:'lessons',store:'lesson_definitions',key:'lessonId',phase:'LESSON_CORE'},
    LESSON_VERSION:{owner:'lessons',store:'lesson_versions',key:'lessonVersionId',phase:'LESSON_CORE'},
    LESSON_STANDARD_LINK:{owner:'lessons',store:'lesson_version_standard_links',key:'lessonStandardLinkId',phase:'LESSON_STANDARD_LINKS'},
    LESSON_COMPETENCY_LINK:{owner:'lessons',store:'lesson_version_competency_links',key:'lessonCompetencyLinkId',phase:'LESSON_COMPETENCY_LINKS'}
  });
  function fail(code,message,context){throw new Storage.StorageError(code,message,context||{});}
  function copy(x){return x==null?x:JSON.parse(JSON.stringify(x));}
  function canonical(x){if(x===null||typeof x!=='object')return JSON.stringify(x);if(Array.isArray(x))return'['+x.map(canonical).join(',')+']';return'{'+Object.keys(x).sort().filter(function(k){return x[k]!==undefined;}).map(function(k){return JSON.stringify(k)+':'+canonical(x[k]);}).join(',')+'}';}
  function bytes(text){return new TextEncoder().encode(text);}
  function hex(buffer){return Array.prototype.map.call(new Uint8Array(buffer),function(x){return x.toString(16).padStart(2,'0');}).join('');}
  async function sha256(value,cryptoApi){if(!cryptoApi||!cryptoApi.subtle)throw Error('PR1 coordinator requires Web Crypto SHA-256.');return hex(await cryptoApi.subtle.digest('SHA-256',typeof value==='string'?bytes(value):value));}
  function exact(value,expected,code,message){if(value!==expected)fail(code||'PACKAGE_CONTRACT_MISMATCH',message||'Frozen package contract differs.',{expected:expected,actual:value});}
  function unique(values,label){var seen={};values.forEach(function(value){var k=String(value);if(!k||seen[k])fail('DUPLICATE_PACKAGE_IDENTITY','Frozen package contains a missing or duplicate '+label+'.',{value:value,label:label});seen[k]=true;});}
  function primary(role){var spec=ROLES[role.roleType],tr=role.targetRepresentation||{},fields=tr.fields||{};if(!spec)fail('UNKNOWN_PACKAGE_ROLE','Unknown frozen role type.',{roleType:role.roleType});exact(tr.owner,spec.owner==='curriculum'?'ArcV8CurriculumPacing':spec.owner==='evidence'?'ArcV8Evidence':'ArcV8LessonPlans','PACKAGE_ROUTE_MISMATCH','Frozen owner route differs.');exact(tr.store,spec.store,'PACKAGE_ROUTE_MISMATCH','Frozen target store differs.');exact(tr.targetIdField,spec.key,'PACKAGE_ROUTE_MISMATCH','Frozen primary-key field differs.');exact(fields[spec.key],tr.targetIdentity,'TARGET_IDENTITY_MISMATCH','Frozen row primary key differs from assigned UUID.');return spec;}
  async function validateModel(payload,identity,cryptoApi){
    exact(payload.format,FORMAT);exact(payload.compilerRevision,COMPILER);exact(payload.status,'PROPOSED_UNPERSISTED');exact(payload.readiness,'READY_FOR_OWNER_IMPLEMENTATION');exact(payload.academicAuthority,'V7_ONLY');
    exact(payload.counts&&payload.counts.roles,859);exact(payload.counts&&payload.counts.retainedLinks,359);exact(payload.counts&&payload.counts.optionalRelationshipsAbsent,259);exact(payload.counts&&payload.counts.legacyLessonVersions,124);exact(payload.counts&&payload.counts.wtLessonCompetencyLinks,51);exact(payload.counts&&payload.counts.awtLessonCompetencyLinks,0);
    if(!Array.isArray(payload.roles)||payload.roles.length!==859||!Array.isArray(payload.membership)||payload.membership.length!==859||!Array.isArray(payload.nonblockingExclusions)||payload.nonblockingExclusions.length!==259)fail('PACKAGE_ACCOUNTING_MISMATCH','Frozen role, membership, or exclusion accounting differs.');
    unique(payload.roles.map(function(x){return x.reviewRecordKey;}),'reviewRecordKey');unique(payload.roles.map(function(x){return x.targetRepresentation&&x.targetRepresentation.targetIdentity;}),'target UUID');
    var membership={};payload.membership.forEach(function(x){if(membership[x.reviewRecordKey])fail('DUPLICATE_MEMBERSHIP','Duplicate membership review key.');membership[x.reviewRecordKey]=x;});
    payload.roles.forEach(function(role){var spec=primary(role),m=membership[role.reviewRecordKey],fields=role.targetRepresentation.fields,expectedCourse=role.course==='wt'?'arc-course-wt':role.course==='awt'?'arc-course-awt':null;if(!expectedCourse)fail('COURSE_SUBSTITUTION','Only canonical WT/AWT source Course contexts are accepted.',{course:role.course});if(fields.courseId&&fields.courseId!==expectedCourse)fail('COURSE_SUBSTITUTION','Frozen role uses a substitute Course.',{reviewRecordKey:role.reviewRecordKey,courseId:fields.courseId});if(Array.isArray(fields.courseIds)&&(fields.courseIds.length!==1||fields.courseIds[0]!==expectedCourse))fail('COURSE_SUBSTITUTION','Frozen role uses a substitute Course list.',{reviewRecordKey:role.reviewRecordKey,courseIds:fields.courseIds});if(!m)fail('MISSING_MEMBERSHIP','Role lacks package membership.',{reviewRecordKey:role.reviewRecordKey});exact(m.targetIdentity,role.targetRepresentation.targetIdentity,'MEMBERSHIP_MISMATCH');exact(m.targetStore,spec.store,'MEMBERSHIP_MISMATCH');exact(m.targetContentHash,role.targetRepresentation.targetContentHash,'MEMBERSHIP_MISMATCH');});
    PHASES.forEach(function(phase){var count=payload.roles.filter(function(r){return ROLES[r.roleType]&&ROLES[r.roleType].phase===phase.name;}).length;exact(count,phase.count,'PHASE_ACCOUNTING_MISMATCH','Frozen phase count differs.');});
    var lessons=payload.roles.filter(function(r){return r.roleType==='LESSON_VERSION';});if(lessons.length!==124)fail('LEGACY_LESSON_POLICY_VIOLATION','Expected exactly 124 preserved Lesson Versions.');lessons.forEach(function(r){var f=r.targetRepresentation.fields;if(f.instructionalAvailability!=='reference_only'||f.instructionalAcceptanceRef!==null||f.preservationState!=='preserved'||f.ordinarySchedulingEligible!==false||f.autoBuildEligible!==false||f.teachingGuide!==undefined)fail('LEGACY_LESSON_POLICY_VIOLATION','Legacy Lesson policy was relaxed or teachingGuide was fabricated.',{reviewRecordKey:r.reviewRecordKey});});
    var identityAssignments=identity.entries; if(!Array.isArray(identityAssignments)||identityAssignments.length!==859)fail('IDENTITY_MAP_MISMATCH','Frozen identity map does not contain 859 assignments.');
    var im={};identityAssignments.forEach(function(x){var key=x.reviewRecordKey||x.key,target=x.targetIdentity||x.targetId||x.uuid;if(!key||!target||im[key])fail('IDENTITY_MAP_MISMATCH','Frozen identity-map assignment is invalid.');im[key]=target;});payload.roles.forEach(function(r){exact(im[r.reviewRecordKey],r.targetRepresentation.targetIdentity,'IDENTITY_MAP_MISMATCH','Payload UUID differs from frozen identity map.');});
    var evidenceChecksum=await sha256(canonical(payload.packageEvidence),cryptoApi);
    return{payload:payload,identityMap:identity,payloadChecksum:PAYLOAD_SHA256,identityMapChecksum:IDENTITY_SHA256,evidenceChecksum:evidenceChecksum,roles:payload.roles.slice(),exclusions:payload.nonblockingExclusions.slice(),phases:PHASES.map(copy)};
  }
  async function preflight(input){
    input=input||{};var cryptoApi=input.crypto||(typeof crypto!=='undefined'?crypto:null),payloadText=String(input.payloadText||''),identityText=String(input.identityMapText||'');
    exact(await sha256(payloadText,cryptoApi),PAYLOAD_SHA256,'PAYLOAD_CHECKSUM_MISMATCH','Resolved payload bytes differ from the accepted R2 artifact.');
    exact(await sha256(identityText,cryptoApi),IDENTITY_SHA256,'IDENTITY_CHECKSUM_MISMATCH','Frozen identity-map bytes differ from the accepted R2 artifact.');
    var payload,identity;try{payload=JSON.parse(payloadText);identity=JSON.parse(identityText);}catch(e){fail('INVALID_FROZEN_JSON','Frozen package JSON could not be parsed.');}
    return validateModel(payload,identity,cryptoApi);
  }
  function create(options){
    options=options||{};var db=options.storage,packages=options.packages,curriculum=options.curriculum,evidence=options.evidence,lessons=options.lessons,cryptoApi=options.crypto||(typeof crypto!=='undefined'?crypto:null),databaseName=String(options.databaseName||'');
    if(!db||!packages||!curriculum||!evidence||!lessons)throw Error('PR1 coordinator requires injected storage and owner services.');
    if(databaseName!==DATABASE_NAME||!db.constants||db.constants.databaseName!==DATABASE_NAME)fail('REHEARSAL_DATABASE_REQUIRED','PR1 execution is hard-bound to its dedicated rehearsal database.',{databaseName:databaseName});
    var owners={curriculum:curriculum,evidence:evidence,lessons:lessons};
    function rolesFor(model,phaseName){var phase=PHASES.find(function(x){return x.name===phaseName;});if(!phase)fail('UNKNOWN_IMPORT_PHASE','Unknown deterministic import phase.',{phase:phaseName});return model.roles.filter(function(r){return ROLES[r.roleType].phase===phaseName;}).sort(function(a,b){return a.reviewRecordKey.localeCompare(b.reviewRecordKey);});}
    function normalizedExpected(role,packageId){var row=copy(role.targetRepresentation.fields);row.importPackageId=packageId;if(role.roleType==='COMPETENCY_VERSION'||role.roleType==='LESSON_VERSION')row.immutableContent=true;return row;}
    function compareRow(role,actual,packageId){var expected=normalizedExpected(role,packageId);if(canonical(actual)!==canonical(expected))fail('PACKAGE_ROW_CONFLICT','Persisted row differs from exact frozen target content.',{roleType:role.roleType,id:role.targetRepresentation.targetIdentity,expected:expected,actual:actual});return expected;}
    async function readRole(role,packageId){var spec=ROLES[role.roleType];return owners[spec.owner].getImportedReference({roleType:role.roleType,packageId:packageId,id:role.targetRepresentation.targetIdentity,auditAuthorized:true});}
    async function findSourceConflict(role){var spec=ROLES[role.roleType],fields=role.targetRepresentation.fields,source=fields.sourceRecordKey||fields.sourceRelationshipIdentity;if(!source)return null;var rows=await db.query(spec.store);return rows.find(function(row){return (row.sourceRecordKey===source||row.sourceRelationshipIdentity===source)&&row[spec.key]!==fields[spec.key];})||null;}
    async function importOne(role,packageId,attemptId){var spec=ROLES[role.roleType],fields=role.targetRepresentation.fields;if(fields.importPackageId&&fields.importPackageId!==packageId)fail('PACKAGE_BINDING_MISMATCH','Frozen record carries another package binding.');var current=await db.read(spec.store,role.targetRepresentation.targetIdentity);if(current){compareRow(role,current,packageId);return{status:'equivalent',role:role,row:current};}var conflict=await findSourceConflict(role);if(conflict)fail('SOURCE_IDENTITY_CONFLICT','Same source identity is already bound to another target ID.',{roleType:role.roleType,existingId:conflict[spec.key],targetId:role.targetRepresentation.targetIdentity});var written=await owners[spec.owner].importPackageRecord({roleType:role.roleType,packageId:packageId,attemptId:attemptId,record:copy(fields)});compareRow(role,written,packageId);return{status:'created',role:role,row:written};}
    async function runPhase(input){var list=rolesFor(input.model,input.phase),created=0,equivalent=0,rows=[];for(var role of list){var result=await importOne(role,input.packageId,input.attemptId);if(result.status==='created')created++;else equivalent++;rows.push(await readRole(role,input.packageId));}var checksum=await sha256(canonical(rows.slice().sort(function(a,b){var ra=list.find(function(x){return x.targetRepresentation.targetIdentity===a[ROLES[x.roleType].key];});return canonical(a).localeCompare(canonical(b));})),cryptoApi);return{phase:input.phase,memberCount:list.length,created:created,equivalent:equivalent,checksum:checksum,readbackVerified:true,rows:rows};}
    async function verifyAll(input){var counts={},rows=[],packageId=input.packageId;for(var role of input.model.roles.slice().sort(function(a,b){return a.reviewRecordKey.localeCompare(b.reviewRecordKey);})){var row=await readRole(role,packageId);compareRow(role,row,packageId);counts[role.roleType]=(counts[role.roleType]||0)+1;rows.push({reviewRecordKey:role.reviewRecordKey,roleType:role.roleType,targetIdentity:role.targetRepresentation.targetIdentity,targetContentHash:role.targetRepresentation.targetContentHash,record:row});}var packageRows=0;for(var spec of Object.values(ROLES)){var found=await db.query(spec.store);packageRows+=found.filter(function(x){return x.importPackageId===packageId;}).length;}if(packageRows!==859)fail('PACKAGE_ACCOUNTING_MISMATCH','Package-bound store row count differs.',{actual:packageRows});var forbidden=['curriculum_item_competency_links','lesson_version_curriculum_links','lesson_version_activity_links'];for(var store of forbidden)if((await db.query(store)).some(function(x){return x.importPackageId===packageId;}))fail('EXCLUSION_BECAME_WRITE','An intentionally absent relationship became a package write.',{store:store});var checksum=await sha256(canonical(rows),cryptoApi);return{roleCount:rows.length,retainedLinkCount:359,intentionalAbsenceCount:input.model.exclusions.length,counts:counts,checksum:checksum,rows:rows,exclusionsVerified:input.model.exclusions.length===259};}
    function completionEvidence(input){var v=input.verification;if(!v||v.roleCount!==859||v.retainedLinkCount!==359||v.intentionalAbsenceCount!==259||!v.exclusionsVerified)fail('COMPLETION_MODEL_INCOMPLETE','Completion evidence requires full exact verification.');if(!Array.isArray(input.phaseSummaries)||input.phaseSummaries.length!==8||input.phaseSummaries.some(function(x){return !x.readbackVerified;}))fail('COMPLETION_MODEL_INCOMPLETE','All eight phases require verified readback.');return{roleCount:859,retainedLinkCount:359,intentionalAbsenceCount:259,memberChecksumsVerified:true,ownerReadbackVerified:true,canonicalCoursesVerified:input.canonicalCoursesVerified===true,evidenceVerified:input.evidenceVerified===true,conflictsAbsent:input.conflictsAbsent===true,backupRecoveryVerified:input.backupRecoveryVerified===true,resolvedPayloadChecksum:PAYLOAD_SHA256,frozenIdentityMapChecksum:IDENTITY_SHA256,readbackChecksum:v.checksum,phaseChecksums:input.phaseSummaries.map(function(x){return{phase:x.phase,memberCount:x.memberCount,checksum:x.checksum};})};}
    async function controlledConflictProbe(input){var role=input.role,copyRow=copy(role.targetRepresentation.fields),field=Object.keys(copyRow).find(function(k){return k!==role.targetRepresentation.targetIdField&&typeof copyRow[k]==='string';});if(!field)fail('CONFLICT_PROBE_UNAVAILABLE','No safe scalar field is available for conflict probe.');copyRow[field]+=' [conflict probe]';var before=await sha256(canonical(await db.query(ROLES[role.roleType].store)),cryptoApi),refused=false,code=null;try{await owners[ROLES[role.roleType].owner].importPackageRecord({roleType:role.roleType,packageId:input.packageId,attemptId:input.attemptId,record:copyRow});}catch(e){refused=true;code=e.code||e.name;}var after=await sha256(canonical(await db.query(ROLES[role.roleType].store)),cryptoApi);if(!refused||before!==after)fail('CONFLICT_PROBE_MUTATED','Same-ID/different-content probe was not safely refused.',{refused:refused,before:before,after:after});return{refused:true,code:code,beforeChecksum:before,afterChecksum:after};}
    return{runPhase:runPhase,verifyAll:verifyAll,readRole:readRole,completionEvidence:completionEvidence,controlledConflictProbe:controlledConflictProbe,databaseName:DATABASE_NAME,phases:PHASES.map(copy),roleContracts:copy(ROLES)};
  }
  return{create:create,preflight:preflight,validateModel:validateModel,DATABASE_NAME:DATABASE_NAME,PAYLOAD_SHA256:PAYLOAD_SHA256,IDENTITY_SHA256:IDENTITY_SHA256,FORMAT:FORMAT,COMPILER:COMPILER,PHASES:PHASES.map(copy),ROLE_CONTRACTS:copy(ROLES),canonical:canonical,sha256:sha256};
}));
