/* Daily Teaching review renderer. Plain text only; read-only teaching options. */
(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcDailyTeachingUI=api;}(this,function(){'use strict';
function el(tag,cls,text){var n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=String(text);return n;}function list(v,cls){var ul=el('ul',cls);(v||[]).forEach(function(x){ul.appendChild(el('li','',x));});return ul;}
function create(o){o=o||{};var root=o.root,read=o.read,onBack=o.onBack||function(){},state=o.state||{},token=0;if(!root||typeof read!=='function')throw new Error('Daily Teaching UI requires a root and read callback.');
function shell(input,title,body){var s=el('section','arc-dt-view'),back=el('button','arc-dt-button','← Sample classes');back.type='button';back.setAttribute('data-action','back');back.onclick=function(){capture();onBack();};s.append(back,el('p','arc-dt-kicker','DAILY TEACHING REVIEW — SAMPLE CLASSES — NOT LIVE CLASSROOM'),el('h1','',input&&input.sectionLabel||'Daily Teaching Review'),el('p','arc-dt-muted',input&&input.schoolDate||''),el('h2','',title),el('p','arc-dt-muted',body));root.replaceChildren(s);}
function capture(){state.scrollY=typeof window!=='undefined'?window.scrollY:0;state.expanded=[];Array.from(root.querySelectorAll('details[data-state-key]')).forEach(function(d){if(d.open)state.expanded.push(d.getAttribute('data-state-key'));});return state;}
async function show(input){var mine=++token;shell(input,'Loading teaching focus…','Reading the selected sample class.');try{var v=await read(input);if(mine!==token)return;var labels={no_section:['Choose a sample class','Select a class to view today’s focus.'],schedule_unknown:['Schedule unavailable','No configured schedule authority exists for this sample date.'],no_class:['No Class','This sample date is explicitly noninstructional.'],pacing_not_configured:['Pacing not configured','This Section has no pacing plan for the Semester.'],no_focus:['No focus recorded','No teaching focus has been recorded for this class today.'],unavailable_reference:['Planned reference unavailable','The recorded focus remains in history, but its pacing item is unavailable.'],invalid_reference:['Invalid planned reference','The focus cannot be resolved to its exact Lesson authority.'],no_guide:['Teaching guidance unavailable','Teaching guidance has not been reviewed for this lesson.']};if(v.status!=='ready'){var m=labels[v.status]||['Unable to load','The checked teaching projection could not be displayed.'];shell({sectionLabel:v.section&&v.section.displayName,schoolDate:v.schoolDate},m[0],m[1]);return;}render(v);}catch(e){if(mine===token)shell(input,'Unable to load',e.message||String(e));}}
function detail(key,title,values,open){var d=el('details','arc-dt-panel');d.setAttribute('data-state-key',key);d.open=!!open;d.append(el('summary','',title),list(values));return d;}
function render(v){var expanded=state.expanded||[],section=el('section','arc-dt-view'),back=el('button','arc-dt-button','← Sample classes');back.type='button';back.setAttribute('data-action','back');back.onclick=function(){capture();onBack();};section.append(back,el('p','arc-dt-kicker','DAILY TEACHING REVIEW — SAMPLE CLASSES — NOT LIVE CLASSROOM'),el('h1','',v.section.displayName||v.section.sectionId),el('p','arc-dt-muted',v.schoolDate+' • '+v.focusLabel));if(v.planningNote)section.appendChild(el('p','',v.planningNote));section.appendChild(detail('preparation','Preparation',v.guide.preparation,expanded.includes('preparation')));var shared=el('section','arc-dt-panel');shared.append(el('h2','',v.mode==='brief'?'Continuation reminder':'Shared instruction'),el('p','',v.guide.sharedInstruction.summary),el('h3','','Ask'),list(v.guide.sharedInstruction.questions),el('h3','','Safety'),list(v.guide.sharedInstruction.safetyPrompts,'arc-dt-safety'));section.appendChild(shared);section.appendChild(detail('demonstration','Demonstration',v.guide.sharedInstruction.demonstrationSteps,expanded.includes('demonstration')));var targets=el('section','arc-dt-panel');targets.append(el('h2','','Targets and success'),list(v.lesson.learningTargets),list(v.lesson.successCriteria));section.appendChild(targets);section.appendChild(el('p','arc-dt-note','Teaching options only — student connections are not recorded here yet.'));var cards=el('div','arc-dt-cards');v.guide.pathways.forEach(function(p){var d=el('details','arc-dt-card'),s=el('summary','',p.title),body=el('div','arc-dt-card-body');d.setAttribute('data-state-key','path:'+p.pathwayKey);d.open=expanded.includes('path:'+p.pathwayKey);s.appendChild(el('span','arc-dt-use',p.useWhen));body.append(el('h3','','Task'),el('p','',p.task),el('h3','','Instructor focus'),el('p','',p.instructorFocus),el('h3','','Ask'),list(p.questions),el('h3','','Look for'),list(p.lookFors),el('h3','','Safety'),list(p.safetyPrompts,'arc-dt-safety'));var help=el('details','arc-dt-help'),hs=el('summary','','Help me teach this'),hb=el('div','arc-dt-help-body');help.setAttribute('data-state-key','help:'+p.pathwayKey);help.open=expanded.includes('help:'+p.pathwayKey);hb.append(el('h4','','Coaching steps'),list(p.coachingSteps));(p.helpSections||[]).forEach(function(h){hb.append(el('h4','',h.title),list(h.body));});help.append(hs,hb);body.appendChild(help);d.append(s,body);cards.appendChild(d);});section.appendChild(cards);root.replaceChildren(section);if(Number.isFinite(state.scrollY)&&typeof window!=='undefined')window.scrollTo(0,state.scrollY);}
return{show:show,capture:capture,cancel:function(){token++;},state:state};}
return{create:create};}));
