/* ARC Schema v8 Academic Foundation. No UI wiring and no Schema v7 access. */
(function(root,factory){var api=factory(root.ArcV8Storage||(typeof require==='function'?require('./arc_v8_storage'):null));if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcV8Academic=api;}(this,function(Storage){
  'use strict';var S=Storage.STORES;
  function fail(code,message,context){throw new Storage.StorageError(code,message,context||{});}
  function date(value,field,nullable){if(nullable&&(value==null||value===''))return null;var parsed=new Date(String(value||'')+'T00:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(String(value||''))||isNaN(parsed.getTime())||parsed.toISOString().slice(0,10)!==value)fail('INVALID_DATE','Invalid academic date.',{field:field,value:value});return value;}
  function range(from,to){from=date(from,'effectiveFrom');to=date(to,'effectiveTo',true);if(to&&to<from)fail('INVALID_DATE_RANGE','End date precedes start date.',{from:from,to:to});return {from:from,to:to};}
  function activeOn(record,day,start,end){return record.lifecycle!=='archived'&&record.lifecycle!=='void'&&record[start]<=day&&(!record[end]||record[end]>=day);}
  function create(options){options=options||{};var storage=options.storage,now=options.now||function(){return new Date().toISOString();},actor=options.actor||'system';if(!storage)throw new Error('Academic repository requires ArcV8Storage.');
    function stamp(input,idField,id,lifecycle){var at=now();return Object.assign({},input,{[idField]:id,lifecycle:lifecycle||'active',revision:1,createdAt:at,createdBy:actor,updatedAt:at,updatedBy:actor});}
    function revise(store,idField,id,expected,changes,immutable){return storage.transaction(store,async function(tx){var current=await tx.get(store,id);if(!current)fail('NOT_FOUND','Academic record was not found.',{store:store,id:id});if(current.revision!==expected)fail('WRITE_CONFLICT','Academic record changed after it was read.',{store:store,id:id,expectedRevision:expected,actualRevision:current.revision});(immutable||[]).forEach(function(field){if(Object.prototype.hasOwnProperty.call(changes,field)&&changes[field]!==current[field])fail('IMMUTABLE_IDENTITY','Immutable academic identity cannot change.',{field:field});});var next=Object.assign({},current,changes,{revision:current.revision+1,updatedAt:now(),updatedBy:actor});await tx.put(store,next);return next;});}
    async function seedCourses(){return storage.transaction(S.courses,async function(tx){var defs=[{courseId:'arc-course-wt',code:'WT',title:'Welding Technology'},{courseId:'arc-course-awt',code:'AWT',title:'Advanced Welding Technology'}],out=[];for(var d of defs){var found=await tx.get(S.courses,d.courseId);if(found&&(found.code!==d.code||found.title!==d.title))fail('COURSE_MANIFEST_MISMATCH','Stable WT/AWT Course identity does not match the reviewed manifest.',{courseId:d.courseId,expected:d,actual:found});if(!found){found=stamp(d,'courseId',d.courseId,'active');await tx.add(S.courses,found);}out.push(found);}return out;});}
    async function student(input){var id=storage.generateId(),record=stamp({preferredName:String(input.preferredName||''),legalFirstName:String(input.legalFirstName||''),legalLastName:String(input.legalLastName||''),gradeLevel:String(input.gradeLevel||'')},'studentId',id,'active');await storage.add(S.students,record);return record;}
    async function schoolYear(input){var r=range(input.startDate,input.endDate),record=stamp({label:String(input.label||''),startDate:r.from,endDate:r.to},'schoolYearId',storage.generateId(),input.lifecycle||'active');await storage.add(S.schoolYears,record);return record;}
    async function semester(input){var year=await storage.read(S.schoolYears,input.schoolYearId);if(!year)fail('REFERENCE_NOT_FOUND','Semester School Year does not exist.',{schoolYearId:input.schoolYearId});var r=range(input.startDate,input.endDate);if(r.from<year.startDate||r.to>year.endDate)fail('ACADEMIC_DATE_OUT_OF_RANGE','Semester dates must remain within the School Year.',{});var record=stamp({schoolYearId:input.schoolYearId,code:String(input.code||''),label:String(input.label||''),startDate:r.from,endDate:r.to,order:Number(input.order)||0},'semesterId',storage.generateId(),input.lifecycle||'active');await storage.add(S.semesters,record);return record;}
    async function gradingPeriod(input){var sem=await storage.read(S.semesters,input.semesterId);if(!sem)fail('REFERENCE_NOT_FOUND','Grading Period Semester does not exist.',{semesterId:input.semesterId});if(input.schoolYearId!==sem.schoolYearId)fail('ACADEMIC_SCOPE_MISMATCH','Grading Period School Year does not match Semester.',{});var r=range(input.startDate,input.endDate);if(r.from<sem.startDate||r.to>sem.endDate)fail('ACADEMIC_DATE_OUT_OF_RANGE','Grading Period dates must remain within the Semester.',{});var record=stamp({semesterId:input.semesterId,schoolYearId:input.schoolYearId,code:String(input.code||''),label:String(input.label||''),startDate:r.from,endDate:r.to,order:Number(input.order)||0},'gradingPeriodId',storage.generateId(),input.lifecycle||'active');await storage.add(S.gradingPeriods,record);return record;}
    async function section(input){var values=await Promise.all([storage.read(S.courses,input.courseId),storage.read(S.schoolYears,input.schoolYearId),input.semesterId?storage.read(S.semesters,input.semesterId):Promise.resolve(null)]);if(!values[0]||!values[1]||(input.semesterId&&!values[2]))fail('REFERENCE_NOT_FOUND','Section academic reference does not exist.',{});if(values[2]&&values[2].schoolYearId!==input.schoolYearId)fail('ACADEMIC_SCOPE_MISMATCH','Section Semester and School Year disagree.',{});var record=stamp({courseId:input.courseId,schoolYearId:input.schoolYearId,semesterId:input.semesterId||'',period:String(input.period),displayName:String(input.displayName||''),scheduleContext:input.scheduleContext&&typeof input.scheduleContext==='object'?structuredClone(input.scheduleContext):null},'sectionId',storage.generateId(),input.lifecycle||'active');await storage.add(S.sections,record);return record;}
    async function enrollment(input){var values=await Promise.all([storage.read(S.students,input.studentId),storage.read(S.courses,input.courseId),storage.read(S.schoolYears,input.schoolYearId)]);if(values.some(function(x){return !x;}))fail('REFERENCE_NOT_FOUND','Enrollment academic reference does not exist.',{});var r=range(input.enrollmentStart,input.enrollmentEnd),year=values[2];if(r.from<year.startDate||(r.to&&r.to>year.endDate))fail('ACADEMIC_DATE_OUT_OF_RANGE','Enrollment dates must remain within the School Year.',{});return storage.transaction(S.enrollments,async function(tx){var existing=await tx.query(S.enrollments,'by_student_course_year',[input.studentId,input.courseId,input.schoolYearId]);if(existing.some(function(x){return x.lifecycle!=='archived'&&x.lifecycle!=='void';}))fail('DUPLICATE_ENROLLMENT','Student already has an Enrollment for this Course and School Year.',{});var record=stamp({studentId:input.studentId,courseId:input.courseId,schoolYearId:input.schoolYearId,enrollmentStart:r.from,enrollmentEnd:r.to,status:input.status||'active'},'enrollmentId',storage.generateId(),input.lifecycle||'active');await tx.add(S.enrollments,record);return record;});}
    function overlap(a,b){return a.effectiveFrom<= (b.effectiveTo||'9999-12-31')&&b.effectiveFrom<= (a.effectiveTo||'9999-12-31');}
    async function assignment(input){var r=range(input.effectiveFrom,input.effectiveTo);return storage.transaction([S.enrollments,S.sections,S.scheduleAssignments],async function(tx){var e=await tx.get(S.enrollments,input.enrollmentId),s=await tx.get(S.sections,input.sectionId);if(!e||!s)fail('REFERENCE_NOT_FOUND','Schedule Assignment reference does not exist.',{});if(e.courseId!==s.courseId||e.schoolYearId!==s.schoolYearId)fail('ACADEMIC_SCOPE_MISMATCH','Section and Enrollment academic authority disagree.',{});if(r.from<e.enrollmentStart||(e.enrollmentEnd&&(!r.to||r.to>e.enrollmentEnd)))fail('ACADEMIC_DATE_OUT_OF_RANGE','Schedule Assignment dates must remain within the Enrollment.',{});var existing=await tx.query(S.scheduleAssignments,'by_enrollment',e.enrollmentId),candidate={effectiveFrom:r.from,effectiveTo:r.to};if(existing.some(function(x){return x.lifecycle!=='void'&&overlap(x,candidate);}))fail('OVERLAPPING_ASSIGNMENT','Enrollment already has an overlapping Section assignment.',{});var record=stamp({enrollmentId:e.enrollmentId,sectionId:s.sectionId,effectiveFrom:r.from,effectiveTo:r.to,reason:String(input.reason||''),source:String(input.source||'instructor')},'scheduleAssignmentId',storage.generateId(),r.to?'ended':'active');await tx.add(S.scheduleAssignments,record);return record;});}
    function previousDay(day){var d=new Date(day+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-1);return d.toISOString().slice(0,10);}
    async function moveEnrollment(input){return storage.transaction([S.enrollments,S.sections,S.scheduleAssignments],async function(tx){var old=await tx.get(S.scheduleAssignments,input.currentAssignmentId),e=await tx.get(S.enrollments,input.enrollmentId),s=await tx.get(S.sections,input.newSectionId);if(!old||!e||!s)fail('REFERENCE_NOT_FOUND','Move reference does not exist.',{});if(old.enrollmentId!==e.enrollmentId||s.courseId!==e.courseId||s.schoolYearId!==e.schoolYearId)fail('ACADEMIC_SCOPE_MISMATCH','Move academic authority disagrees.',{});if(old.revision!==input.expectedRevision)fail('WRITE_CONFLICT','Schedule Assignment changed after it was read.',{});var from=date(input.effectiveFrom,'effectiveFrom'),end=previousDay(from);if(end<old.effectiveFrom)fail('INVALID_DATE_RANGE','Move cannot end the prior assignment before it began.',{});var all=await tx.query(S.scheduleAssignments,'by_enrollment',e.enrollmentId),candidate={effectiveFrom:from,effectiveTo:null};if(all.some(function(x){return x.scheduleAssignmentId!==old.scheduleAssignmentId&&x.lifecycle!=='void'&&overlap(x,candidate);}))fail('OVERLAPPING_ASSIGNMENT','Move would overlap another assignment.',{});var ended=Object.assign({},old,{effectiveTo:end,lifecycle:'ended',revision:old.revision+1,updatedAt:now(),updatedBy:actor});await tx.put(S.scheduleAssignments,ended);var next=stamp({enrollmentId:e.enrollmentId,sectionId:s.sectionId,effectiveFrom:from,effectiveTo:null,reason:String(input.reason||'section_move'),source:String(input.source||'instructor')},'scheduleAssignmentId',storage.generateId(),'active');await tx.add(S.scheduleAssignments,next);return {ended:ended,created:next};});}
    async function roster(sectionId,day){date(day,'date');var assignments=await storage.query(S.scheduleAssignments,'by_section',sectionId),out=[];for(var a of assignments){if(!activeOn(a,day,'effectiveFrom','effectiveTo'))continue;var e=await storage.read(S.enrollments,a.enrollmentId);if(!e||!activeOn(e,day,'enrollmentStart','enrollmentEnd'))continue;var st=await storage.read(S.students,e.studentId);if(st&&st.lifecycle==='active')out.push(st);}return out.sort(function(a,b){return (a.preferredName||a.legalLastName).localeCompare(b.preferredName||b.legalLastName)||a.studentId.localeCompare(b.studentId);});}
    async function periodForDate(day){date(day,'date');var periods=await storage.query(S.gradingPeriods);var found=periods.filter(function(p){return p.lifecycle==='active'&&p.startDate<=day&&p.endDate>=day;}).sort(function(a,b){return a.order-b.order;})[0]||null;if(!found)return null;return {gradingPeriod:found,semester:await storage.read(S.semesters,found.semesterId),schoolYear:await storage.read(S.schoolYears,found.schoolYearId)};}
    return {initialize:seedCourses,createStudent:student,updateStudent:function(id,revision,changes){return revise(S.students,'studentId',id,revision,changes,['studentId']);},archiveStudent:function(id,revision){return revise(S.students,'studentId',id,revision,{lifecycle:'archived'},['studentId']);},archiveCourse:function(id,revision){return revise(S.courses,'courseId',id,revision,{lifecycle:'archived'},['courseId','code']);},createSchoolYear:schoolYear,archiveSchoolYear:function(id,revision){return revise(S.schoolYears,'schoolYearId',id,revision,{lifecycle:'archived'},['schoolYearId']);},createSemester:semester,createGradingPeriod:gradingPeriod,createSection:section,archiveSection:function(id,revision){return revise(S.sections,'sectionId',id,revision,{lifecycle:'archived'},['sectionId','courseId','schoolYearId']);},createEnrollment:enrollment,closeEnrollment:function(id,revision,end){date(end,'enrollmentEnd');return revise(S.enrollments,'enrollmentId',id,revision,{enrollmentEnd:end,status:'closed',lifecycle:'closed'},['enrollmentId','studentId','courseId','schoolYearId']);},createScheduleAssignment:assignment,endScheduleAssignment:function(id,revision,end){date(end,'effectiveTo');return revise(S.scheduleAssignments,'scheduleAssignmentId',id,revision,{effectiveTo:end,lifecycle:'ended'},['scheduleAssignmentId','enrollmentId','sectionId','effectiveFrom']);},moveEnrollment:moveEnrollment,rosterForSection:roster,gradingPeriodForDate:periodForDate,stores:S};
  }
  return {create:create};
}));
