/* ARC Schema v8 Evidence Engine Foundation. Derived competency authority only; no v7 or Gradebook access. */
(function(root,factory){
  var api=factory(root.ArcV8Storage||(typeof require==='function'?require('./arc_v8_storage'):null));
  if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcV8Evidence=api;
}(this,function(Storage){
  'use strict';
  var S=Storage.STORES;
  var FAMILIES=['Performance Confirmation','Continuous Safety','Comprehensive Knowledge','Versioned Product','Diagnose & Correct','Integrated Project','Continuous Workplace'];
  var QUALIFICATIONS=['Qualifying','Supporting','Nonqualifying','Excluded'];
  var MODES=['Rubric','Challenge/Assignment','Workflow','Habit/Continuous'];
  var SOURCE_TYPES=['Practice','Skill Challenge','Technical Assignment','Test','Project Checkpoint','Project Rubric','Instructor Observation','Continuous Event','Continuous Safety','Continuous Workplace'];
  function fail(code,message,context){throw new Storage.StorageError(code,message,context||{});}
  function list(value){return Array.isArray(value)?value:[];}
  function canonical(value){if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==='object'){var out={};Object.keys(value).sort().forEach(function(k){out[k]=canonical(value[k]);});return out;}return value;}
  function stable(value){return JSON.stringify(canonical(value));}
  function fingerprint(value){var text=stable(value),hash=2166136261;for(var i=0;i<text.length;i++){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619);}return('00000000'+(hash>>>0).toString(16)).slice(-8);}
  function scopeKey(scope){return stable(scope||{});}
  function create(options){
    options=options||{};var db=options.storage,now=options.now||function(){return new Date().toISOString();},actor=options.actor||'system';
    if(!db)throw Error('Evidence repository requires storage.');
    function stamp(value,key,id,lifecycle){var at=now();return Object.assign({},value,{[key]:id,lifecycle:lifecycle||'active',revision:1,createdAt:at,createdBy:actor,updatedAt:at,updatedBy:actor});}
    async function createCompetency(input){
      return db.transaction([S.courses,S.competencyDefinitions],async function(tx){
        var courseIds=Array.from(new Set(list(input.courseIds)));if(!input.catalogId||!input.code||!courseIds.length)fail('INVALID_COMPETENCY','Catalog, stable code, and Course applicability are required.');
        for(var i=0;i<courseIds.length;i++)if(!await tx.get(S.courses,courseIds[i]))fail('REFERENCE_NOT_FOUND','Competency Course does not exist.',{courseId:courseIds[i]});
        var duplicate=(await tx.query(S.competencyDefinitions,'by_catalog_code',[input.catalogId,input.code]))[0];if(duplicate)fail('DUPLICATE_COMPETENCY_CODE','Competency code already exists in this catalog.');
        var row=stamp({catalogId:String(input.catalogId),code:String(input.code),courseIds:courseIds,domainCode:String(input.domainCode||input.code),catalogProvenance:input.catalogProvenance||{}},'competencyId',db.generateId(),'active');await tx.add(S.competencyDefinitions,row);return row;
      });
    }
    async function updateCompetency(id,expectedRevision,changes){
      return db.transaction([S.courses,S.competencyDefinitions,S.competencyVersions],async function(tx){
        var current=await tx.get(S.competencyDefinitions,id);if(!current)fail('REFERENCE_NOT_FOUND','Competency does not exist.');if(current.revision!==expectedRevision)fail('WRITE_CONFLICT','Competency changed after it was read.');
        if(changes.competencyId||changes.catalogId||changes.code)fail('IMMUTABLE_IDENTITY','Competency identity and stable code are immutable.');if((await tx.query(S.competencyVersions,'by_competency',id)).length)fail('HISTORICAL_LOCK','Versioned competency authority is historically locked.');
        var courseIds=changes.courseIds?Array.from(new Set(list(changes.courseIds))):current.courseIds;for(var i=0;i<courseIds.length;i++)if(!await tx.get(S.courses,courseIds[i]))fail('REFERENCE_NOT_FOUND','Competency Course does not exist.',{courseId:courseIds[i]});
        var next=Object.assign({},current,changes,{competencyId:current.competencyId,catalogId:current.catalogId,code:current.code,courseIds:courseIds,revision:current.revision+1,updatedAt:now(),updatedBy:actor});await tx.put(S.competencyDefinitions,next);return next;
      });
    }
    async function createCompetencyVersion(input){
      return db.transaction([S.competencyDefinitions,S.competencyVersions],async function(tx){
        var c=await tx.get(S.competencyDefinitions,input.competencyId);if(!c)fail('REFERENCE_NOT_FOUND','Competency does not exist.');
        var number=Number(input.versionNumber);if(!(number>0)||!input.title)fail('INVALID_COMPETENCY_VERSION','Positive version and title are required.');
        if((await tx.query(S.competencyVersions,'by_competency_version',[c.competencyId,number])).length)fail('DUPLICATE_COMPETENCY_VERSION','Competency version already exists.');
        var row=stamp({competencyId:c.competencyId,versionNumber:number,title:String(input.title),description:String(input.description||''),catalogVersion:String(input.catalogVersion||''),provenance:input.provenance||{},publicationState:input.publicationState||'Draft'},'competencyVersionId',db.generateId(),'active');await tx.add(S.competencyVersions,row);return row;
      });
    }
    async function updateCompetencyVersion(id,expectedRevision,changes){
      return db.transaction([S.competencyVersions,S.evidenceRecords],async function(tx){var current=await tx.get(S.competencyVersions,id);if(!current)fail('REFERENCE_NOT_FOUND','Competency version does not exist.');if(current.revision!==expectedRevision)fail('WRITE_CONFLICT','Competency version changed after it was read.');if((await tx.query(S.evidenceRecords,'by_competency',current.competencyId)).some(function(r){return r.competencyVersionId===id;}))fail('HISTORICAL_LOCK','Used competency wording is immutable.');if(changes.competencyId&&changes.competencyId!==current.competencyId)fail('IMMUTABLE_IDENTITY','Competency parent is immutable.');var next=Object.assign({},current,changes,{competencyVersionId:current.competencyVersionId,competencyId:current.competencyId,versionNumber:current.versionNumber,revision:current.revision+1,updatedAt:now(),updatedBy:actor});await tx.put(S.competencyVersions,next);return next;});
    }
    function validateStrategy(input){
      if(FAMILIES.indexOf(input.family)<0)fail('INVALID_STRATEGY','Unknown strategy family.');var config=input.config||{};
      if(list(config.unresolvedRequiredParameters).length)fail('UNRESOLVED_STRATEGY_PARAMETERS','Official computation cannot invent unresolved parameters.',{parameters:config.unresolvedRequiredParameters});
      if(config.confirmation&&config.confirmation.enabled&&!(Number.isInteger(config.confirmation.requiredCount)&&config.confirmation.requiredCount>0))fail('INVALID_STRATEGY','Confirmation count is required.');
      if(config.diversity&&config.diversity.enabled&&(!config.diversity.dimension||!(Number.isInteger(config.diversity.requiredDistinct)&&config.diversity.requiredDistinct>0)))fail('INVALID_STRATEGY','Diversity dimension and count are required.');
      if(config.recency&&config.recency.enabled&&config.recency.windowRequired&&!(config.recency.windowDays>0))fail('UNRESOLVED_STRATEGY_PARAMETERS','Recency window is required but unresolved.');
      if(config.contradiction&&['preserve_weaker','latest_weaker_flags_concern','ignore_weaker'].indexOf(config.contradiction.mode)<0)fail('INVALID_STRATEGY','Contradiction mode is invalid.');
      if(config.reassessmentPreference&&['include_all','latest_reassessment','prefer_highest'].indexOf(config.reassessmentPreference)<0)fail('INVALID_STRATEGY','Reassessment preference is invalid.');
      return config;
    }
    async function createStrategy(input){
      var version=await db.read(S.competencyVersions,input.competencyVersionId);if(!version)fail('REFERENCE_NOT_FOUND','Competency version does not exist.');var config=validateStrategy(input),number=Number(input.strategyVersion);if(!(number>0))fail('INVALID_STRATEGY','Positive strategy version is required.');
      if((await db.query(S.competencyStrategies,'by_competency_strategy_version',[version.competencyVersionId,number])).length)fail('DUPLICATE_STRATEGY_VERSION','Strategy version already exists.');
      var row=stamp({competencyId:version.competencyId,competencyVersionId:version.competencyVersionId,strategyVersion:number,family:input.family,config:config,provenance:input.provenance||{}},'strategyConfigId',db.generateId(),'active');await db.add(S.competencyStrategies,row);return row;
    }
    async function updateStrategy(id,expectedRevision,changes){
      return db.transaction([S.competencyStrategies,S.evidenceRecords],async function(tx){var current=await tx.get(S.competencyStrategies,id);if(!current)fail('REFERENCE_NOT_FOUND','Strategy does not exist.');if(current.revision!==expectedRevision)fail('WRITE_CONFLICT','Strategy changed after it was read.');if(changes.competencyId||changes.competencyVersionId||changes.strategyVersion||changes.family)fail('IMMUTABLE_IDENTITY','Strategy identity is immutable.');if((await tx.query(S.evidenceRecords)).some(function(r){return r.strategyConfigId===id;}))fail('HISTORICAL_LOCK','Used strategy configuration is immutable.');var config=validateStrategy({family:current.family,config:changes.config||current.config}),next=Object.assign({},current,changes,{config:config,revision:current.revision+1,updatedAt:now(),updatedBy:actor});await tx.put(S.competencyStrategies,next);return next;});
    }
    async function declaration(tx,id){var d=await tx.get(S.activityDeclarations,id);if(!d)fail('REFERENCE_NOT_FOUND','Evidence Declaration does not exist.');return d;}
    async function validateSource(tx,input){
      var student=await tx.get(S.students,input.studentId),enrollment=await tx.get(S.enrollments,input.enrollmentId);if(!student||!enrollment||enrollment.studentId!==input.studentId)fail('INTEGRITY_MISMATCH','Evidence Source Student and Enrollment disagree.');
      var result={student:student,enrollment:enrollment,activityVersion:null,activityDefinition:null,declaration:null};
      if((input.activityVersionId&&!input.projectId)||input.studentActivityId||input.activityAttemptId){if(!input.studentActivityId)fail('INTEGRITY_MISMATCH','ActivityVersion Evidence requires StudentActivity lineage.');var sa=await tx.get(S.studentActivities,input.studentActivityId);if(!sa||sa.studentId!==input.studentId||sa.enrollmentId!==input.enrollmentId)fail('INTEGRITY_MISMATCH','StudentActivity lineage is invalid.');var av=await tx.get(S.activityVersions,sa.versionId),ad=av&&await tx.get(S.activityDefinitions,av.definitionId);if(!av||!ad||input.activityVersionId!==av.versionId)fail('INTEGRITY_MISMATCH','ActivityVersion lineage is invalid.');if(input.activityAttemptId){var attempt=await tx.get(S.activityAttempts,input.activityAttemptId);if(!attempt||attempt.studentActivityId!==sa.studentActivityId)fail('INTEGRITY_MISMATCH','ActivityAttempt lineage is invalid.');}result.activityVersion=av;result.activityDefinition=ad;}
      if(input.projectId||input.buildId||input.checkpointEventId||input.rubricAssessmentId){var project=await tx.get(S.projectInstances,input.projectId),build=await tx.get(S.projectBuilds,input.buildId);if(!project||project.studentId!==input.studentId||project.enrollmentId!==input.enrollmentId||!build||build.projectId!==project.projectId)fail('INTEGRITY_MISMATCH','Project and Build lineage is invalid.');if(input.activityVersionId!==project.versionId)fail('INTEGRITY_MISMATCH','Project Version lineage is invalid.');if(input.checkpointEventId){var event=await tx.get(S.projectCheckpointEvents,input.checkpointEventId);if(!event||event.projectId!==project.projectId||event.buildId!==build.buildId||event.checkpointCode!==input.sourcePoint)fail('INTEGRITY_MISMATCH','Checkpoint event lineage is invalid.');}if(input.rubricAssessmentId){var rubric=await tx.get(S.projectRubrics,input.rubricAssessmentId);if(!rubric||rubric.projectId!==project.projectId)fail('INTEGRITY_MISMATCH','Project rubric lineage is invalid.');}}
      if(input.declarationId){var dec=await declaration(tx,input.declarationId);if(dec.versionId!==input.activityVersionId||dec.sourcePoint!==input.sourcePoint)fail('UNAUTHORIZED_SOURCE_POINT','Declaration does not authorize the exact Version/source point.');result.declaration=dec;}
      if(input.projectId&&!result.declaration)fail('UNAUTHORIZED_SOURCE_POINT','Project Evidence requires an exact Declaration.');return result;
    }
    async function createSource(input){
      var stores=[S.students,S.enrollments,S.studentActivities,S.activityAttempts,S.activityVersions,S.activityDefinitions,S.activityDeclarations,S.projectInstances,S.projectBuilds,S.projectCheckpointEvents,S.projectRubrics,S.evidenceSources];
      return db.transaction(stores,async function(tx){if(!input.studentId||!input.enrollmentId||SOURCE_TYPES.indexOf(input.sourceType)<0||!input.occurredAt)fail('INVALID_EVIDENCE_SOURCE','One Student, Enrollment, valid source type, and occurrence time are required.');await validateSource(tx,input);var row=stamp({studentId:input.studentId,enrollmentId:input.enrollmentId,sourceType:String(input.sourceType),occurredAt:String(input.occurredAt),recordedAt:input.recordedAt||now(),recordedBy:input.recordedBy||actor,academicScope:input.academicScope||{},activityVersionId:input.activityVersionId||null,studentActivityId:input.studentActivityId||null,activityAttemptId:input.activityAttemptId||null,projectId:input.projectId||null,buildId:input.buildId||null,checkpointEventId:input.checkpointEventId||null,rubricAssessmentId:input.rubricAssessmentId||null,sourcePoint:input.sourcePoint||null,declarationId:input.declarationId||null,context:input.context||{},notes:String(input.notes||''),reassessmentOfSourceId:input.reassessmentOfSourceId||null,supersedesSourceId:input.supersedesSourceId||null,voidReason:null},'sourceId',db.generateId(),'active');if(row.reassessmentOfSourceId){var priorSource=await tx.get(S.evidenceSources,row.reassessmentOfSourceId);if(!priorSource)fail('REFERENCE_NOT_FOUND','Reassessment source does not exist.');if(priorSource.studentId!==row.studentId||priorSource.enrollmentId!==row.enrollmentId)fail('INTEGRITY_MISMATCH','Reassessment source lineage is invalid.');}await tx.add(S.evidenceSources,row);return row;});
    }
    async function correctSource(input){
      var stores=[S.students,S.enrollments,S.studentActivities,S.activityAttempts,S.activityVersions,S.activityDefinitions,S.activityDeclarations,S.projectInstances,S.projectBuilds,S.projectCheckpointEvents,S.projectRubrics,S.evidenceSources];
      return db.transaction(stores,async function(tx){var prior=await tx.get(S.evidenceSources,input.supersedesSourceId);if(!prior)fail('REFERENCE_NOT_FOUND','Prior Evidence Source does not exist.');if(prior.revision!==input.expectedSourceRevision)fail('WRITE_CONFLICT','Evidence Source changed after it was read.');var replacement=Object.assign({},prior,input.replacement||{},{studentId:prior.studentId,enrollmentId:prior.enrollmentId,supersedesSourceId:prior.sourceId,sourceId:undefined,voidReason:input.void?String(input.reason||'voided'):null});delete replacement.sourceId;await validateSource(tx,replacement);var row=stamp(replacement,'sourceId',db.generateId(),input.void?'voided':'active'),revised=Object.assign({},prior,{revision:prior.revision+1,updatedAt:now(),updatedBy:actor});await tx.put(S.evidenceSources,revised);await tx.add(S.evidenceSources,row);return{source:row,prior:revised};});
    }
    async function validateRecord(tx,input,source){
      var version=await tx.get(S.competencyVersions,input.competencyVersionId),competency=version&&await tx.get(S.competencyDefinitions,version.competencyId);if(!version||!competency||competency.competencyId!==input.competencyId)fail('INTEGRITY_MISMATCH','Evidence competency/version lineage is invalid.');
      if(QUALIFICATIONS.indexOf(input.qualification)<0||MODES.indexOf(input.evidenceMode)<0)fail('INVALID_EVIDENCE_RECORD','Qualification or evidence mode is invalid.');
      if(input.demonstratedLevel!==null&&input.demonstratedLevel!==undefined&&![1,2,3,4].includes(input.demonstratedLevel))fail('INVALID_EVIDENCE_RECORD','Demonstrated level must be 1–4 or an allowed null.');
      if(input.demonstratedLevel===null||input.demonstratedLevel===undefined){var strategy=input.strategyConfigId&&await tx.get(S.competencyStrategies,input.strategyConfigId);if(MODES.indexOf(input.evidenceMode)<0||['Workflow','Habit/Continuous'].indexOf(input.evidenceMode)<0||!strategy||!strategy.config.allowNullLevelEvidence)fail('INVALID_NULL_LEVEL','Null level requires an authorized event/continuous strategy.');}
      if(input.declarationId){var dec=await declaration(tx,input.declarationId),ref=dec.competencyRef||{},matches=ref.competencyId===competency.competencyId||(ref.code===competency.code&&(!ref.catalogId||ref.catalogId===competency.catalogId));if(dec.versionId!==source.activityVersionId||source.declarationId!==dec.declarationId||!matches)fail('DECLARATION_MISMATCH','Declaration does not authorize this competency claim.');}
      if(source.declarationId&&!input.declarationId)fail('DECLARATION_MISMATCH','Declaration-backed Source requires Declaration-backed Records.');
      if(source.activityVersionId){var av=await tx.get(S.activityVersions,source.activityVersionId),ad=av&&await tx.get(S.activityDefinitions,av.definitionId);if(ad&&ad.type==='Practice'&&input.qualification==='Qualifying')fail('INVALID_QUALIFICATION','Practice Evidence cannot be Qualifying.');}
      return{version:version,competency:competency};
    }
    async function createRecord(input){
      return db.transaction([S.evidenceSources,S.evidenceRecords,S.competencyDefinitions,S.competencyVersions,S.competencyStrategies,S.activityDeclarations,S.activityVersions,S.activityDefinitions,S.enrollments],async function(tx){var source=await tx.get(S.evidenceSources,input.sourceId);if(!source||source.lifecycle!=='active')fail('REFERENCE_NOT_FOUND','Active Evidence Source does not exist.');var validated=await validateRecord(tx,input,source),enrollment=await tx.get(S.enrollments,source.enrollmentId);if(!enrollment||validated.competency.courseIds.indexOf(enrollment.courseId)<0)fail('INTEGRITY_MISMATCH','Competency is not applicable to the Evidence Course.');var row=stamp({sourceId:source.sourceId,studentId:source.studentId,enrollmentId:source.enrollmentId,competencyId:input.competencyId,competencyVersionId:input.competencyVersionId,declarationId:input.declarationId||null,strategyConfigId:input.strategyConfigId||null,demonstratedLevel:input.demonstratedLevel===undefined?null:input.demonstratedLevel,qualification:input.qualification,evidenceMode:input.evidenceMode,qualificationReason:input.qualificationReason||{},criterionRefs:list(input.criterionRefs),resultRefs:list(input.resultRefs),context:input.context||{},diversity:input.diversity||null,reassessmentRelation:input.reassessmentRelation||null,supersedesEvidenceRecordId:null,correctionReason:null},'evidenceRecordId',db.generateId(),'active');await tx.add(S.evidenceRecords,row);return row;});
    }
    async function correctRecord(input){
      return db.transaction([S.evidenceSources,S.evidenceRecords,S.competencyDefinitions,S.competencyVersions,S.competencyStrategies,S.activityDeclarations,S.activityVersions,S.activityDefinitions],async function(tx){var prior=await tx.get(S.evidenceRecords,input.supersedesEvidenceRecordId);if(!prior)fail('REFERENCE_NOT_FOUND','Prior Evidence Record does not exist.');var source=await tx.get(S.evidenceSources,prior.sourceId);if(source.revision!==input.expectedSourceRevision)fail('WRITE_CONFLICT','Evidence Source changed after it was read.');var replacement=Object.assign({},prior,input.replacement||{},{sourceId:prior.sourceId,studentId:prior.studentId,enrollmentId:prior.enrollmentId,competencyId:prior.competencyId,competencyVersionId:prior.competencyVersionId,declarationId:prior.declarationId,strategyConfigId:prior.strategyConfigId,supersedesEvidenceRecordId:prior.evidenceRecordId,correctionReason:String(input.reason||''),evidenceRecordId:undefined});delete replacement.evidenceRecordId;await validateRecord(tx,replacement,source);var row=stamp(replacement,'evidenceRecordId',db.generateId(),input.void?'voided':'active');source=Object.assign({},source,{revision:source.revision+1,updatedAt:now(),updatedBy:actor});await tx.put(S.evidenceSources,source);await tx.add(S.evidenceRecords,row);return{record:row,source:source};});
    }
    function inScope(source,scope){if(!scope||!scope.enrollmentId)fail('INVALID_SCOPE','Explicit Enrollment scope is required.');if(source.enrollmentId!==scope.enrollmentId)return false;for(var k in scope)if(k!=='enrollmentId'&&scope[k]!==undefined&&source.academicScope&&source.academicScope[k]!==scope[k])return false;return true;}
    async function derive(input){
      var strategy=await db.read(S.competencyStrategies,input.strategyConfigId);if(!strategy||strategy.competencyId!==input.competencyId)fail('INTEGRITY_MISMATCH','Strategy does not belong to competency.');validateStrategy(strategy);var sources=await db.query(S.evidenceSources,'by_student',input.studentId),records=await db.query(S.evidenceRecords,'by_competency',input.competencyId),safetyEvents=await db.query(S.safetyEvents,'by_student',input.studentId),workplaceDays=await db.query(S.workplaceDays,'by_student',input.studentId),sourceMap={},successors={},safetySuccessors={},safetyUsable={};safetyEvents.forEach(function(x){if(x.supersedesSafetyEventId)safetySuccessors[x.supersedesSafetyEventId]=x;});safetyEvents.forEach(function(x){var latest=x,seen={};while(safetySuccessors[latest.safetyEventId]&&!seen[latest.safetyEventId]){seen[latest.safetyEventId]=true;latest=safetySuccessors[latest.safetyEventId];}if(latest.lifecycle==='active')safetyUsable[x.safetyEventId]=true;});sources.forEach(function(s){if(s.supersedesSourceId)successors[s.supersedesSourceId]=s;});sources.forEach(function(source){var latest=source,seen={};while(successors[latest.sourceId]&&!seen[latest.sourceId]){seen[latest.sourceId]=true;latest=successors[latest.sourceId];}var safetyId=latest.context&&latest.context.safetyEventId,safetyValid=latest.sourceType!=='Continuous Safety'||!safetyId||safetyUsable[safetyId],workplaceDayId=latest.context&&latest.context.workplaceDayId,workplaceValid=latest.sourceType!=='Continuous Workplace'||!workplaceDayId||workplaceDays.some(function(d){return d.workplaceDayId===workplaceDayId&&d.lifecycle==='active'&&d.applicabilityState==='Applicable';});if(latest.lifecycle==='active'&&safetyValid&&workplaceValid&&inScope(latest,input.scope))sourceMap[source.sourceId]=latest;});
      var superseded={};records.filter(function(r){return sourceMap[r.sourceId]&&r.supersedesEvidenceRecordId;}).forEach(function(r){superseded[r.supersedesEvidenceRecordId]=true;});var relevant=records.filter(function(r){return sourceMap[r.sourceId]&&!superseded[r.evidenceRecordId]&&r.lifecycle==='active';});
      if(strategy.config.reassessmentPreference==='latest_reassessment'){var replaced={};Object.values(sourceMap).forEach(function(s){if(s.reassessmentOfSourceId)replaced[s.reassessmentOfSourceId]=true;});relevant=relevant.filter(function(r){return !replaced[r.sourceId];});}
      relevant.sort(function(a,b){var sa=sourceMap[a.sourceId],sb=sourceMap[b.sourceId];return sa.occurredAt.localeCompare(sb.occurredAt)||a.evidenceRecordId.localeCompare(b.evidenceRecordId);});
      var qualificationFilter=list(strategy.config.qualificationFilter).length?strategy.config.qualificationFilter:['Qualifying'],allowedModes=list(strategy.config.allowedEvidenceModes),allowedSources=list(strategy.config.allowedSourceTypes),contributing=relevant.filter(function(r){return qualificationFilter.indexOf(r.qualification)>=0&&r.demonstratedLevel!==null&&(!allowedModes.length||allowedModes.indexOf(r.evidenceMode)>=0)&&(!allowedSources.length||allowedSources.indexOf(sourceMap[r.sourceId].sourceType)>=0);}),levels=contributing.map(function(r){return r.demonstratedLevel;}),highest=levels.length?Math.max.apply(null,levels):null,latest=contributing.length?contributing[contributing.length-1].demonstratedLevel:null,derived=highest,contradictory=[];
      if(highest!==null)contradictory=contributing.filter(function(r){return r.demonstratedLevel<highest;}).map(function(r){return r.evidenceRecordId;});
      var confirmationConfig=strategy.config.confirmation||{},required=confirmationConfig.enabled?confirmationConfig.requiredCount:1,confirming=derived===null?[]:contributing.filter(function(r){return r.demonstratedLevel===derived;}),confirmed=derived!==null&&confirming.length>=required;
      var diversityConfig=strategy.config.diversity||{},values=[];if(diversityConfig.enabled)confirming.forEach(function(r){if(r.diversity&&r.diversity.dimension===diversityConfig.dimension&&r.diversity.value!==undefined&&values.indexOf(r.diversity.value)<0)values.push(r.diversity.value);});var diversitySatisfied=!diversityConfig.enabled||values.length>=diversityConfig.requiredDistinct;
      var concern=!!(strategy.config.contradiction&&strategy.config.contradiction.mode==='latest_weaker_flags_concern'&&highest!==null&&latest<highest),requirements=[];if(derived!==null&&!confirmed)requirements.push({type:'confirmation',remaining:required-confirming.length});if(!diversitySatisfied)requirements.push({type:'diversity',dimension:diversityConfig.dimension,remaining:diversityConfig.requiredDistinct-values.length});
      var recency={enabled:!!(strategy.config.recency&&strategy.config.recency.enabled),windowDays:strategy.config.recency&&strategy.config.recency.windowDays||null,status:strategy.config.recency&&strategy.config.recency.enabled?(strategy.config.recency.windowDays?'configured':'capability_without_window'):'not_applicable'};
      var fpData={studentId:input.studentId,competencyId:input.competencyId,scope:input.scope,strategy:{id:strategy.strategyConfigId,revision:strategy.revision,version:strategy.strategyVersion},records:relevant.map(function(r){return{id:r.evidenceRecordId,revision:r.revision,sourceRevision:sourceMap[r.sourceId].revision};})};
      return{studentId:input.studentId,competencyId:input.competencyId,scope:canonical(input.scope),strategyConfigId:strategy.strategyConfigId,strategyVersion:strategy.strategyVersion,family:strategy.family,evidenceDerivedLevel:derived,confirmation:{confirmed:confirmed,count:confirming.length,required:required},highestDemonstratedLevel:highest,recentDemonstratedLevel:latest,contributingRecordIds:contributing.map(function(r){return r.evidenceRecordId;}),contradictoryRecordIds:contradictory,relevantRecordIds:relevant.map(function(r){return r.evidenceRecordId;}),requirementsSatisfied:derived!==null&&confirmed&&diversitySatisfied,requirementsRemaining:requirements,diversity:{enabled:!!diversityConfig.enabled,dimension:diversityConfig.dimension||null,values:values,satisfied:diversitySatisfied},recency:recency,operationalHooks:{concern:concern},structuredReasons:{qualificationFiltering:qualificationFilter,sourceTypeFiltering:allowedSources,evidenceModeFiltering:allowedModes,contradictionPolicy:strategy.config.contradiction&&strategy.config.contradiction.mode||'preserve_weaker',reassessmentPreference:strategy.config.reassessmentPreference||'include_all'},evidenceFingerprint:fingerprint(fpData),calculatedAt:input.calculatedAt||now()};
    }
    async function appendOverride(input){
      var competency=await db.read(S.competencyDefinitions,input.competencyId),student=await db.read(S.students,input.studentId),version=input.competencyVersionId&&await db.read(S.competencyVersions,input.competencyVersionId);if(!competency||!student||!input.scope||!input.scope.enrollmentId)fail('REFERENCE_NOT_FOUND','Override Student, competency, and explicit scope are required.');if(input.competencyVersionId&&(!version||version.competencyId!==competency.competencyId))fail('INTEGRITY_MISMATCH','Override competency Version is invalid.');var key=scopeKey(input.scope),history=await db.query(S.instructorOverrides,'by_scope',[input.studentId,input.competencyId,key]),chainRevision=history.reduce(function(max,x){return Math.max(max,x.chainRevision||0);},0),latest=history.find(function(x){return x.chainRevision===chainRevision;});if(chainRevision!==(input.expectedChainRevision||0))fail('WRITE_CONFLICT','Override authority changed after it was read.');if(input.action!=='Apply'&&input.action!=='Revoke')fail('INVALID_OVERRIDE','Override action is invalid.');if(input.action==='Apply'&&![1,2,3,4].includes(input.authoritativeLevel))fail('INVALID_OVERRIDE','Override level must be 1–4.');if(chainRevision>0&&(!input.supersedesOverrideId||!latest||input.supersedesOverrideId!==latest.overrideId))fail('INVALID_OVERRIDE','New Override authority must supersede the current chain head.');if(input.action==='Revoke'&&chainRevision===0)fail('INVALID_OVERRIDE','There is no Override authority to revoke.');var row=stamp({studentId:input.studentId,competencyId:input.competencyId,competencyVersionId:input.competencyVersionId||null,scope:canonical(input.scope),scopeKey:key,strategyConfigId:input.strategyConfigId||null,derivationFingerprint:input.derivationFingerprint||null,action:input.action,authoritativeLevel:input.action==='Apply'?input.authoritativeLevel:null,authoritativeState:input.authoritativeState||null,reason:input.reason||{},explanation:String(input.explanation||''),reviewPolicy:input.reviewPolicy||{},reviewDate:input.reviewDate||null,supersedesOverrideId:input.supersedesOverrideId||null,chainRevision:chainRevision+1},'overrideId',db.generateId(),'active');await db.add(S.instructorOverrides,row);return row;
    }
    async function resolve(input){var derivation=await derive(input),key=scopeKey(input.scope),history=await db.query(S.instructorOverrides,'by_scope',[input.studentId,input.competencyId,key]);history.sort(function(a,b){return (a.chainRevision||0)-(b.chainRevision||0);});var latest=history.length?history[history.length-1]:null,active=latest&&latest.action==='Apply'?latest:null,review=false;if(active&&active.reviewPolicy&&active.reviewPolicy.onNewEvidence){var records=await db.query(S.evidenceRecords,'by_competency',input.competencyId),sources=await db.query(S.evidenceSources,'by_student',input.studentId),sourceMap={};sources.forEach(function(s){sourceMap[s.sourceId]=s;});review=records.some(function(r){var source=sourceMap[r.sourceId];return derivation.relevantRecordIds.indexOf(r.evidenceRecordId)>=0&&source&&source.recordedAt>active.createdAt;});}return{studentId:input.studentId,competencyId:input.competencyId,scope:derivation.scope,evidenceDerivedState:derivation,resolvedOfficialLevel:active?active.authoritativeLevel:derivation.evidenceDerivedLevel,authoritySource:active?'InstructorOverride':'EvidenceDerivation',confirmation:derivation.confirmation,overrideProvenance:active?{overrideId:active.overrideId,chainRevision:active.chainRevision,reason:active.reason}:null,structuredReasons:active?{override:true,evidencePreserved:true}:derivation.structuredReasons,reviewRequired:review};}
    return{createCompetency:createCompetency,updateCompetency:updateCompetency,createCompetencyVersion:createCompetencyVersion,updateCompetencyVersion:updateCompetencyVersion,createStrategy:createStrategy,updateStrategy:updateStrategy,createEvidenceSource:createSource,correctEvidenceSource:correctSource,createEvidenceRecord:createRecord,correctEvidenceRecord:correctRecord,appendInstructorOverride:appendOverride,deriveCompetency:derive,resolveCompetency:resolve,families:FAMILIES,qualifications:QUALIFICATIONS,modes:MODES,sourceTypes:SOURCE_TYPES,fingerprint:fingerprint};
  }
  return{create:create,FAMILIES:FAMILIES,QUALIFICATIONS:QUALIFICATIONS,MODES:MODES,SOURCE_TYPES:SOURCE_TYPES,fingerprint:fingerprint};
}));
