/* Stage 14 P4 shared academic consumer projection. No persisted view state. */
(function(root,factory){var req=typeof require==='function'?require:null,api=factory(root.ArcV8Storage||(req&&req('./arc_v8_storage')),root.ArcEffectiveSectionContext||(req&&req('./arc_effective_section_context')));if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcAcademicConsumerProjection=api;}(this,function(Storage,Effective){
  'use strict';
  var S=Storage.STORES,CONSUMERS=Object.freeze(['dashboard','class-selector','students-directory','global-search','fast-roster','student-profile','current-class','gradebook','projects','technical','workplace']);
  function copy(x){return x==null?x:JSON.parse(JSON.stringify(x));}
  function active(row,day,start,end){return row&&row.lifecycle!=='archived'&&row.lifecycle!=='void'&&row[start]<=day&&(!row[end]||row[end]>=day);}
  function studentName(s){return String(s.preferredName||[s.legalFirstName,s.legalLastName].filter(Boolean).join(' ')||s.name||'').trim();}
  function sortStudent(a,b){return a.displayName.localeCompare(b.displayName)||a.studentId.localeCompare(b.studentId);}
  function legacyContext(section){return section?{section:section,sectionId:section.sectionId,courseId:section.courseId,schoolYearId:section.schoolYearId,semesterId:section.semesterId,periodCode:String(section.period),placementId:null,effectiveFrom:null,effectiveTo:null}:null;}
  function build(input){input=input||{};var day=String(input.day),legacy=input.authorityState==='V7_ONLY',sections=(input.sections||[]).slice(),students=(input.students||[]).slice(),enrollments=(input.enrollments||[]).slice(),assignments=(input.scheduleAssignments||[]).slice(),courses=(input.courses||[]).slice(),years=(input.schoolYears||[]).slice(),semesters=(input.semesters||[]).slice(),placements=(input.sectionPlacements||[]).slice(),selectedId=input.selectedSectionId||null,courseMap={},sectionMap={};courses.forEach(function(x){courseMap[x.courseId]=x;});sections.forEach(function(x){sectionMap[x.sectionId]=x;});var effectiveMap={};if(!legacy)sections.forEach(function(section){effectiveMap[section.sectionId]=Effective.resolve({sectionId:section.sectionId,schoolDate:day,sections:sections,sectionPlacements:placements,semesters:semesters,schoolYears:years});});var currentYear=years.filter(function(x){return active(x,day,'startDate','endDate');}).sort(function(a,b){return a.startDate.localeCompare(b.startDate);})[0]||null,currentSemester=semesters.filter(function(x){return active(x,day,'startDate','endDate')&&(!currentYear||x.schoolYearId===currentYear.schoolYearId);}).sort(function(a,b){return a.order-b.order;})[0]||null,contexts=[];
    students.forEach(function(student){var studentEnrollments=enrollments.filter(function(x){return x.studentId===student.studentId;}).sort(function(a,b){return a.enrollmentStart.localeCompare(b.enrollmentStart)||a.enrollmentId.localeCompare(b.enrollmentId);}),currentEnrollment=studentEnrollments.filter(function(x){return active(x,day,'enrollmentStart','enrollmentEnd');}).slice(-1)[0]||null,currentAssignment=currentEnrollment?assignments.filter(function(x){return x.enrollmentId===currentEnrollment.enrollmentId&&active(x,day,'effectiveFrom','effectiveTo');}).sort(function(a,b){return a.effectiveFrom.localeCompare(b.effectiveFrom)||a.scheduleAssignmentId.localeCompare(b.scheduleAssignmentId);}).slice(-1)[0]||null:null,section=currentAssignment?sectionMap[currentAssignment.sectionId]||null:null,sectionContext=section?(legacy?legacyContext(section):effectiveMap[section.sectionId]||null):null,course=currentEnrollment?courseMap[currentEnrollment.courseId]||null:null;contexts.push({studentId:student.studentId,displayName:studentName(student),student:student,currentEnrollment:currentEnrollment,currentScheduleAssignment:currentAssignment,currentSection:section,currentSectionContext:sectionContext,currentCourse:course,isCurrent:student.lifecycle==='active'&&!!currentEnrollment&&!!currentAssignment&&!!sectionContext,enrollmentHistory:studentEnrollments,scheduleHistory:assignments.filter(function(x){return studentEnrollments.some(function(e){return e.enrollmentId===x.enrollmentId;});})});});
    contexts.sort(sortStudent);var currentContexts=contexts.filter(function(x){return x.isCurrent;}),rosters={};sections.forEach(function(section){rosters[section.sectionId]=currentContexts.filter(function(x){return x.currentSection&&x.currentSection.sectionId===section.sectionId;});});var currentSection=null,currentSectionContext=null;if(input.currentPeriodCode!=null){if(legacy){currentSection=sections.find(function(x){return String(x.period)===String(input.currentPeriodCode)&&x.lifecycle==='active';})||null;currentSectionContext=legacyContext(currentSection);}else{var matches=Object.keys(effectiveMap).map(function(k){return effectiveMap[k];}).filter(function(x){return x&&x.periodCode===String(input.currentPeriodCode);});if(matches.length>1){var e=new Error('More than one Section occupies the requested period.');e.code='AMBIGUOUS_SECTION_PLACEMENT';throw e;}currentSectionContext=matches[0]||null;currentSection=currentSectionContext&&sectionMap[currentSectionContext.sectionId]||null;}}
    var selectedCandidate=sectionMap[selectedId]||null,selectedSectionContext=selectedCandidate?(legacy?legacyContext(selectedCandidate):effectiveMap[selectedCandidate.sectionId]||null):null,selectedSection=selectedSectionContext?selectedCandidate:null,scope={day:day,schoolYearId:currentYear&&currentYear.schoolYearId||null,semesterId:currentSemester&&currentSemester.semesterId||null,selectedSectionId:selectedSection&&selectedSection.sectionId||null,currentSectionId:currentSection&&currentSection.sectionId||null};
    function contextForStudent(id){return contexts.find(function(x){return x.studentId===id;})||null;}function rosterForSection(id){return(rosters[id]||[]).slice();}function scopeForStudent(id){var x=contextForStudent(id);return x&&x.isCurrent?{studentId:x.studentId,enrollmentId:x.currentEnrollment.enrollmentId,scheduleAssignmentId:x.currentScheduleAssignment.scheduleAssignmentId,sectionId:x.currentSectionContext.sectionId,courseId:x.currentCourse&&x.currentCourse.courseId||x.currentEnrollment.courseId,schoolYearId:x.currentSectionContext.schoolYearId,semesterId:x.currentSectionContext.semesterId,periodCode:x.currentSectionContext.periodCode,placementId:x.currentSectionContext.placementId}:null;}function consumerContext(name,studentId){if(CONSUMERS.indexOf(name)<0)throw new Error('Unknown academic consumer: '+name);return{consumer:name,authorityState:input.authorityState,scope:copy(scope),studentScope:studentId?scopeForStudent(studentId):null,selectedSection:selectedSection,selectedSectionContext:copy(selectedSectionContext),currentSection:currentSection,currentSectionContext:copy(currentSectionContext),roster:selectedSection?rosterForSection(selectedSection.sectionId):[]};}return{authorityState:input.authorityState,day:day,students:contexts,sections:sections.slice(),selectedSection:selectedSection,selectedSectionContext:selectedSectionContext,currentSection:currentSection,currentSectionContext:currentSectionContext,schoolYear:currentYear,semester:currentSemester,scope:scope,contextForStudent:contextForStudent,rosterForSection:rosterForSection,scopeForStudent:scopeForStudent,consumerContext:consumerContext,consumers:CONSUMERS};}
  function legacy(state,options){options=options||{};var students=[],seen={},enrollments=[],assignments=[];(Object.keys(state.classes||{})).forEach(function(course){(state.classes[course]||[]).forEach(function(s){if(!seen[s.id]){seen[s.id]=true;students.push({studentId:s.id,preferredName:s.name,gradeLevel:String(s.grade||''),lifecycle:s.archived?'archived':'active',legacyRecord:s});}(s.enrollments||[]).forEach(function(e,i){var enrollmentId=e.enrollmentId||['legacy-enrollment',s.id,e.year,e.course||course,i].join(':'),assignmentId=e.scheduleAssignmentId||['legacy-assignment',enrollmentId,e.sectionId,i].join(':'),isCurrent=e.active!==false&&e.year===state.academicYear&&e.semester===state.semester;enrollments.push({enrollmentId:enrollmentId,studentId:s.id,courseId:e.course==='awt'?'arc-course-awt':'arc-course-wt',schoolYearId:e.year,enrollmentStart:e.startDate||'0001-01-01',enrollmentEnd:isCurrent?null:(e.endDate||'0001-01-01'),status:isCurrent?'active':'closed',lifecycle:isCurrent?'active':'closed',legacyRecord:e});assignments.push({scheduleAssignmentId:assignmentId,enrollmentId:enrollmentId,sectionId:e.sectionId,effectiveFrom:e.startDate||'0001-01-01',effectiveTo:isCurrent?null:(e.endDate||'0001-01-01'),lifecycle:isCurrent?'active':'ended',legacyRecord:e});});});});return build({authorityState:'V7_ONLY',day:options.day,selectedSectionId:options.selectedSectionId,currentPeriodCode:options.currentPeriodCode,courses:[{courseId:'arc-course-wt',code:'WT'},{courseId:'arc-course-awt',code:'AWT'}],schoolYears:[{schoolYearId:state.academicYear,label:state.academicYear,startDate:'0001-01-01',endDate:'9999-12-31',lifecycle:'active'}],semesters:[{semesterId:state.semester,schoolYearId:state.academicYear,label:state.semester,startDate:'0001-01-01',endDate:'9999-12-31',order:1,lifecycle:'active'}],sections:(state.sections||[]).map(function(x){return{sectionId:x.id,courseId:x.course==='awt'?'arc-course-awt':'arc-course-wt',schoolYearId:state.academicYear,semesterId:state.semester,period:String(x.period),displayName:x.name,lifecycle:'active',legacyRecord:x};}),students:students,enrollments:enrollments,scheduleAssignments:assignments,sectionPlacements:[]});}
  async function loadV8Snapshot(storage){var values=await Promise.all([storage.query(S.courses),storage.query(S.schoolYears),storage.query(S.semesters),storage.query(S.sections),storage.query(S.students),storage.query(S.enrollments),storage.query(S.scheduleAssignments),storage.query(S.infrastructure)]);return{courses:values[0],schoolYears:values[1],semesters:values[2],sections:values[3],students:values[4],enrollments:values[5],scheduleAssignments:values[6],sectionPlacements:values[7].filter(function(x){return x.authorityType==='section-placement';})};}
  function fromV8Snapshot(snapshot,options){options=options||{};return build(Object.assign({},snapshot,{authorityState:options.authorityState||'V8_ISOLATED_VERIFICATION',day:options.day,selectedSectionId:options.selectedSectionId,currentPeriodCode:options.currentPeriodCode}));}
  async function v8(storage,options){return fromV8Snapshot(await loadV8Snapshot(storage),options);}
  function createCache(options){options=options||{};if(typeof options.load!=='function')throw new Error('Academic projection cache requires one v8 loader.');var generation=0,loadedGeneration=-1,value=null,loading=null;
    async function reload(context){var target=++generation;loading=Promise.resolve(options.load(context||{})).then(function(next){if(target===generation){value=next;loadedGeneration=target;}return next;}).finally(function(){loading=null;});return loading;}
    function get(){if(!value||loadedGeneration!==generation){var e=new Error('The authoritative academic projection has not been initialized or was invalidated.');e.code='ACADEMIC_PROJECTION_NOT_READY';throw e;}return value;}
    function invalidate(){generation++;value=null;loadedGeneration=-1;}
    return{initialize:reload,reload:reload,get:get,invalidate:invalidate,isReady:function(){return!!value&&loadedGeneration===generation;},generation:function(){return generation;}};
  }
  function createAuthoritativeCache(options){options=options||{};var storage=options.storage,authorityState=options.authorityState||'V8_AUTHORITATIVE',snapshot=null,generation=0;if(!storage)throw new Error('Authoritative projection cache requires v8 storage.');return{initialize:async function(){snapshot=await loadV8Snapshot(storage);generation++;return fromV8Snapshot(snapshot,Object.assign({},arguments[0],{authorityState:authorityState}));},reload:async function(context){snapshot=await loadV8Snapshot(storage);generation++;return fromV8Snapshot(snapshot,Object.assign({},context,{authorityState:authorityState}));},get:function(context){if(!snapshot){var e=new Error('The authoritative academic projection has not been initialized or was invalidated.');e.code='ACADEMIC_PROJECTION_NOT_READY';throw e;}return fromV8Snapshot(snapshot,Object.assign({},context,{authorityState:authorityState}));},invalidate:function(){snapshot=null;generation++;},isReady:function(){return!!snapshot;},generation:function(){return generation;}};}
  return{fromLegacy:legacy,fromV8:v8,loadV8Snapshot:loadV8Snapshot,fromV8Snapshot:fromV8Snapshot,build:build,createCache:createCache,createAuthoritativeCache:createAuthoritativeCache,consumers:CONSUMERS};
}));
