/* Engineering-only read-only capture of the live Schema-7 schedule configuration. */
(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcV7ScheduleConfigurationCapture=api;}(this,function(){
'use strict';
var KEY='weld_v013';
function fail(code,message,context){var error=new Error(message);error.code=code;error.context=context||{};throw error;}
function object(value,family){if(!value||typeof value!=='object'||Array.isArray(value))fail('LIVE_SCHEMA7_CONFIGURATION_INVALID','A present configuration family must be an object.',{family:family});return value;}
function own(source,key){return Object.prototype.hasOwnProperty.call(source,key);}
function scalar(source,key,target){if(own(source,key)){var value=source[key];if(value!==null&&typeof value==='object')fail('LIVE_SCHEMA7_CONFIGURATION_INVALID','Configuration scalar fields must not contain nested values.',{field:key});target[key]=value;}}
function timeRows(source,family){source=object(source,family);var out={};Object.keys(source).forEach(function(key){var row=object(source[key],family+'.'+key),safe={};scalar(row,'start',safe);scalar(row,'end',safe);out[key]=safe;});return out;}
function exactDate(value,field){value=String(value==null?'':value).trim();var parsed=new Date(value+'T00:00:00.000Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(value)||Number.isNaN(parsed.getTime())||parsed.toISOString().slice(0,10)!==value)fail('LIVE_ACADEMIC_STRUCTURE_INVALID','Academic Structure contains an invalid date.',{field:field,value:value});return value;}
function required(value,field){value=String(value==null?'':value).trim();if(!value)fail('LIVE_ACADEMIC_STRUCTURE_INVALID','Academic Structure contains a missing required field.',{field:field});return value;}
function academicStructure(source){
  source=object(source,'academicStructure');if(Number(source.version)!==1)fail('LIVE_ACADEMIC_STRUCTURE_INVALID','Academic Structure version must be 1.');
  var yearSource=object(source.schoolYear,'academicStructure.schoolYear'),year={key:required(yearSource.key,'schoolYear.key'),label:required(yearSource.label,'schoolYear.label'),startDate:exactDate(yearSource.startDate,'schoolYear.startDate'),endDate:exactDate(yearSource.endDate,'schoolYear.endDate')};if(year.endDate<year.startDate)fail('LIVE_ACADEMIC_STRUCTURE_INVALID','School Year date range is invalid.');
  if(!Array.isArray(source.semesters)||!source.semesters.length)fail('LIVE_ACADEMIC_STRUCTURE_INVALID','Academic Structure requires at least one known Semester.');
  var semesterKeys={},semesterCodes={},semesterOrders={},semesters=source.semesters.map(function(value,index){var row=object(value,'academicStructure.semesters.'+index),semester={key:required(row.key,'semester.key'),code:required(row.code,'semester.code'),label:required(row.label,'semester.label'),startDate:exactDate(row.startDate,'semester.startDate'),endDate:exactDate(row.endDate,'semester.endDate'),order:Number(row.order),gradingPeriods:[]};if(!Number.isInteger(semester.order)||semester.order<1||semester.startDate<year.startDate||semester.endDate>year.endDate||semester.endDate<semester.startDate)fail('LIVE_ACADEMIC_STRUCTURE_INVALID','Semester range or order is invalid.',{semesterKey:semester.key});var code=semester.code.toLowerCase();if(semesterKeys[semester.key]||semesterCodes[code]||semesterOrders[semester.order])fail('LIVE_ACADEMIC_STRUCTURE_INVALID','Semester identities, codes, and orders must be unique.');semesterKeys[semester.key]=semester;semesterCodes[code]=true;semesterOrders[semester.order]=true;if(!Array.isArray(row.gradingPeriods)||!row.gradingPeriods.length)fail('LIVE_ACADEMIC_STRUCTURE_INVALID','Every known Semester requires Grading Periods.',{semesterKey:semester.key});var keys={},codes={},orders={};semester.gradingPeriods=row.gradingPeriods.map(function(periodValue,periodIndex){var periodRow=object(periodValue,'academicStructure.semesters.'+index+'.gradingPeriods.'+periodIndex),period={key:required(periodRow.key,'gradingPeriod.key'),code:required(periodRow.code,'gradingPeriod.code'),label:required(periodRow.label,'gradingPeriod.label'),startDate:exactDate(periodRow.startDate,'gradingPeriod.startDate'),endDate:exactDate(periodRow.endDate,'gradingPeriod.endDate'),order:Number(periodRow.order)};var periodCode=period.code.toLowerCase();if(!Number.isInteger(period.order)||period.order<1||period.startDate<semester.startDate||period.endDate>semester.endDate||period.endDate<period.startDate||keys[period.key]||codes[periodCode]||orders[period.order])fail('LIVE_ACADEMIC_STRUCTURE_INVALID','Grading Period range, identity, code, or order is invalid.',{semesterKey:semester.key,gradingPeriodKey:period.key});keys[period.key]=true;codes[periodCode]=true;orders[period.order]=true;return period;}).sort(function(a,b){return a.order-b.order;});for(var p=1;p<semester.gradingPeriods.length;p++)if(semester.gradingPeriods[p].startDate<=semester.gradingPeriods[p-1].endDate)fail('LIVE_ACADEMIC_STRUCTURE_INVALID','Grading Period date ranges overlap.',{semesterKey:semester.key});return semester;}).sort(function(a,b){return a.order-b.order;});
  for(var s=1;s<semesters.length;s++)if(semesters[s].startDate<=semesters[s-1].endDate)fail('LIVE_ACADEMIC_STRUCTURE_INVALID','Semester date ranges overlap.');
  var currentSemesterKey=required(source.currentSemesterKey,'currentSemesterKey');if(!semesterKeys[currentSemesterKey])fail('LIVE_ACADEMIC_STRUCTURE_INVALID','Current Semester does not identify a configured Semester.',{currentSemesterKey:currentSemesterKey});
  return{version:1,schoolYear:year,semesters:semesters,currentSemesterKey:currentSemesterKey};
}
function capture(localStorageLike){
  if(!localStorageLike||typeof localStorageLike.getItem!=='function')fail('SCHEMA7_STORAGE_REQUIRED','A same-origin localStorage reader is required.');
  var raw=localStorageLike.getItem(KEY);if(raw==null||raw==='')fail('LIVE_SCHEMA7_STATE_MISSING','The live weld_v013 state is absent; repository defaults are not migration authority.');
  var state;try{state=JSON.parse(raw);}catch(error){fail('LIVE_SCHEMA7_STATE_UNREADABLE','The live weld_v013 state is not valid JSON.');}
  if(!state||typeof state!=='object'||Array.isArray(state))fail('LIVE_SCHEMA7_STATE_UNREADABLE','The live weld_v013 state must be an object.');
  var snapshot={};scalar(state,'academicYearLabel',snapshot);scalar(state,'semesterLabel',snapshot);scalar(state,'academicYear',snapshot);scalar(state,'semester',snapshot);scalar(state,'planningPeriod',snapshot);
  if(own(state,'academicStructure'))snapshot.academicStructure=academicStructure(state.academicStructure);
  if(own(state,'periodTimes'))snapshot.periodTimes=timeRows(state.periodTimes,'periodTimes');
  if(own(state,'bellSchedules')){snapshot.bellSchedules={};var bells=object(state.bellSchedules,'bellSchedules');Object.keys(bells).forEach(function(key){var row=object(bells[key],'bellSchedules.'+key),safe={};scalar(row,'id',safe);scalar(row,'name',safe);if(own(row,'times'))safe.times=timeRows(row.times,'bellSchedules.'+key+'.times');snapshot.bellSchedules[key]=safe;});}
  if(own(state,'weeklyScheduleDefaults')){snapshot.weeklyScheduleDefaults={};var week=object(state.weeklyScheduleDefaults,'weeklyScheduleDefaults');Object.keys(week).forEach(function(key){var row=object(week[key],'weeklyScheduleDefaults.'+key),safe={};scalar(row,'scheduleId',safe);scalar(row,'instructionMode',safe);snapshot.weeklyScheduleDefaults[key]=safe;});}
  if(own(state,'calendarEvents')){if(!Array.isArray(state.calendarEvents))fail('LIVE_SCHEMA7_CONFIGURATION_INVALID','Calendar Events must be an array.',{family:'calendarEvents'});snapshot.calendarEvents=state.calendarEvents.map(function(value,index){var row=object(value,'calendarEvents.'+index),safe={};['id','date','title','time','remindDaysBefore','createdAt'].forEach(function(key){scalar(row,key,safe);});return safe;});}
  if(own(state,'calendarOverrides')){snapshot.calendarOverrides={};var overrides=object(state.calendarOverrides,'calendarOverrides');Object.keys(overrides).forEach(function(key){var row=object(overrides[key],'calendarOverrides.'+key),safe={};['dayType','instructionMode','scheduleId'].forEach(function(field){scalar(row,field,safe);});snapshot.calendarOverrides[key]=safe;});}
  if(own(state,'sections')){if(!Array.isArray(state.sections))fail('LIVE_SCHEMA7_CONFIGURATION_INVALID','Sections must be an array.',{family:'sections'});snapshot.sections=state.sections.map(function(value,index){var row=object(value,'sections.'+index),safe={};['id','course','name','period'].forEach(function(key){scalar(row,key,safe);});return safe;});}
  return{sourceKey:KEY,snapshot:snapshot};
}
return Object.freeze({STORAGE_KEY:KEY,capture:capture});
}));
