/* ARC Material Inventory v1. Physical stock pieces are authoritative. */
(function(root,factory){
  var api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  else root.ArcMaterialInventory=api;
}(this,function(){
  'use strict';
  var VERSION=1;
  var PURPOSES=['Student Project','Skill Practice','Shop/School Project','Other Department','Waste/Scrap','Adjustment'];
  var KINDS=['linear','plate'];
  function clone(x){return JSON.parse(JSON.stringify(x));}
  function text(x){return String(x==null?'':x).trim();}
  function num(x){var n=Number(x);return Number.isFinite(n)?Math.round(n*1000)/1000:0;}
  function uid(prefix){return prefix+'_'+Date.now()+'_'+Math.random().toString(36).slice(2,8);}
  function time(options){return text(options&&options.timestamp)||new Date().toISOString();}
  function academicYear(options){return text(options&&options.academicYear);}
  function normalizeDefinition(x){x=x||{};var kind=KINDS.indexOf(x.kind)>=0?x.kind:'linear';return {id:text(x.id)||uid('mat'),name:text(x.name),kind:kind,description:text(x.description),profile:text(x.profile),grade:text(x.grade),location:text(x.location),minimumRetainedInches:Math.max(0,num(x.minimumRetainedInches)),lowStockPieceCount:Math.max(0,Math.floor(num(x.lowStockPieceCount))),archived:x.archived===true,createdAt:text(x.createdAt),updatedAt:text(x.updatedAt)};}
  function normalizePiece(x){x=x||{};var kind=KINDS.indexOf(x.kind)>=0?x.kind:'linear';return {id:text(x.id)||uid('piece'),definitionId:text(x.definitionId),kind:kind,lengthInches:Math.max(0,num(x.lengthInches)),widthInches:Math.max(0,num(x.widthInches)),thicknessInches:Math.max(0,num(x.thicknessInches)),status:['available','consumed','scrap'].indexOf(x.status)>=0?x.status:'available',sourcePieceId:text(x.sourcePieceId),receivedAt:text(x.receivedAt),closedAt:text(x.closedAt),note:text(x.note)};}
  function normalizeLedger(x){x=x||{};return {id:text(x.id)||uid('matlog'),type:text(x.type),purpose:text(x.purpose),timestamp:text(x.timestamp),academicYear:text(x.academicYear),definitionId:text(x.definitionId),materialSnapshot:x.materialSnapshot&&typeof x.materialSnapshot==='object'?clone(x.materialSnapshot):{},sourcePieceId:text(x.sourcePieceId),resultPieceId:text(x.resultPieceId),amountInches:Math.max(0,num(x.amountInches)),dimensions:x.dimensions&&typeof x.dimensions==='object'?clone(x.dimensions):{},remainder:x.remainder&&typeof x.remainder==='object'?clone(x.remainder):null,studentId:text(x.studentId),studentName:text(x.studentName),projectId:text(x.projectId),projectName:text(x.projectName),department:text(x.department),note:text(x.note),reason:text(x.reason)};}
  function normalize(model){model=model||{};return {version:VERSION,definitions:(Array.isArray(model.definitions)?model.definitions:[]).map(normalizeDefinition),pieces:(Array.isArray(model.pieces)?model.pieces:[]).map(normalizePiece),ledger:(Array.isArray(model.ledger)?model.ledger:[]).map(normalizeLedger)};}
  function requireDefinition(model,id){var d=model.definitions.find(function(x){return x.id===id;});if(!d)throw new Error('Material definition was not found.');return d;}
  function snapshot(d){return {id:d.id,name:d.name,kind:d.kind,description:d.description,profile:d.profile,grade:d.grade,location:d.location};}
  function nextId(options,key,prefix,index){var ids=options&&options.ids;return ids&&ids[key]?(Array.isArray(ids[key])?ids[key][index||0]:ids[key]):uid(prefix);}
  function addDefinition(model,input,options){var out=normalize(model),d=normalizeDefinition(Object.assign({},input,{id:text(input&&input.id)||nextId(options,'definition','mat'),createdAt:time(options),updatedAt:time(options)}));if(!d.name)throw new Error('Material name is required.');if(out.definitions.some(function(x){return x.id===d.id;}))throw new Error('Material ID already exists.');out.definitions.push(d);return out;}
  function updateDefinition(model,id,changes,options){var out=normalize(model),i=out.definitions.findIndex(function(x){return x.id===id;});if(i<0)throw new Error('Material definition was not found.');var old=out.definitions[i],d=normalizeDefinition(Object.assign({},old,changes,{id:old.id,createdAt:old.createdAt,updatedAt:time(options)}));if(!d.name)throw new Error('Material name is required.');out.definitions[i]=d;return out;}
  function receive(model,definitionId,input,options){var out=normalize(model),d=requireDefinition(out,definitionId);input=input||{};var quantity=Math.floor(num(input.quantity));if(quantity<1)throw new Error('Receipt quantity must be at least one piece.');var dims=d.kind==='linear'?{lengthInches:num(input.lengthInches)}:{lengthInches:num(input.lengthInches),widthInches:num(input.widthInches),thicknessInches:num(input.thicknessInches)};if(!(dims.lengthInches>0)||(d.kind==='plate'&&(!(dims.widthInches>0)||!(dims.thicknessInches>0))))throw new Error(d.kind==='linear'?'Linear stock requires a positive length.':'Plate stock requires positive length, width, and thickness.');var stamp=time(options),pieceIds=[];
    for(var i=0;i<quantity;i++){var pid=nextId(options,'pieces','piece',i);if(out.pieces.some(function(x){return x.id===pid;})||pieceIds.indexOf(pid)>=0)throw new Error('Piece ID already exists.');pieceIds.push(pid);out.pieces.push(normalizePiece({id:pid,definitionId:d.id,kind:d.kind,lengthInches:dims.lengthInches,widthInches:dims.widthInches,thicknessInches:dims.thicknessInches,status:'available',receivedAt:stamp,note:input.note}));}
    out.ledger.unshift(normalizeLedger({id:nextId(options,'ledger','matlog'),type:'Receive',purpose:'Receive',timestamp:stamp,academicYear:academicYear(options),definitionId:d.id,materialSnapshot:snapshot(d),dimensions:Object.assign({quantity:quantity},dims),note:input.note,resultPieceId:pieceIds.join(',')}));return out;}
  function context(input){input=input||{};var purpose=text(input.purpose);if(PURPOSES.indexOf(purpose)<0)throw new Error('A valid material-use purpose is required.');if(purpose==='Student Project'&&(!text(input.studentId)||!text(input.projectId)))throw new Error('Student Project use requires student and project context.');return {purpose:purpose,studentId:text(input.studentId),studentName:text(input.studentName),projectId:text(input.projectId),projectName:text(input.projectName),department:text(input.department),note:text(input.note),reason:text(input.reason)};}
  function useLinear(model,pieceId,input,options){var out=normalize(model),i=out.pieces.findIndex(function(x){return x.id===pieceId;}),piece=i>=0?out.pieces[i]:null;if(!piece||piece.status!=='available')throw new Error('Source piece is missing or no longer available.');if(piece.kind!=='linear')throw new Error('This operation requires linear stock.');var used=num(input&&input.usedLengthInches);if(!(used>0))throw new Error('Used length must be greater than zero.');if(used>piece.lengthInches)throw new Error('Requested length exceeds the source piece.');var d=requireDefinition(out,piece.definitionId),ctx=context(input),remainder=Math.round((piece.lengthInches-used)*1000)/1000,retain=remainder>0&&(input.retainRemainder===true||remainder>=d.minimumRetainedInches),stamp=time(options),resultId='';piece.status='consumed';piece.closedAt=stamp;out.pieces[i]=piece;
    if(retain){resultId=nextId(options,'remainder','piece');if(out.pieces.some(function(x){return x.id===resultId;}))throw new Error('Piece ID already exists.');out.pieces.push(normalizePiece({id:resultId,definitionId:d.id,kind:'linear',lengthInches:remainder,status:'available',sourcePieceId:piece.id,receivedAt:stamp,note:'Remainder from '+piece.id}));}
    out.ledger.unshift(normalizeLedger(Object.assign({id:nextId(options,'ledger','matlog'),type:ctx.purpose==='Waste/Scrap'?'Waste/Scrap':'Use',timestamp:stamp,academicYear:academicYear(options),definitionId:d.id,materialSnapshot:snapshot(d),sourcePieceId:piece.id,resultPieceId:resultId,amountInches:used,dimensions:{sourceLengthInches:piece.lengthInches,usedLengthInches:used},remainder:{lengthInches:remainder,retained:retain,scrapped:remainder>0&&!retain}},ctx)));
    return out;}
  function usePlate(model,pieceId,input,options){var out=normalize(model),i=out.pieces.findIndex(function(x){return x.id===pieceId;}),piece=i>=0?out.pieces[i]:null;if(!piece||piece.status!=='available')throw new Error('Source piece is missing or no longer available.');if(piece.kind!=='plate')throw new Error('This operation requires plate stock.');var length=num(input&&input.usedLengthInches),width=num(input&&input.usedWidthInches);if(!(length>0&&width>0)||length>piece.lengthInches||width>piece.widthInches)throw new Error('Cut rectangle must fit within the source plate.');var d=requireDefinition(out,piece.definitionId),ctx=context(input),stamp=time(options),candidates=[];if(piece.lengthInches>length)candidates.push({lengthInches:piece.lengthInches-length,widthInches:piece.widthInches});if(piece.widthInches>width)candidates.push({lengthInches:length,widthInches:piece.widthInches-width});var retained=[];piece.status='consumed';piece.closedAt=stamp;out.pieces[i]=piece;candidates.forEach(function(r,n){var keep=input.retainRemainder===true||Math.min(r.lengthInches,r.widthInches)>=d.minimumRetainedInches;if(!keep)return;var rid=nextId(options,'remainders','piece',n);if(out.pieces.some(function(x){return x.id===rid;}))throw new Error('Piece ID already exists.');out.pieces.push(normalizePiece({id:rid,definitionId:d.id,kind:'plate',lengthInches:r.lengthInches,widthInches:r.widthInches,thicknessInches:piece.thicknessInches,status:'available',sourcePieceId:piece.id,receivedAt:stamp,note:'Rectangular remainder from '+piece.id}));retained.push({id:rid,lengthInches:r.lengthInches,widthInches:r.widthInches});});out.ledger.unshift(normalizeLedger(Object.assign({id:nextId(options,'ledger','matlog'),type:ctx.purpose==='Waste/Scrap'?'Waste/Scrap':'Use',timestamp:stamp,academicYear:academicYear(options),definitionId:d.id,materialSnapshot:snapshot(d),sourcePieceId:piece.id,resultPieceId:retained.map(function(x){return x.id;}).join(','),dimensions:{sourceLengthInches:piece.lengthInches,sourceWidthInches:piece.widthInches,usedLengthInches:length,usedWidthInches:width,thicknessInches:piece.thicknessInches},remainder:{retained:retained,scrapped:candidates.length-retained.length,note:'Deterministic guillotine rectangles; advanced nesting is not modeled.'}},ctx)));return out;}
  function adjust(model,pieceId,input,options){var out=normalize(model),i=out.pieces.findIndex(function(x){return x.id===pieceId;}),piece=i>=0?out.pieces[i]:null;if(!piece)throw new Error('Piece was not found.');var reason=text(input&&input.reason);if(!reason)throw new Error('Adjustment reason is required.');var d=requireDefinition(out,piece.definitionId),before=clone(piece);if(input.status)piece.status=input.status;if(input.lengthInches!=null){if(!(num(input.lengthInches)>0))throw new Error('Adjusted length must be greater than zero.');piece.lengthInches=num(input.lengthInches);}if(input.widthInches!=null){if(piece.kind!=='plate'||!(num(input.widthInches)>0))throw new Error('Adjusted width must be valid plate stock.');piece.widthInches=num(input.widthInches);}out.pieces[i]=normalizePiece(piece);out.ledger.unshift(normalizeLedger({id:nextId(options,'ledger','matlog'),type:'Adjustment',purpose:'Adjustment',timestamp:time(options),academicYear:academicYear(options),definitionId:d.id,materialSnapshot:snapshot(d),sourcePieceId:piece.id,dimensions:{before:before,after:out.pieces[i]},reason:reason,note:input.note}));return out;}
  function availablePieces(model,definitionId){return normalize(model).pieces.filter(function(x){return x.definitionId===definitionId&&x.status==='available';});}
  function groups(model){var out=normalize(model),defs={};out.definitions.forEach(function(d){defs[d.id]=d;});var map={};out.pieces.filter(function(p){return p.status==='available';}).forEach(function(p){var key=[p.definitionId,p.kind,p.lengthInches,p.widthInches,p.thicknessInches].join('|');if(!map[key])map[key]={definition:defs[p.definitionId]||null,kind:p.kind,lengthInches:p.lengthInches,widthInches:p.widthInches,thicknessInches:p.thicknessInches,count:0,pieceIds:[]};map[key].count++;map[key].pieceIds.push(p.id);});return Object.keys(map).map(function(k){return map[k];}).sort(function(a,b){return ((a.definition&&a.definition.name)||'').localeCompare((b.definition&&b.definition.name)||'')||b.lengthInches-a.lengthInches;});}
  function totals(model,definitionId){var pieces=availablePieces(model,definitionId);return {pieces:pieces.length,totalLinearInches:pieces.filter(function(x){return x.kind==='linear';}).reduce(function(n,x){return n+x.lengthInches;},0),totalPlateAreaSquareInches:pieces.filter(function(x){return x.kind==='plate';}).reduce(function(n,x){return n+x.lengthInches*x.widthInches;},0)};}
  function canSupplyLinear(model,definitionId,lengthInches,quantity){var need=num(lengthInches),count=Math.max(1,Math.floor(num(quantity)||1));return availablePieces(model,definitionId).filter(function(p){return p.kind==='linear'&&p.lengthInches>=need;}).length>=count;}
  function stockSummary(model){var out=normalize(model);return out.definitions.filter(function(d){return !d.archived;}).map(function(d){var pieces=availablePieces(out,d.id),status=pieces.length===0?'zero':(d.lowStockPieceCount>0&&pieces.length<=d.lowStockPieceCount?'low':'healthy');return {definition:d,status:status,pieceCount:pieces.length,groups:groups(out).filter(function(g){return g.definition&&g.definition.id===d.id;}),totals:totals(out,d.id)};});}
  function usageSummary(model){var rows={};normalize(model).ledger.filter(function(x){return x.type==='Use'||x.type==='Waste/Scrap';}).forEach(function(x){var key=[x.academicYear,x.definitionId,x.purpose].join('|');if(!rows[key])rows[key]={academicYear:x.academicYear,definitionId:x.definitionId,materialName:x.materialSnapshot.name||'',purpose:x.purpose,transactions:0,totalLinearInches:0,totalPlateAreaSquareInches:0};rows[key].transactions++;rows[key].totalLinearInches+=x.amountInches||0;if(x.dimensions.usedLengthInches&&x.dimensions.usedWidthInches)rows[key].totalPlateAreaSquareInches+=x.dimensions.usedLengthInches*x.dimensions.usedWidthInches;});return Object.keys(rows).map(function(k){return rows[k];});}
  return {VERSION:VERSION,PURPOSES:PURPOSES,KINDS:KINDS,normalize:normalize,normalizeDefinition:normalizeDefinition,normalizePiece:normalizePiece,addDefinition:addDefinition,updateDefinition:updateDefinition,receive:receive,useLinear:useLinear,usePlate:usePlate,adjust:adjust,availablePieces:availablePieces,groups:groups,totals:totals,canSupplyLinear:canSupplyLinear,stockSummary:stockSummary,usageSummary:usageSummary};
}));
