/* Teacher-facing derived models for Material Inventory. No persistence. */
(function(root,factory){var api=factory(root.ArcMaterialInventory||(typeof require==='function'?require('./material_inventory'):null));if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcMaterialInventoryPresenter=api;}(this,function(Materials){
  'use strict';
  function formatLength(value){var p=Materials.splitInches(value),inch=p.inches?(' '+p.inches+'"'):'';return p.feet?(p.feet+"'"+inch):(p.inches+'"');}
  function dimensions(value){value=value||{};if(value.kind==='plate'||value.widthInches)return formatLength(value.lengthInches)+' × '+formatLength(value.widthInches)+(value.thicknessInches?' × '+value.thicknessInches+'"':'');return formatLength(value.lengthInches);}
  function families(model){var used={};Materials.normalize(model).definitions.forEach(function(d){if(!d.archived)used[d.family]=true;});return Materials.FAMILIES.filter(function(x){return used[x];});}
  function stock(model,family){return Materials.stockSummary(model).filter(function(x){return !family||x.definition.family===family;});}
  function sources(model,family,definitionId){return Materials.groups(model).filter(function(g){return (!family||(g.definition&&g.definition.family===family))&&(!definitionId||(g.definition&&g.definition.id===definitionId));});}
  function purposes(){return ['All Uses','Student Project','Skill Practice','Shop/School Project','Other Department','Waste/Scrap','Adjustment','Receive'];}
  function ledger(model,filters){filters=filters||{};return Materials.normalize(model).ledger.filter(function(x){var family=x.materialSnapshot.family||Materials.inferFamily(x.materialSnapshot);return (!filters.family||family===filters.family)&&(!filters.purpose||filters.purpose==='All Uses'||x.purpose===filters.purpose);}).sort(function(a,b){return String(b.timestamp).localeCompare(String(a.timestamp));});}
  function beforeAfter(x){if(x.stockBefore&&x.stockAfter){if(Object.prototype.hasOwnProperty.call(x.stockBefore,'pieces'))return {before:x.stockBefore.pieces+' pieces',after:x.stockAfter.pieces+' pieces'};return {before:dimensions(x.stockBefore),after:x.stockAfter.pieces?x.stockAfter.pieces.map(dimensions).join(' + '):(x.stockAfter?dimensions(x.stockAfter):'None')};}var d=x.dimensions||{},r=x.remainder||null;return {before:d.sourceLengthInches?dimensions({kind:d.sourceWidthInches?'plate':'linear',lengthInches:d.sourceLengthInches,widthInches:d.sourceWidthInches,thicknessInches:d.thicknessInches}):'',after:r&&r.lengthInches?formatLength(r.lengthInches):''};}
  function card(x){var ba=beforeAfter(x),used=x.dimensions&&x.dimensions.usedWidthInches?dimensions({kind:'plate',lengthInches:x.dimensions.usedLengthInches,widthInches:x.dimensions.usedWidthInches,thicknessInches:x.dimensions.thicknessInches}):(x.amountInches?formatLength(x.amountInches):'');return {material:x.materialSnapshot.name||'Material',family:x.materialSnapshot.family||Materials.inferFamily(x.materialSnapshot),timestamp:x.timestamp,purpose:x.purpose,used:used,before:ba.before,after:ba.after,disposition:x.disposition||'',studentName:x.studentName,sectionName:x.sectionName,projectName:x.projectName,checkpointName:x.checkpointName,department:x.department,note:x.note||x.reason};}
  function student(model,studentId){return Materials.studentHistory(model,studentId).map(card);}
  return {formatLength:formatLength,dimensions:dimensions,families:families,stock:stock,sources:sources,purposes:purposes,ledger:ledger,card:card,student:student};
}));
