/* ARC Material Inventory. Physical stock pieces are authoritative. */
(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ArcMaterialInventory=api;}(this,function(){
  'use strict';
  var VERSION=1,PURPOSES=['Student Project','Skill Practice','Shop/School Project','Other Department','Waste/Scrap','Adjustment'],FAMILIES=['Angle','Flat Bar','Square Tube','Rectangular Tube','Round Tube','Pipe','Round Bar/Rod','Plate/Sheet','Channel','Expanded Metal','Other'],KINDS=['linear','plate'];
  function clone(x){return JSON.parse(JSON.stringify(x));} function text(x){return String(x==null?'':x).trim();} function num(x){var n=Number(x);return Number.isFinite(n)?Math.round(n*1000)/1000:0;} function uid(p){return p+'_'+Date.now()+'_'+Math.random().toString(36).slice(2,8);} function time(o){return text(o&&o.timestamp)||new Date().toISOString();} function year(o){return text(o&&o.academicYear);}
  function inferFamily(x){x=x||{};if(FAMILIES.indexOf(x.family)>=0)return x.family;var v=(text(x.name)+' '+text(x.profile)).toLowerCase();if(/expanded/.test(v))return 'Expanded Metal';if(x.kind==='plate'||/plate|sheet|gauge|\bga\b/.test(v))return 'Plate/Sheet';if(/rectangular|rect tube/.test(v))return 'Rectangular Tube';if(/square/.test(v)&&/tube/.test(v))return 'Square Tube';if(/round/.test(v)&&/tube/.test(v))return 'Round Tube';if(/pipe/.test(v))return 'Pipe';if(/flat/.test(v)&&/bar/.test(v))return 'Flat Bar';if((/round/.test(v)&&/(bar|rod)/.test(v))||/\brod\b|rebar/.test(v))return 'Round Bar/Rod';if(/angle/.test(v))return 'Angle';if(/channel/.test(v))return 'Channel';return 'Other';}
  function normalizeDefinition(x){x=x||{};var k=KINDS.indexOf(x.kind)>=0?x.kind:'linear';return {id:text(x.id)||uid('mat'),name:text(x.name),kind:k,family:inferFamily(Object.assign({},x,{kind:k})),description:text(x.description),profile:text(x.profile),grade:text(x.grade),location:text(x.location),minimumRetainedInches:Math.max(0,num(x.minimumRetainedInches)),lowStockPieceCount:Math.max(0,Math.floor(num(x.lowStockPieceCount))),archived:x.archived===true,createdAt:text(x.createdAt),updatedAt:text(x.updatedAt)};}
  function normalizePiece(x){x=x||{};var k=KINDS.indexOf(x.kind)>=0?x.kind:'linear';return {id:text(x.id)||uid('piece'),definitionId:text(x.definitionId),kind:k,lengthInches:Math.max(0,num(x.lengthInches)),widthInches:Math.max(0,num(x.widthInches)),thicknessInches:Math.max(0,num(x.thicknessInches)),status:['available','consumed','scrap'].indexOf(x.status)>=0?x.status:'available',sourcePieceId:text(x.sourcePieceId),receivedAt:text(x.receivedAt),closedAt:text(x.closedAt),note:text(x.note)};}
  function normalizeLedger(x){x=x||{};return {id:text(x.id)||uid('matlog'),type:text(x.type),purpose:text(x.purpose),timestamp:text(x.timestamp),academicYear:text(x.academicYear),definitionId:text(x.definitionId),materialSnapshot:x.materialSnapshot&&typeof x.materialSnapshot==='object'?clone(x.materialSnapshot):{},sourcePieceId:text(x.sourcePieceId),resultPieceId:text(x.resultPieceId),amountInches:Math.max(0,num(x.amountInches)),dimensions:x.dimensions&&typeof x.dimensions==='object'?clone(x.dimensions):{},remainder:x.remainder&&typeof x.remainder==='object'?clone(x.remainder):null,stockBefore:x.stockBefore&&typeof x.stockBefore==='object'?clone(x.stockBefore):null,stockAfter:x.stockAfter&&typeof x.stockAfter==='object'?clone(x.stockAfter):null,disposition:text(x.disposition),studentId:text(x.studentId),studentName:text(x.studentName),sectionId:text(x.sectionId),sectionName:text(x.sectionName),projectId:text(x.projectId),projectName:text(x.projectName),checkpointId:text(x.checkpointId),checkpointName:text(x.checkpointName),department:text(x.department),note:text(x.note),reason:text(x.reason)};}
  function normalize(m){m=m||{};return {version:VERSION,definitionSeedVersion:Math.max(0,Math.floor(num(m.definitionSeedVersion))),definitions:(Array.isArray(m.definitions)?m.definitions:[]).map(normalizeDefinition),pieces:(Array.isArray(m.pieces)?m.pieces:[]).map(normalizePiece),ledger:(Array.isArray(m.ledger)?m.ledger:[]).map(normalizeLedger)};}
  function starterDefinitions(){return [
    {id:'mat_starter_angle',name:'1-1/2 × 1-1/2 × 1/8 in Angle',family:'Angle',kind:'linear',profile:'1-1/2 × 1-1/2 × 1/8 in',minimumRetainedInches:12,lowStockPieceCount:2},
    {id:'mat_starter_flat_bar',name:'1 × 1/8 in Flat Bar',family:'Flat Bar',kind:'linear',profile:'1 × 1/8 in',minimumRetainedInches:12,lowStockPieceCount:2},
    {id:'mat_starter_square_tube',name:'1 × 1 × 1/8 in Square Tube',family:'Square Tube',kind:'linear',profile:'1 × 1 × 1/8 in',minimumRetainedInches:12,lowStockPieceCount:2},
    {id:'mat_starter_rect_tube',name:'2 × 1 × 1/8 in Rectangular Tube',family:'Rectangular Tube',kind:'linear',profile:'2 × 1 × 1/8 in',minimumRetainedInches:12,lowStockPieceCount:2},
    {id:'mat_starter_round_tube',name:'1 in Round Tube',family:'Round Tube',kind:'linear',profile:'1 in',minimumRetainedInches:12,lowStockPieceCount:2},
    {id:'mat_starter_pipe',name:'1 in Schedule 40 Pipe',family:'Pipe',kind:'linear',profile:'1 in Schedule 40',minimumRetainedInches:12,lowStockPieceCount:2},
    {id:'mat_starter_round_bar',name:'1/2 in Round Bar',family:'Round Bar/Rod',kind:'linear',profile:'1/2 in',minimumRetainedInches:8,lowStockPieceCount:2},
    {id:'mat_starter_plate',name:'1/8 in Plate',family:'Plate/Sheet',kind:'plate',profile:'1/8 in plate',minimumRetainedInches:6,lowStockPieceCount:1},
    {id:'mat_starter_sheet',name:'16 ga Sheet',family:'Plate/Sheet',kind:'plate',profile:'16 ga sheet',minimumRetainedInches:6,lowStockPieceCount:1},
    {id:'mat_starter_channel',name:'1-1/2 in Channel',family:'Channel',kind:'linear',profile:'1-1/2 in',minimumRetainedInches:12,lowStockPieceCount:2},
    {id:'mat_starter_expanded',name:'#9 Expanded Metal',family:'Expanded Metal',kind:'plate',profile:'#9',minimumRetainedInches:6,lowStockPieceCount:1}
  ].map(normalizeDefinition);}
  function seedStarterDefinitions(m){var out=normalize(m);if(out.definitionSeedVersion>=1)return out;var ids={},names={};out.definitions.forEach(function(d){ids[d.id]=true;names[d.name.toLowerCase()]=true;});starterDefinitions().forEach(function(d){if(!ids[d.id]&&!names[d.name.toLowerCase()])out.definitions.push(d);});out.definitionSeedVersion=1;return out;}
  function req(m,id){var d=m.definitions.find(function(x){return x.id===id;});if(!d)throw new Error('Material definition was not found.');return d;} function snap(d){return {id:d.id,name:d.name,kind:d.kind,family:d.family,description:d.description,profile:d.profile,grade:d.grade,location:d.location};} function nextId(o,k,p,i){var ids=o&&o.ids;return ids&&ids[k]?(Array.isArray(ids[k])?ids[k][i||0]:ids[k]):uid(p);} function pieceSnap(p){return p?{kind:p.kind,lengthInches:p.lengthInches,widthInches:p.widthInches,thicknessInches:p.thicknessInches,status:p.status}:null;}
  function addDefinition(m,input,o){var out=normalize(m),d=normalizeDefinition(Object.assign({},input,{id:text(input&&input.id)||nextId(o,'definition','mat'),createdAt:time(o),updatedAt:time(o)}));if(!d.name)throw new Error('Material name is required.');if(out.definitions.some(function(x){return x.id===d.id;}))throw new Error('Material ID already exists.');out.definitions.push(d);return out;}
  function updateDefinition(m,id,c,o){var out=normalize(m),i=out.definitions.findIndex(function(x){return x.id===id;});if(i<0)throw new Error('Material definition was not found.');var old=out.definitions[i],d=normalizeDefinition(Object.assign({},old,c,{id:old.id,createdAt:old.createdAt,updatedAt:time(o)}));if(!d.name)throw new Error('Material name is required.');out.definitions[i]=d;return out;}
  function availablePieces(m,id){return normalize(m).pieces.filter(function(x){return (!id||x.definitionId===id)&&x.status==='available';});}
  function totals(m,id){var p=availablePieces(m,id);return {pieces:p.length,totalLinearInches:p.filter(function(x){return x.kind==='linear';}).reduce(function(n,x){return n+x.lengthInches;},0),totalPlateAreaSquareInches:p.filter(function(x){return x.kind==='plate';}).reduce(function(n,x){return n+x.lengthInches*x.widthInches;},0)};}
  function receive(m,id,input,o){var out=normalize(m),d=req(out,id);input=input||{};var q=Math.floor(num(input.quantity));if(q<1)throw new Error('Receipt quantity must be at least one piece.');var dims=d.kind==='linear'?{lengthInches:num(input.lengthInches)}:{lengthInches:num(input.lengthInches),widthInches:num(input.widthInches),thicknessInches:num(input.thicknessInches)};if(!(dims.lengthInches>0)||(d.kind==='plate'&&(!(dims.widthInches>0)||!(dims.thicknessInches>0))))throw new Error(d.kind==='linear'?'Linear stock requires a positive length.':'Plate stock requires positive length, width, and thickness.');var stamp=time(o),ids=[],before=totals(out,d.id);for(var i=0;i<q;i++){var pid=nextId(o,'pieces','piece',i);if(out.pieces.some(function(x){return x.id===pid;})||ids.indexOf(pid)>=0)throw new Error('Piece ID already exists.');ids.push(pid);out.pieces.push(normalizePiece({id:pid,definitionId:d.id,kind:d.kind,lengthInches:dims.lengthInches,widthInches:dims.widthInches,thicknessInches:dims.thicknessInches,status:'available',receivedAt:stamp,note:input.note}));}out.ledger.unshift(normalizeLedger({id:nextId(o,'ledger','matlog'),type:'Receive',purpose:'Receive',timestamp:stamp,academicYear:year(o),definitionId:d.id,materialSnapshot:snap(d),dimensions:Object.assign({quantity:q},dims),note:input.note,resultPieceId:ids.join(','),stockBefore:before,stockAfter:totals(out,d.id),disposition:'Received '+q+' physical piece'+(q===1?'':'s')}));return out;}
  function context(input){input=input||{};var p=text(input.purpose);if(PURPOSES.indexOf(p)<0)throw new Error('A valid material-use purpose is required.');if(p==='Student Project'&&(!text(input.studentId)||!text(input.projectId)))throw new Error('Student Project use requires student and project context.');return {purpose:p,studentId:text(input.studentId),studentName:text(input.studentName),sectionId:text(input.sectionId),sectionName:text(input.sectionName),projectId:text(input.projectId),projectName:text(input.projectName),checkpointId:text(input.checkpointId),checkpointName:text(input.checkpointName),department:text(input.department),note:text(input.note),reason:text(input.reason)};}
  function useLinear(m,pieceId,input,o){var out=normalize(m),i=out.pieces.findIndex(function(x){return x.id===pieceId;}),p=i>=0?out.pieces[i]:null;if(!p||p.status!=='available')throw new Error('Source piece is missing or no longer available.');if(p.kind!=='linear')throw new Error('This operation requires linear stock.');var used=num(input&&input.usedLengthInches);if(!(used>0))throw new Error('Used length must be greater than zero.');if(used>p.lengthInches)throw new Error('Requested length exceeds the source piece.');var d=req(out,p.definitionId),ctx=context(input),rem=Math.round((p.lengthInches-used)*1000)/1000,override=input.retainRemainder===true,retain=rem>0&&(override||rem>=d.minimumRetainedInches),stamp=time(o),rid='',before=pieceSnap(p);p.status='consumed';p.closedAt=stamp;out.pieces[i]=p;if(retain){rid=nextId(o,'remainder','piece');if(out.pieces.some(function(x){return x.id===rid;}))throw new Error('Piece ID already exists.');out.pieces.push(normalizePiece({id:rid,definitionId:d.id,kind:'linear',lengthInches:rem,status:'available',sourcePieceId:p.id,receivedAt:stamp,note:'Remainder from '+p.id}));}var after=retain?pieceSnap(out.pieces[out.pieces.length-1]):null,disp=rem<=0?'Fully consumed':retain?(override&&rem<d.minimumRetainedInches?'Remainder retained by instructor override':'Usable remainder retained'):'Below-threshold remainder recorded as scrap';out.ledger.unshift(normalizeLedger(Object.assign({id:nextId(o,'ledger','matlog'),type:ctx.purpose==='Waste/Scrap'?'Waste/Scrap':'Use',timestamp:stamp,academicYear:year(o),definitionId:d.id,materialSnapshot:snap(d),sourcePieceId:p.id,resultPieceId:rid,amountInches:used,dimensions:{sourceLengthInches:p.lengthInches,usedLengthInches:used},remainder:{lengthInches:rem,retained:retain,scrapped:rem>0&&!retain,override:override},stockBefore:before,stockAfter:after,disposition:disp},ctx)));return out;}
  function usePlate(m,pieceId,input,o){var out=normalize(m),i=out.pieces.findIndex(function(x){return x.id===pieceId;}),p=i>=0?out.pieces[i]:null;if(!p||p.status!=='available')throw new Error('Source piece is missing or no longer available.');if(p.kind!=='plate')throw new Error('This operation requires plate stock.');var l=num(input&&input.usedLengthInches),w=num(input&&input.usedWidthInches);if(!(l>0&&w>0)||l>p.lengthInches||w>p.widthInches)throw new Error('Cut rectangle must fit within the source plate.');var d=req(out,p.definitionId),ctx=context(input),stamp=time(o),c=[],before=pieceSnap(p);if(p.lengthInches>l)c.push({lengthInches:p.lengthInches-l,widthInches:p.widthInches});if(p.widthInches>w)c.push({lengthInches:l,widthInches:p.widthInches-w});var kept=[];p.status='consumed';p.closedAt=stamp;out.pieces[i]=p;c.forEach(function(r,n){if(!(input.retainRemainder===true||Math.min(r.lengthInches,r.widthInches)>=d.minimumRetainedInches))return;var rid=nextId(o,'remainders','piece',n);if(out.pieces.some(function(x){return x.id===rid;}))throw new Error('Piece ID already exists.');var next=normalizePiece({id:rid,definitionId:d.id,kind:'plate',lengthInches:r.lengthInches,widthInches:r.widthInches,thicknessInches:p.thicknessInches,status:'available',sourcePieceId:p.id,receivedAt:stamp,note:'Rectangular remainder from '+p.id});out.pieces.push(next);kept.push({id:rid,lengthInches:r.lengthInches,widthInches:r.widthInches,thicknessInches:p.thicknessInches});});out.ledger.unshift(normalizeLedger(Object.assign({id:nextId(o,'ledger','matlog'),type:ctx.purpose==='Waste/Scrap'?'Waste/Scrap':'Use',timestamp:stamp,academicYear:year(o),definitionId:d.id,materialSnapshot:snap(d),sourcePieceId:p.id,resultPieceId:kept.map(function(x){return x.id;}).join(','),dimensions:{sourceLengthInches:p.lengthInches,sourceWidthInches:p.widthInches,usedLengthInches:l,usedWidthInches:w,thicknessInches:p.thicknessInches},remainder:{retained:kept,scrapped:c.length-kept.length,override:input.retainRemainder===true,note:'Deterministic guillotine rectangles; advanced nesting is not modeled.'},stockBefore:before,stockAfter:{pieces:kept.map(function(x){return {lengthInches:x.lengthInches,widthInches:x.widthInches,thicknessInches:x.thicknessInches,status:'available'};})},disposition:kept.length?kept.length+' rectangular remnant'+(kept.length===1?'':'s')+' retained':'Unused plate recorded as scrap'},ctx)));return out;}
  function adjust(m,pieceId,input,o){var out=normalize(m),i=out.pieces.findIndex(function(x){return x.id===pieceId;}),p=i>=0?out.pieces[i]:null;if(!p)throw new Error('Piece was not found.');var reason=text(input&&input.reason);if(!reason)throw new Error('Adjustment reason is required.');var d=req(out,p.definitionId),before=pieceSnap(p);if(input.status)p.status=input.status;if(input.lengthInches!=null){if(!(num(input.lengthInches)>0))throw new Error('Adjusted length must be greater than zero.');p.lengthInches=num(input.lengthInches);}if(input.widthInches!=null){if(p.kind!=='plate'||!(num(input.widthInches)>0))throw new Error('Adjusted width must be valid plate stock.');p.widthInches=num(input.widthInches);}out.pieces[i]=normalizePiece(p);out.ledger.unshift(normalizeLedger({id:nextId(o,'ledger','matlog'),type:'Adjustment',purpose:'Adjustment',timestamp:time(o),academicYear:year(o),definitionId:d.id,materialSnapshot:snap(d),sourcePieceId:p.id,dimensions:{before:before,after:pieceSnap(out.pieces[i])},stockBefore:before,stockAfter:pieceSnap(out.pieces[i]),disposition:'Physical count corrected with audit reason',reason:reason,note:input.note}));return out;}
  function groups(m){var out=normalize(m),defs={};out.definitions.forEach(function(d){defs[d.id]=d;});var map={};out.pieces.filter(function(p){return p.status==='available';}).forEach(function(p){var k=[p.definitionId,p.kind,p.lengthInches,p.widthInches,p.thicknessInches].join('|');if(!map[k])map[k]={definition:defs[p.definitionId]||null,kind:p.kind,lengthInches:p.lengthInches,widthInches:p.widthInches,thicknessInches:p.thicknessInches,count:0,pieceIds:[],pieces:[]};map[k].count++;map[k].pieces.push(p);});return Object.keys(map).map(function(k){var g=map[k];g.pieces.sort(function(a,b){return String(a.receivedAt).localeCompare(String(b.receivedAt))||a.id.localeCompare(b.id);});g.pieceIds=g.pieces.map(function(p){return p.id;});return g;}).sort(function(a,b){return ((a.definition&&a.definition.family)||'').localeCompare((b.definition&&b.definition.family)||'')||((a.definition&&a.definition.name)||'').localeCompare((b.definition&&b.definition.name)||'')||a.lengthInches-b.lengthInches;});}
  function selectGroupPiece(m,id,l,w,t){var g=groups(m).find(function(x){return x.definition&&x.definition.id===id&&x.lengthInches===num(l)&&x.widthInches===num(w)&&x.thicknessInches===num(t);});return g&&g.pieces.length?g.pieces[0]:null;}
  function canSupplyLinear(m,id,l,q){var need=num(l),count=Math.max(1,Math.floor(num(q)||1));return availablePieces(m,id).filter(function(p){return p.kind==='linear'&&p.lengthInches>=need;}).length>=count;}
  function stockSummary(m){var out=normalize(m),gs=groups(out);return out.definitions.filter(function(d){return !d.archived;}).map(function(d){var p=availablePieces(out,d.id),s=p.length===0?'zero':(d.lowStockPieceCount>0&&p.length<=d.lowStockPieceCount?'low':'healthy');return {definition:d,status:s,pieceCount:p.length,groups:gs.filter(function(g){return g.definition&&g.definition.id===d.id;}),totals:totals(out,d.id)};});}
  function usageSummary(m){var rows={};normalize(m).ledger.forEach(function(x){var family=x.materialSnapshot.family||inferFamily(x.materialSnapshot),k=[x.academicYear,x.definitionId,x.purpose].join('|');if(!rows[k])rows[k]={academicYear:x.academicYear,definitionId:x.definitionId,materialName:x.materialSnapshot.name||'',family:family,purpose:x.purpose,transactions:0,totalLinearInches:0,totalPlateAreaSquareInches:0};rows[k].transactions++;if(x.type==='Use'||x.type==='Waste/Scrap'){rows[k].totalLinearInches+=x.amountInches||0;if(x.dimensions.usedLengthInches&&x.dimensions.usedWidthInches)rows[k].totalPlateAreaSquareInches+=x.dimensions.usedLengthInches*x.dimensions.usedWidthInches;}});return Object.keys(rows).map(function(k){return rows[k];});}
  function studentHistory(m,id){return normalize(m).ledger.filter(function(x){return x.studentId===id;}).sort(function(a,b){return String(b.timestamp).localeCompare(String(a.timestamp));});}
  function inchesFromParts(f,i,allowZero){f=Math.floor(Math.max(0,num(f)));i=Math.max(0,num(i));if(i>=12)throw new Error('Inches must be less than 12.');var total=Math.round((f*12+i)*1000)/1000;if(!(total>0)&&!allowZero)throw new Error('Length must be greater than zero.');return total;} function splitInches(v){var total=Math.max(0,num(v)),f=Math.floor(total/12);return {feet:f,inches:Math.round((total-f*12)*1000)/1000};}
  return {VERSION:VERSION,PURPOSES:PURPOSES,FAMILIES:FAMILIES,KINDS:KINDS,inferFamily:inferFamily,normalize:normalize,starterDefinitions:starterDefinitions,seedStarterDefinitions:seedStarterDefinitions,normalizeDefinition:normalizeDefinition,normalizePiece:normalizePiece,normalizeLedger:normalizeLedger,addDefinition:addDefinition,updateDefinition:updateDefinition,receive:receive,useLinear:useLinear,usePlate:usePlate,adjust:adjust,availablePieces:availablePieces,groups:groups,selectGroupPiece:selectGroupPiece,totals:totals,canSupplyLinear:canSupplyLinear,stockSummary:stockSummary,usageSummary:usageSummary,studentHistory:studentHistory,inchesFromParts:inchesFromParts,splitInches:splitInches};
}));
