/* ARC v0.18 Needs Attention adapter.
   Converts existing ARC state into normalized engine facts without mutating state.
   Conservative rule: if ARC cannot prove an opportunity, opportunityConfirmed stays false. */
(function(root,factory){
  var api=factory();
  if(typeof module==='object'&&module.exports) module.exports=api;
  else root.ArcNeedsAttentionAdapter=api;
}(this,function(){
  function arr(x){return Array.isArray(x)?x:[];}
  function obj(x){return x&&typeof x==='object'&&!Array.isArray(x)?x:{};}
  function activeEnrollment(student,state,course,sectionId){return arr(student.enrollments).find(function(e){return e&&e.active&&e.year===state.academicYear&&e.semester===state.semester&&e.course===course&&(!sectionId||e.sectionId===sectionId);})||null;}
  function scopedRating(student,code,state,enrollment){var ratings=obj(student.ratings),scopes=obj(student.ratingScopes),scope=scopes[code];if(!Object.prototype.hasOwnProperty.call(ratings,code))return 0;if(!scope)return 0;if(scope.academicYear!==state.academicYear||scope.semester!==state.semester)return 0;if(enrollment&&scope.sectionId&&scope.sectionId!==enrollment.sectionId)return 0;return Number(ratings[code]||0);}
  function boolMapHas(map,studentId,key){var s=obj(obj(map)[studentId]);return s[key]===true;}
  function dateMapValue(map,studentId,key){var s=obj(obj(map)[studentId]);return typeof s[key]==='string'?s[key]:'';}
  function standardsForCompetency(comp){return String((comp&&comp.standard)||'').split(';').map(function(x){return x.trim();}).filter(Boolean);}
  function lessonAddressesCompetency(lesson,comp){var standards=standardsForCompetency(comp);if(!standards.length)return false;return arr(lesson&&lesson.standards).some(function(ls){var text=String(ls||'');return standards.some(function(code){return text.indexOf(code)!==-1;});});}
  function attendanceStatus(state,studentId,sectionId,date){var bucket=obj(obj(state.attendanceRecords)[sectionId+'::'+date]),rec=obj(obj(bucket.students)[studentId]);return rec.status||'present';}
  function attendanceAllowsOpportunity(status){return status!=='excused'&&status!=='activity'&&status!=='noclass';}
  function completedPacingOpportunity(state,course,sectionId,comp,studentId){var plan=obj(obj(state.pacingPlans)[sectionId]),bank=arr(obj(state.lessonBank)[course]),dates=[];arr(plan.items).forEach(function(item){if(!item||item.status!=='completed')return;var lesson=bank.find(function(l){return l&&l.id===item.lessonId;});if(!lessonAddressesCompetency(lesson,comp))return;arr(item.actualDates).forEach(function(d){if(typeof d==='string'&&d&&(!studentId||attendanceAllowsOpportunity(attendanceStatus(state,studentId,sectionId,d))))dates.push(d);});});dates.sort();return {confirmed:dates.length>0,date:dates.length?dates[dates.length-1]:''};}
  function competencyDefinitions(config,course){return arr(obj(config.competencyDefinitions)[course]);}
  function technicalLibrary(state,course){return arr(obj(state.technicalLibrary)[course]);}
  function technicalTemplateCurrent(t,state,course,sectionId){if(!t)return false;if(t.course&&t.course!==course)return false;if(t.academicYear&&t.academicYear!==state.academicYear)return false;if(t.semester&&t.semester!==state.semester)return false;var sections=arr(t.sectionIds);return !sections.length||sections.indexOf(sectionId)>=0;}
  function technicalDue(t,today){return !!(t&&t.date&&today&&String(t.date)<=String(today));}
  function technicalOpportunity(state,studentId,sectionId,t){return !!(t&&t.date&&attendanceAllowsOpportunity(attendanceStatus(state,studentId,sectionId,t.date)));}
  function adaptTechnical(state,student,course,enrollment,today){var templates=technicalLibrary(state,course),byId={};templates.forEach(function(t){if(t&&t.id)byId[t.id]=t;});return arr(student.tech).map(function(rec){var t=byId[rec&&rec.templateId];if(!t||!technicalTemplateCurrent(t,state,course,enrollment.sectionId))return null;return {id:t.id,name:rec.name||t.title||'Technical assessment',date:t.date||rec.date||'',due:technicalDue(t,today),status:rec.status||'makeup',opportunityConfirmed:technicalOpportunity(state,student.id,enrollment.sectionId,t)};}).filter(Boolean);}
  function workplaceWeekCurrent(week,state,course,sectionId){return !!(week&&week.sectionId===sectionId&&week.course===course&&week.academicYear===state.academicYear&&week.semester===state.semester);}
  function addDaysKey(key,n){var d=new Date(String(key)+'T12:00:00');if(isNaN(d.getTime()))return '';d.setDate(d.getDate()+n);var y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return y+'-'+m+'-'+day;}
  function workplaceDayDate(weekKey,dayKey){var offsets={mon:0,tue:1,wed:2,thu:3,fri:4,sat:5,sun:6};return Object.prototype.hasOwnProperty.call(offsets,dayKey)?addDaysKey(weekKey,offsets[dayKey]):'';}
  function adaptWorkplace(state,student,course,enrollment){var out=[];Object.keys(obj(student.workplacePoints)).forEach(function(weekKey){var week=obj(student.workplacePoints[weekKey]);if(!workplaceWeekCurrent(week,state,course,enrollment.sectionId))return;Object.keys(obj(week.days)).forEach(function(dayKey){var day=obj(week.days[dayKey]);if(day.status&&day.status!=='present')return;var date=workplaceDayDate(weekKey,dayKey);if(!date)return;arr(day.deductions).forEach(function(d){if(!d||Number(d.points)<=0)return;if(d.sectionId&&d.sectionId!==enrollment.sectionId)return;out.push({id:d.id||weekKey+'-'+dayKey+'-'+out.length,date:date,points:Number(d.points),label:d.label||d.ruleId||'Workplace concern',ruleId:d.ruleId||'',occurrence:Number(d.occurrence||1)});});});});return out;}
  function checkpointProjectId(project,index){return project.id||project.assignmentId||project.templateId||('project-'+index);}
  function projectActivitySummary(state,student,enrollment,project){var eligible=0,evidence=[];arr(project.checkpointActivity).forEach(function(raw){if(!raw||!raw.date)return;var status=attendanceStatus(state,student.id,enrollment.sectionId,raw.date);if(raw.type==='opportunity'&&raw.opportunityConfirmed===true&&attendanceAllowsOpportunity(status))eligible++;if(raw.meaningfulProgress===true||raw.type==='review'||raw.type==='verification')evidence.push(String(raw.date));});evidence.sort();return {eligibleOpportunities:eligible,opportunityConfirmed:eligible>0,lastEvidenceDate:evidence.length?evidence[evidence.length-1]:''};}
  function adaptProjects(state,student,enrollment){return arr(student.projects).map(function(project,index){if(!project||!Array.isArray(project.checkpoints))return null;var ready=project.checkpoints.filter(function(c){return c&&c.enabled!==false&&c.status==='ready_for_review';}),activity=projectActivitySummary(state,student,enrollment,project);var activeStatus=project.status!=='completed'&&project.status!=='NE'&&project.status!=='absent';if(!ready.length&&!activity.opportunityConfirmed&&!activity.lastEvidenceDate)return null;var dates=ready.map(function(c){return c.updatedAt||c.startedAt||'';}).filter(Boolean).concat(activity.lastEvidenceDate?[activity.lastEvidenceDate]:[]).sort();return {id:checkpointProjectId(project,index),name:project.name||project.title||'Project',active:activeStatus,readyForReview:ready.length>0,lastEvidenceDate:dates.length?dates[dates.length-1]:'',opportunityConfirmed:activity.opportunityConfirmed,eligibleOpportunities:activity.eligibleOpportunities};}).filter(Boolean);}
  function adapt(state,config){state=state||{};config=config||{};var sectionId=config.sectionId||state.activeSectionId||'',section=arr(state.sections).find(function(x){return x.id===sectionId;}),courses=section?[section.course]:['wt','awt'];var essential=obj(config.essentialCodes),opportunities=obj(config.competencyOpportunities),reassess=obj(config.readyForReassessment),evidenceDates=obj(config.competencyEvidenceDates),today=config.today||'',students=[];courses.forEach(function(course){var definitions=competencyDefinitions(config,course),defByCode={};definitions.forEach(function(c){if(c&&c.code)defByCode[c.code]=c;});arr(obj(state.classes)[course]).forEach(function(s){var enrollment=activeEnrollment(s,state,course,sectionId||null);if(!enrollment)return;var facts={studentId:s.id,studentName:s.name||'',sectionId:enrollment.sectionId,active:true,competencies:[],projects:[],workplace:[],technical:[]};var codes={};Object.keys(obj(s.ratings)).forEach(function(k){codes[k]=true;});Object.keys(obj(s.ratingScopes)).forEach(function(k){codes[k]=true;});definitions.forEach(function(c){if(c&&c.code)codes[c.code]=true;});Object.keys(codes).forEach(function(code){var comp=defByCode[code]||{code:code,name:code,standard:''},pacing=completedPacingOpportunity(state,course,enrollment.sectionId,comp,s.id),explicitOpportunity=boolMapHas(opportunities,s.id,code),explicitDate=dateMapValue(evidenceDates,s.id,code);facts.competencies.push({id:code,name:comp.name||code,essential:essential[code]===true,rating:scopedRating(s,code,state,enrollment),opportunityConfirmed:explicitOpportunity||pacing.confirmed,readyForReassessment:boolMapHas(reassess,s.id,code),evidenceDate:explicitDate||pacing.date});});facts.projects=adaptProjects(state,s,enrollment);facts.technical=adaptTechnical(state,s,course,enrollment,today);facts.workplace=adaptWorkplace(state,s,course,enrollment);students.push(facts);});});return {today:today,students:students};}
  return {adapt:adapt,activeEnrollment:activeEnrollment,scopedRating:scopedRating,standardsForCompetency:standardsForCompetency,lessonAddressesCompetency:lessonAddressesCompetency,attendanceStatus:attendanceStatus,attendanceAllowsOpportunity:attendanceAllowsOpportunity,completedPacingOpportunity:completedPacingOpportunity,technicalLibrary:technicalLibrary,technicalTemplateCurrent:technicalTemplateCurrent,technicalDue:technicalDue,technicalOpportunity:technicalOpportunity,adaptTechnical:adaptTechnical,workplaceWeekCurrent:workplaceWeekCurrent,workplaceDayDate:workplaceDayDate,adaptWorkplace:adaptWorkplace,checkpointProjectId:checkpointProjectId,projectActivitySummary:projectActivitySummary,adaptProjects:adaptProjects};
}));
