/* ARC Project Bank v1 domain model.
   Reusable definitions are separate from student assignments. Project stages,
   needs, and difficulty are operational context and never automatic grades. */
(function(root,factory){
  var api=factory(root.ArcProjectCheckpoints||(typeof require==='function'?require('./project_checkpoints'):null));
  if(typeof module==='object'&&module.exports) module.exports=api;
  else root.ArcProjectBank=api;
}(this,function(ProjectCheckpoints){
  var TYPES=['Skill Challenge','Build Project','Student-Designed Project'];
  var NEEDS=['Ready to Work','Needs Help','Needs Instructor Check','Needs Material','Needs Demonstration','Needs Reassessment','Equipment Problem','Needs Next Project'];
  var DEFAULT_STAGES=[
    {id:'assigned',name:'Assigned',requiresInstructorCheck:false},
    {id:'planning',name:'Planning',requiresInstructorCheck:false},
    {id:'layout',name:'Layout',requiresInstructorCheck:false},
    {id:'cut_prep',name:'Cut / Prep',requiresInstructorCheck:false},
    {id:'fit_up',name:'Fit-Up',requiresInstructorCheck:true},
    {id:'welding_fabrication',name:'Welding / Fabrication',requiresInstructorCheck:false},
    {id:'inspect_correct',name:'Inspect / Correct',requiresInstructorCheck:true},
    {id:'finish',name:'Finish',requiresInstructorCheck:false},
    {id:'complete',name:'Complete',requiresInstructorCheck:false}
  ];
  var SKILL_STAGES=[
    {id:'assigned',name:'Assigned',requiresInstructorCheck:false},
    {id:'setup',name:'Set Up',requiresInstructorCheck:true},
    {id:'practice',name:'Practice',requiresInstructorCheck:false},
    {id:'inspect_correct',name:'Inspect / Correct',requiresInstructorCheck:true},
    {id:'complete',name:'Complete',requiresInstructorCheck:false}
  ];
  function clone(x){return JSON.parse(JSON.stringify(x));}
  function arr(x){return Array.isArray(x)?x:[];}
  function text(x){return x==null?'':String(x).trim();}
  function uniqueStrings(x){var seen={};return arr(x).map(text).filter(function(v){if(!v||seen[v])return false;seen[v]=true;return true;});}
  function slug(value,index){var s=text(value).toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'');return s||('stage_'+(index+1));}
  function stages(input,type){var source=arr(input);if(!source.length)source=type==='Skill Challenge'?SKILL_STAGES:DEFAULT_STAGES;var used={};return source.map(function(stage,index){var name=text(typeof stage==='string'?stage:stage&&stage.name)||('Stage '+(index+1)),base=slug(stage&&stage.id||name,index),id=base,n=2;while(used[id])id=base+'_'+n++;used[id]=true;return {id:id,name:name,requiresInstructorCheck:!!(stage&&stage.requiresInstructorCheck)};});}
  function checkpoints(input){return arr(input).map(function(item,index){var name=text(typeof item==='string'?item:item&&item.name)||('Checkpoint '+(index+1));return {id:text(item&&item.id)||slug(name,index),name:name,stageId:text(item&&item.stageId),required:item&&item.required===false?false:true};});}
  function listObjects(input){return arr(input).map(function(item){if(typeof item==='string')return {name:text(item),quantity:'',notes:''};return {name:text(item&&item.name),quantity:text(item&&item.quantity),notes:text(item&&item.notes)};}).filter(function(item){return item.name;});}
  function applicability(input,fallbackCourse){input=input||{};return {wt:input.wt===true||fallbackCourse==='wt',awt:input.awt===true||fallbackCourse==='awt'};}
  function normalizeDefinition(input,options){input=input||{};options=options||{};var type=TYPES.indexOf(input.type)>=0?input.type:'Build Project',difficulty=Math.max(1,Math.min(5,Number(input.difficulty)||1));return {
    id:text(input.id)||text(options.id),title:text(input.title||input.name)||'Untitled Project',studentTitle:text(input.studentTitle)||text(input.title||input.name)||'Untitled Project',studentDescription:text(input.studentDescription||input.description),studentInstructions:text(input.studentInstructions||input.instructions),type:type,difficulty:difficulty,
    applicability:applicability(input.applicability,options.course),estimatedShopTime:text(input.estimatedShopTime),instructorNotes:text(input.instructorNotes),materials:listObjects(input.materials),equipmentRequirements:uniqueStrings(input.equipmentRequirements),processRequirements:uniqueStrings(input.processRequirements),linkedStandards:uniqueStrings(input.linkedStandards),linkedCompetencies:uniqueStrings(input.linkedCompetencies),recommendedReadiness:text(input.recommendedReadiness),minimumClearance:input.minimumClearance==null||input.minimumClearance===''?null:Math.max(1,Math.min(5,Number(input.minimumClearance)||1)),
    stages:stages(input.stages,type),instructorCheckpoints:checkpoints(input.instructorCheckpoints),archived:input.archived===true,source:text(input.source)||'instructor',createdAt:text(input.createdAt||input.created),updatedAt:text(input.updatedAt),copiedFrom:text(input.copiedFrom),futureLinks:Object.assign({lessonModuleIds:[],growthMilestoneIds:[],competitionIds:[],inventoryMaterialIds:[],essentialStandardIds:[],sloEvidenceTags:[]},input.futureLinks||{})
  };}
  function starterDefinitions(){return [
    normalizeDefinition({id:'pb_wt_thermal_straight_cut',title:'Thermal Cutting — Straight Cuts',studentTitle:'Straight-Cut Challenge',studentDescription:'Practice setting up safely and making clean, straight thermal cuts.',studentInstructions:'Set up with the correct PPE, mark your cut lines, make the cuts, and bring the best sample for an instructor check.',type:'Skill Challenge',difficulty:1,applicability:{wt:true,awt:false},estimatedShopTime:'2–3 shop periods',materials:[{name:'Mild-steel practice coupons',quantity:'As assigned'}],equipmentRequirements:['Thermal-cutting station','Layout tools'],processRequirements:['Thermal cutting'],linkedStandards:['WT 4.1','WT 4.2','WT 4.3'],linkedCompetencies:['WT-T1','WT-T2','WT-T3','WT-T4'],recommendedReadiness:'Shop safety and required PPE reviewed.',stages:SKILL_STAGES,instructorCheckpoints:[{id:'setup_check',name:'Safe setup check',stageId:'setup',required:true},{id:'cut_check',name:'Cut quality check',stageId:'inspect_correct',required:true}],source:'arc_starter'}),
    normalizeDefinition({id:'pb_wt_smaw_stringer',title:'SMAW Stringer-Bead Practice',studentTitle:'Run Better Beads',studentDescription:'Build steady arc control and make consistent stringer beads.',studentInstructions:'Prepare your plate, set the machine with your instructor, run practice beads, correct one thing at a time, and submit your strongest sample.',type:'Skill Challenge',difficulty:1,applicability:{wt:true,awt:false},estimatedShopTime:'3–5 shop periods',materials:[{name:'Mild-steel practice plate',quantity:'1 or more'},{name:'SMAW electrodes',quantity:'As assigned'}],equipmentRequirements:['SMAW machine','Welding booth'],processRequirements:['SMAW'],linkedStandards:['Course Description','WT 1.1'],linkedCompetencies:['WT-W1','WT-W2','WT-W3','WT-W6'],recommendedReadiness:'SMAW safety and equipment orientation completed.',stages:SKILL_STAGES,instructorCheckpoints:[{id:'setup_check',name:'Machine setup check',stageId:'setup',required:true},{id:'bead_check',name:'Bead inspection',stageId:'inspect_correct',required:true}],source:'arc_starter'}),
    normalizeDefinition({id:'pb_wt_coupon_holder',title:'Welding Coupon Holder',studentTitle:'Build a Coupon Holder',studentDescription:'Build a simple holder that keeps welding coupons organized.',studentInstructions:'Review the plan, lay out and cut the parts, check the fit-up, weld the holder, inspect it, and finish sharp edges.',type:'Build Project',difficulty:2,applicability:{wt:true,awt:false},estimatedShopTime:'5–8 shop periods',materials:[{name:'Mild-steel flat bar or plate',quantity:'Per instructor plan'}],equipmentRequirements:['Layout tools','Cutting equipment','Welding booth'],processRequirements:['Layout','Cutting','SMAW or approved joining process'],linkedStandards:['WT 2.1','WT 3.1','WT 4.2'],linkedCompetencies:['WT-M1','WT-M2','WT-M3','WT-F1','WT-F2','WT-F3'],recommendedReadiness:'Basic measurement, cutting, and introductory welding practice.',stages:DEFAULT_STAGES,instructorCheckpoints:[{id:'fitup_check',name:'Fit-up approval',stageId:'fit_up',required:true},{id:'final_check',name:'Final inspection',stageId:'inspect_correct',required:true}],source:'arc_starter'}),
    normalizeDefinition({id:'pb_wt_helmet_rack',title:'Welding Helmet Rack',studentTitle:'Build a Helmet Rack',studentDescription:'Build a useful rack for storing welding helmets safely and neatly.',studentInstructions:'Plan the rack, verify measurements, prepare and fit the parts, get fit-up approval, weld it, and complete a final inspection.',type:'Build Project',difficulty:2,applicability:{wt:true,awt:false},estimatedShopTime:'8–12 shop periods',materials:[{name:'Mild-steel stock',quantity:'Per instructor plan'}],equipmentRequirements:['Layout tools','Cutting equipment','Welding booth'],processRequirements:['Layout','Cutting','Fit-up','SMAW or approved joining process'],linkedStandards:['WT 2.1','WT 3.1','WT 4.2'],linkedCompetencies:['WT-M1','WT-M2','WT-M3','WT-W4','WT-W5','WT-F1','WT-F2','WT-F3'],recommendedReadiness:'Consistent basic measurement, cutting, fit-up, and safe welding setup.',minimumClearance:2,stages:DEFAULT_STAGES,instructorCheckpoints:[{id:'plan_check',name:'Plan and material check',stageId:'planning',required:true},{id:'fitup_check',name:'Fit-up approval',stageId:'fit_up',required:true},{id:'final_check',name:'Final inspection',stageId:'inspect_correct',required:true}],source:'arc_starter'})
  ];}
  function mergeDefinitions(existing,legacyLibraries){var byId={};arr(existing).forEach(function(d){var n=normalizeDefinition(d);if(n.id)byId[n.id]=n;});['wt','awt'].forEach(function(course){arr(legacyLibraries&&legacyLibraries[course]).forEach(function(d,index){var id=text(d&&d.id)||('legacy_'+course+'_'+index),n=normalizeDefinition(Object.assign({},d,{id:id}),{course:course});if(byId[id]){byId[id].applicability[course]=true;}else byId[id]=n;});});starterDefinitions().forEach(function(d){if(!byId[d.id])byId[d.id]=d;});return Object.keys(byId).map(function(id){return byId[id];});}
  function assignment(definition,context){var d=normalizeDefinition(definition),ctx=context||{},now=text(ctx.timestamp)||new Date().toISOString(),stage=d.stages[0]||{id:'assigned',name:'Assigned'};return {id:text(ctx.assignmentId)||('pa_'+Date.now()+'_'+Math.random().toString(36).slice(2,7)),assignmentId:text(ctx.assignmentId)||'',templateId:d.id,name:d.title,projectTitleSnapshot:d.title,type:d.type,difficulty:d.difficulty,sectionId:text(ctx.sectionId),course:text(ctx.course),academicYear:text(ctx.academicYear),semester:text(ctx.semester),assignedAt:now,assignedBy:text(ctx.assignedBy)||'Instructor',assignmentSource:text(ctx.source)||'Instructor',archivedDefinitionAtAssignment:d.archived,currentStageId:stage.id,currentStageName:stage.name,currentNeed:'Ready to Work',needSource:'Instructor',isPrimary:ctx.isPrimary===true,status:'in_progress',stages:clone(d.stages),projectBankCheckpoints:d.instructorCheckpoints.map(function(c){return Object.assign({},c,{status:'pending',updatedAt:''});}),stageHistory:[{at:now,fromStageId:'',toStageId:stage.id,toStageName:stage.name,source:text(ctx.source)||'Instructor'}],needHistory:[{at:now,from:'',to:'Ready to Work',source:'Instructor'}],rubric:{},rubricNotes:'',score:null};}
  function normalizeAssignment(record,definition,context){record=record||{};context=context||{};var base=assignment(definition||{id:record.templateId,title:record.name||'Project'},{assignmentId:record.id||record.assignmentId,sectionId:record.sectionId||context.sectionId,course:record.course||context.course,academicYear:record.academicYear||context.academicYear,semester:record.semester||context.semester,timestamp:record.assignedAt||record.created||context.timestamp,source:record.assignmentSource||'Instructor',isPrimary:record.isPrimary===true}),copy=Object.assign(base,clone(record));copy.id=text(copy.id||copy.assignmentId)||base.id;copy.assignmentId=copy.id;copy.stages=arr(record.stages).length?clone(record.stages):base.stages;var stage=copy.stages.find(function(s){return s.id===copy.currentStageId;})||copy.stages[0];copy.currentStageId=stage?stage.id:'';copy.currentStageName=stage?stage.name:'';copy.currentNeed=NEEDS.indexOf(copy.currentNeed)>=0?copy.currentNeed:'Ready to Work';copy.stageHistory=arr(record.stageHistory).length?clone(record.stageHistory):base.stageHistory;copy.needHistory=arr(record.needHistory).length?clone(record.needHistory):base.needHistory;copy.projectBankCheckpoints=arr(record.projectBankCheckpoints).length?clone(record.projectBankCheckpoints):base.projectBankCheckpoints;copy.rubric=record.rubric&&typeof record.rubric==='object'?clone(record.rubric):{};return copy;}
  function setStage(record,stageId,context){context=context||{};var copy=clone(record),stage=arr(copy.stages).find(function(s){return s.id===stageId;});if(!stage||copy.currentStageId===stage.id)return copy;var now=text(context.timestamp)||new Date().toISOString(),prior=copy.currentStageId||'';copy.currentStageId=stage.id;copy.currentStageName=stage.name;copy.stageHistory=arr(copy.stageHistory).concat([{at:now,fromStageId:prior,toStageId:stage.id,toStageName:stage.name,source:text(context.source)||'Instructor'}]);if(stage.requiresInstructorCheck){copy=setNeed(copy,'Needs Instructor Check',{timestamp:now,source:text(context.source)||'Instructor'});}if(stage.id==='complete')copy.status='completed';return copy;}
  function setNeed(record,need,context){if(NEEDS.indexOf(need)<0)return clone(record);context=context||{};var copy=clone(record),prior=copy.currentNeed||'';if(prior===need)return copy;var now=text(context.timestamp)||new Date().toISOString();copy.currentNeed=need;copy.needSource=text(context.source)||'Instructor';copy.needHistory=arr(copy.needHistory).concat([{at:now,from:prior,to:need,source:copy.needSource,note:text(context.note)}]);return copy;}
  function setPrimary(projects,assignmentId){return arr(projects).map(function(p){var copy=Object.assign({},p);copy.isPrimary=(p.id||p.assignmentId)===assignmentId;return copy;});}
  function primary(projects){var active=arr(projects).filter(function(p){return p&&p.status!=='completed'&&p.status!=='archived';});return active.find(function(p){return p.isPrimary;})||active[0]||null;}
  function clearanceReview(definition,storedClearance){var d=normalizeDefinition(definition),clearance=Number(storedClearance);if(!d.minimumClearance)return {review:false,reason:''};if(!Number.isFinite(clearance))return {review:true,reason:'No project clearance is stored. Review recommended readiness before assigning.'};if(d.minimumClearance>clearance)return {review:true,reason:'Project Level '+d.difficulty+' recommends clearance '+d.minimumClearance+'; stored clearance is '+clearance+'.'};return {review:false,reason:''};}
  return {TYPES:TYPES,NEEDS:NEEDS,DEFAULT_STAGES:DEFAULT_STAGES,SKILL_STAGES:SKILL_STAGES,normalizeDefinition:normalizeDefinition,starterDefinitions:starterDefinitions,mergeDefinitions:mergeDefinitions,assignment:assignment,normalizeAssignment:normalizeAssignment,setStage:setStage,setNeed:setNeed,setPrimary:setPrimary,primary:primary,clearanceReview:clearanceReview,clone:clone};
}));
