(function(){
  'use strict';
  var out=document.getElementById('output'),status=document.getElementById('pu2Status'),build=window.ARC_BUILD||{};
  var runtime=ArcV8Stage2Verification.RUNTIME_REVISION||'unknown-runtime',params=new URLSearchParams(window.location.search);
  var publicationCommit=(params.get('publicationCommit')||'').trim(),publicationTree=(params.get('publicationTree')||'').trim();
  var bridge=ArcV8Stage2Verification.create({build:build});
  var physical=ArcV8ProtectedProductionUpgradePhysical.create({build:build,expectedPublicationCommit:publicationCommit,expectedPublicationTree:publicationTree});
  var preBackup=null,postBackup=null,inspected=false,upgraded=false;
  document.getElementById('identity').textContent='Build '+(build.build||'unknown')+' · Stage 2 runtime '+runtime+' · PU2 runtime '+physical.constants.runtimeRevision+' · publication '+(publicationCommit||'missing')+' / '+(publicationTree||'missing')+' · V7_ONLY';
  function value(id){return document.getElementById(id).value.trim();}
  function safe(value){return JSON.stringify(value,function(key,item){return key==='text'?'[verified recovery package prepared for download]':item;},2);}
  function show(value){out.textContent=safe(value);}
  function download(pkg){if(!pkg||!pkg.text)throw Error('Verified recovery package is not available.');var url=URL.createObjectURL(new Blob([pkg.text],{type:pkg.mimeType||'application/json'})),a=document.createElement('a');a.href=url;a.download=pkg.filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
  function refresh(){var fields=value('pu2Operator')&&value('pu2Commit')===publicationCommit&&value('pu2Tree')===publicationTree&&value('pu2Rollback')&&value('pu2Confirmation')===physical.constants.confirmation;document.getElementById('downloadPreUpgradeBackup').disabled=!preBackup;document.getElementById('upgradeProtectedProduction').disabled=!(inspected&&preBackup&&publicationCommit&&publicationTree&&fields);document.getElementById('verifyUpgradedProduction').disabled=!upgraded;document.getElementById('downloadPostUpgradeBackup').disabled=!postBackup;status.textContent='Live inspection '+(inspected?'passed':'pending')+' · pre-upgrade backup '+(preBackup?'verified':'pending')+' · post-upgrade backup '+(postBackup?'verified':'pending')+' · instructional import none · V7_ONLY';}
  function upgradeInput(){return{confirmedBy:value('pu2Operator'),startingCommit:value('pu2Commit'),startingTree:value('pu2Tree'),rollbackRef:value('pu2Rollback'),confirmation:value('pu2Confirmation')};}
  var actions={
    inspectProduction:function(){return bridge.inspectProduction();},initializeProduction:function(){return bridge.initializeProduction({confirmedBy:value('operator'),startingCommit:value('commit'),startingTree:value('tree'),rollbackRef:value('rollback'),confirmation:value('productionConfirmation')});},productionActivationPreflight:function(){return bridge.productionActivationPreflight();},activateProductionAcademic:function(){return bridge.activateProductionAcademic({startingCommit:value('commit'),startingTree:value('tree'),rollbackRef:value('rollback'),confirmation:value('activationConfirmation')});},activationPreflight:function(){return bridge.activationPreflight();},initializeVerification:function(){return bridge.initializeVerification();},seedFixture:function(){return bridge.seedFixture();},projectionBefore:function(){return bridge.projection('2026-09-09');},rehearseFailedMove:function(){return bridge.rehearseFailedMove();},moveEnrollment:function(){return bridge.moveEnrollment();},projectionAfter:function(){return bridge.projection('2026-09-10');},createBackup:function(){return bridge.createBackup();},restoreBackup:function(){return bridge.restoreBackup();},identity:function(){return bridge.identity();},cleanupVerificationDatabase:function(){return bridge.cleanupVerificationDatabase(value('cleanupConfirmation'));},
    inspectProtectedUpgrade:async function(){var result=await physical.inspectProtectedProduction();inspected=true;refresh();return result;},capturePreUpgradeBackup:async function(){preBackup=await physical.captureHistoricalBackup();inspected=true;refresh();return preBackup;},downloadPreUpgradeBackup:function(){download(preBackup);return{downloaded:true,filename:preBackup.filename,fileChecksum:preBackup.fileChecksum,packageChecksum:preBackup.packageChecksum};},upgradeProtectedProduction:async function(){var result=await physical.upgradeProtectedProduction(upgradeInput());upgraded=true;postBackup=result.postUpgradeBackup;refresh();return result;},verifyUpgradedProduction:async function(){var result=await physical.verifyUpgradedProduction();postBackup=result.postUpgradeBackup;refresh();return result;},downloadPostUpgradeBackup:function(){download(postBackup);return{downloaded:true,filename:postBackup.filename,fileChecksum:postBackup.fileChecksum,packageChecksum:postBackup.packageChecksum};}
  };
  document.getElementById('loadPreUpgradeBackup').addEventListener('change',async function(event){var file=event.target.files&&event.target.files[0];if(!file)return;try{preBackup=await physical.loadHistoricalBackup(await file.text());refresh();show(preBackup);}catch(error){preBackup=null;refresh();show({ok:false,code:error.code||error.name,message:error.message,context:error.context||null,runtimeRevision:physical.constants.runtimeRevision,authorityState:'V7_ONLY'});}});
  ['pu2Operator','pu2Commit','pu2Tree','pu2Rollback','pu2Confirmation'].forEach(function(id){document.getElementById(id).addEventListener('input',refresh);});
  document.querySelectorAll('[data-action]').forEach(function(button){button.addEventListener('click',async function(){button.disabled=true;out.textContent='Running '+button.textContent+'…';try{show(await actions[button.dataset.action]());}catch(error){show({ok:false,code:error.code||error.name,message:error.message,context:error.context||null,runtimeRevision:button.dataset.action.indexOf('Protected')>=0||button.dataset.action.indexOf('Upgrade')>=0?physical.constants.runtimeRevision:runtime,authorityState:'V7_ONLY'});}finally{refresh();}});});
  refresh();
}());
