(function(){
  'use strict';
  var out=document.getElementById('output'),status=document.getElementById('pu2Status'),pi1Status=document.getElementById('pi1Status'),pi1PackageStatus=document.getElementById('pi1PackageStatus'),build=window.ARC_BUILD||{};
  var runtime=ArcV8Stage2Verification.RUNTIME_REVISION||'unknown-runtime',params=new URLSearchParams(window.location.search);
  var publicationCommit=(params.get('publicationCommit')||'').trim(),publicationTree=(params.get('publicationTree')||'').trim();
  var bridge=ArcV8Stage2Verification.create({build:build});
  var physical=ArcV8ProtectedProductionUpgradePhysical.create({build:build,expectedPublicationCommit:publicationCommit,expectedPublicationTree:publicationTree});
  var instructional=ArcV8InstructionalImportProductionPhysical.create({build:build,expectedPublicationCommit:publicationCommit,expectedPublicationTree:publicationTree});
  var preBackup=null,postBackup=null,inspected=false,upgraded=false;
  var preImportBackup=null,postImportBackup=null,importReady=false,packageImported=false,payloadLoaded=false,identityMapLoaded=false;
  document.getElementById('identity').textContent='Build '+(build.build||'unknown')+' · Stage 2 runtime '+runtime+' · PU2 runtime '+physical.constants.runtimeRevision+' · PI1 runtime '+instructional.constants.runtimeRevision+' · publication '+(publicationCommit||'missing')+' / '+(publicationTree||'missing')+' · V7_ONLY';
  function value(id){return document.getElementById(id).value.trim();}
  function safe(value){return JSON.stringify(value,function(key,item){return key==='text'?'[verified recovery package prepared for download]':item;},2);}
  function show(value){out.textContent=safe(value);}
  function download(pkg){if(!pkg||!pkg.text)throw Error('Verified recovery package is not available.');var url=URL.createObjectURL(new Blob([pkg.text],{type:pkg.mimeType||'application/json'})),a=document.createElement('a');a.href=url;a.download=pkg.filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
  function refresh(){
    var fields=value('pu2Operator')&&value('pu2Commit')===publicationCommit&&value('pu2Tree')===publicationTree&&value('pu2Rollback')&&value('pu2Confirmation')===physical.constants.confirmation;
    var pi1Fields=value('pi1Operator')&&value('pi1Commit')===publicationCommit&&value('pi1Tree')===publicationTree&&value('pi1Rollback')&&value('pi1Confirmation')===instructional.constants.confirmation;
    document.getElementById('downloadPreUpgradeBackup').disabled=!preBackup;
    document.getElementById('upgradeProtectedProduction').disabled=!(inspected&&preBackup&&publicationCommit&&publicationTree&&fields);
    document.getElementById('verifyUpgradedProduction').disabled=!upgraded;
    document.getElementById('downloadPostUpgradeBackup').disabled=!postBackup;
    status.textContent='Live inspection '+(inspected?'passed':'pending')+' · pre-upgrade backup '+(preBackup?'verified':'pending')+' · post-upgrade backup '+(postBackup?'verified':'pending')+' · instructional import none · V7_ONLY';
    document.getElementById('downloadPreImportBackup').disabled=!preImportBackup;
    document.getElementById('importVerifiedInstructionalPackage').disabled=!(importReady&&preImportBackup&&payloadLoaded&&identityMapLoaded&&publicationCommit&&publicationTree&&pi1Fields);
    document.getElementById('verifyImportedInstructionalPackage').disabled=!packageImported;
    document.getElementById('downloadPostImportBackup').disabled=!postImportBackup;
    pi1Status.textContent='Live readiness '+(importReady?'passed':'pending')+' · pre-import backup '+(preImportBackup?'verified':'pending')+' · post-import backup '+(postImportBackup?'verified':'pending')+' · V7_ONLY';
    pi1PackageStatus.textContent='Resolved payload '+(payloadLoaded?'exact bytes verified':'pending')+' · identity map '+(identityMapLoaded?'exact bytes verified':'pending')+' · package '+(packageImported?'verified_complete / unavailable':'not imported')+' · V7_ONLY';
  }
  function upgradeInput(){return{confirmedBy:value('pu2Operator'),startingCommit:value('pu2Commit'),startingTree:value('pu2Tree'),rollbackRef:value('pu2Rollback'),confirmation:value('pu2Confirmation')};}
  function importInput(){return{operator:value('pi1Operator'),publicationCommit:value('pi1Commit'),publicationTree:value('pi1Tree'),rollbackRef:value('pi1Rollback'),confirmation:value('pi1Confirmation')};}
  var actions={
    inspectProduction:function(){return bridge.inspectProduction();},initializeProduction:function(){return bridge.initializeProduction({confirmedBy:value('operator'),startingCommit:value('commit'),startingTree:value('tree'),rollbackRef:value('rollback'),confirmation:value('productionConfirmation')});},productionActivationPreflight:function(){return bridge.productionActivationPreflight();},activateProductionAcademic:function(){return bridge.activateProductionAcademic({startingCommit:value('commit'),startingTree:value('tree'),rollbackRef:value('rollback'),confirmation:value('activationConfirmation')});},activationPreflight:function(){return bridge.activationPreflight();},initializeVerification:function(){return bridge.initializeVerification();},seedFixture:function(){return bridge.seedFixture();},projectionBefore:function(){return bridge.projection('2026-09-09');},rehearseFailedMove:function(){return bridge.rehearseFailedMove();},moveEnrollment:function(){return bridge.moveEnrollment();},projectionAfter:function(){return bridge.projection('2026-09-10');},createBackup:function(){return bridge.createBackup();},restoreBackup:function(){return bridge.restoreBackup();},identity:function(){return bridge.identity();},cleanupVerificationDatabase:function(){return bridge.cleanupVerificationDatabase(value('cleanupConfirmation'));},
    inspectProtectedUpgrade:async function(){var result=await physical.inspectProtectedProduction();inspected=true;refresh();return result;},capturePreUpgradeBackup:async function(){preBackup=await physical.captureHistoricalBackup();inspected=true;refresh();return preBackup;},downloadPreUpgradeBackup:function(){download(preBackup);return{downloaded:true,filename:preBackup.filename,fileChecksum:preBackup.fileChecksum,packageChecksum:preBackup.packageChecksum};},upgradeProtectedProduction:async function(){var result=await physical.upgradeProtectedProduction(upgradeInput());upgraded=true;postBackup=result.postUpgradeBackup;refresh();return result;},verifyUpgradedProduction:async function(){var result=await physical.verifyUpgradedProduction();postBackup=result.postUpgradeBackup;refresh();return result;},downloadPostUpgradeBackup:function(){download(postBackup);return{downloaded:true,filename:postBackup.filename,fileChecksum:postBackup.fileChecksum,packageChecksum:postBackup.packageChecksum};},
    inspectInstructionalImport:async function(){var result=await instructional.inspectProduction();importReady=true;refresh();return result;},capturePreImportBackup:async function(){preImportBackup=await instructional.capturePreImportBackup();importReady=true;refresh();return preImportBackup;},downloadPreImportBackup:function(){download(preImportBackup);return{downloaded:true,filename:preImportBackup.filename,fileChecksum:preImportBackup.fileChecksum,packageChecksum:preImportBackup.packageChecksum};},importVerifiedInstructionalPackage:async function(){var result=await instructional.importVerifiedPackage(importInput());packageImported=true;postImportBackup=result.postImportBackup;refresh();return result;},verifyImportedInstructionalPackage:async function(){var result=await instructional.verifyImportedPackage();packageImported=true;postImportBackup=result.postImportBackup;refresh();return result;},downloadPostImportBackup:function(){download(postImportBackup);return{downloaded:true,filename:postImportBackup.filename,fileChecksum:postImportBackup.fileChecksum,packageChecksum:postImportBackup.packageChecksum};}
  };
  document.getElementById('loadPreUpgradeBackup').addEventListener('change',async function(event){var file=event.target.files&&event.target.files[0];if(!file)return;try{preBackup=await physical.loadHistoricalBackup(await file.text());refresh();show(preBackup);}catch(error){preBackup=null;refresh();show({ok:false,code:error.code||error.name,message:error.message,context:error.context||null,runtimeRevision:physical.constants.runtimeRevision,authorityState:'V7_ONLY'});}});
  document.getElementById('loadPreImportBackup').addEventListener('change',async function(event){var file=event.target.files&&event.target.files[0];if(!file)return;try{preImportBackup=await instructional.loadPreImportBackup(await file.text());refresh();show(preImportBackup);}catch(error){preImportBackup=null;refresh();show({ok:false,code:error.code||error.name,message:error.message,context:error.context||null,runtimeRevision:instructional.constants.runtimeRevision,authorityState:'V7_ONLY'});}});
  document.getElementById('loadResolvedPayload').addEventListener('change',async function(event){var file=event.target.files&&event.target.files[0];if(!file)return;try{var result=await instructional.loadResolvedPayload(await file.text());payloadLoaded=true;refresh();show(result);}catch(error){payloadLoaded=false;refresh();show({ok:false,code:error.code||error.name,message:error.message,context:error.context||null,runtimeRevision:instructional.constants.runtimeRevision,authorityState:'V7_ONLY'});}});
  document.getElementById('loadIdentityMap').addEventListener('change',async function(event){var file=event.target.files&&event.target.files[0];if(!file)return;try{var result=await instructional.loadIdentityMap(await file.text());identityMapLoaded=true;refresh();show(result);}catch(error){identityMapLoaded=false;refresh();show({ok:false,code:error.code||error.name,message:error.message,context:error.context||null,runtimeRevision:instructional.constants.runtimeRevision,authorityState:'V7_ONLY'});}});
  ['pu2Operator','pu2Commit','pu2Tree','pu2Rollback','pu2Confirmation'].forEach(function(id){document.getElementById(id).addEventListener('input',refresh);});
  ['pi1Operator','pi1Commit','pi1Tree','pi1Rollback','pi1Confirmation'].forEach(function(id){document.getElementById(id).addEventListener('input',refresh);});
  document.querySelectorAll('[data-action]').forEach(function(button){button.addEventListener('click',async function(){button.disabled=true;out.textContent='Running '+button.textContent+'…';try{show(await actions[button.dataset.action]());}catch(error){var pi1=button.dataset.action.indexOf('Instructional')>=0||button.dataset.action.indexOf('Import')>=0||button.dataset.action.indexOf('Package')>=0;show({ok:false,code:error.code||error.name,message:error.message,context:error.context||null,runtimeRevision:pi1?instructional.constants.runtimeRevision:(button.dataset.action.indexOf('Protected')>=0||button.dataset.action.indexOf('Upgrade')>=0?physical.constants.runtimeRevision:runtime),authorityState:'V7_ONLY'});}finally{refresh();}});});
  refresh();
}());
